### PR TITLE
MBL-12497 - update rubrics with animations

### PR DESCRIPTION
**Pull request by bluwave**
refs: MBL-12497
affects: Student
release note: none

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-12497](https://instructure.atlassian.net/browse/MBL-12497)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Core** | 95.15% | 95.14% | 0.01%
**Student** | 92.2% | 92.69% | -0.49%
**Teacher** | 100% | 100% | 0%
**React Native** | 92.79% | 92.79% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1000170&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by bluwave** [comment]
Agreed.  I think there will be some follow up to this one i'll need to do in some smaller tickets.

**Comment by bluwave** [comment]
thanks for looking at this one

**Pull request merged**
