### PR TITLE
Add user pronouns to Context Card

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBL-13763
affects: teacher
release note: none

Test plan:
* Teacher app > narmstrong : t
* CS 1400 > People > Student1 Armstrong
* Context card should display pronouns

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by armstrongnate** [comment]
Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-24 at 11 11 29

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Teacher

[MBL-13763](https://instructure.atlassian.net/browse/MBL-13763)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.56% | 93.58% | -0.02%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1019765&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|23
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Pull request merged**
