### PR TITLE
Update English source strings

### PR DESCRIPTION
**Pull request by inst-danger**
[ignore-commit-lint]

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/ydtkzos) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fydtkzos)
teacher: [Link](https://rebrand.ly/ljvx1wf) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fljvx1wf)
parent: [Link](https://rebrand.ly/tmc2u44) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Ftmc2u44)

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1026187&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|1
Medium|13
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---
High|1

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.64% | 93.63% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Pull request merged**
