### PR TITLE
Hide syllabus if it's not Home and disabled

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBl-13778
affects: parent
release note: Fixed a bug that would cause the syllabus to show when it should not be shown

Test plan:
* Log in to Parent app as `o` on narmstrong
* Select Student Two
* _Fight Club_ should not show syllabus
* _Modules_ course should show the Syllabus
* _CS 1400_ should not show the syllabus but should show Front Page

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by inst-danger** [comment]
#### Release Note: 
Fixed a bug that would cause the syllabus to show when it should not be shown

#### Affected Apps: Parent

[MBL-13778](https://instructure.atlassian.net/browse/MBL-13778)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.41% | 93.41% | -0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1017891&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|23
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1017892&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|23
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by bluwave** [comment]
this code business of showing which tab has gotten out of control 😂

**Pull request merged**
