### PR TITLE
Add HeapID and Access Token to developer menu

### PR DESCRIPTION
**Pull request by szabinst**
HeapID and Access Token is now available in the Developer Menu. 

refs: MBL-16732
affects: Student, Teacher, Parent
release note: none 
test plan:  See ticket

## Screenshots

<table>
<tr><th>HeapID</th><th>Access Token</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Tested on phone

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student, Teacher, Parent

[MBL-16732](https://instructure.atlassian.net/browse/MBL-16732)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.91% | 91.91% | 0%
Core/Core/Extensions/PublisherExtensions.swift | 22.73% | 22.73% | 0%
Core/Core/Courses/CourseDetails/ViewModel/CourseDetailsViewModel.swift | 48.89% | 48.89% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f92276cfe3ebafc5a5cf0564ac7ac73ca3983049
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by idevainstr — APPROVED** [review]

**Pull request merged**
