### PR TITLE
Remove Persistence protocol

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-12080
affects: none
release note: none

### CODE REVIEW

**Comment by vanwagonet** [comment]
Student presenter tests keep failing in bitrise. :( I've tried a few different fixes, but I'm not sure I understand the root cause.

**Comment by armstrongnate** [comment]
I have an idea. I'll push it up in a sec.

**Comment by armstrongnate** [comment]
I think that using expectations in that way still allows for race conditions. I think using callbacks like I have in https://github.com/instructure/canvas-ios/pull/250/commits/dce417b5a18c3cae9a69a539f4eafadbfd855784 will be more stable. We'll see what the builds say.

**Comment by armstrongnate** [comment]
The root problem is that the expectations get called multiple times, so we would have to know exactly how many times they need to get called and then set `expectedFulfillmentCount` but that is extremely brittle.

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: None

[MBL-12080](https://instructure.atlassian.net/browse/MBL-12080)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Core** | 95.13% | 95.16% | -0.03%
**Student** | 92.84% | 92.84% | 0%
**Teacher** | 100% | 100% | 0%
**React Native** | 92.68% | 92.68% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Pull request merged**
