### PR TITLE
Fix discussion scroll to new comment

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15543
affects: Student, Teacher
release note: none

test plan:
- Create a new discussion or enter one where all comments plus your upcoming one fits the screen
- Add a new reply
- Screen shouldn't scroll

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/83671007/p/f90201b963bc7de660cad449447760d4">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/83671034/p/2185a08a2b1c4005017f6bf5ce1463ba">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/83670957/p/16afbc57486bd6bc0c15776d28f778e2">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.98% | 91.98% | 0%

[MBL-15543](https://instructure.atlassian.net/browse/MBL-15543)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]

**Pull request merged**
