### PR TITLE
Support navigating within login web view

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBL-14726
affects: student, teacher, parent
release note: Fixed logging in for some institutions

test plan:
- Find My School > search for "mit" > tap Massachusetts Institute of Technology
- Tap MIT Students, Faculty, and Staff
- It should load the next login page within the web view
- A back button should appear at the bottom
- Tapping the back button should take you back in the web view and the back button should disappear

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/LoginWebViewControllerTests/testRedirectFlow</summary>


    Assertion Failure: LoginWebViewControllerTests.swift:69: XCTAssertEqual failed: ("WKNavigationActionPolicy") is not equal to ("WKNavigationActionPolicy")
    Assertion Failure: LoginWebViewControllerTests.swift:71: XCTAssertEqual failed: ("nil") is not equal to ("Optional(https://community.canvaslms.com)")
</details>


[MBL-14726](https://instructure.atlassian.net/browse/MBL-14726)

#### Affected Apps: Student, Teacher, Parent

#### Release Note: 
Fixed logging in for some institutions
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/49590512/p/c467c223670df2181d9addb11c14c130">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/49590525/p/1a5122ca99f14aae381f2a1c2dfdf7aa">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/49590500/p/d0de40d135ee0e622c4a278c5d0e895f">
    
  </a>
</details>

**Review by vanwagonet — APPROVED** [review]
QA+1

**Review by vanwagonet — APPROVED** [review]
QA+1 Much nicer with the progress!

**Pull request merged**
