### PR TITLE
Fix student calendar freeze

### PR DESCRIPTION
**Pull request by szabolcs-instructure**
refs: MBL-16282
affects: Student
release note: Fix calendar freeze

test plan:
1. Have an account with many events so that they don't fit on one page. (You can spam ToDo events on the calendar page with the + button, create at least 11 items.)
2. Start the app in landscape (iPhone 13 Pro Max).
3. Tap on calendar tab.

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] A11y checked
- [x] Tested on phone
- [x] Tested on tablet
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/CircleRefreshControlTests/testRefresh</summary>


    Assertion Failure at CircleRefreshControlTests.swift:57: XCTAssertEqual failed: ("false") is not equal to ("true")
    Assertion Failure at CircleRefreshControlTests.swift:58: XCTAssertEqual failed: ("true") is not equal to ("false")
    Assertion Failure at CircleRefreshControlTests.swift:59: XCTAssertEqual failed: ("true") is not equal to ("false")
    Assertion Failure at CircleRefreshControlTests.swift:62: XCTAssertEqual failed: ("false") is not equal to ("true")
    Assertion Failure at CircleRefreshControlTests.swift:63: XCTAssertEqual failed: ("true") is not equal to ("false")
    Assertion Failure at CircleRefreshControlTests.swift:64: XCTAssertEqual failed: ("true") is not equal to ("false")
</details>
<details><summary>:x: XCTest failed: CoreTests/PlannerViewControllerTests/testLayout</summary>


    Assertion Failure at PlannerViewControllerTests.swift:39: XCTAssertGreaterThan failed: ("0.0") is not greater than ("143.0")
    Assertion Failure at PlannerViewControllerTests.swift:40: XCTAssertGreaterThan failed: ("0.0") is not greater than ("143.0")
    Assertion Failure at PlannerViewControllerTests.swift:85: XCTAssertEqual failed: ("0.0") is not equal to ("360.0")
    Assertion Failure at PlannerViewControllerTests.swift:86: XCTAssertEqual failed: ("0.0") is not equal to ("360.0")
    Assertion Failure at PlannerViewControllerTests.swift:95: XCTAssertEqual failed: ("360.0") is not equal to ("144.0")
</details>


[MBL-16282](https://instructure.atlassian.net/browse/MBL-16282)

#### Affected Apps: Student

#### Release Note: 
Fix calendar freeze
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by vargaat — CHANGES_REQUESTED** [review]
Still freezes for me even on an SE2. `PlannerListViewController` still has `ListBackgroundView` in it which causes the infinite loop.

**Review by vargaat — APPROVED** [review]
QA+1

**Review by idevainstr — APPROVED** [review]

**Pull request merged**
