### PR TITLE
Update offline sync selector loading state.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-17066
affects: Student
release note: none

test plan:
- Enter "Manage Offline Content" screen on an account with lots of courses and files.
- Check the loading state of the page: it should display a still panda with a message.

## Checklist

- [ ] Follow-up e2e test ticket created
- [x] A11y checked
- [ ] Tested on phone
- [x] Tested on tablet
- [x] Tested in dark mode
- [x] Tested in light mode
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-17066](https://instructure.atlassian.net/browse/MBL-17066)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.41% | 92.42% | -0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ebffe3a3a6f9bb4f6ed5e1da3e36842dfaeb5d79
</p>

**Review by balintbartok — DISMISSED** [review]
QA + 1

**Review by ndrsszsz — DISMISSED** [review]
QA +1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by szabinst — APPROVED** [review]
QA + 1

**Pull request merged**
