### PR TITLE
Fix grades not showing

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-15796
affects: Parent
release note: Fix total grades not showing on course list
test plan: see ticket, also check MBL-15675

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/104020280/p/56f8fd72cc0c99ddf3f1c2e5cda375fa">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/104020302/p/ac4ecf4d10f20700e7c10ab72bf680d0">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/104020258/p/988adbacb02c6cf8a1e28d3926ce0b8f">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: ParentUnitTests/CourseListViewControllerTests/testLayout</summary>


    Assertion Failure at CourseListViewControllerTests.swift:143: XCTAssertEqual failed: ("Optional("")") is not equal to ("Optional("N/A")")
</details>


[MBL-15796](https://instructure.atlassian.net/browse/MBL-15796)
[MBL-15675](https://instructure.atlassian.net/browse/MBL-15675)

#### Affected Apps: Parent

#### Release Note: 
Fix total grades not showing on course list
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
