### PR TITLE
Recent Activity page in course filters all courses' activities

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15594
affects: Student
release note: Show course related recent activities.
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/89436953/p/c7e4fcc9c2010c151fe628f0761e6b1e">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/89436960/p/f2a68d67ce101f0ee4268797970d3f65">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/89436936/p/ca3b288164cfb5dd4688b6e40add153b">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/GetActivitiesTests/testScope</summary>


    Assertion Failure at GetActivitiesTests.swift:43: XCTAssertEqual failed: ("Scope(predicate: (typeRaw != "WebConference" AND typeRaw != "Collaboration" AND typeRaw != "AssessmentRequest") AND TRUEPREDICATE, order: [(updatedAt, descending, compare:)], sectionNameKeyPath: nil)") is not equal to ("Scope(predicate: typeRaw != "WebConference" AND typeRaw != "Collaboration" AND typeRaw != "AssessmentRequest", order: [(updatedAt, descending, compare:)], sectionNameKeyPath: nil)")
</details>


[MBL-15594](https://instructure.atlassian.net/browse/MBL-15594)

#### Affected Apps: Student

#### Release Note: 
Show course related recent activities.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by davidvarga93 — DISMISSED** [review]
QA + 1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
