### PR TITLE
Long submission comments do not retain focus

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-16726
affects: Student, Teacher
release note: Improved submission comment entry field.
test plan: See ticket. Submission comments should grow up to 10 lines both on student submission and teacher speedgrader pages. Drawer should override the textview height. Comments should be scrollable.

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [x] Tested on phone
- [x] Tested on tablet
- [ ] Tested in dark mode
- [x] Tested in light mode
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Release Note: 
Improved submission comment entry field.

#### Affected Apps: Student, Teacher

[MBL-16726](https://instructure.atlassian.net/browse/MBL-16726)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92% | 92.02% | -0.02%
Core/Core/CourseSync/CourseSyncProgress/Model/CourseSyncProgressInteractor.swift | 0% | 0% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e5c7ea86b164982a14eaf85f098448b9c01da7b4
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Comment by ndrsszsz** [comment]
QA +1
iPhone 11 - iOS 16.5 (Student, Teacher)

**Review by ndrsszsz — APPROVED** [review]
Nice fix. 👍

**Pull request merged**
