### PR TITLE
Teacher Bulk Publish Progress screen UI

### PR DESCRIPTION
**Pull request by rh12**
refs: [MBL-17305](https://instructure.atlassian.net/browse/MBL-17305)
affects: Teacher
release note: none

## What's new
- added Progress screen for All Modules or single Module bulk publish
- added Cancel snackbar
- integrated them into ModuleList

### Details
- added view & viewmodel
- added temporary dummy interactor for QA purposes
- refactored publish action enum to `ModulePublishAction` to include `subject`
- updated `findSnackBarViewModel()` to handle more cases
- unified ProgressViewStyle coloring

## Test plan
- Enable experimental feature flag in Developer Menu
- To reproduce success case: publish/unpublish All Modules (in navBar)
- To reproduce failure case: publish/unpublish a Module (in Module section header)
  - update should fail after a few seconds
- See ticket for expectations

## Screenshots

<table>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [x] A11y checked
- [x] Tested on phone
- [ ] Tested on tablet
- [x] Tested in dark mode
- [x] Tested in light mode

[MBL-17305]: https://instructure.atlassian.net/browse/MBL-17305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Teacher

[MBL-17305](https://instructure.atlassian.net/browse/MBL-17305)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.82% | 91.79% | 0.03%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 109f4180fde1216de7cb638f6f8c94004a1ddbb4
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by vargaat — APPROVED** [review]
Looks good, we'll iron out the issues we discussed later.

**Review by ndrsszsz — COMMENTED** [review]
QA +1

**Pull request merged**
