### PR TITLE
Add voiceover status updates.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-14907
affects: Student
release note: Improved accessibility features.

test plan: See ticket

### CODE REVIEW

**Comment by vargaat** [comment]
I couldn’t trigger the pull-to-refresh event when VoiceOver was enabled, the screen must have been changed since the creation of this ticket. Announcements can be checked using Charles, setup a breakpoint on the to-do API call and abort execution to trigger the error state announcement or setup a high round trip latency in throttle options to check the loading state announcement.

Unfortunately, the default behaviour of VoiceOver announcements are a little hectic. They abort or silence each other, so often not all announcements are audible.

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/75608571/p/72b0e6c3d4d19091c94cfd12ac652695">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/75608578/p/500cbd79bf2bb263af03822d27e91ffc">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/75608561/p/ebfd3850e19d6e62669b95c165946e77">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.85% | 91.85% | 0%
Core/Core/Dashboard/K5/ViewModel/K5DashboardViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Grades/K5GradesViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/K5DashboardNavigationViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Schedule/K5ScheduleViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Homeroom/K5HomeroomViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Resources/K5ResourcesViewModel.swift | 0% | 0% | 0%

[MBL-14907](https://instructure.atlassian.net/browse/MBL-14907)

#### Affected Apps: Student

#### Release Note: 
Improved accessibility features.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Comment by davidvarga93** [comment]
QA+1

**Pull request merged**
