### PR TITLE
Unable to take quiz via the assignments tab which has been unlocked

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15800
affects: Student
release note: Fixed unable to take unlocked quiz via the assignments tab.
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/104966386/p/fa6057da448054720e68c9aaedaf579e">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/104966423/p/ba11231a1aab933e567d5b1bdb027366">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/104966302/p/c85d4158642c68bc74cab52b2af0456d">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.47% | 91.47% | 0%

[MBL-15800](https://instructure.atlassian.net/browse/MBL-15800)

#### Affected Apps: Student

#### Release Note: 
Fixed unable to take unlocked quiz via the assignments tab.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by vargaat — CHANGES_REQUESTED** [review]
If I login to a clean app install, then the "Take quiz" button doesn't appear only if I manually do a pull-to-refresh. In addition to this the "This assignment was locked..." status text also changes: the date format becomes different and the hour of the day also changes.

https://user-images.githubusercontent.com/72396990/147912826-4c152ba4-e975-40aa-96aa-e8587f75f145.MP4

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
