### PR TITLE
Use current grading scores, even in case of totals enabled

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-15259
affects: Student
release note: Fixed course grades in specific cases.

test plan: see ticket

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/69457361/p/da8baadad7089f91c74619bebe5686be">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/69457372/p/8839735d66bf1c530b3971afe4e35641">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/69457341/p/1da92f711082c8c40255c02e26e56492">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/FileDetailsViewControllerTests/testModel</summary>


    Assertion Failure at FileDetailsViewControllerTests.swift:175: Asynchronous wait failed: Exceeded timeout of 5 seconds, with unfulfilled expectations: "done".
    Assertion Failure at FileDetailsViewControllerTests.swift:176: XCTAssertTrue failed
    Assertion Failure at FileDetailsViewControllerTests.swift:177: XCTAssertTrue failed
    Assertion Failure at FileDetailsViewControllerTests.swift:178: XCTAssertFalse failed
</details>
<details><summary>:x: XCTest failed: CoreTests/RichContentEditorViewControllerTests/testBadMedia</summary>


    Assertion Failure at RichContentEditorViewControllerTests.swift:56: Asynchronous wait failed: Exceeded timeout of 10 seconds, with unfulfilled expectations: "updated".
</details>
<details><summary>:x: XCTest failed: CoreTests/RichContentEditorViewControllerTests/testLink</summary>


    Assertion Failure at RichContentEditorViewControllerTests.swift:56: Asynchronous wait failed: Exceeded timeout of 10 seconds, with unfulfilled expectations: "updated".
</details>


[MBL-15259](https://instructure.atlassian.net/browse/MBL-15259)

#### Affected Apps: Student

#### Release Note: 
Fixed course grades in specific cases.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by idevainstr** [comment]
QA+1

**Review by idevainstr — APPROVED** [review]

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
