### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by inst-danger**
affects: Parent, Student, Teacher<br/><br/>[ignore-commit-lint]

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.69% | 91.69% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f8c1b95e4d36a8d45146772dd3228a87dd34e4c1
</p>

**Review by szabinst — APPROVED** [review]

**Pull request merged**
