### PR TITLE
Fix empty screens and parent dark mode switch

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-16124, MBL-16118
affects: Student, Teacher, Parent
release note: none
test plan: See tickets.

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.76% | 91.76% | -0.01%

[MBL-16124](https://instructure.atlassian.net/browse/MBL-16124)
[MBL-16118](https://instructure.atlassian.net/browse/MBL-16118)

#### Affected Apps: Student, Teacher, Parent
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/a709dff4-4787-42de-9d5f-6ec42f4c6b24/artifact/56622096346a7cf4/p/d767f66168edeef8c2bef73c739ea7b1">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/a709dff4-4787-42de-9d5f-6ec42f4c6b24/artifact/f185e90a1b7c14ff/p/15b0224ad37b10d7900a6dacb938f31b">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/a709dff4-4787-42de-9d5f-6ec42f4c6b24/artifact/e512a7649ec5fd7d/p/fb15b013c94de750e1b8ddbd4a572d6e">
    
  </a>
</details>

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
