### PR TITLE
Hide panda image from voice over, group title and message

### PR DESCRIPTION
**Pull request by tamasiscoming**
refs: MBL-15972
affects: Student, Teacher, Parent
release note: none
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/fe52cb00-a106-435e-89eb-d41672469bb2/artifact/f426cf3a3214cc0c/p/37cfb843625a3308482d21c10ca44502">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/fe52cb00-a106-435e-89eb-d41672469bb2/artifact/30cf72151fa35809/p/4c9121bd147683cae47628c794ba037a">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/fe52cb00-a106-435e-89eb-d41672469bb2/artifact/b33b6074b99c4871/p/41f8b2ffcc6be3f281be27b28faea138">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.8% | 91.8% | 0%

[MBL-15972](https://instructure.atlassian.net/browse/MBL-15972)

#### Affected Apps: Student, Teacher, Parent
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
