### PR TITLE
No longer use deprecated store review method.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15890
affects: Student, Teacher, Parent
release note: none

test plan:
- Launch the app.
- Go to Developer menu.
- Enter Manage Rating Request menu.
- Clear "Last Request" and "Last View" fields.
- Set "Consecutive Days" to 10.
- Go back.
- Put the app to background.
- Tap the app icon to bring it foreground.
- App review dialog should appear.

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.45% | 91.45% | 0%

[MBL-15890](https://instructure.atlassian.net/browse/MBL-15890)

#### Affected Apps: Student, Teacher, Parent
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/111932484/p/622ad18ebf842b6e55f0d36b6023baa5">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/111932492/p/cf25ac0f3edd977586202ea245036e11">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/111932471/p/59ae627f2bb9f70710abe7eacddf1e9c">
    
  </a>
</details>

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]

**Pull request merged**
