### PR TITLE
Enhance crash reports

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16451
affects: Student, Teacher, Parent
release note: none

test plan:
- Setup production secrets for crashlytics.
- Switch scheme's Run action to build Production config, uncheck debug executable.
- Run the app.
- Switch screens.
- Go to developer menu and tap Force Native Crash.
- Restart the app.
- Locate the app.DSYM file in derived data, zip it.
- Upload it to crashlytics.
- Wait for the crash to be symbolicated.
- Check if crash logs include screen routes.

## Screenshots

<table>
<tr>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Review by balintbartok — APPROVED** [review]

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.75% | 91.75% | 0%
Core/Core/Submissions/SubmissionBreakdown/SubmissionBreakdownViewModelProtocol.swift | 0% | 0% | 0%
Core/Core/Quizzes/QuizDetails/ViewModel/PreviewQuizDetailsViewModel.swift | 0% | 0% | 0%

[MBL-16451](https://instructure.atlassian.net/browse/MBL-16451)

#### Affected Apps: Student, Teacher, Parent
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by idevainstr — APPROVED** [review]

**Review by szabinst — APPROVED** [review]

**Pull request merged**
