### PR TITLE
Fix PageViewEvent persistency crash

### PR DESCRIPTION
**Pull request by szabinst**
refs: MBL-16867
affects: Student
release note: Fixed a silent crash that occurred while processing data
test plan: See more below

1. Open a few screens. 
2. Close the app
3. Open the app 

## Checklist

- [ ] Tested on phone
- [x] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Comment by inst-danger** [comment]
#### Release Note: 
Fixed a silent crash that occurred while processing data

#### Affected Apps: Student

[MBL-16867](https://instructure.atlassian.net/browse/MBL-16867)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.39% | 92.4% | -0.02%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6076947b92d34cd1c645b49fe9828638098ae169
</p>

**Review by ndrsszsz — APPROVED** [review]
QA +1

**Pull request merged**
