### PR TITLE
Include account ID in pairing QR code

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBL-14752
affects: student
release note: none

test plan: You would need to have an Android device to test this. I have
one and tested it locally. I will test with the ad-hoc build as well.

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.13% | 93.13% | 0%

[MBL-14752](https://instructure.atlassian.net/browse/MBL-14752)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/50162643/p/8d4502488386b7abfda619324b44b46d">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/50162644/p/b4d81f708ad8f185cba26891baefea65">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/50162615/p/d4fc3f8ceef739398abab7a063159849">
    
  </a>
</details>

**Review by cobbal — APPROVED** [review]
Tried to give it a QA, but having too many android problems. I checked the QR code contains the right ID, but I'll leave it to you for the android side.

**Comment by armstrongnate** [comment]
QA +1 worked as expected.

**Pull request merged**
