### PR TITLE
Display fitting panda for pending users

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-15407
affects: Teacher, Student
release note: Fixed error page for pending users

test plan: see ticket, use balintbartok, "nota" user

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.96% | 91.96% | 0%

[MBL-15407](https://instructure.atlassian.net/browse/MBL-15407)

#### Affected Apps: Teacher, Student

#### Release Note: 
Fixed error page for pending users
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80329174/p/2e645ee46ca41cb12bb945ce69fe1447">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80329200/p/de52a54baff3a1d07dafa8b3def15822">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80329125/p/49f2b7ec77b0b5feec8fb31ba5f2f273">
    
  </a>
</details>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
