### PR TITLE
Dashboard course card images are flickering on refresh

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-16394
affects: Student, Teacher
release note: Fixed course header images are flickering on refresh.
test plan: See ticket.

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by vargaat — APPROVED** [review]
QA+1

On dashboard the pull to refresh on the course image is broken but works correctly on the course details page, no flickering.

**Review by szabolcs-instructure — APPROVED** [review]
QA + 1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
