### PR TITLE
Add attempt picker to assignment details

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16516
affects: Student
release note: Added attempt selector to the assignment details page to institutes where Assignment Enhancements is turned on.

test plan: Go to assignment details and select a previous attempt. Grade box should update to reflect that attempt's grade.

## Screenshots

<table>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [x] Tested on phone
- [ ] Tested on tablet
- [x] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Release Note: 
Added an attempt selector to the assignment details page.

#### Affected Apps: Student

[MBL-16516](https://instructure.atlassian.net/browse/MBL-16516)
[MBL-16514](https://instructure.atlassian.net/browse/MBL-16514)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.96% | 91.97% | -0.01%
Core/Core/Inbox/Addressbook/ViewModel/AddressbookViewModel.swift | 0% | 0% | 0%
Core/Core/Inbox/Addressbook/Model/AddressbookInteractorLive.swift | 0% | 0% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 78b019d3f8f76188aa015f7c9579d43b1d4151f2
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
