### PR TITLE
Login screen refinements

### PR DESCRIPTION
**Pull request by szabinst**
Login refinements, see [Figma](https://www.figma.com/file/ucO95BbZULecZelrkAplKc/02.02-Student-%5BAndroid-iOS-iPadOS%5D?node-id=458%3A0&t=S9KoCjfYQpD7e3of-0) for details. 

## Screenshots

<table>
<tr><th>Before - No prev. logins </th><th>After - No prev. logins</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr><th>Before - 1 prev login </th><th>After - 1 prev login</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr><th>Before - Multiple prev. logins </th><th>After - Multiple prev. logins</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr><th>Before - iPad Multiple prev. logins </th><th>After - iPad Multiple prev. logins</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [x] Tested on phone
- [x] Tested on tablet
- [x] Tested in dark mode
- [x] Tested in light mode
- [ ] Approve from product or not needed

### CODE REVIEW

**Comment by szabinst** [comment]
fyi: According to the Figma design, I adjusted the canvas logo size from 76 to 64 after the screenshots have been taken.

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.91% | 91.91% | 0%
Core/Core/Courses/CourseDetails/ViewModel/CourseDetailsViewModel.swift | 48.89% | 48.89% | 0%

[MBL-16349](https://instructure.atlassian.net/browse/MBL-16349)

#### Affected Apps: Student, Teacher, Parent

#### Release Note: 
Updated login screen visualization
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by vargaat — DISMISSED** [review]
QA+1

**Review by vargaat — APPROVED** [review]
QA+1

**Review by idevainstr — APPROVED** [review]
QA +1

**Pull request merged**
