### PR TITLE
[Horizon] Button styles

### PR DESCRIPTION
**Pull request by reabbotted**
Adding the button component styles.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Horizon Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please run `yarn update-headers`. The following do not have the correct license header: 
* packages/HorizonUI/Sources/HorizonUI/Sources/Components/Button/AIButtonStyle.swift
* packages/HorizonUI/Sources/HorizonUI/Sources/Components/Button/BeigeButtonStyle.swift
* packages/HorizonUI/Sources/HorizonUI/Sources/Components/Button/BlackButtonStyle.swift
* packages/HorizonUI/Sources/HorizonUI/Sources/Components/Button/BlueButtonStyle.swift
* packages/HorizonUI/Sources/HorizonUI/Sources/Components/Button/ButtonConfig.swift
* packages/HorizonUI/Sources/HorizonUI/Sources/Components/Button/InverseButtonStyle.swift
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.01% | 91.17% | -0.17%
Core/Core/Courses/CourseProgression/CDCourseProgression.swift | 0% | -- | --
Core/Core/AppEnvironment/AppEnvironmentOverride.swift | 32.76% | 32.76% | 0%
Core/Core/Extensions/CGSizeExtensions.swift | 0% | 0% | 0%
Core/Core/Courses/CourseProgression/GetCoursesProgressionRequest.swift | 0% | -- | --
Core/Core/Search/Model/SearchSupportButtonModel.swift | 0% | 0% | 0%
Core/Core/Courses/SmartSearch/View/CourseSmartSearchViewsProvider.swift | 13.64% | 13.64% | 0%
Core/Core/Courses/SmartSearch/Model/CourseSmartSearchViewAttributes.swift | 30.77% | 30.77% | 0%
Core/Core/Store/FetchedCollection.swift | 48.72% | 48.72% | 0%
Core/Core/Courses/CourseProgression/GetCoursesProgressionUseCase.swift | 0% | -- | --
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c1b00333366f63859983b4589b8b02adbe791253
</p>

**Review by szabinst — CHANGES_REQUESTED** [review]
Looking at figma there are a few options missing: 
- Optional leading or trailing icon
- Relative width button 

I'm thinking if buttonStyle is the right approach: 
- We have a lot of repeating code for setting the height, corner radius, opacity
- We can achieve leading or trailing icon placement by using a `LabelStyle` 
- but then creating a button becomes 

```
Button {
    // invoke tap action
} label: {
    Label {
        Text("Some button")
    } icon: {
        Image(systemName: "some.image")
    }
}
.buttonStyle(.bordered)
.labelStyle(.iconOnly)
```

...and I think it's not ideal. 

What if we create a custom view component that has a (convenience) init like:
```
SomeButton(
    title: String(localized: "example", bundle: .myBundle),
    style: .black,
    height: .normal,
    width: .block,
    leadingIcon: .huiIcons.plus,
    trailingIcon: nil
) {
    someAction()
}
```

We could further shorten it by providing default values like black style, normal height, block width, no icons: 

```
SomeButton(
    title: String(localized: "example", bundle: .myBundle)
) {
    someAction()
}
```

Then to provide flexibility we could have a base initializer that expects @ViewBuilder blocks instead of concrete types likes String and Icon names and use the init above as a convenience init. 

What do you think?

**Comment by reabbotted** [comment]
@szabinst take a look at the updates and let me know what you think.

I wanted to try to keep the configuration for the Horizon buttons to be consistent with SwiftUI patterns. But you're exactly right about code duplication.

The one thing I wasn't able to do that I would have liked is to not have to provide a width parameter. It seems like the button should only have the width of its content normally. But if the .frame(maxWidth: .infinity) modifier is set on the Button, it should then grow to match. But I wasn't able to get it to do that.

**Review by szabinst — APPROVED** [review]

**Review by Ahmed-Naguib93 — APPROVED** [review]

**Pull request merged**
