### PR TITLE
Fix crash while generating preview in share extension

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16160
affects: Student
release note: Fixed a file share extension crash when submitting large files. Added file share extension previews for pdfs and screen recording videos.

test plan:
- Try to submit a large non-pdf file via share extension.
- Share extension should start without crashing.
- Try to submit a pdf and a screen recording file.
- Both should display previews in share extension dialog.

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/scripts/swift/main.swift:29:5: For Where Violation: `where` clauses are preferred over a single `if` inside a `for`. (for_where)
    /Users/vagrant/git/Core/Core/Assignments/AssignmentEditor/AssignmentAssigneePicker.swift:78:50: error: Void Function in Ternary Violation: Using ternary to call Void functions should be avoided. (void_function_in_ternary)
    /Users/vagrant/git/Core/Core/Files/Model/FileSubmissionsStatus.swift:50:17: error: For Where Violation: `where` clauses are preferred over a single `if` inside a `for`. (for_where)
    ❌ /Users/vagrant/git/Core/Core/AppEnvironment/CacheManager.swift:40:13: For Where Violation: `where` clauses are preferred over a single `if` inside a `for`. (for_where)
    /Users/vagrant/git/Core/Core/Analytics/Analytics.swift:52:26: error: Void Function in Ternary Violation: Using ternary to call Void functions should be avoided. (void_function_in_ternary)
    /Users/vagrant/git/TestsFoundation/TestsFoundation/Element/Element.swift:232:13: error: For Where Violation: `where` clauses are preferred over a single `if` inside a `for`. (for_where)
</details>


[MBL-16160](https://instructure.atlassian.net/browse/MBL-16160)

#### Affected Apps: Student

#### Release Note: 
Fixed a file share extension crash when submitting large files. Added file share extension previews for pdfs and screen recording videos.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
