### PR TITLE
Fix webview getting released after moving to full screen

### PR DESCRIPTION
**Pull request by vargaat**
### What happened?
- When moving a html video to full screen hosted from a webview embedded inside SwiftUI the webview got deallocated after moving to full screen.
- I solved this by keeping a strong reference (effectively a retain cycle) to the webview from the full screen handler until the webview is in fullscreen mode and release it after it exits.
- There might be animation / display glitches, like a white border during fullscreen playback. I couldn't get rid of them. Also the touch areas seem to be off sometimes in full screen.

refs: MBL-17645
affects: Student, Teacher
release note: Fixed full screen video playback in announcements and discussions not working.

test plan:
- Embed a studio video inside a discussion.
- Turn on new discussion feature flag.
- Go to the discussion inside the app and move the video to full screen.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [x] Tested on phone
- [x] Tested on tablet
- [x] Tested in dark mode
- [ ] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Fixed full screen video playback in announcements and discussions not working.

#### Affected Apps: Student, Teacher

[MBL-17645](https://instructure.atlassian.net/browse/MBL-17645)

<details><summary>:x: XCTest failed: CoreTests/CourseSyncCleanupInteractorTests/testApplicationOfflineDirectoryForUserDeleted</summary>


    XCTAssertFalse failed
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e3c636683463bcddf6c97693704338ea162f2eb5
</p>

**Review by szabinst — COMMENTED** [review]
I'm not sure if the rotation layout issue falls into the same category as 

> There might be animation / display glitches

but there are some resizing imperfections when switching between portrait and landscape orientation. 

https://github.com/instructure/canvas-ios/assets/110813321/420a7823-17d5-41ea-98e9-bef9858c803f

**Review by ndrsszsz — APPROVED** [review]
QA +1

**Pull request merged**
