### PR TITLE
Improve dashboard favourite button's a11y announcements

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-14908
affects: Student, Teacher
release note: Improved accessibility features.

test plan:
- Enter edit Dashboard menu.
- Turn on VoiceOver.
- Toggle a course's favourite state.
- VoiceOver should announce the actual state correctly.

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.85% | 91.84% | 0%
Core/Core/Dashboard/K5/ViewModel/K5DashboardViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Grades/K5GradesViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/K5DashboardNavigationViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Schedule/K5ScheduleViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Homeroom/K5HomeroomViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Resources/K5ResourcesViewModel.swift | 0% | 0% | 0%

[MBL-14908](https://instructure.atlassian.net/browse/MBL-14908)

#### Affected Apps: Student

#### Release Note: 
Improved accessibility features.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/75619388/p/eca4fcfcd7cc201b115541b5a0b9acd2">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/75619395/p/c9b9cdc3c6cf189cfba5a1307e1a5d6b">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/75619386/p/171f16b3585045487d594a307643473e">
    
  </a>
</details>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Pull request merged**
