### PR TITLE
Calculate letter grade

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16994
affects: Student, Parent
release note: none

test plan:
- Compare assignment/course grades on letter grade only courses, they should match what we can see on the website.

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [x] Tested on phone
- [ ] Tested on tablet
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student, Parent

[MBL-16994](https://instructure.atlassian.net/browse/MBL-16994)

<details><summary>:x: XCTest failed: ParentUnitTests/CourseListCellGradesTests/testScoreWithoutGradeWhenQuantitativeDataEnabled</summary>


    XCTAssertEqual failed: ("N/A") is not equal to ("")
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 26c7f3cbd53a9a892cb76def948d1b5e5afa371d
</p>

**Review by idevainstr — APPROVED** [review]
QA +1

**Review by ndrsszsz — APPROVED** [review]
QA +1

**Pull request merged**
