### PR TITLE
Make file submission icon color reflect course color.

### PR DESCRIPTION
**Pull request by Attila-Varga-Instructure**
refs: MBL-14832
affects: Student
release note: Make file submission icon color reflect course color.

test plan:
- Submit a file upload.
- View the submission comments.
- The file type icon should be the course color.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/52722949/p/ebae40b0b87a34372201f63850f36f72">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/52722957/p/920796dbd41128a9b7ac9c9cce122dda">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/52722940/p/8b6171f3efac356c35a9e4c6be28ea38">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/APIURLTests/testCodableValid</summary>


    Assertion Failure at APITests.swift:320: XCTAssertNotNil failed
</details>
<details><summary>:x: XCTest failed: CoreTests/PageViewEventRequestManagerTests/testRetrievePandataEndpointInfo</summary>


    Assertion Failure at PageViewEventRequestManagerTests.swift:68: Asynchronous wait failed: Exceeded timeout of 5 seconds, with unfulfilled expectations: "events added".
</details>
<details><summary>:x: XCTest failed: CoreTests/PageViewEventViewControllerLoggingProtocolTests/testTracking</summary>


    Assertion Failure at PageViewEventViewControllerLoggingProtocolTests.swift:75: Asynchronous wait failed: Exceeded timeout of 0.5 seconds, with unfulfilled expectations: "description".
    Assertion Failure at PageViewEventViewControllerLoggingProtocolTests.swift:78: XCTAssertEqual failed: ("nil") is not equal to ("Optional(1)")
    Assertion Failure at PageViewEventViewControllerLoggingProtocolTests.swift:79: XCTAssertEqual failed: ("nil") is not equal to ("Optional("testTracking()")")
</details>
<details><summary>:x: XCTest failed: CoreTests/PersistencyTests/testAddToQueue</summary>


    Assertion Failure at PersistencyTests.swift:61: Asynchronous wait failed: Exceeded timeout of 0.5 seconds, with unfulfilled expectations: "expectation".
    Assertion Failure at PersistencyTests.swift:62: XCTAssertEqual failed: ("0") is not equal to ("1")
</details>


[MBL-14832](https://instructure.atlassian.net/browse/MBL-14832)

#### Affected Apps: Student

#### Release Note: 
Make file submission icon color reflect course color.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by vanwagonet — CHANGES_REQUESTED** [review]
seems like it would be much easier to set the tintColor on SubmissionCommentsViewController & then make sure it gets inherited by these icons.

**Comment by Attila-Varga-Instructure** [comment]
> seems like it would be much easier to set the tintColor on SubmissionCommentsViewController & then make sure it gets inherited by these icons.

Nice catch! Actually, tintColor was already set in the view hierarchy, so removing the explicit icon color runtime attribute from the file view xib did the trick.

**Review by vanwagonet — APPROVED** [review]
QA+1

**Pull request merged**
