### PR TITLE
Add script to measure Student app build times

### PR DESCRIPTION
**Pull request by vargaat**
[ignore-commit-lint]

### CODE REVIEW

**Comment by vargaat** [comment]
- 521 sec
- 496 sec
- 575 sec
- 546 sec

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.65% | 91.65% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by szabolcs-instructure** [comment]
- 215 sec
- 194 sec
- 182 sec
- 189 sec
- 186 sec

**Review by szabolcs-instructure — APPROVED** [review]
LGTM! ✅

**Review by davidvarga93 — APPROVED** [review]
506.626 sec

**Review by balintbartok — APPROVED** [review]

**Pull request merged**
