### PR TITLE
Fix Archive swipe action not available after staring a message

### PR DESCRIPTION
**Pull request by Ahmed-Naguib93**
refs: [MBL-17833](https://instructure.atlassian.net/browse/MBL-17833)
affects: Student , Teacher
release note: Fixed archive message swipe action not always available in Inbox

test plan:
See ticket

## Screenshots
https://github.com/user-attachments/assets/bcded85f-b8c1-45b5-a26a-119dacbf4888

https://github.com/user-attachments/assets/e27d57c6-8c96-499c-84a2-58934ddb39a9

## Checklist

- [ ] Tested on phone
- [ ] Tested in dark mode
- [ ] Tested in light mode

[MBL-17833]: https://instructure.atlassian.net/browse/MBL-17833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add a release note. If no release note is wanted, use `none`. Example: `release note: Fixed a bug that prevented users from enjoying the app.`
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student, Teacher

[MBL-17833](https://instructure.atlassian.net/browse/MBL-17833)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.66% | 91.64% | 0.02%
Core/Core/Extensions/UISplitViewControllerExtensions.swift | 23.08% | 23.08% | 0%
Core/Core/Planner/CalendarEvent/Model/API/PostCalendarEventRequest.swift | 0% | 0% | 0%
Core/Core/Extensions/UITabBarControllerExtensions.swift | 0% | 0% | 0%
Core/Core/Extensions/UINavigationControllerExtensions.swift | 0% | 0% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7241c86cee2c61b03eaead9d20f333dc4d96ef02
</p>

**Review by szabinst — DISMISSED** [review]
QA + 1

**Review by rh12 — APPROVED** [review]
Congrats on your first PR! :)
I would have some minor notes about the PR itself, not the code.

Accept the CLA as stated in the comments.

Please name the title using either the ticket naming or just a summary of it, but let it be readable. Like instead of
`Bugfix/MBL-17833-Archive-swipe-action-not-available-after-star-ing-a-message`
something like
`Archive swipe-action not available after staring a message`

The release note will be used in the actual release notes, which have some rules, but in summary: use past tense, add period in the end, make it user-facing, no need to mention the affected app's name.
For example: `Fixed archive message swipe action not always available in Inbox.`

Make sure that when you merge the proper and latest commit description is used (including ref, apps, release note)

Please assign the PR to yourself

**Comment by Ahmed-Naguib93** [comment]
> Congrats on your first PR! :) I would have some minor notes about the PR itself, not the code.
> 
> Accept the CLA as stated in the comments.
> 
> Please name the title using either the ticket naming or just a summary of it, but let it be readable. Like instead of `Bugfix/MBL-17833-Archive-swipe-action-not-available-after-star-ing-a-message` something like `Archive swipe-action not available after staring a message`
> 
> The release note will be used in the actual release notes, which have some rules, but in summary: use past tense, add period in the end, make it user-facing, no need to mention the affected app's name. For example: `Fixed archive message swipe action not always available in Inbox.`
> 
> Make sure that when you merge the proper and latest commit description is used (including ref, apps, release note)
> 
> Please assign the PR to yourself

@rh12 
Thanks for your comment and will do it in next PR

**Comment by rh12** [comment]
@Ahmed-Naguib93 
> Thanks for your comment and will do it in next PR

Please update at least the release note in this one, too ;-)
(you can edit both the title and description, and then copypaste the commit description when you merge)

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
