### PR TITLE
Skip displaying error in case push notifications are not configured.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16520
affects: Student, Teacher
release note: Fixed an error dialog being shown upon app start for institutions where no push notifications are configured.

test plan:
- Log in to the app on an instance that has no push notifications setup (See ticket for credentials).
- No error messages should display on dashboard.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [x] Tested on phone
- [x] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: TeacherTests/AttendanceViewControllerTests/testCourseError</summary>


    XCTAssertEqual failed: ("Optional(true)") is not equal to ("Optional(false)")
</details>


[MBL-16520](https://instructure.atlassian.net/browse/MBL-16520)

#### Affected Apps: Student, Teacher

#### Release Note: 
Fixed an error dialog being shown upon app start for institutions where no push notifications are configured.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by idevainstr — APPROVED** [review]

**Review by szabinst — APPROVED** [review]

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
