### PR TITLE
File module item publish form

### PR DESCRIPTION
**Pull request by vargaat**
### What's new?
- Added new file publish state icons to modules list to match web and the options of the permission dialog.
- Added form to control a file's permissions.

refs: MBL-17355
affects: Teacher
release note: none

test plan:
- Enable experimental feature flag in developer menu.
- Add a file to a module on web.
- Go to modules list and tap the kebab menu on the file's row.
- Check the editor dialog if it correctly prefills with the file's permission values.
- Modify file permissions and check if the displayed icon on the modules list matches the one on web.

## Screenshots

<table>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Teacher

[MBL-17355](https://instructure.atlassian.net/browse/MBL-17355)

<details><summary>:x: XCTest failed: CoreTests/ModuleListViewControllerTests/testSubHeaders</summary>


    XCTAssertEqual failed: ("Optional("I am a sub header, Published")") is not equal to ("Optional("I am a sub header, published")")
    XCTAssertEqual failed: ("Optional("other subheader, Unpublished")") is not equal to ("Optional("other subheader, unpublished")")
</details>
<details><summary>:x: XCTest failed: CoreTests/ModuleListViewControllerTests/testTableViewSort</summary>


    XCTAssertEqual failed: ("Optional("assignment, A1, Unpublished")") is not equal to ("Optional("assignment, A1, unpublished")")
    XCTAssertEqual failed: ("Optional("assignment, B2, Published")") is not equal to ("Optional("assignment, B2, published")")
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 3372aee08c06880bea420d0bbf80116c5f0904c2
</p>

**Review by rh12 — APPROVED** [review]
QA + 1

**Review by ndrsszsz — APPROVED** [review]
QA +1

**Pull request merged**
