### PR TITLE
Offline sync settings interactor

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16666
affects: Student
release note: none

test plan: Check if selected values are restored after app restart and after screen re-opening

## Checklist

- [ ] Follow-up e2e test ticket created
- [x] A11y checked
- [x] Tested on phone
- [ ] Tested on tablet
- [x] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

### CODE REVIEW

**Comment by szabinst** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by idevainstr — DISMISSED** [review]
QA +1

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-16666](https://instructure.atlassian.net/browse/MBL-16666)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.9% | 91.91% | -0.01%
Core/Core/Extensions/PublisherExtensions.swift | 22.73% | 22.73% | 0%
Core/Core/Courses/CourseDetails/ViewModel/CourseDetailsViewModel.swift | 48.89% | 48.89% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b3950c86a16eacd1eaad8dd19e26923948dc833a
</p>

**Review by idevainstr — APPROVED** [review]

**Pull request merged**
