### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by inst-danger**
affects: Parent, Student, Teacher<br/><br/>[ignore-commit-lint]

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/CourseSyncSyllabusInteractorLiveTests/testSuccessfulFetch</summary>


    XCTAssertEqual failed: ("0") is not equal to ("2")
    XCTAssertEqual failed: ("nil") is not equal to ("Optional("1")")
    XCTAssertEqual failed: ("nil") is not equal to ("Optional("2")")
</details>
<details><summary>:x: XCTest failed: StudentUnitTests/AssignmentRemindersInteractorLiveTests/testListsRemindersInChronologicalOrder</summary>


    failed - waitUntil timed out
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 616c985a15b8a242598098681067c5baea7b170f
</p>

**Review by rh12 — APPROVED** [review]

**Pull request merged**
