### PR TITLE
Fix TA enrollment dashboard

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-15277
affects: Student, Teacher
release note: Fixed course cards for TAs

test plan:
Enroll a user as a TA on a course. Check if the course is visible on the dashboard from the teacher app. Student app is not affected.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73218809/p/75c068782523103e7eb462b7f8f80480">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73218817/p/56b766d4a683553c06963048c9bdfcf6">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73218803/p/2b88e1924fb4f430d9142cfc67a6b77d">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.06% | -- | --

[MBL-15277](https://instructure.atlassian.net/browse/MBL-15277)

#### Affected Apps: Student, Teacher

#### Release Note: 
Fixed course cards for TAs
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
