### PR TITLE
Fix a11y for new todo item screen

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-15107
affects: Student
release note: none

test plan:
in the calendar add a new to do item, and test the view for a11y

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.06% | 92.07% | -0.01%

[MBL-15107](https://instructure.atlassian.net/browse/MBL-15107)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/72088973/p/7495efb381dc579e84f54e44786909ec">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/72088996/p/cf9cd0b270bf13d1d53f9c8ef98c18a4">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/72088910/p/16f9e5e06a766854fb1934321723045b">
    
  </a>
</details>

**Review by vargaat — DISMISSED** [review]
QA+1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
