### PR TITLE
Remove tableview header and footer re-set to avoid infinite cycle.

### PR DESCRIPTION
**Pull request by vargaat**
This change removes a hack from ListBackgroundView that causes an infinite layout cycle in some cases. This view is used on a lot of other places in the app so I marked all apps as affected. When testing please also take a look on these pages if the layout is still ok.

- Conferences
- Announcements
- Discussions
- Files
- Grades
- Modules
- Pages
- Peoples
- Calendar Filter
- Quizzes
- ToDos
- CourseList
- Students (parent app only)
- Alerts (parent app only)
- Submissions (teacher app only)

refs: MBL-16703
affects: Student, Teacher, Parent
release note: Fixed a crash on app start when landing page is set to the ToDo tab.

test plan:
- Use an iPhone with notch and iOS 16.
- Start the teacher app.
- Set the landing page to the ToDo tab.
- Restart the app.
- Check layout on affected pages.

## Checklist

- [x] Tested on phone
- [x] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Release Note: 
Fixed a crash on app start when landing page is set to the ToDo tab.

#### Affected Apps: Student, Teacher, Parent

[MBL-16703](https://instructure.atlassian.net/browse/MBL-16703)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92% | 92% | 0%
Core/Core/Courses/CourseDetails/ViewModel/CourseDetailsViewModel.swift | 48.89% | 48.89% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8c7cf6f1eb940d289fc1af8292365df7eac10218
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
