### PR TITLE
Fix module item locking

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15405
affects: Student
release note: Fixed module item locking.
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/ModuleListViewControllerTests/testLockedForUserNotDisabledWhenVisibleWhenLocked</summary>


    Assertion Failure at ModuleListViewControllerTests.swift:184: XCTAssertTrue failed
    Assertion Failure at ModuleListViewControllerTests.swift:185: XCTAssertTrue failed
</details>
<details><summary>:x: XCTest failed: CoreTests/ModuleListViewControllerTests/testSubHeaders</summary>


    Assertion Failure at ModuleListViewControllerTests.swift:374: XCTAssertFalse failed
</details>


[MBL-15405](https://instructure.atlassian.net/browse/MBL-15405)

#### Affected Apps: Student

#### Release Note: 
Fixed module item locking.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/76235134/p/f7532bb00b4b5642a7ca5c64ec8eb44c">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/76235141/p/2b6b15240b021446659b090537f9dd78">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/76235124/p/10808e1bbbc3f608c88773e06f43be2a">
    
  </a>
</details>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Review by vargaat — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]

**Pull request merged**
