### PR TITLE
Add accessible paging mechanism to homeroom schedule

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15572
affects: Student
release note: Added week change buttons to homeroom schedule screen.

test plan: K5 schedule page should show buttons to change week.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/90651664/p/6c67165b42463b50b6baee22ea200fe5">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/90651667/p/75447dafa59bdbf016c50b13ae2dd933">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/90651657/p/371feedd26515beac6c7f45bb0e645b0">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.84% | 91.86% | -0.02%

[MBL-15572](https://instructure.atlassian.net/browse/MBL-15572)

#### Affected Apps: Student

#### Release Note: 
Added week change buttons to homeroom schedule screen.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
