### PR TITLE
Fix K5 dashboard not resizing to full screen when tab bar icon is tapped

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15553
affects: Student
release note: none

test plan:
- Launch the app on iPad or a landscape capable iPhone with a K5 account.
- Enter Course > Assignment.
- Note that assignment details are visible on the right side of the split view.
- Tap on the Homeroom icon on the bottom tab bar.
- K5 dashboard should resize to full screen.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/90061676/p/30765e6d1026b1b168b9fa851ec3e5a1">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/90061699/p/e4d0d0a66b6b5eb28743ec11dd58e362">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/90061644/p/212b3cf588d8a603fc6e36ca7c884bfd">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.86% | 91.86% | 0%

[MBL-15553](https://instructure.atlassian.net/browse/MBL-15553)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
