### PR TITLE
Clear failed offline progress upon dismissing dashboard notification

### PR DESCRIPTION
**Pull request by szabinst**
refs: MBL-17224
affects: Student
release note: Failed offline sync banner on the dashboard won't reappear after closing it.
test plan: See ticket

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] Tested on phone

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Failed offline sync banner on the dashboard won't reappear after closing it.

#### Affected Apps: Student

[MBL-17224](https://instructure.atlassian.net/browse/MBL-17224)

<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/Core/Dashboard/OfflineSync/Model/DashboardOfflineSyncInteractorPreview.swift:49:7: Type Name Violation: Type name 'DashboardOfflineSyncProgressWriterInteractorPreview' should be between 3 and 50 characters long (type_name)
    /Users/vagrant/git/Core/Core/Dashboard/OfflineSync/ViewModel/DashboardOfflineSyncProgressCardViewModel.swift:161:1: error: Trailing Whitespace Violation: Lines should not have trailing whitespace (trailing_whitespace)
    
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ac0349979ddfb3c95dd3107810c59c9298f09165
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by rh12 — APPROVED** [review]

**Review by ndrsszsz — APPROVED** [review]
QA +1

**Pull request merged**
