### PR TITLE
Remove scanner for media recordings

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-15312
affects: Student
release note: Disabled scanner for media recordings

test plan: see ticket (balintbartok sandbox has a media recording upload type assignment)
* scanner should not be available, when user selects media recording
* it should be available for file uploads as before

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Danger failed to run `dangerfile.js`.
  </td>
    </tr>
  </tbody>
</table>



## Error Error
```
Cannot find module 'commander'
Require stack:
- /Users/vagrant/git/scripts/update-headers.js
- dangerfile.js
- /snapshot/danger-js/distribution/runner/runners/inline.js
- /snapshot/danger-js/distribution/commands/danger-runner.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
Error: Cannot find module 'commander'
Require stack:
- /Users/vagrant/git/scripts/update-headers.js
- dangerfile.js
- /snapshot/danger-js/distribution/runner/runners/inline.js
- /snapshot/danger-js/distribution/commands/danger-runner.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:795:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1287:46)
    at Function.Module._load (internal/modules/cjs/loader.js:688:27)
    at Function._load (/snapshot/danger-js/node_modules/override-require/dist/overrideRequire.js:43:25)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/vagrant/git/scripts/update-headers.js:30:17)
    at Module._compile (internal/modules/cjs/loader.js:957:30)
    at Module._compile (pkg/prelude/bootstrap.js:1222:32)
```
### Dangerfile
```
------------------^
```
  
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8252600ffed4574f2e1112527b0e96167c4d0ba2
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74911990/p/5cf1aa3880617a796d2a570ba04221b4">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74912002/p/3156c33a66779b1a9a3cd1e82da6a2ba">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74911960/p/5ba4f905b77a297be2cb0e2932e53635">
    
  </a>
</details>

**Review by vargaat — APPROVED** [review]

**Comment by vargaat** [comment]
QA+1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
