### PR TITLE
Update Student app icon

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-14115
affects: Student
release note: Updated app icon design

### CODE REVIEW

**Comment by vanwagonet** [comment]
Looks like the gradient is heavy. The new folder 38KB heavier than before. 😞

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/f2xq4w6) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Ff2xq4w6)
teacher: [Link](https://rebrand.ly/sd5gdot) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fsd5gdot)
parent: [Link](https://rebrand.ly/pnd6b6s) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fpnd6b6s)

**Comment by vanwagonet** [comment]
Going to try with a static bg color from Dave. I'll then either update this PR or let you know the gradient will stay.

**Comment by inst-danger** [comment]
#### Release Note: 
Updated app icon design

#### Affected Apps: Student

[MBL-14115](https://instructure.atlassian.net/browse/MBL-14115)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.63% | 93.62% | 0.01%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by vanwagonet** [comment]
Without gradient is only 30KB total. That's 15% of gradient's total size, and 127KB smaller than previous app icon set

**Pull request merged**
