### PR TITLE
Add file upload progress indication to share extension

### PR DESCRIPTION
**Pull request by vargaat**
New upload screen for the share extension. It's built on top of the old upload business logic so there might be still issues with it. Rewriting of that upload code will come next where we'll eliminate all the known issues!

refs: MBL-16143
affects: Student
release note: Added file upload progress screen when submitting files via share extension.

test plan: Upload files with share extension.

<table>
<tr><th>Shared Files Not Compatible With Assignment</th><th>Incompatibility Explanation</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr><th>Uploading...</th><th>Uploading Failed</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr><th>Last File Being Removed From Submission</th><th>Submission Successful!</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr><th>Upload Succeeded But Submission Failed</th><th></th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 90.72% | 91.63% | -0.91%
Core/Core/Files/FileUploadProgress/View/PreviewSupport/FileProgressItemPreview.swift | 0% | -- | --
Core/Core/Files/FileUploadProgress/View/FileProgressListViewModelProtocol.swift | 33.33% | -- | --
Core/Core/Files/FileUploadProgress/View/PreviewSupport/FileProgressListViewPreview.swift | 0% | -- | --

[MBL-16143](https://instructure.atlassian.net/browse/MBL-16143)

#### Affected Apps: Student

#### Release Note: 
Added file upload progress screen when submitting files via share extension.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by idevainstr — DISMISSED** [review]
QA+1 🏅

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by szabolcs-instructure — APPROVED** [review]
QA + 1

**Pull request merged**
