### PR TITLE
Update PSPDFKit

### PR DESCRIPTION
**Pull request by vargaat**
- Update pod dependency.
- Update custom drag icon to match new button style.
- Fix annotation z order.

refs: MBL-16246
affects: Student, Teacher
release note: none

test plan: Test if student / teacher annotations still work.

## Checklist

- [x] Tested on phone
- [x] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


<details><summary>:x: XCTest failed: CoreTests/CircleRefreshControlTests/testRefresh</summary>


    Assertion Failure at CircleRefreshControlTests.swift:57: XCTAssertEqual failed: ("false") is not equal to ("true")
    Assertion Failure at CircleRefreshControlTests.swift:58: XCTAssertEqual failed: ("true") is not equal to ("false")
    Assertion Failure at CircleRefreshControlTests.swift:59: XCTAssertEqual failed: ("true") is not equal to ("false")
    Assertion Failure at CircleRefreshControlTests.swift:62: XCTAssertEqual failed: ("false") is not equal to ("true")
    Assertion Failure at CircleRefreshControlTests.swift:63: XCTAssertEqual failed: ("true") is not equal to ("false")
    Assertion Failure at CircleRefreshControlTests.swift:64: XCTAssertEqual failed: ("true") is not equal to ("false")
</details>
<details><summary>:x: XCTest failed: CoreTests/DocViewerAnnotationProviderTests/testAddEmpty</summary>


    Uncaught Exception at DocViewerAnnotationProviderTests.swift:124: XCTAssertEqual failed: throwing "documentProvider must be set on annotation to create a core annotation"
</details>
<details><summary>:x: XCTest failed: CoreTests/DocViewerAnnotationProviderTests/testAddNoData</summary>


    Uncaught Exception at DocViewerAnnotationProviderTests.swift:104: XCTAssertEqual failed: throwing "documentProvider must be set on annotation to create a core annotation"
    Assertion Failure at DocViewerAnnotationProviderTests.swift:105: XCTAssertEqual failed: ("nil") is not equal to ("Optional(Core.APIDocViewerError.noData)")
</details>
<details><summary>:x: XCTest failed: CoreTests/DocViewerAnnotationProviderTests/testAddSuccess</summary>


    Uncaught Exception at DocViewerAnnotationProviderTests.swift:140: XCTAssertEqual failed: throwing "documentProvider must be set on annotation to create a core annotation"
</details>
<details><summary>:x: XCTest failed: CoreTests/DocViewerAnnotationProviderTests/testAddTooBig</summary>


    Uncaught Exception at DocViewerAnnotationProviderTests.swift:114: XCTAssertEqual failed: throwing "documentProvider must be set on annotation to create a core annotation"
    Assertion Failure at DocViewerAnnotationProviderTests.swift:115: XCTAssertEqual failed: ("nil") is not equal to ("Optional(Core.APIDocViewerAnnotation(id: "89992A4D-7AE2-4477-8896-CF8ED0E13BE1", document_id: nil, user_id: nil, user_name: "", page: 0, created_at: Optional(2022-10-11 07:35:51 +0000), modified_at: nil, deleted: Optional(false), deleted_at: nil, deleted_by: nil, deleted_by_id: nil, type: Core.APIDocViewerAnnotationType.text, color: Optional("#000000"), bgColor: Optional("transparent"), icon: Optional("Comment"), contents: nil, inreplyto: nil, coords: nil, rect: Optional([[0.0, 0.0], [0.0, 0.0]]), font: nil, inklist: nil, width: Optional(0.0)))")
</details>
<details><summary>:x: XCTest failed: CoreTests/DocViewerAnnotationProviderTests/testAddUnsupported</summary>


    Uncaught Exception at DocViewerAnnotationProviderTests.swift:131: XCTAssertEqual failed: throwing "documentProvider must be set on annotation to create a core annotation"
</details>


[MBL-16246](https://instructure.atlassian.net/browse/MBL-16246)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by szabolcs-instructure — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
