### PR TITLE
Update file upload API for self-hosted institutions

### PR DESCRIPTION
**Pull request by vargaat**
- Update file upload API to work with uppercase parameter name in file upload target response.
- Increase rate-limit timeout to avoid API requests being retried in an infinite cycle.

refs: MBL-16697
affects: Student, Teacher
release note: Fixed Inbox attachments not uploaded correctly on some self-hosted instances.

test plan: Test if file attachments from inbox upload correctly on the account in the ticket and on a regular canvas-hosted account.

## Checklist

- [ ] Tested on phone
- [ ] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Release Note: 
Fixed Inbox attachments not uploaded correctly on some self-hosted instances.

#### Affected Apps: Student, Teacher

[MBL-16697](https://instructure.atlassian.net/browse/MBL-16697)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.96% | 91.95% | 0.01%
Core/Core/Extensions/PublisherExtensions.swift | 22.73% | 22.73% | 0%
Core/Core/Courses/CourseDetails/ViewModel/CourseDetailsViewModel.swift | 48.89% | 48.89% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 28afe304440ebc79d21bf0ced06a3e5224df48ef
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA +1

**Pull request merged**
