### PR TITLE
Offline sync success feedback

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-17065
affects: Student
release note: none

test plan:
- Successfully finish an offline sync while the sync progress page is on screen.
- State at the top of the screen should be communicated.
- Successfully finish an offline sync while the sync progress page is not on screen.
- Local notification about the sync success should arrive.

## Screenshots

<table>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [x] Tested on phone
- [ ] Tested on tablet
- [x] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-17065](https://instructure.atlassian.net/browse/MBL-17065)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.41% | 92.41% | 0.01%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 051310e7ad213a6c33e35db66a62b3e9df52b131
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by ndrsszsz — APPROVED** [review]
QA +1

**Pull request merged**
