### PR TITLE
Add Store and UseCase improvements

### PR DESCRIPTION
**Pull request by armstrongnate**
[ignore-commit-lint]

### CODE REVIEW

**Comment by vanwagonet** [comment]
This looks pretty good. I sounded like you had some more changes you wanted to add to it, though.

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Core** | 91.07% | 90.44% | 0.63%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Student** | 93.12% | 93.12% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by vanwagonet** [comment]
since the build was updated to be on push instead of pr, I can't retrigger the failing build. Please push again to get the lastest builds.

**Pull request merged**
