### PR TITLE
Fix split view bugs

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBl-13352
affects: student
release note: Fixed layout issues with split view on iPad

* Trying to avoid `targetDisplayModeForAction`. It doesn't seem like we need to implement it and it's called 8 times on rotation on iOS 13. Who wants all that noise.
* Consolidating to one UISplitViewController subclass so that we don't have to maintain two
* Fixed some cases where displayModeButtonItem was not showing up when it should
* Call super in a few `viewWillTransition(to:coordinator:)` overrides because docs say to

**Test plan:**
* Tap around with iPad, expanding and collapsing split view
* Expand/collapse button should persist across navigation
* Enable and disable side-by-side and tap around the student app on iPad

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1007776&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by inst-danger** [comment]
#### Release Note: 
Fixed layout issues with split view on iPad

#### Affected Apps: Student

[MBL-13352](https://instructure.atlassian.net/browse/MBL-13352)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.36% | 93.35% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by armstrongnate** [comment]
@bluwave I had to merge conflicts.

**Pull request merged**
