### PR TITLE
Offline Discussions

### PR DESCRIPTION
**Pull request by szabinst**
refs: MBL-16771
affects: Student
release note: none
test plan: See ticket

## Checklist

- [x] Tested on phone
- [x] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-16771](https://instructure.atlassian.net/browse/MBL-16771)

<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncDiscussionsInteractorLiveTests.swift:62:18: Trailing Comma Violation: Multi-line collection literals should have trailing commas (trailing_comma)
    /Users/vagrant/git/Core/Core/CourseSync/CourseSyncDownloader/CourseSyncDownloaderAssembly.swift:32:50: error: Trailing Comma Violation: Multi-line collection literals should have trailing commas (trailing_comma)
    /Users/vagrant/git/Core/Core/Contexts/TabName.swift:47:21: error: Trailing Comma Violation: Multi-line collection literals should have trailing commas (trailing_comma)
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d1fdc2ab9c4eef61e4de5d77663c6ea669ea4407
</p>

**Review by vargaat — CHANGES_REQUESTED** [review]
I noticed that the attachment icon is still active and results in an error when tapped. Let's disable that one as well in offline mode.

<table>
<tr>
<td></td>
<td></td>
</tr>
</table>

**Comment by szabinst** [comment]
@vargaat fixed the attachment button being available while offline.

**Review by vargaat — DISMISSED** [review]
QA+1

**Review by vargaat — DISMISSED** [review]

**Comment by cha0uki** [comment]
Merge shouldn't be blocked...

**Review by idevainstr — APPROVED** [review]
QA +1

**Pull request merged**
