### PR TITLE
Integrate offline mode feature flag

### PR DESCRIPTION
**Pull request by vargaat**
- Removed the experimental feature flag.
- Added the flag to the environment flags API response and to CoreData.
- Modified OfflineModeInteractorLive to observe flag changes in CoreData.
- Created a model group in the Offline folder for the interactors.
- Moved from OfflineModeInteractorLive.shared to an assembly based solution. 

refs: MBL-16772
affects: Student
release note: none

test plan:
- Feature flag set on web should be reflected in the app.
- Experimental feature flag from developer menu shouldn't be visible.

## Screenshots

On this screen recording we can see that when a delayed feature flag API response arrives the feature flag state is applied and the dashboard updates accordingly.

https://github.com/instructure/canvas-ios/assets/72396990/3a57f8ee-ab6a-4cee-9f4e-8d395e8b7afc

## Checklist

- [x] Tested on phone
- [ ] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-16772](https://instructure.atlassian.net/browse/MBL-16772)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.36% | 92.4% | -0.04%
Core/Core/Offline/Model/OfflineModeInteractorDummy.swift | 20% | -- | --
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f32f4a77c346c82278689ce1af9cd90dc3a788e9
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA +1

**Pull request merged**
