### PR TITLE
Support disabling the syllabus summary view

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-13804
affects: Student, Parent
release note: Added support to hide the summary list on syllabus

### CODE REVIEW

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/bifmq1v) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fbifmq1v)
teacher: [Link](https://rebrand.ly/i3qhmmn) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fi3qhmmn)
parent: [Link](https://rebrand.ly/1g5mi7p) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2F1g5mi7p)

**Comment by inst-danger** [comment]
#### Release Note: 
Added support to hide the summary list on syllabus

#### Affected Apps: Student, Parent

[MBL-13804](https://instructure.atlassian.net/browse/MBL-13804)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.19% | 93.19% | 0.01%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by vanwagonet** [comment]
> The summary still shows in the parent app with the flag enabled. I deleted the app first to make sure the cache got cleared. Does Parent use its own syllabus vc that needs updated?

It does. It was. & unit tested. Can you give more specific on how to repro?

**Comment by armstrongnate** [comment]
I see, Parent/CourseDetailsViewController. narmstrong > o > CS 1400. I have the summary set to hidden but it's still showing. maybe I'm doing something wrong. I'll try again in a bit.

**Pull request merged**
