### PR TITLE
Add grades e2e test for teacher

### PR DESCRIPTION
**Pull request by davidvarga93**
refs: MBL-15508
affects: Teacher
release note: none

test plan:

### CODE REVIEW

**Comment by davidvarga93** [comment]
Nightly tests:
https://app.bitrise.io/build/cc595bdd-b6ea-47f2-86f6-1541f39d3440#?tab=log

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/81263666/p/ef29ecf357962e9d8d53ad924e4f50c8">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/81263698/p/fa5eb7c6c67790027bb587efa1acb6d9">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/81263646/p/24ba857f96e87cfcfaf72bb335fed8dc">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.97% | 91.98% | -0.02%

[MBL-15508](https://instructure.atlassian.net/browse/MBL-15508)

#### Affected Apps: Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by davidvarga93** [comment]
Screenshot 2021-07-01 at 13 32 31

**Review by vargaat — APPROVED** [review]
```
GradesE2ETests
    ✔ testGradesE2E (17.677 seconds)
```

**Pull request merged**
