### PR TITLE
Native assignments list

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-14857
affects: Student, Teacher
release note: none
test plan: Compare Assignment list with old version in both apps

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


<details><summary>:x: Yarn lint</summary>


    
    /Users/vagrant/git/rn/Teacher/src/routing/register-screens.js
      23:8  error  'AssignmentList' is defined but never used  no-unused-vars
    
    ✖ 1 problem (1 error, 0 warnings)
    
</details>


[MBL-14857](https://instructure.atlassian.net/browse/MBL-14857)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/110677714/p/208f0aebdf7e0fbdc1bedbb4bb5688f2">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/110677744/p/75a7646bbf211ce6ba9da60c7bebf91e">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/110677643/p/4b133f2d26e9e943f1d396e62b47e08f">
    
  </a>
</details>

**Review by balintbartok — DISMISSED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
