### PR TITLE
Filter out invalid help item links

### PR DESCRIPTION
**Pull request by ndrsszsz**
affects: Student, Teacher, Parent
release note: None
test plan: See ticket

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student, Teacher, Parent

[MBL-17943](https://instructure.atlassian.net/browse/MBL-17943)

<details><summary>:x: XCTest failed: CoreTests/SyllabusSummaryViewControllerTests/testLayout</summary>


    failed - waitUntil timed out
    XCTAssertEqual failed: ("nil") is not equal to ("Optional("assignment")")
    XCTAssertEqual failed: ("Optional(<UIImage:0x600007117180 named(com.instructure.icanvas.Core: calendarMonthLine) {24, 24} renderingMode=alwaysTemplate>)") is not equal to ("Optional(<UIImage:0x6000031f46c0 named(com.instructure.icanvas.Core: assignmentLine) {24, 24} renderingMode=alwaysTemplate>)")
    XCTAssertEqual failed: ("Optional("No Due Date")") is not equal to ("Optional("Feb 12, 2020 at 12:00 AM")")
    XCTAssertEqual failed: ("nil") is not equal to ("Optional("event")")
    XCTAssertEqual failed: ("Optional("No Due Date")") is not equal to ("Optional("Feb 13, 2020 at 12:00 AM")")
    XCTAssertEqual failed: ("nil") is not equal to ("Optional("nil date")")
    XCTAssertEqual failed: ("Optional(<UIImage:0x600007117180 named(com.instructure.icanvas.Core: calendarMonthLine) {24, 24} renderingMode=alwaysTemplate>)") is not equal to ("Optional(<UIImage:0x6000031f46c0 named(com.instructure.icanvas.Core: assignmentLine) {24, 24} renderingMode=alwaysTemplate>)")
    XCTAssertTrue failed
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f5035b0c195271a941c4977c9f8e65b1f24d0be1
</p>

**Review by rh12 — APPROVED** [review]
QA + 1

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
