### PR TITLE
Fix pages image upload

### PR DESCRIPTION
**Pull request by szabinst**
refs: MBL-16540
affects: Student, Teacher
release note: Fixed an issue where image upload was not possible on Pages

test plan: See ticket

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [x] Tested on phone
- [x] Tested on tablet
- [x] Tested in dark mode
- [x] Tested in light mode
- [ ] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.88% | 91.89% | -0.01%
Core/Core/Courses/CourseDetails/ViewModel/CourseDetailsViewModel.swift | 48.89% | 48.89% | 0%

[MBL-16540](https://instructure.atlassian.net/browse/MBL-16540)

#### Affected Apps: Student, Teacher

#### Release Note: 
Fixed an issue where image upload was not possible on Pages
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by idevainstr — DISMISSED** [review]
QA +1

**Pull request merged**
