### PR TITLE
Optimize UI tests (for xcuitest)

### PR DESCRIPTION
**Pull request by armstrongnate**
[ignore-commit-lint]

We don't want to wait for things that are not visible/enabled to be
not visible/enabled because we end up waiting the entire duration.

Relies on https://github.com/instructure/SwiftUITest/pull/5

### CODE REVIEW

**Comment by vanwagonet** [comment]
Did this make a significant impact on the speed when using the XCUITest driver? I'm wondering if rather than making `*Now` properties, if we just always want this behavior. It may be a little more effort in a test case to have explicit waits for things, but those are already in our tests.

The typical pattern is `setup -> wait -> assert+ (-> action -> wait -> assert+)*`.

**Comment by armstrongnate** [comment]
@vanwagonet Yes, it made a significant impact on the speed of the xcuitest driver. I noticed that XCUITest does not wait the full timeout in `waitForExistence` so its use is not a performance issue. The problem was that we were waiting for something that doesn't exist to not exist.. which would cause `waitForExistence` to wait the entire timeout.

I agree that removing all the waits from SwiftUITest might be the direction that we want to go but I don't think it's pressing since `waitForExistence` is optimized to bail as soon as it discovers the element exists.

We might find that having the waits in SwiftUITest is convenient, especially with live data. TBD. We might very well soon decide to switch to the model you described. For now, this is a small step toward optimization.

**Comment by armstrongnate** [comment]
I'm perfectly fine with not merging this until all of my research is done and we decide on a direction. I mostly didn't want these changes to get lost. But it isn't much and is subject to change.

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Core** | 95.04% | 95.04% | 0%
**Student** | 92.34% | 92.34% | 0%
**Teacher** | 100% | 100% | 0%
**React Native** | 92.71% | 92.71% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Pull request merged**
