### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by inst-danger**
affects: Parent, Student, Teacher<br/><br/>[ignore-commit-lint]

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.82% | 91.81% | 0.01%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f2f72e8ff4ce7a2619b643b27e1c553292d86c9d
</p>

**Review by vargaat — APPROVED** [review]

**Pull request merged**
