### PR TITLE
Show media from media comment in the Inbox

### PR DESCRIPTION
**Pull request by Ahmed-Naguib93**
refs: [MBL-17959](https://instructure.atlassian.net/browse/MBL-17959)
affects: Teacher, Student
release note: Show media from media comment in the Inbox

### Test plan:
 - Open your account as a teacher or student from the web.
 - Go through your inbox.
 - Try to add a media comment, such as a video or audio.
 - Open the iOS app and go through your inbox to access the media.
 
### Please Note
 - I've tried to play the media inside the app, but i've seen the url got from  "mediaComment" is totally different and can't get the file id. 
 - In my opinion, we should create a new ticket to develop a new media player that can handle this URL, instead of applying a workaround to the current player, which is already very large.

## Screenshots
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>

<tr>
<td></td>
<td></td>
</tr>

<tr>
<td></td>
<td></td>
</tr>

</table>

https://github.com/user-attachments/assets/a4dc82cc-2f3f-4e53-ad18-7d405490d696

## Checklist
- [ ] Tested on phone
- [ ] Tested in light mode

[MBL-17959]: https://instructure.atlassian.net/browse/MBL-17959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Show media from media comment in the Inbox

#### Affected Apps: Teacher, Student

[MBL-17959](https://instructure.atlassian.net/browse/MBL-17959)

<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/Core/Inbox/MessageDetails/ViewModel/MessageViewModel.swift:71:45: Comma Spacing Violation: There should be no space before and one after any comma (comma)
    
    
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 96e9e0952a8c80976d85e50845b4186baca01709
</p>

**Comment by suhaibabsi-inst** [comment]
QA + 1

https://github.com/user-attachments/assets/078c729a-6f0f-4264-b446-f0ade59e5cae

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
