### PR TITLE
Fix non-canvas urls opening native screens if the path matches a valid route in the app.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16427
affects: Student, Teacher, Parent
release note: Fixed some external website urls opening in-app screens instead of the actual url.

test plan:
- See ticket for test data.
- From now on all external http(s) urls passed to the router will open a modal webview with the contents of that url.

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [x] A11y checked
- [x] Tested on phone
- [ ] Tested on tablet
- [x] Tested in dark mode
- [x] Tested in light mode
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: StudentUnitTests/RoutesTests/testFallbackAbsoluteHTTPs</summary>


    XCTAssertEqual failed: ("nil") is not equal to ("Optional(https://instructure.com)")
</details>
<details><summary>:x: XCTest failed: StudentUnitTests/RoutesTests/testFallbackAuthenticatedError</summary>


    XCTAssertEqual failed: ("nil") is not equal to ("Optional(https://google.com)")
</details>


[MBL-16427](https://instructure.atlassian.net/browse/MBL-16427)

#### Affected Apps: Student, Teacher, Parent

#### Release Note: 
Fixed some external website urls opening in-app screens instead of the actual url.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by szabinst — APPROVED** [review]
QA + 1

**Pull request merged**
