### PR TITLE
Fix Empty state on Dashboard screen

### PR DESCRIPTION
**Pull request by domonkosadam**
refs: MBL-17487
affects: Teacher, Student
release note: none
test plan: See ticket

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Teacher, Student

[MBL-17487](https://instructure.atlassian.net/browse/MBL-17487)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.46% | 91.45% | 0.01%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against dd2093506fe1c7a697f36a6b35fb161ad9150353
</p>

**Review by vargaat — CHANGES_REQUESTED** [review]

**Review by vargaat — APPROVED** [review]
QA+1

**Review by ndrsszsz — APPROVED** [review]
QA +1
Tested on iPhone 11, iOS 17.5.1

**Pull request merged**
