### PR TITLE
Fix bug preventing new courses from showing in the app

### PR DESCRIPTION
**Pull request by shichongrui**
refs: MBL-13751
affects: student
release note: Fixed a bug preventing new courses from showing in the dashboard

Test Plan:
 - See ticket for repro steps

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1017575&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|23
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Fixed a bug preventing new courses from showing in the dashboard

#### Affected Apps: Student

[MBL-13751](https://instructure.atlassian.net/browse/MBL-13751)

<details><summary>:x: Yarn lint</summary>


    
    /Users/vagrant/git/rn/Teacher/src/modules/courses/__tests__/courses-reducer.test.js
      108:1   error  Expected indentation of 8 spaces but found 6   indent
      109:1   error  Expected indentation of 10 spaces but found 8  indent
      110:1   error  Expected indentation of 10 spaces but found 8  indent
      111:1   error  Expected indentation of 8 spaces but found 6   indent
      112:1   error  Expected indentation of 8 spaces but found 6   indent
      113:1   error  Expected indentation of 10 spaces but found 8  indent
      114:1   error  Expected indentation of 10 spaces but found 8  indent
      115:1   error  Expected indentation of 8 spaces but found 6   indent
      115:8   error  Missing trailing comma                         comma-dangle
      116:1   error  Expected indentation of 6 spaces but found 4   indent
      134:41  error  Missing trailing comma                         comma-dangle
      141:86  error  Missing trailing comma                         comma-dangle
      142:8   error  Missing trailing comma                         comma-dangle
    
    ✖ 13 problems (13 errors, 0 warnings)
      13 errors and 0 warnings potentially fixable with the `--fix` option.
    
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by cobbal** [comment]
QA +1

**Pull request merged**
