### PR TITLE
Fix parsing of quiz submission response so extra time on quiz shows up

### PR DESCRIPTION
**Pull request by bluwave**
refs: MBL-14217
affects: Student
release note: Fixed bug on quizzes so extra time will be shown.

### CODE REVIEW

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/q640hcm) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fq640hcm)
teacher: [Link](https://rebrand.ly/ift1r0w) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fift1r0w)
parent: [Link](https://rebrand.ly/my19r97) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fmy19r97)

**Comment by inst-danger** [comment]
#### Release Note: 
Fixed bug on quizzes so extra time will be shown.

#### Affected Apps: Student

[MBL-14217](https://instructure.atlassian.net/browse/MBL-14217)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.59% | 93.59% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by bluwave** [comment]
@vanwagonet that property was parsed as part of an `if let` before, so if that `attempts` property was missing the object is nil it did not drop in to create the object.

**Comment by vanwagonet** [comment]
Thanks for the explanation. That makes sense.

**Pull request merged**
