### PR TITLE
Support disabled modules list

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBL-14712
affects: student
release note: Fixed a bug that would allow access to the modules list when it was disabled

test plan:
- see ticket for an example of modules being disabled
- narmstrong > s > CS 1400 > Should be able to access modules from Home page
- Should be able to access Modules from a regular course tab

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/ModuleListViewControllerTests/testError</summary>


    Assertion Failure: ModuleListViewControllerTests.swift:189: XCTAssertEqual failed: ("Optional("There was an error loading modules.")") is not equal to ("Optional("There was an error loading modules. Pull to refresh to try again.")")
</details>


[MBL-14712](https://instructure.atlassian.net/browse/MBL-14712)

#### Affected Apps: Student

#### Release Note: 
Fixed a bug that would allow access to the modules list when it was disabled
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/49999940/p/86c914e0ba6a41decd15dd3d3cbd186f">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/49999945/p/43253aaebc23d051d830fa25906dc35f">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/49999913/p/bbd476ccd010f259fbe30493e38c0755">
    
  </a>
</details>

**Review by cobbal — CHANGES_REQUESTED** [review]
I get a flash of "this page disabled" from your course when the cache is empty.

**Review by cobbal — APPROVED** [review]
QA+1

**Pull request merged**
