### PR TITLE
Fix elementary theme opening when course is non-elementary

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15935
affects: Student
release note: Fixed elementary subject view being shown instead of the regular course home.

test plan: See ticket.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/ae92fd0c-f57f-4cf2-841a-dd12445e0f5c/artifact/6e145742979b57a4/p/b36a81cddfd3707111a7155402422429">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/ae92fd0c-f57f-4cf2-841a-dd12445e0f5c/artifact/5aa1f4bd62a28d55/p/77025ce3c52152b597486865ea989362">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/ae92fd0c-f57f-4cf2-841a-dd12445e0f5c/artifact/18a3fd26f17ac916/p/cf3d057acd6460883e2137fc6f07c64b">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.49% | 91.46% | 0.03%

[MBL-15935](https://instructure.atlassian.net/browse/MBL-15935)

#### Affected Apps: Student

#### Release Note: 
Fixed elementary subject view being shown instead of the regular course home.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — DISMISSED** [review]
QA + 1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by idevainstr — DISMISSED** [review]
QA+1

**Review by idevainstr — DISMISSED** [review]

**Review by balintbartok — APPROVED** [review]

**Review by idevainstr — APPROVED** [review]

**Pull request merged**
