### PR TITLE
CanvadocViewer -> DocViewer

### PR DESCRIPTION
**Pull request by vanwagonet**
extra: rework SubmissionViewer to display more file uploads

refs: MBL-14654
affects: Teacher
release note: Fixed viewing some online upload submissions

### CODE REVIEW

**Comment by vanwagonet** [comment]
Test plan:
- in Student app check that PDF submissions still load without the toolbar or saving header.
- in Teacher app check that PDF submissions load like they did prior to this change.
- in Teacher app check other submission types to see that they look good.
twilson / teacher1 > Assignment Grades > Lots of submission types
has many submissions from student1 to try out. (Previously audio & video sent to online_upload would fail in PSPDFViewController, now should display an AVPlayerViewController)

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/wxc1eyr) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fwxc1eyr)
teacher: [Link](https://rebrand.ly/xn6sre7) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fxn6sre7)
parent: [Link](https://rebrand.ly/72i3q5i) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2F72i3q5i)

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



[MBL-14654](https://instructure.atlassian.net/browse/MBL-14654)

#### Affected Apps: Teacher

#### Release Note: 
Fixed viewing some online upload submissions
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by armstrongnate** [comment]
Video of highlight and strikethrough error in teacher app.

[RPReplay_Final1598388499.MP4.zip](https://github.com/instructure/canvas-ios/files/5126219/RPReplay_Final1598388499.MP4.zip)

It does not error on master but I did notice that on master the highlight does not have the correct opacity when viewed on web. Below is a screenshot of a highlight made on master. Can we make sure highlights are correct?

image

**Comment by vanwagonet** [comment]
I cannot get the highlighter to work correctly even in web & master. web just always shows it will full opacity. I did fix the error you were seeing.

**Pull request merged**
