### PR TITLE
Add custom back button to discussion sections picker.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15556
affects: Student, Teacher
release note: none

test plan: See ticket.

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by vargaat** [comment]
It seems like that the default back button generated by UINavigationController while embedding SwiftUI views has some bugs. It actually generates two back buttons, one with the < icon, which actually works and another one with the title of the previous view controller's title which does nothing just disappears after tap.

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/88322729/p/2470f6e96338227a741b710cca0b70b4">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/88322743/p/c3b0513789be1a110c00764dec8a2a07">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/88322711/p/17bcd1024fe9805465a6fa8164c16af7">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.85% | 91.85% | 0%

[MBL-15556](https://instructure.atlassian.net/browse/MBL-15556)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Comment by idevainstr** [comment]
On appear the back button with title text gets replaced by the simple back button.

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
