### PR TITLE
remove userID and domain from crashlytics reports

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-16187
affects: Student, Teacher, Parent
release note: none
test plan: check if everything works

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.63% | 91.63% | -0%

[MBL-16187](https://instructure.atlassian.net/browse/MBL-16187)

#### Affected Apps: Student, Teacher, Parent
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by idevainstr — APPROVED** [review]

**Pull request merged**
