### PR TITLE
Fix audio comment test

### PR DESCRIPTION
**Pull request by vanwagonet**
There were already lots of good tests for commenting.

refs: MBL-12799
affects: none
release note: none

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1004109&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by armstrongnate** [comment]
Still failed on bitrise 😭

**Comment by vanwagonet** [comment]
It passes for me when the permission alert has already been handled, but I can't get `allowAccessToMicrophone` to work reliably anymore, so we should just leave this test disabled.

**Pull request closed without merging**
