### PR TITLE
Fix pull to refresh circle not disappearing when syllabus is empty.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16300
affects: Student, Teacher
release note: none

test plan: See ticket.

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] A11y checked
- [x] Tested on phone
- [x] Tested on tablet
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Review by szabolcs-instructure — DISMISSED** [review]
QA + 1

**Review by vargaat — COMMENTED** [review]
QA+1

**Review by szabolcs-instructure — APPROVED** [review]

**Pull request merged**
