### PR TITLE
Write tests for TextSubmission & RichContentEditor

### PR DESCRIPTION
**Pull request by vanwagonet**
Move presenter into controller since controller is now tested

extra: simplify ErrorViewController protocol & use router.show
extra: remove some unused categories

refs: MBL-13505
affects: Student
release note: none

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1010698&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-13505](https://instructure.atlassian.net/browse/MBL-13505)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.14% | 93.28% | -0.14%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by vanwagonet** [comment]
One of the new test cases flaked, & I haven't yet been able to repro locally.

**Comment by vanwagonet** [comment]
Looks like a different test flaked on bitrise. 😢

**Pull request merged**
