### PR TITLE
Disable unavailable UI elements when offline

### PR DESCRIPTION
**Pull request by vargaat**
### What changed?
This PR disables / removes buttons leading to features/actions not available in offline mode:
1. Disabled unavailable tab bar buttons.
2. Disabled unavailable profile setting buttons including profile image change.
3. Disabled unavailable app settings rows.
4. Disabled customize course on dashboard course cards.
5. Disabled conference tap action on dashboard.
6. Disabled accept / decline of course invitations.
7. Hid course home tab for now as it may lead to not synced course tabs.

refs: MBL-16774
affects: Student
release note: none
test plan: Check if there are any elements enabled which unavailable in offline mode.

## Checklist

- [ ] Tested on phone
- [x] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-16774](https://instructure.atlassian.net/browse/MBL-16774)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9c5f40b830d8c0d24b05f9df5bef11be2fb23165
</p>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by balintbartok — DISMISSED** [review]
QA + 1

**Review by szabinst — APPROVED** [review]
QA + 1

**Pull request merged**
