### PR TITLE
Fix loading cross-trust observer enrollments

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-14754
affects: Parent
release note: Fixed an issue with missing observed students

### CODE REVIEW

**Comment by vanwagonet** [comment]
Test Plan: See ticket. Observed student should show up.

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/50708187/p/21cc586aafd6f35bddd72d8b8832a7d1">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/50708200/p/e7741c43d880a5cf98d46000b7401d83">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/50708139/p/055fcc63423c614fa19fc2e1d454556a">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.93% | 92.93% | -0%

[MBL-14754](https://instructure.atlassian.net/browse/MBL-14754)

#### Affected Apps: Parent

#### Release Note: 
Fixed an issue with missing observed students
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by armstrongnate — APPROVED** [review]
QA +1

**Pull request merged**
