### PR TITLE
Fix date calculation.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15499
affects: Student
release note: Fixed a crash on the calendar screen.

test plan: See ticket.

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80966712/p/d3dbf3e4df7abfd85c87384ce18c80b0">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80966719/p/5748e65b04a49c8b51bfcc96fd766fb5">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80966706/p/c944e06a9223d7532afc9ae196e8ef2d">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.98% | 91.98% | 0%

[MBL-15499](https://instructure.atlassian.net/browse/MBL-15499)

#### Affected Apps: Student

#### Release Note: 
Fixed a crash on the calendar screen.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
