### PR TITLE
Background sync scheduler

### PR DESCRIPTION
**Pull request by vargaat**
### Notes
1. Wifi only sync switch logic will be implemented in another ticket.
2. The case when the offline sync is disabled on OS level is not handled yet and will be improved in a follow-up ticket as well.

refs: MBL-16758
affects: Student
release note: none

test plan: 

### Debug Testing
1. Build the app to a real device.
3. Go to Offline Content Settings.
4. Enable auto sync.
5. Set sync frequency to "As frequent as the OS allows (DEBUG)".
6. Put the app into the background, this will schedule a sync.
7. Stop the app with the debugger and enter the following command: `e -l objc -- (void)[[BGTaskScheduler sharedScheduler] _simulateLaunchForTaskWithIdentifier:@"com.instructure.icanvas.offline-sync"]`
8. Continue running the app, sync should start.
9. To abort an in progress sync enter the following debugger command: `e -l objc -- (void)[[BGTaskScheduler sharedScheduler] _simulateExpirationForTaskWithIdentifier:@"com.instructure.icanvas.offline-sync"]`

### Manual Testing
1. Repeat steps 1-5 from Debug Testing steps. (Except that sync frequency have to be set to daily.)
2. Wait enough time for the sync to happen (mostly at night I assume).
3. Open the app, go to debug settings, check logs about the background sync.

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [x] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [x] Tested in light mode
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-16758](https://instructure.atlassian.net/browse/MBL-16758)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.47% | 92.46% | 0.01%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 59a126c392ecd467ac36f399a47cd33e0b0aec46
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by balintbartok — DISMISSED** [review]

**Review by ndrsszsz — APPROVED** [review]
QA +1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
