### PR TITLE
Add AnnouncementsE2ETests for Teacher

### PR DESCRIPTION
**Pull request by davidvarga93**
refs: MBL-15494
affects: Teacher
release note: none

test plan:

### CODE REVIEW

**Comment by davidvarga93** [comment]
Nightly:
https://app.bitrise.io/build/81f1e9f0-5a93-45cd-a487-f55b95962b63#?tab=log

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/85937871/p/afda5b271919ce4ed96b2629a6814886">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/85937882/p/9a2ca6a5915e3800368b8e290ab31e27">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/85937868/p/7c5ab0b9b3bc0ed44a962410a42d2c3d">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.98% | 91.98% | 0%

[MBL-15494](https://instructure.atlassian.net/browse/MBL-15494)

#### Affected Apps: Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]

**Comment by davidvarga93** [comment]
AnnouncementsE2ETests
    ✔ testAnnouncementsE2E (17.938 seconds)

**Review by vargaat — APPROVED** [review]

**Pull request merged**
