### PR TITLE
Course Smart Search "How it works" screen

### PR DESCRIPTION
**Pull request by suhaibabsi-inst**
refs: [MBL-18010](https://instructure.atlassian.net/browse/MBL-18010)
affects: Student
release note: Course Smart Search "How it works" screen

Related PR(s):
https://github.com/instructure/canvas-ios/pull/2932

## Test Plan
* Make sure to activate "Smart Search" on account & course level. [See here.](https://community.canvaslms.com/t5/Smart-Search-Feature-Preview/How-to-Enable-Smart-Search/ta-p/604577)
* Login to Student app.
* Go to courses, open one of the courses. 
* You should expect a search icon shown on the top-right button. Follow on the experience.
   - Tap on question-mark icon button
   - A sheet is shown with help content about smart search
   
## Screenshot

Help Screen

## Video Record

https://github.com/user-attachments/assets/1e0d66f1-ffff-4043-a2aa-f96cf60464f4

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [x] Tested on phone
- [x] Tested on tablet
- [ ] Tested in dark mode
- [x] Tested in light mode
- [ ] Approve from product

[MBL-18010]: https://instructure.atlassian.net/browse/MBL-18010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Course Smart Search "How it works" screen

#### Affected Apps: Student

[MBL-18010](https://instructure.atlassian.net/browse/MBL-18010)

<details><summary>:x: Swift lint</summary>


    
    ----- xcbeautify -----
    Version: 2.11.0
    ----------------------
    
    ❌ /Users/vagrant/git/Core/Core/Courses/SmartSearch/View/CourseSmartSearchHelpView.swift:32:1: Line Length Violation: Line should be 200 characters or less; currently it has 202 characters (line_length)
    /Users/vagrant/git/Core/Core/Courses/SmartSearch/View/CourseSmartSearchHelpView.swift:35:1: error: Line Length Violation: Line should be 200 characters or less; currently it has 374 characters (line_length)
    /Users/vagrant/git/Core/Core/Courses/SmartSearch/View/CourseSmartSearchHelpView.swift:41:1: error: Line Length Violation: Line should be 200 characters or less; currently it has 222 characters (line_length)
    ❌ /Users/vagrant/git/Core/Core/Courses/SmartSearch/View/CourseSmartSearchHelpView.swift:30:60: Opening Brace Spacing Violation: Opening braces should be preceded by a single space and on the same line as the declaration (opening_brace)
    
    
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d0e5c178e6a21412b7eb08c5b89530781e341556
</p>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by ndrsszsz — APPROVED** [review]
QA +1

**Pull request merged**
