### PR TITLE
Rename apps

### PR DESCRIPTION
**Pull request by szabinst**
refs: MBL-16308
affects: Student, Teacher, Parent
release note: Renamed the application
test plan: See ticket

## Screenshots

<table>
<tr><th>iPhone SE Home</th><th>iPhone SE Setttings</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<tr><th>iPhone 14 Home</th><th>iPhone 14 Settings</th></tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] A11y checked
- [x] Tested on phone
- [x] Tested on tablet
- [x] Tested in dark mode
- [x] Tested in light mode
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/Core/Submissions/Submission.swift:130:24: Function Body Length Violation: Function body should span 100 lines or less excluding comments and whitespace: currently spans 110 lines (function_body_length)
    
    
</details>


[MBL-16308](https://instructure.atlassian.net/browse/MBL-16308)

#### Affected Apps: Student, Teacher, Parent

#### Release Note: 
Renamed the application
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by vargaat — APPROVED** [review]
QA+1, iOS 15

**Review by idevainstr — CHANGES_REQUESTED** [review]
Let's also set the default name in case of missing locale translations.

**Review by idevainstr — APPROVED** [review]

**Pull request merged**
