### PR TITLE
Update courses screen for offline mode

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-17063
affects: Student
release note: none

test plan:
- Edit dashboard button renamed to All Courses.
- Added downloaded icon for courses selected for offline availability.
- In offline mode not selected courses for offline mode are not tappable.
- Star button is disabled while in offline mode.
- Minor UI updates, mostly paddings.

## Screenshots

<table>
<tr><th>Online</th><th>Offline</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [X] Follow-up e2e test ticket created (MBL-17113)
- [ ] A11y checked
- [x] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-17063](https://instructure.atlassian.net/browse/MBL-17063)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.42% | 92.42% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 99401ed50f6a882cf7f173fd3f21adcb3d18c5ff
</p>

**Comment by balintbartok** [comment]
It's kind of an edge case, but if you have never opened the all courses page in online mode, it will not be populated in offline mode. It might not make sense to fix this, people not using the all courses in online mode doesn't need it in offline mode either, just wanted to point this out, let's think about it.
IMG_0024

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by szabinst — APPROVED** [review]
QA + 1

**Pull request merged**
