### PR TITLE
Update PSPDFKit to version 10.3.0

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15125
affects: Student, Teacher
release note: Update PSPDFKit to version 10.3.0
test plan: see ticket

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74069444/p/ac495276388c30c1b89d993bb5b093f6">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74069453/p/0ed3ee6dcc4316d58e6421b9fccda32b">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74069407/p/575c1ae9dae9a9b578e8dfa81da907b9">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92% | 92% | 0%

[MBL-15125](https://instructure.atlassian.net/browse/MBL-15125)

#### Affected Apps: Student, Teacher

#### Release Note: 
Update PSPDFKit to version 10.3.0
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by vargaat — CHANGES_REQUESTED** [review]
Builds crash a few seconds after startup.

**Review by balintbartok — APPROVED** [review]
QA + 1

**Comment by davidvarga93** [comment]
QA +1 manual

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
