### PR TITLE
Inactive students are listed in not submitted tab when swiping

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15360
affects: Teacher
release note: Fix inactive students visible is speedgrader while swiping.
test plan: See ticket.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74487823/p/b12ea7ced26eb6cbc631d09cbd588dda">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74487854/p/4818f1667def045e0613b00f797d9ed1">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74487775/p/5e10344848f6531a95ce8ab068a39d43">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92% | 92% | -0%

[MBL-15360](https://instructure.atlassian.net/browse/MBL-15360)

#### Affected Apps: Teacher

#### Release Note: 
Fix inactive students visible is speedgrader while swiping.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by vargaat — APPROVED** [review]
QA+1

**Comment by davidvarga93** [comment]
QA +1 manual

**Pull request merged**
