### PR TITLE
Use native todo list in Teacher

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-14925
affects: Teacher
release note: Polished To Do list

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/55499835/p/a70f35267a33eb6dc8c62b2870b446e3">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/55499836/p/6768458963a8801ded54b32434cdd08c">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/55499827/p/da14b7430ed17dcc1001bbe74173b287">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.83% | -- | --

[MBL-14925](https://instructure.atlassian.net/browse/MBL-14925)

#### Affected Apps: Teacher

#### Release Note: 
Polished To Do list
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by vanwagonet** [comment]
Note that this assumes the new native speedgrader, so the link may not be filtered properly in the old RN speedgrader.

**Comment by balintbartok** [comment]
-found something: opening a submission after a fresh install from the todo list: the tutorial screen pops up, and we get a "Whoops!" screen, with no option to dismiss it
-also the order of todo items is different then the latest version on master, I don't really see any pattern in either, but maybe worth a check

**Comment by balintbartok** [comment]
Screenshot 2020-11-11 at 9 27 30
code looks good, functionality is perfect, just a few minor differences between the 2 versions, they are visible on the screenshot: size, section names, I don't know if it's intentional

**Comment by vanwagonet** [comment]
The tutorials are only in the RN version of speedgrader and this assumes we are using the native one.

Yeah I noticed the order ended up a little different. The RN version just used the order from the api call & CoreData necessitates sorting.

**Comment by vanwagonet** [comment]
This todo list isn't like the one the web uses, so I'll double check with Android tomorrow about the order they show & if necessary keep track of the original order from the api instead of sorting by dueAt.

**Comment by balintbartok** [comment]
QA + 1

**Review by balintbartok — APPROVED** [review]

**Review by balintbartok — DISMISSED** [review]
QA+1

**Comment by vanwagonet** [comment]
more conflicts to resolve. :( sorry

**Review by balintbartok — APPROVED** [review]

**Review by balintbartok — DISMISSED** [review]

**Review by balintbartok — APPROVED** [review]
QA+1

**Pull request merged**
