### PR TITLE
Assignment List and List Preferences Improvements

### PR DESCRIPTION
**Pull request by ndrsszsz**
refs: MBL-18168
affects: Student, Teacher
release note: Improved assignment list and assignment list preferences screen.
test plan: See ticket.

## Should fix the following issues (test plan)

- When opening the assignment list screen for the first time, the current grading period fails to get selected automatically and shows "All" instead of the current one, and only shows the correct one after PTR.
- Assignment List Preferences screen doesn't have backgroundLightest as background colour.

### Assignment List Preferences (background colour difference)

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Improved assignment list and assignment list preferences screen.

#### Affected Apps: Student, Teacher

[MBL-18168](https://instructure.atlassian.net/browse/MBL-18168)

<details><summary>:x: XCTest failed: CoreTests/AssignmentListViewModelTests/testFilterOptionsDidUpdate</summary>


    XCTAssertEqual failed: ("nil") is not equal to ("Optional("GP1")")
</details>
<details><summary>:x: XCTest failed: CoreTests/AssignmentListViewModelTests/testGroupAssignmentsByAssignmentType</summary>


    failed - Normal Assignments View Model is not available.
</details>
<details><summary>:x: XCTest failed: CoreTests/AssignmentListViewModelTests/testGroupeAssignmentsByAssignmentGroups</summary>


    failed - AssignmentGroup1 View Model is not available.
</details>
<details><summary>:x: XCTest failed: CoreTests/AssignmentListViewModelTests/testInitialState</summary>


    XCTAssertEqual failed: ("empty") is not equal to ("loading")
    XCTAssertNil failed: "2"
</details>
<details><summary>:x: XCTest failed: CoreTests/CourseSyncCleanupInteractorTests/testSharedOfflineDirectoryForUserDeleted</summary>


    XCTAssertFalse failed
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 89f5eac82172d0126bc9284b6477a811747587a4
</p>

**Review by rh12 — APPROVED** [review]
QA + 1

**Review by vargaat — APPROVED** [review]
QA+1, I couldn't reproduce the issue with a few tries. The solution is quite hacky (as we discussed) but works so let's keep it as-is and improve the `AssignmentListViewModel` as a whole at a later time.

**Pull request merged**
