### PR TITLE
Add Grade Slider tap feature

### PR DESCRIPTION
**Pull request by idevainstr**
Extract grade slider, make it tappable along the Slider track, align Slider min/max value Texts vertically, only show bottom divider when the rubrics section is available.

refs: MBL-15250
affects: Teacher
release note: Improved Grade Slider
test plan: see ticket

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/69055957/p/b2fb512e8f04ffc45e0817d588bfd848">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/69055982/p/2fee5283c00ac51c96ba1950de58ebee">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/69055905/p/146618fb4788f8599ed27724c7b012f8">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.09% | 92.09% | 0%

[MBL-15250](https://instructure.atlassian.net/browse/MBL-15250)

#### Affected Apps: Teacher

#### Release Note: 
Improved Grade Slider
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by balintbartok — CHANGES_REQUESTED** [review]
It's perfect with bare hands, although apple pencil is too precise still, can you check that?

**Review by balintbartok — APPROVED** [review]

**Pull request merged**
