### PR TITLE
Add support to submission viewer to properly display for non-enhanced assignments

### PR DESCRIPTION
**Pull request by vargaat**
refs: [MBL-17856](https://instructure.atlassian.net/browse/MBL-17856)
affects: Parent
release note: Add support to submission viewer to properly display for non-enhanced assignments.

test plan:
- Turn assignment enhancements off.
- Create an assignment, submit an attempt, add a grade.
- Open the parent app and go to the assignment and view the submission.
- Submission viewer should show the attempt.
- Close the window.
- Turn assignment enhancements on.
- Pull to refresh the parent app's assignment screen.
- Open the submission viewer.
- Submission viewer should still show the attempt.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [x] Tested on phone
- [ ] Tested on tablet
- [ ] Approve from product

[MBL-17856]: https://instructure.atlassian.net/browse/MBL-17856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Release Note: 
Add support to submission viewer to properly display for non-enhanced assignments.

#### Affected Apps: Parent

[MBL-17856](https://instructure.atlassian.net/browse/MBL-17856)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.64% | 91.64% | 0%
Core/Core/Extensions/UISplitViewControllerExtensions.swift | 23.08% | 23.08% | 0%
Core/Core/Planner/CalendarEvent/Model/API/PostCalendarEventRequest.swift | 0% | 0% | 0%
Core/Core/Extensions/UITabBarControllerExtensions.swift | 0% | 0% | 0%
Core/Core/Extensions/UINavigationControllerExtensions.swift | 0% | 0% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a5e7241826d1e02c6c73e6070b3bda4526a0e18f
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by ndrsszsz — APPROVED** [review]
QA +1

**Pull request merged**
