### PR TITLE
Native quiz preview

### PR DESCRIPTION
**Pull request by vargaat**
There's a slight change in the behaviour compared to the react version: upon loading the webview with the quiz preview url the react version automatically started the quiz submission. I couldn't easily reproduce the same so now the user has to start the preview inside the webview which will result in 1 or 2 extra taps.

refs: MBL-16290
affects: Teacher
release note: none

test plan:
- Enable native teacher quiz feature flag
- Go to quizzes, select a quiz
- On the quiz details page tap on preview quiz button
- Observe loading indicator, quiz preview load, modal presentation styles.

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [x] A11y checked
- [x] Tested on phone
- [x] Tested on tablet
- [x] Tested in dark mode
- [x] Tested in light mode
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.93% | 91.95% | -0.02%
Core/Core/Courses/CourseDetails/ViewModel/CourseDetailsViewModel.swift | 48.89% | 48.89% | 0%

[MBL-16290](https://instructure.atlassian.net/browse/MBL-16290)

#### Affected Apps: Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by vargaat** [comment]
> I noticed a few differences with the react native version:
> 
> * after submitting the quiz (in preview mode) in the new version preview loads again automatically again
> * assignment quiz opens in an external webview, with full canvas appearance (with sidebar) balintbartok / t / Classic quiz12

Fixed these, please re-test. Note the change in the behaviour I described in the PR description.

**Comment by balintbartok** [comment]
QA + 1

**Review by balintbartok — APPROVED** [review]

**Review by szabinst — APPROVED** [review]
QA + 1

**Comment by ndrsszsz** [comment]
QA +1

**Pull request merged**
