### PR TITLE
Do not show hidden events in syllabus summary

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16258
affects: Student, Teacher
release note: Fixed calendar events from other course sections showing up in syllabus summary.

test plan: See ticket.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] A11y checked
- [x] Tested on phone
- [x] Tested on tablet
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/CoreActivityViewControllerTests/testDismissesItselfWhenAppMovesToBackground</summary>


    Assertion Failure at CoreActivityViewControllerTests.swift:37: XCTAssertNil failed: "<Core.CoreActivityViewController: 0x7fd9dbcde600>"
</details>


[MBL-16258](https://instructure.atlassian.net/browse/MBL-16258)

#### Affected Apps: Student, Teacher

#### Release Note: 
Fixed calendar events from other course sections showing up in syllabus summary.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by szabolcs-instructure — APPROVED** [review]
QA + 1

**Pull request merged**
