### PR TITLE
Fix offline retry logic

### PR DESCRIPTION
**Pull request by szabinst**
refs: MBL-17022
affects: Student
release note: none
test plan: Start sync, turn Wi-Fi off, retry

## Checklist

- [x] Tested on phone
- [x] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-17022](https://instructure.atlassian.net/browse/MBL-17022)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 42bb0a1a8c7b18689405fc9f7af2ebefeedce20c
</p>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by vargaat — CHANGES_REQUESTED** [review]
Add a test for the save method in `CDCourseSyncDownloadProgress` to bump the coverage.

**Review by vargaat — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
