### PR TITLE
Make url parsing in course navigation response more tolerant.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16043
affects: Teacher
release note: Fixed attendance tool opening in a web view.

test plan: See ticket. Attendance tool should open natively.

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/10053f75-f34f-40c1-b515-b84f56b77574/artifact/4fd807a3d923b081/p/00fe27ce15f0e5593fda4493b66b47e0">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/10053f75-f34f-40c1-b515-b84f56b77574/artifact/9df3e98af3251c97/p/068debdf88bd5a5727f888fae6344d4a">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/10053f75-f34f-40c1-b515-b84f56b77574/artifact/369930a59c8eb5c9/p/b25ea3344ce2f178f1a6054ce188c71f">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.82% | 91.82% | 0%

[MBL-16043](https://instructure.atlassian.net/browse/MBL-16043)

#### Affected Apps: Teacher

#### Release Note: 
Fixed attendance tool opening in a web view.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
