### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-15902
affects: Student, Teacher
release note: none

test plan: Make sure all products can be built

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/8fc82ab8-7ffa-4c55-8f87-9cdd025187ac/artifact/ce50f4b2dcc02bfd/p/9368e95d5997d020c8b08b2aadebd489">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/8fc82ab8-7ffa-4c55-8f87-9cdd025187ac/artifact/47f75fb0f642966d/p/cc480f7b29adce84dd76ad6e2e2b725e">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/8fc82ab8-7ffa-4c55-8f87-9cdd025187ac/artifact/ca10ae438fa86dbc/p/8dfbe3a971303bea4682433498ecd005">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.69% | 91.76% | -0.07%

[MBL-15902](https://instructure.atlassian.net/browse/MBL-15902)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by vargaat — APPROVED** [review]
Student assignment list still works. QA+1

**Comment by vargaat** [comment]
Since only the student project was modified this doesn't affect the teacher app.

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
