### PR TITLE
Student total grade is rounded down

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15383
affects: Teacher, Student
release note: Fix total grades with decimal values.
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Danger failed to run `dangerfile.js`.
  </td>
    </tr>
  </tbody>
</table>



## Error Error
```
Cannot find module 'commander'
Require stack:
- /Users/vagrant/git/scripts/update-headers.js
- dangerfile.js
- /snapshot/danger-js/distribution/runner/runners/inline.js
- /snapshot/danger-js/distribution/commands/danger-runner.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
Error: Cannot find module 'commander'
Require stack:
- /Users/vagrant/git/scripts/update-headers.js
- dangerfile.js
- /snapshot/danger-js/distribution/runner/runners/inline.js
- /snapshot/danger-js/distribution/commands/danger-runner.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:795:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1287:46)
    at Function.Module._load (internal/modules/cjs/loader.js:688:27)
    at Function._load (/snapshot/danger-js/node_modules/override-require/dist/overrideRequire.js:43:25)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/vagrant/git/scripts/update-headers.js:30:17)
    at Module._compile (internal/modules/cjs/loader.js:957:30)
    at Module._compile (pkg/prelude/bootstrap.js:1222:32)
```
### Dangerfile
```
------------------^
```
  
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against dc887df27070409ebf9d10b281e1888d78c10e0f
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74918460/p/5e830b845dd8a2c501dbdb0b0b33d8dd">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74918477/p/3f97652416026fb0c81f1273efb12720">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74918437/p/e0a3e79983f528cd39a0bf7c925180d1">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.03% | 92.03% | 0%

[MBL-15383](https://instructure.atlassian.net/browse/MBL-15383)

#### Affected Apps: Teacher

#### Release Note: 
Fix total grades with decimal values.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
