### PR TITLE
Unpublished course is visible for student

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15924
affects: Student
release note: Unpublished courses are now hidden.
test plan: see ticket

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/CourseListViewModelTests/testCreatesAssignmentList</summary>


    Assertion Failure at CourseListViewModelTests.swift:40: XCTAssertEqual failed: ("1") is not equal to ("2")
    Assertion Failure at CourseListViewModelTests.swift:42: XCTAssertEqual failed: ("0") is not equal to ("1")
</details>
<details><summary>:x: XCTest failed: CoreTests/CourseListViewModelTests/testFilter</summary>


    Assertion Failure at CourseListViewModelTests.swift:62: XCTAssertEqual failed: ("0") is not equal to ("1")
    Assertion Failure at CourseListViewModelTests.swift:63: XCTAssertEqual failed: ("nil") is not equal to ("Optional("Fall 2020")")
</details>
<details><summary>:x: XCTest failed: CoreTests/PreviewStoreTests/testPreviewStore</summary>


    Assertion Failure at PreviewStoreTests.swift:26: XCTAssertEqual failed: ("0") is not equal to ("1")
</details>


[MBL-15924](https://instructure.atlassian.net/browse/MBL-15924)

#### Affected Apps: Student

#### Release Note: 
Unpublished courses are now hidden.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/117097550/p/30cfcd2542069b2762c1c0ab2768a0e8">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/117097593/p/c4fa5e8c64a4d7da47f5f8b05b28a3f5">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/117097437/p/91a2edbbf9e3302700e7a463495bd300">
    
  </a>
</details>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
