### PR TITLE
Update translation import script

### PR DESCRIPTION
**Pull request by vargaat**
### Export Script
- Removed exporting of react-native translations.
- Deleted step that made PR of new english react strings.
- Removed hub dependency install step that was use by the PR creation step.
- Extracted localizable files list to external file so the import script also can use it.

### Import Script
- Modified the script to use new string catalogs.
- Builds now can fail in case of a misformatted translation so I added the `affects` line to the translations import PR to trigger all app builds and reveal any compilation errors.
- Removed importing of react-native translations.

refs: MBL-17281
affects: Student, Teacher, Parent
release note: none

test plan: New translations should be correctly imported.

Example [PR](https://github.com/instructure/canvas-ios/pull/2682) is here, just ignore the changes from this branch.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student, Teacher, Parent

[MBL-17281](https://instructure.atlassian.net/browse/MBL-17281)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.06% | 92.07% | -0.01%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 759cdec89f0cef9866acbad6be25b008f82846b0
</p>

**Review by balintbartok — APPROVED** [review]

**Review by szabinst — APPROVED** [review]

**Pull request merged**
