### PR TITLE
Add SAML login UI test

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBL-12593
affects: student
release note: none

### CODE REVIEW

**Comment by armstrongnate** [comment]
Relies on https://github.com/instructure/steps-canvas-ios-secrets/pull/17

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-12593](https://instructure.atlassian.net/browse/MBL-12593)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Core** | 95.28% | 95.28% | 0%
**Student** | 93.19% | 93.19% | 0%
**Teacher** | 100% | 100% | 0%
**React Native** | 92.76% | 92.76% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by vanwagonet** [comment]
The newly added test was the one that failed, so I ran it locally & it passed. I've re-triggered the build to see if it was a temporary issue on bitrise.

**Comment by armstrongnate** [comment]
Signing in with Azure fails because it wants to verify the authenticity since the login is occurring in a far away place. I'm going to close this until we get SAML set up on the automation account.

**Pull request closed without merging**
