### PR TITLE
Lato font

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15911
affects: Parent, Student, Teacher
release note: none

test plan: Check fonts in native screens, webviews, React screens, widgets and in the share extension in non-K5 mode.

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.72% | 91.82% | -0.1%
Core/Core/Fonts/FontPreview.swift | 0% | -- | --

[MBL-15911](https://instructure.atlassian.net/browse/MBL-15911)

#### Affected Apps: Parent, Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/9dd39657-d575-45bb-a5bb-f29c5a4f84df/artifact/7fa3805ec6638d3b/p/f92753438f4b10b495174ecf64e69bff">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/9dd39657-d575-45bb-a5bb-f29c5a4f84df/artifact/61dfd82f89b6ee3e/p/d4167dee5b3a614a11524fed0eb5b8e3">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/9dd39657-d575-45bb-a5bb-f29c5a4f84df/artifact/261ddc8d033b2a95/p/e6041cb138e2591d5574fddb00ae18a6">
    
  </a>
</details>

**Review by idevainstr — CHANGES_REQUESTED** [review]
Please check the header theming in general for fullscreen, split-screen and modal presentations!
Please check the text entry fields in general!

**Review by idevainstr — CHANGES_REQUESTED** [review]
Please check the input fields on the inbox > new message page in Student/Teacher!

**Review by idevainstr — CHANGES_REQUESTED** [review]
Please check the search fields in general (iOS 14)!
Inbox > New message > To +
Course > People
Course > Files
etc.

**Comment by vargaat** [comment]
I fixed the native search bar fonts, however I couldn't get any custom font settings on the react search bar.

**Review by idevainstr — DISMISSED** [review]
QA+1 🏅

**Review by idevainstr — APPROVED** [review]

**Review by idevainstr — APPROVED** [review]

**Pull request merged**
