### PR TITLE
Data seeding foundations

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15482
affects: none
release note: none

test plan:

### CODE REVIEW

**Comment by vargaat** [comment]
Usage example:
```
func testExample() {
    let seeder = DataSeeder()
    let users = seeder.createUsers(2)
    let course = seeder.createCourse()
    seeder.enrollStudent(users[0], in: course)
    seeder.enrollTeacher(users[1], in: course)
}
```

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/109543253/p/eb599db61423f768dfe92cdd56f4130e">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/109543263/p/20f56c440aed6b7c19e03b178d07f8e2">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/109543246/p/244f61f918da1077d750f75285615a58">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.5% | 91.5% | 0%

[MBL-15482](https://instructure.atlassian.net/browse/MBL-15482)

#### Affected Apps: None
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by davidvarga93 — APPROVED** [review]
QA + 1
HERE WE GO

**Review by balintbartok — APPROVED** [review]

**Pull request merged**
