### PR TITLE
Missing translations

### PR DESCRIPTION
**Pull request by rh12**
refs: [MBL-17518](https://instructure.atlassian.net/browse/MBL-17518)
affects: All
release note: Fixed missing localizations.

## Problem
`bundle: .core` needs to be added for all `NSLocalizedString()`, `String(localized:)`, `Text()` method calls in `Core` module.
Otherwise all of these will fall back to the apps module.

## What's new
- Added `bundle: .core` in all places in Core
- Added `bundle: .canvas` in all places in CanvasCore
- Added `bundle: .student/teacher/parent` in all places in app modules (to save us from mistakes when we move code around modules)
- Changed (almost) all `NSLocalizedString()` usages to `String(localized:)`
- Fixed some misc issues

## What's not changed
- Backend driven texts are not fixed (ie.: Assignment List section headers)

## Test plan
See ticket and use already setup account described there.
Smoke test all apps.

## Checklist
- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [x] Tested on phone
- [x] Tested on tablet

[MBL-17518]: https://instructure.atlassian.net/browse/MBL-17518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>You have included an invalid app. Valid values are: Student, Teacher, Parent, None</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Fixed missing localizations.

[MBL-17518](https://instructure.atlassian.net/browse/MBL-17518)

<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/Core/Inbox/MessageDetails/ViewModel/MessageDetailsViewModel.swift:34:34: Colon Spacing Violation: Colons should be next to the identifier when specifying a type and next to the key in dictionary literals (colon)
    
    
</details>
<details><summary>:x: XCTest failed: ParentUnitTests/DashboardViewControllerTests/testLayoutMenu</summary>


    XCTAssertEqual failed: ("Optional("conversation_unread_messages")") is not equal to ("Optional("3 unread conversations")")
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e9e17830d1e7a56770a8ed8dc4793113c61c59ee
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by ndrsszsz — APPROVED** [review]
QA +1

**Pull request merged**
