### PR TITLE
Update routes from K5 homeroom card.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15653
affects: Student
release note: none

test plan:
- Create a course announcement and an overdue assignment on an elementary account.
- Log in to the student app.
- Elementary dashboard card for the above course should display that 1 item is missing and the course announcement title.
- Tap on the announcement.
- App should route to the subject home where the announcement is fully displayed.
- Go back.
- Tap on the missing item text.
- App should route to the subject schedule page.

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


<details><summary>:x: XCTest failed: CoreTests/K5HomeroomViewModelTests/testLoadsNonHomeroomCourses</summary>


    Assertion Failure at K5HomeroomViewModelTests.swift:103: XCTAssertEqual failed: ("InfoLine(icon: SwiftUI.Image(provider: SwiftUI.ImageProviderBox<SwiftUI.Image.(unknown context at $7fff5cd373d0).NamedImageProvider>), route: "/courses/1#schedule", text: "1 due today | ", highlightedText: "2 missing")") is not equal to ("InfoLine(icon: SwiftUI.Image(provider: SwiftUI.ImageProviderBox<SwiftUI.Image.(unknown context at $7fff5cd373d0).NamedImageProvider>), route: "/courses/1/assignments", text: "1 due today | ", highlightedText: "2 missing")")
    Assertion Failure at K5HomeroomViewModelTests.swift:104: XCTAssertEqual failed: ("InfoLine(icon: SwiftUI.Image(provider: SwiftUI.ImageProviderBox<SwiftUI.Image.(unknown context at $7fff5cd373d0).NamedImageProvider>), route: "/courses/1", text: "Non homeroom announcement", highlightedText: "")") is not equal to ("InfoLine(icon: SwiftUI.Image(provider: SwiftUI.ImageProviderBox<SwiftUI.Image.(unknown context at $7fff5cd373d0).NamedImageProvider>), route: "/courses/1/announcements", text: "Non homeroom announcement", highlightedText: "")")
</details>


[MBL-15653](https://instructure.atlassian.net/browse/MBL-15653)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/101987790/p/e00edc5ca84e6a7ed1d0565fb1048342">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/101987811/p/ec60060db7cb0b6197bf060cd8269873">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/101987773/p/da5b22b2e59602afb9f03b0517b72935">
    
  </a>
</details>

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by davidvarga93 — APPROVED** [review]

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
