### PR TITLE
Fix add page for groups

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-15209
affects: Student
release note: Fixed page editor not showing title

test plan:
see ticket (add a page from groups)

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73284681/p/12f757bf6c3a40b1b361a0d99e7dcd5d">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73284691/p/b8c39048181b073f257b393674b4fa94">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73284673/p/db90d7107f7755622ef0627cc36fe801">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.06% | 92.07% | -0.01%

[MBL-15209](https://instructure.atlassian.net/browse/MBL-15209)

#### Affected Apps: Student

#### Release Note: 
Fixed page aditor not showing title
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
