### PR TITLE
Fix Latex equations

### PR DESCRIPTION
**Pull request by vargaat**
refs: Student, Teacher
affects: MBL-15806
release note: Fixed LaTeX equations not rendering correctly.

test plan: See ticket.

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  You have included an invalid app. Valid values are: Student, Teacher, Parent, None
  </td>
    </tr>
  </tbody>
</table>



Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.84% | 91.85% | -0%

[MBL-15806](https://instructure.atlassian.net/browse/MBL-15806)

#### Release Note: 
Fixed LaTeX equations not rendered correctly.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/17ed9171-95c4-43d8-99ed-ca8ea5c3ff2b/artifact/7484ec7931933260/p/e47d4ef586d76cc9a83ab31a0ea15718">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/17ed9171-95c4-43d8-99ed-ca8ea5c3ff2b/artifact/e0381afdc6901cd6/p/2c3b6b4556624040c7760bde63210a59">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/17ed9171-95c4-43d8-99ed-ca8ea5c3ff2b/artifact/fe3a37ed633d8ec7/p/da37b8031e8bc1d6ebf0da1be85cae62">
    
  </a>
</details>

**Review by davidvarga93 — DISMISSED** [review]
QA + 1

**Review by tamasiscoming — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1 🏅

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
