### PR TITLE
[Teacher] Support modules with more than 100 items 

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBL-13507, MBL-13154
affects: teacher
release note: Fixed modules with more than 100 items

Test plan:
* See [ticket](https://instructure.atlassian.net/browse/MBL-13507) for a module with more than 100 items. All the items should load eventually as you scroll
* Use narmstrong > t and view CS 1400 > Modules
* Make sure all the modules and their items load eventually
* Collapse and expand module headers
* View CS 1400 > Pages > Links to Stuff > Module 1 > see that it auto scrolls to the module
* Tap the various module item types and see that they load
* See [this ticket as well](https://instructure.atlassian.net/browse/MBL-13154). I left a comment with login credentials for that account. Follow the repro in that ticket.

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1010857&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by inst-danger** [comment]
#### Release Note: 
Fixed modules with more than 100 items

#### Affected Apps: Teacher

[MBL-13507](https://instructure.atlassian.net/browse/MBL-13507)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.37% | 93.29% | 0.07%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by armstrongnate** [comment]
@vanwagonet where are you auto scrolling from? A page?

**Comment by armstrongnate** [comment]
@vanwagonet never mind, I can repro.

**Comment by armstrongnate** [comment]
It's still not a perfect scroll when loading the modules for the first time. I don't really know why. But I think it is better now because the first row is always shown (in my experience).

**Comment by vanwagonet** [comment]
Changes look good, but it looks like bitrise didn't build the Teacher app, so I'll just try it out locally.

**Pull request merged**
