### PR TITLE
Show quiz icon in parent grades list, assignments come back as `lockedForUser` in parent

### PR DESCRIPTION
**Pull request by bluwave**
refs: MBL-14100
affects: Parent
release note: Fix quiz icon always showing locked

Testing
quiz icons in grades on parent should not show locked.

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/3qdlm8j) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2F3qdlm8j)
teacher: [Link](https://rebrand.ly/v14cgfe) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fv14cgfe)
parent: [Link](https://rebrand.ly/nmw5cii) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fnmw5cii)

**Comment by inst-danger** [comment]
#### Release Note: 
Fix quiz icon always showing locked

#### Affected Apps: Parent

[MBL-14100](https://instructure.atlassian.net/browse/MBL-14100)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.64% | 93.63% | 0.02%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1025504&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|13
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Pull request merged**
