### PR TITLE
Enhance reporting

### PR DESCRIPTION
**Pull request by vargaat**
**What changed:**
- Updated google info plist files.
- Updated firebase SDK versions.
- Enhanced screen_view events with the screen's route, reliable class name and app information.
- Disabled automatic screen_view event as they weren't that useful.
- Set up audiences in firebase for all 3 apps.

refs: MBL-15651
affects: Parent, Student, Teacher
release note: none

test plan: Use the app, check Firebase if screen_view events are reported.

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


<details><summary>:x: JS tests</summary>


    Summary of all failing tests
     FAIL  src/routing/__tests__/Navigator.test.js (8.829s)
      ● Navigator › forwards show as a push
    
        expect(jest.fn()).toHaveBeenCalledWith(...expected)
    
        Expected: "push", "/courses/:courseID", {"courseID": "1", "location": Any<Object>, "screenInstanceID": Any<String>}, {"canBecomeMaster": true, "deepLink": true, "detail": false}
    
        Number of calls: 0
    
          56 |   it('forwards show as a push', () => {
          57 |     new Navigator('push').show('/courses/1')
        > 58 |     expect(NativeModules.Helm.pushFrom).toHaveBeenCalledWith(
             |                                         ^
          59 |       'push',
          60 |       '/courses/:courseID',
          61 |       { courseID: '1', screenInstanceID: expect.any(String), location: expect.any(Object) },
    
          at Object.<anonymous> (src/routing/__tests__/Navigator.test.js:58:41)
    
      ● Navigator › passes detail option from show to push
    
        expect(jest.fn()).toHaveBeenCalledWith(...expected)
    
        Expected: "detail", "/courses/:courseID", Any<Object>, {"canBecomeMaster": true, "deepLink": true, "detail": true}
    
        Number of calls: 0
    
          66 |   it('passes detail option from show to push', () => {
          67 |     new Navigator('detail').show('/courses/1', { detail: true })
        > 68 |     expect(NativeModules.Helm.pushFrom).toHaveBeenCalledWith(
             |                                         ^
          69 |       'detail',
          70 |       '/courses/:courseID',
          71 |       expect.any(Object),
    
          at Object.<anonymous> (src/routing/__tests__/Navigator.test.js:68:41)
    
      ● Navigator › forwards replace as a push
    
        expect(jest.fn()).toHaveBeenCalledWith(...expected)
    
        Expected: "replace", "/courses/:courseID", {"courseID": "2", "location": Any<Object>, "screenInstanceID": Any<String>}, {"canBecomeMaster": true, "deepLink": true, "replace": true}
    
        Number of calls: 0
    
          81 |   it('forwards replace as a push', () => {
          82 |     new Navigator('replace').replace('/courses/2')
        > 83 |     expect(NativeModules.Helm.pushFrom).toHaveBeenCalledWith(
             |                                         ^
          84 |       'replace',
          85 |       '/courses/:courseID',
          86 |       { courseID: '2', screenInstanceID: expect.any(String), location: expect.any(Object) },
    
          at Object.<anonymous> (src/routing/__tests__/Navigator.test.js:83:41)
    
      ● Navigator › forwards present to native helm
    
        expect(jest.fn()).toHaveBeenCalledWith(...expected)
    
        Expected: "/courses/:courseID", {"courseID": "1", "location": Any<Object>, "screenInstanceID": Any<String>}, {"canBecomeMaster": true, "disableSwipeDownToDismissModal": true, "embedInNavigationController": true, "modal": true, "modalPresentationStyle": "formsheet"}
    
        Number of calls: 0
    
          91 |   it('forwards present to native helm', () => {
          92 |     new Navigator('present').show('/courses/1', { modal: true })
        > 93 |     expect(NativeModules.Helm.present).toHaveBeenCalledWith(
             |                                        ^
          94 |       '/courses/:courseID',
          95 |       { courseID: '1', screenInstanceID: expect.any(String), location: expect.any(Object) },
          96 |       { canBecomeMaster: true, embedInNavigationController: true, modal: true, modalPresentationStyle: 'formsheet', disableSwipeDownToDismissModal: true }
    
          at Object.<anonymous> (src/routing/__tests__/Navigator.test.js:93:40)
    
      ● Navigator › shows as a modal if modal config is true
    
        expect(jest.fn()).toHaveBeenCalledWith(...expected)
    
        Expected: "/:context/:contextID/announcements/:announcementID", {"announcementID": "3", "context": "courses", "contextID": "1", "location": Any<Object>, "screenInstanceID": Any<String>}, {"canBecomeMaster": false, "disableSwipeDownToDismissModal": true, "embedInNavigationController": true, "modal": true, "modalPresentationStyle": "formsheet"}
    
        Number of calls: 0
    
          122 |     })
          123 | 
        > 124 |     expect(NativeModules.Helm.present).toHaveBeenCalledWith(
              |                                        ^
          125 |       '/:context/:contextID/announcements/:announcementID',
          126 |       { context: 'courses', contextID: '1', announcementID: '3', screenInstanceID: expect.any(String), location: expect.any(Object) },
          127 |       { canBecomeMaster: false, embedInNavigationController: true, modal: true, modalPresentationStyle: 'formsheet', disableSwipeDownToDismissModal: true }
    
          at Object.<anonymous> (src/routing/__tests__/Navigator.test.js:124:40)
    
    
    Test Suites: 1 failed, 173 passed, 174 total
    Tests:       5 failed, 1145 passed, 1150 total
    Snapshots:   272 passed, 272 total
    Time:        133.724s
</details>


[MBL-15651](https://instructure.atlassian.net/browse/MBL-15651)

#### Affected Apps: Parent, Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/114965185/p/79fc08678c01b79f3e6072a99622c64e">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/114965190/p/f541e3edc354de6e8066727b401ccd72">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/114965177/p/182a18be2036807563dde3638d00afa4">
    
  </a>
</details>

**Comment by vargaat** [comment]
Screenshot 2022-02-25 at 11 35 50

**Review by idevainstr — APPROVED** [review]
QA+1 🏅

**Pull request merged**
