### PR TITLE
Don't save announcement plannables

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-14728
affects: Student, Teacher
release note: Hide announcements on calendar to match web

### CODE REVIEW

**Comment by vanwagonet** [comment]
Test Plan: See ticket. The announcement should not show up that did on the 9/9

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



[MBL-14728](https://instructure.atlassian.net/browse/MBL-14728)

#### Affected Apps: Student, Teacher

#### Release Note: 
Hide announcements on calendar to match web
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/50130727/p/8a344c2d89abded0fb1a33b61939610c">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/50130744/p/a6c6e90a0f1606723dc7fcb538d03c26">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/50130700/p/6d232057124fc4a9b3df8f065f866648">
    
  </a>
</details>

**Comment by armstrongnate** [comment]
I think you meant to have this affect `Parent`, not `Teacher`. Could you make that fix when you squash and merge so that it gets included in parent release notes?

**Review by armstrongnate — APPROVED** [review]
I suppose this is fine for Parent app because they can get announcements via alerts.

**Pull request merged**
