### PR TITLE
Improve accessibility in inbox

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-14910
affects: Student, Teacher
release note: Improved accessibility.

test plan: See ticket.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/75934367/p/3d5e3dc31666c93a57b0d1f991794006">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/75934379/p/ca936d83a9167058fdad75e29ea5a59f">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/75934348/p/79e6e614aa42da66f71e531c112f8402">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.84% | 91.84% | 0%
Core/Core/Dashboard/K5/ViewModel/K5DashboardViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Grades/K5GradesViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/K5DashboardNavigationViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Schedule/K5ScheduleViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Homeroom/K5HomeroomViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Resources/K5ResourcesViewModel.swift | 0% | 0% | 0%

[MBL-14910](https://instructure.atlassian.net/browse/MBL-14910)

#### Affected Apps: Student, Teacher

#### Release Note: 
Improved accessibility.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
