### PR TITLE
Polish CourseList & remove it from nativeDashboard flag

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-14926
affects: Teacher, Student
release note: Moved managing favorites to updated All Courses list

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/56413132/p/d6ca8bf65c82f2adea3dab3a5e1c3d96">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/56413153/p/9619edc1e4823ff26bc88940b9222e89">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/56413068/p/bd62ea556b6d69fd55090e76de1a60a1">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/Core/Courses/CourseListView.swift:100:5: Large Tuple Violation: Tuples should have at most 2 members. (large_tuple)
    
    
</details>


[MBL-14926](https://instructure.atlassian.net/browse/MBL-14926)

#### Affected Apps: Teacher, Student

#### Release Note: 
Moved managing favorites to updated All Courses list
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by vargaat — APPROVED** [review]

**Comment by vargaat** [comment]
On iOS 13.0 the term text is cropped although there's still space, I don't know if we can do anything with it. Otherwise looks good.

**Comment by vanwagonet** [comment]
I'll get that fixed.

**Review by vargaat — APPROVED** [review]

**Comment by vargaat** [comment]
QA+1

**Pull request merged**
