### PR TITLE
Groups in soft-concluded courses show up on dashboard and give error

### PR DESCRIPTION
**Pull request by idevainstr**
Fix groups scope for group without a course.

refs: MBL-15336
affects: Student
release note: none
test plan: see ticket

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/79763153/p/2c29f79f2d3148ba713431c983bddafd">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/79763162/p/2350feee477750a80f4be658b976c4fa">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/79763115/p/a54a5134ab62a56505a8dc847456bf68">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add only one affects.
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add only one release note.
  </td>
    </tr>
  </tbody>
</table>



Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.97% | 91.97% | 0%

[MBL-15336](https://instructure.atlassian.net/browse/MBL-15336)

#### Affected Apps: Student

#### Release Note: 
Hide concluded course groups on the dashboard.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Pull request merged**
