### PR TITLE
Add description text color

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-16203
affects: Student
release note: Fix todo item description color in dark mode.
test plan: Check ticket

### CODE REVIEW

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.65% | 91.65% | 0%

[MBL-16203](https://instructure.atlassian.net/browse/MBL-16203)

#### Affected Apps: Student

#### Release Note: 
Fix todo item description color in dark mode.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
