### PR TITLE
Email Notification Settings throws error

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15616
affects: Student
release note: Fix email notification settings.
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/90742621/p/23275ec2a4bbe3b218a066d4b3d2dc98">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/90742634/p/910bff5a221f419126ce60e2d08e0e8c">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/90742612/p/eaf574dc0a10d12f95c03f86b1dc62c4">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.81% | 91.81% | -0%

[MBL-15616](https://instructure.atlassian.net/browse/MBL-15616)

#### Affected Apps: Student

#### Release Note: 
Fix email notification settings.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
