### PR TITLE
Fix course action sheet from showing same course twice

### PR DESCRIPTION
**Pull request by shichongrui**
refs: MBL-13788
affects: parent
release note: none

Test Plan: see ticket for credentials
 - In the inbox for the user the course CS1400
   should show up multiple times.
 - Ignore blank CS 2810 student name, this is
   just bad data from the api

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Parent

[MBL-13788](https://instructure.atlassian.net/browse/MBL-13788)

<details><summary>:x: XCTest failed: CoreTests/LoginWebViewControllerTests/testPreloaded</summary>


    Assertion Failure: LoginWebViewControllerTests.swift:61: Asynchronous wait failed: Exceeded timeout of 9 seconds, with unfulfilled expectations: "credentials get posted".
    Assertion Failure: LoginWebViewControllerTests.swift:62: XCTAssertEqual failed: ("nil") is not equal to ("Optional(https://localhost:1/?username=u&password=p)")
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1018462&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|23
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Pull request merged**
