### PR TITLE
Fix group submission comment upload when using share extension

### PR DESCRIPTION
**Pull request by szabinst**
refs: MBL-17690
affects: Student
release note: Fixed group submission comment not being uploaded when using share extension
test plan: See ticket but use *.beta.instructure.com environment by logging in on the web and generate QR code to log in on mobile. 

## Checklist

- [ ] Follow-up e2e test ticket created
- [x] Tested on phone
- [x] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Fixed group submission comment not being uploaded when using share extension

#### Affected Apps: Student

[MBL-17690](https://instructure.atlassian.net/browse/MBL-17690)

<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/CoreTests/Files/FileSubmission/Model/PrepareUpload/FileSubmissionComposerTests.swift:40:1: Trailing Whitespace Violation: Lines should not have trailing whitespace (trailing_whitespace)
    /Users/vagrant/git/Core/CoreTests/Files/FileSubmission/Model/FileSubmissionAssemblyTests.swift:44:1: error: Line Length Violation: Line should be 200 characters or less; currently it has 211 characters (line_length)
    /Users/vagrant/git/Core/CoreTests/Files/FileSubmission/Model/Submission/FileSubmissionSubmitterTests.swift:83:1: error: Trailing Whitespace Violation: Lines should not have trailing whitespace (trailing_whitespace)
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5da9f35c824a71ea8ba1670372ffa8e80ad28f4c
</p>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by ndrsszsz — APPROVED** [review]
QA +1
Tested on iPad, iOS 16.7.1

**Pull request merged**
