### PR TITLE
Submission details enhancement

### PR DESCRIPTION
**Pull request by szabinst**
refs: MBL-16515
affects: Student, Teacher
release note: none
test plan: See ticket

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
<tr>
<td></td>
<td></td>
<tr>
<td></td>
<td></td>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [x] Tested on phone
- [x] Tested on tablet
- [x] Tested in dark mode
- [x] Tested in light mode
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/Core/Extensions/InstIconExtensions.swift:440:1: Trailing Whitespace Violation: Lines should not have trailing whitespace (trailing_whitespace)
    /Users/vagrant/git/rn/Teacher/ios/TeacherTests/SpeedGrader/SubmissionCommentListViewModelTests.swift:27:102: error: Comma Spacing Violation: There should be no space before and one after any comma (comma)
    
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ae190a07fbd6e819ce1e299ae1f8b53ba9b1f838
</p>

**Comment by balintbartok** [comment]
Submission sensitive comment is not showing in real time, always the last submission's comments are visible. They are added to the right attempt, but needs re-selection
https://github.com/instructure/canvas-ios/assets/72031065/f882d6ec-1856-48ed-98ca-a49254febe56

**Comment by szabinst** [comment]
thanks @balintbartok , I'll look into it.

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by vargaat — CHANGES_REQUESTED** [review]
Upon rotation the selection indicator doesn't properly reposition under the selected tab. Also in landscape mode the tab's text seems to be not centered on the indicator or the indicator is at the wrong position.

https://github.com/instructure/canvas-ios/assets/72396990/949cdc97-113e-426f-b31a-39710a1bf337

**Review by vargaat — APPROVED** [review]
QA+1

**Review by balintbartok — COMMENTED** [review]
QA + 1

**Pull request merged**
