### PR TITLE
Confused action buttons on edit assignment dialog

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15479
affects: Teacher
release note: Fix navigation bar buttons on the assignment editor screen.
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/82023512/p/2b3ea4e5ddef075a7976da95eecec161">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/82023559/p/a4815fa04e3099465c0432169c52f0b2">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/82023443/p/e164e1a02e71502a310813fd62b1202b">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: JS tests</summary>


    Summary of all failing tests
     FAIL  src/modules/assignment-due-dates/__tests__/AssignmentDueDates.test.js
      ● routes to assignment edit
    
        expect(jest.fn()).toHaveBeenCalledWith(...expected)
    
        - Expected
        + Received
    
          "/courses/1/assignments/1/edit",
          Object {
        +   "embedInNavigationController": false,
            "modal": true,
          },
    
        Number of calls: 1
    
          116 |   const editButton: any = explore(tree).selectRightBarButton('assignment-due-dates.edit-btn')
          117 |   editButton.action()
        > 118 |   expect(props.navigator.show).toHaveBeenCalledWith('/courses/1/assignments/1/edit', { modal: true })
              |                                ^
          119 | })
          120 | 
          121 | test('routes to quiz edit', () => {
    
          at Object.<anonymous> (src/modules/assignment-due-dates/__tests__/AssignmentDueDates.test.js:118:32)
    
      ● routes to quiz edit
    
        expect(jest.fn()).toHaveBeenCalledWith(...expected)
    
        - Expected
        + Received
    
          "/courses/1/quizzes/2/edit",
          Object {
        +   "embedInNavigationController": false,
            "modal": true,
          },
    
        Number of calls: 1
    
          132 |   const editButton: any = explore(tree).selectRightBarButton('assignment-due-dates.edit-btn')
          133 |   editButton.action()
        > 134 |   expect(props.navigator.show).toHaveBeenCalledWith('/courses/1/quizzes/2/edit', { modal: true })
              |                                ^
          135 | })
          136 | 
          137 | test('null assignment', () => {
    
          at Object.<anonymous> (src/modules/assignment-due-dates/__tests__/AssignmentDueDates.test.js:134:32)
    
    
    Test Suites: 1 failed, 173 passed, 174 total
    Tests:       2 failed, 1153 passed, 1155 total
    Snapshots:   273 passed, 273 total
    Time:        97.193s
</details>


[MBL-15479](https://instructure.atlassian.net/browse/MBL-15479)

#### Affected Apps: Teacher

#### Release Note: 
Fix navigation bar buttons on the assignment editor screen.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by davidvarga93** [comment]
Nightly tests:
https://app.bitrise.io/build/012354b0-6689-428e-820c-4d1f006dfeed#?tab=log

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
