### PR TITLE
Move FileAnnotations inside DocViewerAnnotataionProvider

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-15223
affects: Teacher
release note: Fixed annotation orientation on rotated submissions

test plan: see ticket, only new annotations will save correctly (check green arrows at bottom)

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/Core/DocViewer/DocViewerAnnotationProvider.swift:41:1: Line Length Violation: Line should be 200 characters or less: currently 201 characters (line_length)
    /Users/vagrant/git/Core/Core/DocViewer/DocViewerViewController.swift:106:1: error: Line Length Violation: Line should be 200 characters or less: currently 233 characters (line_length)
    
</details>


[MBL-15223](https://instructure.atlassian.net/browse/MBL-15223)

#### Affected Apps: Teacher

#### Release Note: 
Fixed annotation orientation on rotated submissions
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/78723769/p/93b0762496fe42f3269d3e920b4756ce">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/78723783/p/8570c9be1c4d3ad84823e9b70b52e1ef">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/78723759/p/70a6da6731b15e3a36d94791facc006d">
    
  </a>
</details>

**Review by idevainstr — APPROVED** [review]
QA+1 🏅

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
