### PR TITLE
Fix calendar course color contrast

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-16509
affects: Student
release note: Fixed the Course color contrast ratio on the Calendar screen.
test plan: See ticket.

--- edit or delete this section ---
## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Tested on phone
- [x] Tested on tablet
- [x] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/PlannerListViewControllerTests/testLayout</summary>


    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x60001bf159c0; provider = <__NSMallocBlock__: 0x60002eed0de0>>)") is not equal to ("Optional(UIExtendedSRGBColorSpace 1 0 0 1)")
</details>


[MBL-16509](https://instructure.atlassian.net/browse/MBL-16509)

#### Affected Apps: Student

#### Release Note: 
Fixed the Course color contrast ratio on the Calendar screen.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by vargaat — CHANGES_REQUESTED** [review]
Seems like the grade pill's text color isn't darkened correctly.

**Review by vargaat — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by szabinst — APPROVED** [review]
QA + 1

**Pull request merged**
