### PR TITLE
Remove unused code which were based on the available iOS version

### PR DESCRIPTION
**Pull request by vargaat**
affects: Student, Teacher, Parent

[ignore-commit-lint]

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: StudentUnitTests/AssignmentRemindersInteractorLiveTests/testListsRemindersInChronologicalOrder</summary>


    failed - waitUntil timed out
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a9ecc37e95c41e1db1e9c6592d1ff66cf331f10b
</p>

**Review by rh12 — APPROVED** [review]

**Review by szabinst — APPROVED** [review]

**Pull request merged**
