### PR TITLE
Dark mode for hybrid discussions

### PR DESCRIPTION
**Pull request by szabinst**
refs: MBL-16423
affects: Student, Teacher
release note: none
test plan: Test normal discussions, group discussions, announcements

## Screenshots

<table>
<tr><th>Announcement - Dark</th><th>Announcement - Light</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr><th>Regular Discussion - Dark</th><th>Regular Discussion - Light</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr><th>Acc. lvl group Discussion - Dark</th><th>Acc. lvl group Discussion - Light</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student, Teacher

[MBL-16423](https://instructure.atlassian.net/browse/MBL-16423)

<details><summary>:x: XCTest failed: StudentUnitTests/RoutesTests/testFallbackAbsoluteHTTPs</summary>


    Unknown command type <NSBatchDeleteRequest : resultType : 0, fetch :<NSFetchRequest: 0x600002b40d90> (entity: AccountNotification; predicate: ((null)); sortDescriptors: ((null)); type: NSManagedObjectIDResultType; includesPropertyValues: NO; includesPendingChanges: NO; ) > (NSInternalInconsistencyException)
</details>
<details><summary>:x: XCTest failed: StudentUnitTests/RoutesTests/testFallbackAuthenticatedError</summary>


    Unknown command type <NSBatchDeleteRequest : resultType : 0, fetch :<NSFetchRequest: 0x600002b404d0> (entity: AccountNotification; predicate: ((null)); sortDescriptors: ((null)); type: NSManagedObjectIDResultType; includesPropertyValues: NO; includesPendingChanges: NO; ) > (NSInternalInconsistencyException)
</details>
<details><summary>:x: XCTest failed: StudentUnitTests/RoutesTests/testFallbackNonHTTP</summary>


    Unknown command type <NSBatchDeleteRequest : resultType : 0, fetch :<NSFetchRequest: 0x600002b3c1c0> (entity: AccountNotification; predicate: ((null)); sortDescriptors: ((null)); type: NSManagedObjectIDResultType; includesPropertyValues: NO; includesPendingChanges: NO; ) > (NSInternalInconsistencyException)
</details>
<details><summary>:x: XCTest failed: StudentUnitTests/RoutesTests/testFallbackOpensAuthenticatedSession</summary>


    Unknown command type <NSBatchDeleteRequest : resultType : 0, fetch :<NSFetchRequest: 0x600002b44070> (entity: AccountNotification; predicate: ((null)); sortDescriptors: ((null)); type: NSManagedObjectIDResultType; includesPropertyValues: NO; includesPendingChanges: NO; ) > (NSInternalInconsistencyException)
</details>
<details><summary>:x: XCTest failed: StudentUnitTests/RoutesTests/testFallbackRelative</summary>


    Unknown command type <NSBatchDeleteRequest : resultType : 0, fetch :<NSFetchRequest: 0x600002b327d0> (entity: AccountNotification; predicate: ((null)); sortDescriptors: ((null)); type: NSManagedObjectIDResultType; includesPropertyValues: NO; includesPendingChanges: NO; ) > (NSInternalInconsistencyException)
</details>
<details><summary>:x: XCTest failed: StudentUnitTests/RoutesTests/testHybridAnnouncementDiscussionDetailsRoute</summary>


    Unknown command type <NSBatchDeleteRequest : resultType : 0, fetch :<NSFetchRequest: 0x600002b48310> (entity: AccountNotification; predicate: ((null)); sortDescriptors: ((null)); type: NSManagedObjectIDResultType; includesPropertyValues: NO; includesPendingChanges: NO; ) > (NSInternalInconsistencyException)
</details>
<details><summary>:x: XCTest failed: StudentUnitTests/RoutesTests/testHybridDiscussionDetailsRoute</summary>


    Unknown command type <NSBatchDeleteRequest : resultType : 0, fetch :<NSFetchRequest: 0x600002b2fa30> (entity: AccountNotification; predicate: ((null)); sortDescriptors: ((null)); type: NSManagedObjectIDResultType; includesPropertyValues: NO; includesPendingChanges: NO; ) > (NSInternalInconsistencyException)
</details>
<details><summary>:x: XCTest failed: StudentUnitTests/RoutesTests/testHybridGroupAnnouncementDiscussionDetailsRoute</summary>


    Unknown command type <NSBatchDeleteRequest : resultType : 0, fetch :<NSFetchRequest: 0x600002b48690> (entity: AccountNotification; predicate: ((null)); sortDescriptors: ((null)); type: NSManagedObjectIDResultType; includesPropertyValues: NO; includesPendingChanges: NO; ) > (NSInternalInconsistencyException)
</details>
<details><summary>:x: XCTest failed: StudentUnitTests/RoutesTests/testHybridGroupDiscussionDetailsRoute</summary>


    Unknown command type <NSBatchDeleteRequest : resultType : 0, fetch :<NSFetchRequest: 0x600002b3d180> (entity: AccountNotification; predicate: ((null)); sortDescriptors: ((null)); type: NSManagedObjectIDResultType; includesPropertyValues: NO; includesPendingChanges: NO; ) > (NSInternalInconsistencyException)
</details>
<details><summary>:x: XCTest failed: TeacherTests/RoutesTests/testHybridAnnouncementDiscussionDetailsRoute</summary>


    Unknown command type <NSBatchDeleteRequest : resultType : 0, fetch :<NSFetchRequest: 0x6000029baa70> (entity: AccountNotification; predicate: ((null)); sortDescriptors: ((null)); type: NSManagedObjectIDResultType; includesPropertyValues: NO; includesPendingChanges: NO; ) > (NSInternalInconsistencyException)
</details>
:x: (and 4 other test failures)

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0f809afc43355b05221009bdea4aaf1df8c18f36
</p>

**Review by vargaat — CHANGES_REQUESTED** [review]
A noticed a few thing we could improvement

1. Loading a discussion/announcement presents a white screen for a moment which could be unpleasant at night using dark mode. Video [here](https://github.com/instructure/canvas-ios/assets/72396990/b298f1a1-3916-4506-85fa-ac8f57e7eef4). 
2. If a discussion is embedded into a module sequence then the pull to refresh gesture reveals a white background area.<br/>
3. We could check if we could ignore various elements from being inverted like profile pictures or videos.<br/>
4. The "Switch To Light Mode" button isn't rendered most of the time only after I try to swipe one page back. Video [here](https://github.com/instructure/canvas-ios/assets/72396990/ae3df814-8f34-42b9-82e8-bf48b4eb17df).

**Comment by szabinst** [comment]
@vargaat Fixed all the picture, video related issues.

**Review by vargaat — CHANGES_REQUESTED** [review]
The color invert looks nice now, good job on that! Unfortunately, the "Switch To Light Mode" button is broken now. The screen blinks for a moment and I can see that the underlying viewcontroller got changed to white theme when doing a pull to refresh but the web content stays dark.

**Review by vargaat — APPROVED** [review]
QA+1, We might improve the dark mode colors in the future by creating a separate CSS specifically tailored for the discussion html content.

**Review by balintbartok — DISMISSED** [review]
QA + 1

**Review by vargaat — APPROVED** [review]

**Pull request merged**
