### PR TITLE
Add a11y identifier for the grade slider

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-15126
affects: Teacher
release note: none

test plan:
*check a submission with a grade slider and use voiceover

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.07% | 92.07% | 0%

[MBL-15126](https://instructure.atlassian.net/browse/MBL-15126)

#### Affected Apps: Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/71537815/p/c5735b48e0b71fcf5ea17d2c60a88260">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/71537822/p/a16d841b756db3a4d9172ee9b41d1099">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/71537791/p/e4dbc9fa6fb43219fb0ebe8fdb6c495e">
    
  </a>
</details>

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
