### PR TITLE
Facelift main calendar UI

### PR DESCRIPTION
**Pull request by rh12**
refs: [MBL-17286](https://instructure.atlassian.net/browse/MBL-17286)
affects: Student, Teacher, Parent
release note: none

## What's new
- Changed Today button icon & added day text
- Adjusted Year label font & spacing
- Adjusted Month button font & spacing
- Changed dropdown icon to chevronDown
- Adjusted Calendars button font
- Fixed Calendars button alignment to not jump around when month is changing
- Adjusted Weekday labels font & fixed automatic resizing
- Adjusted Day button font
- Changed Day button selected/today styles to match new design
- Fixed clipping issues after rotation
- Added bottom divider to last Event
- Adjusted Event cell spacings
- Added "To Do" text after course name for ToDos
- Added calendar color for ToDos in list
- Added calendar color to the left side of selected Event and adjusted selected color

Maintenance:
- Removed obsolete `Plannable.save()` method

## What's not changed
- Did not update Event cell fonts
- Did not fix existing Calendar Days view & Panda views a11y issues
- Already done: "Color event icon and course name based on course color"
- Did not add course name & color to Parent app events

## Test plan
See changes above, compare with [Figma](https://www.figma.com/file/asf3Fh7xqLsFpVOJND5QLd/%E2%9C%85-%5BDelivered%5D-(Canvas-Teacher)-Calendar-V01--Marci?type=design&node-id=6884-63220&mode=design&t=aupjKtaSqmnjGwHs-4)

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist
- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [ ] Tested on phone portrait
- [ ] Tested on phone landscape
- [x] Tested on tablet
- [x] Tested in dark mode
- [x] Tested in light mode
- [ ] Approve from product

[MBL-17286]: https://instructure.atlassian.net/browse/MBL-17286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student, Teacher, Parent

[MBL-17286](https://instructure.atlassian.net/browse/MBL-17286)

<details><summary>:x: XCTest failed: CoreTests/CalendarViewControllerTests/testLayout</summary>


    XCTAssertEqual failed: ("Optional(32.0)") is not equal to ("Optional(28.0)")
    XCTAssertGreaterThanOrEqual failed: ("859.0") is less than ("883.0")
    XCTAssertEqual failed: ("244.0") is not equal to ("264.0")
    XCTAssertEqual failed: ("52.0") is not equal to ("48.0")
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 45809aabe16c3a4d0d7a5436412866f88f4f0187
</p>

**Review by vargaat — APPROVED** [review]
QA+1

I just noticed that we have double day selection indicators that looks strange while scrolling through months. This is not a regression however so we can improve this later.

Screenshot 2024-05-27 at 09 58 01

**Review by szabinst — APPROVED** [review]
QA + 1, Looks good!

**Comment by rh12** [comment]
> I just noticed that we have double day selection indicators that looks strange while scrolling through months. This is not a regression however so we can improve this later.

Good point, thanks! As discussed in private, I took a note for future improvement and discussion.

**Pull request merged**
