### PR TITLE
Automatically mark read visible entries 1 second after scrolling ends

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-14432
affects: Student, Teacher
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/af3kpqv) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Faf3kpqv)
teacher: [Link](https://rebrand.ly/akdt02y) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fakdt02y)
parent: [Link](https://rebrand.ly/8ddzm6u) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2F8ddzm6u)

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student, Teacher

[MBL-14432](https://instructure.atlassian.net/browse/MBL-14432)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.54% | 94.29% | -0.74%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by vanwagonet** [comment]
Test Plan:
- With a user create some new posts.
- With a different user view that discussion. If at least a line of the unread entry stays visible without you scrolling, it should mark itself as read
- Force mark an entry as unread
- Verify it won't automark as read again

Note that the deep nested replies view isn't expected to work yet

**Comment by bluwave** [comment]
Looks like it's working.  There is a big flash of all the user avatars when it marks them as read.

**Comment by vanwagonet** [comment]
Yeah, I think I'm going to need to try something else for the renderer to make updates less terrible.

**Pull request merged**
