### PR TITLE
Add confetti for on-time submission

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-14302
affects: Student
release note: Added support for celebrations for on-time submissions

### CODE REVIEW

**Comment by vanwagonet** [comment]
I was going to add a test to SubmitButtonPresenterTests, but they are all x-ed out right now, so I didn't.

**Comment by vanwagonet** [comment]
Test Plan:
- make sure you have enabled the account level flag & not enabled the "disable celebrations" user flag.
- submit an assignment that isn't past due from either the empty submission or assignment detail screen. You should see confetti.
- submit an assignment that is past due. no confetti
- enable the "disable celebrations" flag for the user
- submit another on-time, no confetti.

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/riol3dj) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Friol3dj)
teacher: [Link](https://rebrand.ly/l004h15) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fl004h15)
parent: [Link](https://rebrand.ly/qtlae0l) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fqtlae0l)

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Added support for celebrations for on-time submissions

#### Affected Apps: Student

[MBL-14302](https://instructure.atlassian.net/browse/MBL-14302)

<details><summary>:x: Swift lint</summary>


    ⚠️  /Users/vagrant/git/Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift:320:23: Empty Parentheses with Trailing Closure Violation: When using trailing closures, empty parentheses should be avoided after the method call. (empty_parentheses_with_trailing_closure)
    /Users/vagrant/git/Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift:311:9: warning: Opening Brace Spacing Violation: Opening braces should be preceded by a single space and on the same line as the declaration. (opening_brace)
    Linting 'SubmissionCommentAttemptCell.swift' (71/122)
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Pull request merged**
