### PR TITLE
Fix crash in File Upload in Quiz

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-13514
affects: Student
release note: Fixed a crash in a Quiz uploading a file on iPad

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1011491&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by inst-danger** [comment]
#### Release Note: 
Fixed a crash in a Quiz uploading a file on iPad

#### Affected Apps: Student

[MBL-13514](https://instructure.atlassian.net/browse/MBL-13514)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.16% | 93.16% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by armstrongnate** [comment]
I'm getting errors when I take a photo on the fly or choose a photo from `Choose a Photo or Video` option. Using `Browse` and `Record Audio` worked fine.

IMG_337CB2AD185B-1

**Comment by vanwagonet** [comment]
Fix crash, reveal additional bugs. :sigh:

**Pull request merged**
