### PR TITLE
Move & refactor Attendance into Teacher

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-13251
affects: Teacher
release note: Fixed branding colors in Attendance

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by vanwagonet** [comment]
Notable user facing changes:
- support for dark mode & high contrast
- fixed some jank in date picker
- date picker button shows current date instead of always "3"
- only show icons for Present, Late, & Absent. No icon is shown for unmarked (nil).
- fixed modal title to use textDarkest
- style the "mark all present" button as primary button with branding colors
- font size changes in date picker headers

Notable under the hood changes:
- moved to Teacher, since it is never used in Student or Parent apps
- use core icons & colors instead of it's own assets
- code style cleanup, use Core helpers where possible

Planned changes in subsequent PR:
- refactor `RollCallSession` & related apis to use Core `API`.
- refactor `RollCallSession` to use `WKWebView` instead of `UIWebView`.

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1009953&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Fixed branding colors in Attendance

#### Affected Apps: Teacher

[MBL-13251](https://instructure.atlassian.net/browse/MBL-13251)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.22% | 93.24% | -2.02%
rn/Teacher/ios/Attendance/RollCallSession.swift | 0% | -- | --
rn/Teacher/ios/Attendance/CKIClient+AuthorizedSections.swift | 0% | -- | --
rn/Teacher/ios/Attendance/Status.swift | 21% | -- | --
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Pull request merged**
