### PR TITLE
Handle not supported font traits.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15544
affects: Student
release note: none

test plan: See ticket.

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.97% | 91.98% | -0%

[MBL-15544](https://instructure.atlassian.net/browse/MBL-15544)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/83526812/p/4187e4692cf09eb424f62043ab92e223">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/83526834/p/5c015bbb55629f0a1a58fea2d6159d07">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/83526788/p/87fe94ed24610cb3407174a58e59ff97">
    
  </a>
</details>

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
