### PR TITLE
Grade slider can give incorrect score if assignment is worth a decimal number

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15292
affects: Teacher
release note: Fixed grade slider decimal value and hold features.

test plan:
- set up an assignment with decimal grade points (eg. 10.5)
- add a student submission
- move the grade slider to the maximum on the submission grading pane
- the slider should be able to take up even values and then the maximal decimal value
- the slider should support holding the slider button on the min/max values and toggle no mark/excused states accordingly.

### CODE REVIEW

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.07% | 92.06% | 0.01%

[MBL-15292](https://instructure.atlassian.net/browse/MBL-15292)

#### Affected Apps: Teacher

#### Release Note: 
Fixed grade slider decimal value and hold features.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/70070005/p/a3ba2b6eda11a10a9d4422cd55e8b4c8">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/70070016/p/5b86cbebb39f9c01e682e37622de92b7">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/70069998/p/537c44d89823fd3d6c3f0cd1b8bef7cf">
    
  </a>
</details>

**Review by balintbartok — CHANGES_REQUESTED** [review]
middle of the slider can't be selected, e.g. if 10 points is the max, you can't select 5

**Review by balintbartok — APPROVED** [review]
QA + 1
nice work with all the tests!

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
