### PR TITLE
Fix announcement order when paging is active

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15732
affects: Student, Teacher
release note: Fixed announcements getting out of order if there were more than 100.

test plan: See ticket.

### CODE REVIEW

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.47% | 91.46% | 0.01%

[MBL-15732](https://instructure.atlassian.net/browse/MBL-15732)

#### Affected Apps: Student, Teacher

#### Release Note: 
Fixed announcements getting out of order if there were more than 100.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/103760434/p/300a82190f903b38297926dd4f7780f5">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/103760465/p/bb51b60cf54b1120ae75c9212c166665">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/103760397/p/3a1584f6061ebf47e48836ecae38603d">
    
  </a>
</details>

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
