### PR TITLE
Execute custom js in discussions

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-14713
affects: Student, Teacher
release note: Fixed custom js in discussions

### CODE REVIEW

**Comment by vanwagonet** [comment]
Test Plan: See ticket. You should get a red banner at the top of the discussion if custom js worked.

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/ImageLoaderTests/testLoadSvg</summary>


    Assertion Failure: UIImageViewExtensionsTests.swift:123: Asynchronous wait failed: Exceeded timeout of 9 seconds, with unfulfilled expectations: "Expect predicate `loadedURL != nil` for object -[ImageLoaderTests testLoadSvg]".
</details>


[MBL-14713](https://instructure.atlassian.net/browse/MBL-14713)

#### Affected Apps: Student, Teacher

#### Release Note: 
Fixed custom js in discussions
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/49993317/p/375e23de9becfc751ab313d7a1fbb407">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/49993318/p/79b0afc1466324deaaa7095bc8039f28">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/49993313/p/41c49b3c9bcc1cff2d06abc14ab68d5b">
    
  </a>
</details>

**Review by armstrongnate — APPROVED** [review]
QA +1

**Pull request merged**
