### PR TITLE
Remove Core, Student, TestsFoundation project files

### PR DESCRIPTION
**Pull request by szabinst**
Remove Core, Student, TestsFoundation project files

- Removed Core.xcodeproj, Student.xcodeproj, TestsFoundation.xcodeproj.
- Added them to gitignore
- Deleted TestsFoundation project, moved the TestsFoundation target under Core project.

To update XcodeGen locally, call `brew upgrade xcodegen`. 
Calling  `make sync` will (re)generate the project files but the changes will be ignored in git.  

affects: Student, Teacher, Parent 
[ignore-commit-lint]

## Checklist

- [x] Tested on phone
- [ ] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 03760e47dda4446090bf5b9ecf81b515a1690a6b
</p>

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Review by ndrsszsz — APPROVED** [review]

**Review by vargaat — DISMISSED** [review]

**Review by rh12 — APPROVED** [review]

**Review by ndrsszsz — APPROVED** [review]

**Pull request merged**
