### PR TITLE
Show error if self registration is not allowed

### PR DESCRIPTION
**Pull request by armstrongnate**
Also removes QR feature flags.

refs: MBL-14722
affects: parent
release note: Added a message for parents that try to create an account using the QR code pairing feature when self registration is not allowed

test plan:
1. On web, go to account settings > Authentication
2. Set `Self registration` to `All account types`
3. Parent app > QR Login > I don't have an account > Scan student QR code
4. You should get the self registration form
5. Set `Self registration` to `Observer accounts only`
6. Repeat step 3
7. You should get the self registration form
8. Set `Self registration` to `Disabled`
9. Repeat step 3
10. You should get an error alert

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/52337504/p/ba3235baefcdbd3fe3436923742e6687">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/52337506/p/56ac2ad0fa88dc3ba08899c34d898261">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/52337491/p/79a7d3eacfd4a896b11feaaea90a3b36">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: Swift lint</summary>


    ⚠️  /Users/vagrant/git/Core/Core/Profile/Settings/PairWithObserverViewController.swift:46:1: Superfluous Disable Command Violation: SwiftLint rule 'line_length' did not trigger a violation in the disabled region. Please remove the disable command. (superfluous_disable_command)
    [student]
    [teacher]
</details>
<details><summary>:x: XCTest failed: CoreTests/APIURLTests/testCodableValid</summary>


    Assertion Failure at APITests.swift:320: XCTAssertNotNil failed
</details>
<details><summary>:x: XCTest failed: CoreTests/PairWithObserverViewControllerTests/testRender</summary>


    Assertion Failure at PairWithObserverViewControllerTests.swift:41: XCTAssertEqual failed: ("Optional("")") is not equal to ("Optional("code")")
    Assertion Failure at PairWithObserverViewControllerTests.swift:44: XCTAssertEqual failed: ("-150.0") is not equal to ("8.0")
    Assertion Failure at PairWithObserverViewControllerTests.swift:46: XCTAssertEqual failed: ("Optional("https://canvas.instructure.com/files/1/download")") is not equal to ("Optional("code")")
</details>
<details><summary>:x: XCTest failed: ParentUnitTests/AddStudentControllerTests/testAddPairingCodeError</summary>


    Assertion Failure at AddStudentControllerTests.swift:62: XCTUnwrap failed: expected non-nil value of type "UIAlertController"
</details>
<details><summary>:x: XCTest failed: ParentUnitTests/AddStudentControllerTests/testAddPairingCodeInput</summary>


    Assertion Failure at AddStudentControllerTests.swift:50: XCTUnwrap failed: expected non-nil value of type "UIAlertController"
</details>
<details><summary>:x: XCTest failed: ParentUnitTests/AddStudentControllerTests/testLayout</summary>


    Assertion Failure at AddStudentControllerTests.swift:33: XCTUnwrap failed: expected non-nil value of type "UIAlertController"
</details>


[MBL-14722](https://instructure.atlassian.net/browse/MBL-14722)

#### Affected Apps: Parent

#### Release Note: 
Added a message for parents that try to create an account using the QR code pairing feature when self registration is not allowed
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by armstrongnate** [comment]
These failing tests look legit. Will fix.

**Comment by armstrongnate** [comment]
Tests pass. That coverage report is very confused.

**Pull request merged**
