### PR TITLE
Fix duplicated modules list on screen.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-17019
affects: Student
release note: none

test plan:
- Create a course with modules as home page.
- Log in to the student app with a split view capable device and go to the course's details.
- Modules should display in the detail view.
- Tap on modules on the master list.
- Modules list should appear on the master list and the detail view should show an empty state instead of displaying also the modules list.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Tested on phone
- [x] Tested on tablet
- [ ] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-17019](https://instructure.atlassian.net/browse/MBL-17019)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.42% | 92.42% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 53eddd4f8a78083a04a2203d512a68a931fb0760
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by ndrsszsz — APPROVED** [review]
QA +1

**Pull request merged**
