### PR TITLE
Fix linking for iOS 14

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15704
affects: Student, Teacher, Parent
release note: none
test plan: the build should not crash on start/restart under iOS 14.x

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/12bdbab6-654f-4678-947b-f227574e50b6/artifact/e37b246f5f641f53/p/cdbb7397974cc5a71c175ae0b69fe157">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/12bdbab6-654f-4678-947b-f227574e50b6/artifact/3eb6b2e189a56963/p/2219e8c9442803a0a92d28fa6ed8371b">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/12bdbab6-654f-4678-947b-f227574e50b6/artifact/4da9eaf78f4020f6/p/59223c7281f59ad9fc77a7d7fc78e39f">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.82% | 91.81% | 0.01%

[MBL-15704](https://instructure.atlassian.net/browse/MBL-15704)

#### Affected Apps: Student, Teacher, Parent
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — CHANGES_REQUESTED** [review]
still crashy

**Review by davidvarga93 — APPROVED** [review]
QA + 1
Looks good on iPad 14.6

**Review by balintbartok — APPROVED** [review]

**Pull request merged**
