### PR TITLE
Remove settings button from quiz submissions list screen.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15538
affects: Teacher
release note: none

test plan: See ticket.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/83505657/p/fd020c31d0fe76da3385d1b5ba93391b">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/83505668/p/6a765b93e866cf0a477d647b9d99c2ec">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/83505648/p/329aeeefd9fc86076b51fc2594edfa9e">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.97% | 91.97% | -0%

[MBL-15538](https://instructure.atlassian.net/browse/MBL-15538)

#### Affected Apps: Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
