### PR TITLE
Remove deprecated, unused field

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-16181
affects: Student, Teacher, Parent
release note: Fix showing public classes with sections.
test plan: Check ticket

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



[MBL-16181](https://instructure.atlassian.net/browse/MBL-16181)

#### Affected Apps: Student, Teacher, Parent

#### Release Note: 
Fix showing public classes with sections.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
