### PR TITLE
Fix Home when front page

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBL-13960
affects: student
release note: Fixed loading the course Home page

Test plan:
* Turn on new_page_details feature flag and make sure a course Home page loads when it is set to Front page
* See [ticket](https://instructure.atlassian.net/browse/MBL-13960)
* Or narmstrong > s > CS 1400 > Home

### CODE REVIEW

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/o94sw4h) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fo94sw4h)
teacher: [Link](https://rebrand.ly/jmct6u1) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fjmct6u1)
parent: [Link](https://rebrand.ly/uvdfeez) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fuvdfeez)

**Comment by inst-danger** [comment]
#### Release Note: 
Fixed loading the course Home page

#### Affected Apps: Student

[MBL-13960](https://instructure.atlassian.net/browse/MBL-13960)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.62% | 93.63% | -0.01%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1022153&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|17
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Pull request merged**
