### PR TITLE
Discussion redesign introduction

### PR DESCRIPTION
**Pull request by vargaat**
What's new:
- Added a website preview screen to the developer menu. You can enter a custom url and add headers fields to load that url in a webview. This is to support future hybrid website integration tests.
- Added a feature flag called hybrid_discussion_details. If this is turned on along with the web's "Discussions/Announcements Redesign" flag then the app will load a course's discussion details in a web view.

Not yet supported:
- Discussions opened from a course or account group.
- Pull to refresh.
- Course announcements.

refs: MBL-15976
affects: Student, Teacher
release note: none

test plan: 
- Check the website preview screen in the Developer Menu > WebSite Preview.
- Enable discussion redesign flag on web and in the app and enter a course discussion's details screen.

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please run `yarn update-headers`. The following do not have the correct license header: 
* Core/Core/WebSitePreview/ViewModel/WebSitePreviewViewModel.swift
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


<details><summary>:x: Yarn lint</summary>


    
    /Users/vagrant/git/rn/Teacher/src/modules/developer-menu/DeveloperMenu.js
      176:1  error  Expected indentation of 4 spaces but found 6  indent
      177:1  error  Expected indentation of 4 spaces but found 6  indent
    
    ✖ 2 problems (2 errors, 0 warnings)
      2 errors and 0 warnings potentially fixable with the `--fix` option.
    
</details>


[MBL-15976](https://instructure.atlassian.net/browse/MBL-15976)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/1bae07bf-6096-472c-bb56-d3f1f1a75208/artifact/44c77a6712298ced/p/2878fb0be9b527c9459b04656120eaa4">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/1bae07bf-6096-472c-bb56-d3f1f1a75208/artifact/2dbad3d00716da30/p/7f130d9781ee91cde1a2c56f5df7d3f6">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/1bae07bf-6096-472c-bb56-d3f1f1a75208/artifact/8147921bac9a9e88/p/68741581c75fa156d70fce1d3b0db011">
    
  </a>
</details>

**Comment by balintbartok** [comment]
IMG_0053
Works as expected, there is more work to do in the future, group discussion is a known issue, I noticed the previous/next buttons being duplicated (in case of modules)

**Review by balintbartok — APPROVED** [review]

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
