### PR TITLE
Fix ActAsUser param not being added

### PR DESCRIPTION
**Pull request by szabinst**
refs: MBL-17413
affects: Student, Teacher
release note: Fixed an issue where File Upload was not possible when using Student View. Fixed act as user not loading the impersonated user's dashboard.
test plan: See ticket

## Checklist

- [x] Tested on phone
- [ ] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by ndrsszsz — APPROVED** [review]
QA +1

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
