### PR TITLE
Date picker saved default value will not update by min, max values if out of range

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-16287
affects: Teacher
release note: Fix date picker date range handling logic.
test plan: See ticket.

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] A11y checked
- [x] Tested on phone
- [x] Tested on tablet
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.69% | 91.68% | 0%

[MBL-16287](https://instructure.atlassian.net/browse/MBL-16287)

#### Affected Apps: Teacher

#### Release Note: 
Fix date picker date range handling logic.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by balintbartok — APPROVED** [review]

**Pull request merged**
