### PR TITLE
Group people page UI glitches

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15917
affects: Student
release note: none
test plan: see ticket

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.47% | 91.47% | 0%

[MBL-15917](https://instructure.atlassian.net/browse/MBL-15917)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/115023136/p/0c6ca51813c241c53ac1064bb51bbbcc">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/115023190/p/2e1b4e83b8b00bc394ef8716bc95af67">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/115023091/p/046830b2de9f5002ebc279d547dee8a9">
    
  </a>
</details>

**Review by balintbartok — APPROVED** [review]

**Comment by vargaat** [comment]
QA+1

**Review by vargaat — APPROVED** [review]

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
