### PR TITLE
Fix file upload state inconsistency

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15296
affects: Student
release note: Fixed assignment details screen indicating a successful submission while the assignment is still not submitted.

test plan: See ticket.

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: StudentUnitTests/AssignmentDetailsViewControllerTests/testUpdateGradeCellWhenThereIsUploadState</summary>


    Assertion Failure at AssignmentDetailsViewControllerTests.swift:213: XCTAssertEqual failed: ("Optional("Resubmission Failed")") is not equal to ("Optional("Submission Failed")")
</details>
<details><summary>:x: XCTest failed: StudentUnitTests/AssignmentDetailsViewControllerTests/testUpdateGradeCellWhenThereIsUploadStateAndUnsubmitted</summary>


    Assertion Failure at AssignmentDetailsViewControllerTests.swift:233: XCTAssertEqual failed: ("Optional("Resubmission Failed")") is not equal to ("Optional("Submission Failed")")
</details>
<details><summary>:x: XCTest failed: StudentUnitTests/AssignmentDetailsViewControllerTests/testUpdateUpdateSubmissionLabelsFailedState</summary>


    Assertion Failure at AssignmentDetailsViewControllerTests.swift:263: XCTAssertEqual failed: ("Optional("Resubmission Failed")") is not equal to ("Optional("Submission Failed")")
</details>


[MBL-15296](https://instructure.atlassian.net/browse/MBL-15296)

#### Affected Apps: Student

#### Release Note: 
Fixed assignment details screen indicating a successful submission while the assignment is still not submitted.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74211154/p/b3dbcdf5afabc5eb5d2efb0200d00ae1">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74211162/p/ba1aea0f6778acf9d51f5412b9df011f">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74211144/p/915d0d403b9712f57a7d219c06dc3169">
    
  </a>
</details>

**Comment by davidvarga93** [comment]
QA +1 manual

**Review by balintbartok — COMMENTED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
