### PR TITLE
Parent E2E Tests - ChangeUser, Logout, Courses, Calendar

### PR DESCRIPTION
**Pull request by ndrsszsz**
[Bitrise - Canvas iOS - Parent - E2ETests](https://app.bitrise.io/build/3e9827cb-03cd-4a3e-a3a5-ea6a5c0d5c8a)
(Failing because of the input field bug on Manage Students page)

- ChangeUserTests
- LogoutTests
- CoursesTests
- CalendarTests
- Fix for failing Student, Teacher tests

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



#### Release Note: 
None

#### Affected Apps: None

[MBL-17130](https://instructure.atlassian.net/browse/MBL-17130)

<details><summary>:x: XCTest failed: StudentUnitTests/RoutesTests/testRoutes</summary>


    Test crashed with signal abrt.
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a7249750a81494c7ba2563fc954e3b47f195b897
</p>

**Review by vargaat — APPROVED** [review]

**Review by szabinst — APPROVED** [review]

**Pull request merged**
