### PR TITLE
Display rubric even if there is no assessment

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-12695
affects: Student
release note: none

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by bluwave** [comment]
my pr relies so heavily on the selected index.  What if were to add a flag to the circleView like `viewOnly` or `nonAssessView = true` or something.  Currently with Dave's changes, you can have 2 circles that are selected.  If we throw another state in there, I'd think the cell would need it's own presenter.  Just some thoughts.  Not sure what the best solution is.

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1000149&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|1
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---
High|1

**Comment by vanwagonet** [comment]
> my pr relies so heavily on the selected index. What if were to add a flag to the circleView like `viewOnly` or `nonAssessView = true` or something. Currently with Dave's changes, you can have 2 circles that are selected. If we throw another state in there, I'd think the cell would need it's own presenter. Just some thoughts. Not sure what the best solution is.

This isn't a new state, you could always see non-selected ratings. Even in the new design, just one of the selected kinds doesn't happen, which you already had to support for all the ratings the grader didn't pick.

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-12695](https://instructure.atlassian.net/browse/MBL-12695)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Core** | 95.15% | 95.15% | 0%
**Student** | 92.7% | 92.69% | 0.01%
**Teacher** | 100% | 100% | 0%
**React Native** | 92.77% | 92.77% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by vanwagonet** [comment]
If this clashes too much with the rubric update PR, I'm fine abandoning it. We just need to be able to display the rubric without an assessment.

**Comment by bluwave** [comment]
I have a commit for this stashed that works w/ my branch once I get my branch in there.

**Pull request closed without merging**
