### PR TITLE
Fix pages greying out

### PR DESCRIPTION
**Pull request by balintbartok**
refs: none
affects: Parent, Student, Teacher
release note: none
test plan:
* Parent: check grades list and click on grading period title

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.48% | 91.48% | 0%

#### Affected Apps: Parent, Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/104330976/p/98edfe5c289f0ad537e8777726a02121">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/104330988/p/7c6e5f22cba52baefc46a4d1b69e602b">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/104330941/p/bc05caa356ff3e2f3104c9fcd717a669">
    
  </a>
</details>

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
