### PR TITLE
Update cell text styles

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16071
affects: Parent, Student, Teacher
release note: none

test plan:
Check if main list cells are displayed correctly.

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/bdfec950-8c3a-4b24-82e5-158e5f79706a/artifact/1f4a83d7010dc763/p/eb455f3d56a0296a571d59c371ac3fce">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/bdfec950-8c3a-4b24-82e5-158e5f79706a/artifact/09cf5204bfc239e0/p/23045fa189da04267ee5716f9971cc62">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/bdfec950-8c3a-4b24-82e5-158e5f79706a/artifact/37180f2a2f9b6650/p/0db2852560938ef65dc22272ab7cc0db">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


<details><summary>:x: XCTest failed: CoreTests/PlannerListViewControllerTests/testLayout</summary>


    Assertion Failure at PlannerListViewControllerTests.swift:85: XCTAssertEqual failed: ("Optional("")") is not equal to ("nil")
</details>


[MBL-16071](https://instructure.atlassian.net/browse/MBL-16071)

#### Affected Apps: Parent, Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by balintbartok — COMMENTED** [review]
not really sure, that it's related to this PR, but doesn't happen on the latest release:
Teacher ->assignment->submissions->eye icon (post/hide grades), iOS14 iPad, the post grade button flashes, then disappears

**Pull request merged**
