### PR TITLE
Offline file version control

### PR DESCRIPTION
**Pull request by szabinst**
refs: MBL-16808
affects: Student
release note: none
test: 

Unchanged file:
1. Sync a file
2. Sync the same file again  - Download shouldn't happen 

Changed file: 
1. Sync a file
2. Log in as teacher on web, rename this file
3. Sync the same file again - It should be downloaded 

## Checklist

- [x] Tested on phone
- [ ] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-16808](https://instructure.atlassian.net/browse/MBL-16808)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.4% | 92.4% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b2f180dec9b83acfae885a27d7bd8acf764e5507
</p>

**Review by idevainstr — DISMISSED** [review]
QA +1

**Review by vargaat — DISMISSED** [review]
QA+1

**Review by vargaat — APPROVED** [review]

**Pull request merged**
