### PR TITLE
Users unable to upload profile picture in app (sfu)

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-16626
affects: Student, Teacher, Parent
release note: Fixed users unable to upload profile picture in app on self hosted domains.
test plan: See ticket.

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Release Note: 
Fixed users unable to upload profile picture in app on self hosted domains.

#### Affected Apps: Student, Teacher, Parent

[MBL-16626](https://instructure.atlassian.net/browse/MBL-16626)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.91% | 91.93% | -0.02%
Core/Core/Courses/CourseDetails/ViewModel/CourseDetailsViewModel.swift | 48.89% | 48.89% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d22ccb6042fae2bad85a5d9cbb92c229d59f87dc
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by vargaat — CHANGES_REQUESTED** [review]
The profile picture upload for the self-hosted instance and on my sandbox works but I wasn't able to submit a file to a submission. From another PR and on the store version file submission works. Please check on that.

**Comment by ndrsszsz** [comment]
On iPad, in teacher app, when I choose a pic from the gallery and click okay, I get this error:

image

**Review by szabinst — DISMISSED** [review]
QA + 1

**Review by vargaat — APPROVED** [review]
QA+1

**Review by szabinst — APPROVED** [review]
QA + 1

**Pull request merged**
