### PR TITLE
Fix iOS 14 datepicker on the calendar's new to do page

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15329
affects: Student
release note: Fixed date picker for iOS 14 on the Calendar's new todo page.

test plan:
see ticket

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73420576/p/4704f4d95ce75a182ae8ab2693a63534">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73420585/p/9e5ebecfbe52a4b354014c575864e21b">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73420566/p/0732b2da9181709217a211f297ec8c5b">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92% | 92% | 0%

[MBL-15329](https://instructure.atlassian.net/browse/MBL-15329)

#### Affected Apps: Student

#### Release Note: 
Fixed date picker for iOS 14 on the Calendar's new todo page.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
