### PR TITLE
Grading scheme letter grade does not appear in total mark

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15799
affects: Student, Parent
release note: Show grade letter on the grades page.
test plan: See ticket.

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.47% | 91.47% | 0%

[MBL-15799](https://instructure.atlassian.net/browse/MBL-15799)

#### Affected Apps: Student

#### Release Note: 
Show grade letter on the grades page.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/107155073/p/009969a0ac29df86b1a7052514c50274">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/107155079/p/85f43db05d3a928f02c81821bc7763dc">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/107155070/p/7cc4de9f6265f32f0d449b7e52240743">
    
  </a>
</details>

**Review by vargaat — APPROVED** [review]
QA+1

This also fixes the same issue in the parent app so when merging we should include that app as well in the affects field of the commit message.

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
