### PR TITLE
Added TestPlan and Scheme for PR tests including all UI tests

### PR DESCRIPTION
**Pull request by davidvarga93**
refs: MBL-16250
affects: Student, Teacher, Parent
release note: none

test plan:

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.57% | 91.57% | 0%
Core/Core/Dashboard/ViewModel/FileUploadNotificationCardListViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/ViewModel/FileUploadNotificationCardItemViewModel.swift | 0% | 0% | 0%
Core/Core/Files/FileSubmission/Model/FileSubmissionAssembly.swift | 0% | 0% | 0%

[MBL-16250](https://instructure.atlassian.net/browse/MBL-16250)

#### Affected Apps: Student, Teacher, Parent
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by vargaat — APPROVED** [review]

**Review by idevainstr — APPROVED** [review]
seems legit

**Pull request merged**
