### PR TITLE
Show the proper rubric description

### PR DESCRIPTION
**Pull request by shichongrui**
refs: MBL-13210
affects: student
release note: Fixed a bug where viewing a description of a rubric item would show the incorrect description

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1006505&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by inst-danger** [comment]
#### Release Note: 
Fixed a bug where viewing a description of a rubric item would show the incorrect description

#### Affected Apps: Student

[MBL-13210](https://instructure.atlassian.net/browse/MBL-13210)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.12% | 93.11% | 0.01%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by armstrongnate** [comment]
QA+1

**Pull request merged**
