### PR TITLE
Use native QuizList in Teacher

### PR DESCRIPTION
**Pull request by vanwagonet**
This also changes the section header to match RN one, since many lists are still using it & consistency is nice.

refs: none
affects: Teacher
release note: Improved order of quizzes

### CODE REVIEW

**Comment by vanwagonet** [comment]
Test Plan:
* In Student, verify the published icons are not shown
* In Teacher, verify the published icons are shown appropriately
* In Teacher, verify the list groups match the order of web & the items more closely match web. I think there are still some order differences related to items with multiple due dates, but the native list is much closer to web than the RN list was.

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/53765971/p/652b51f0c7e9a1f6ac60ea05654395ea">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/53765978/p/cba89ca6b40eb141c80a66e4c479b72c">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/53765931/p/3602212c7dccf9eac30699d21207c171">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.24% | -- | --

#### Affected Apps: Teacher

#### Release Note: 
Improved order of quizzes
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by armstrongnate — DISMISSED** [review]
QA +1 nice job!

**Review by armstrongnate — APPROVED** [review]

**Pull request merged**
