### PR TITLE
Students can see replies on discussions that have not yet started

### PR DESCRIPTION
**Pull request by idevainstr**
affects: Student
release note: Hide replies for future discussions in the Student app.
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74697856/p/6195dce698b3e24a7356e7ef5c67af64">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74697887/p/4d1762cc379442f28693aec77c86d5fa">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74697836/p/5f0495c6485e395e7afcd16823f8623a">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.03% | 92.03% | 0%

[MBL-15337](https://instructure.atlassian.net/browse/MBL-15337)

#### Affected Apps: Student

#### Release Note: 
Hide replies for future discussions in the Student app.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — DISMISSED** [review]
QA + 1

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
