### PR TITLE
Show missing tag for all submission types

### PR DESCRIPTION
**Pull request by szabinst**
refs: MBL-17468
affects: Student, Parent
release note: Missing tag is visible for all submission types now.
test plan: See ticket, check web.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Tested on phone
- [x] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
#### Release Note: 
Missing tag is visible for all submission types now.

#### Affected Apps: Student, Parent

[MBL-17468](https://instructure.atlassian.net/browse/MBL-17468)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.87% | 91.87% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d6e0b4133161584333451cfec4edc9ab89d2012a
</p>

**Review by ndrsszsz — DISMISSED** [review]
QA +1

**Review by vargaat — COMMENTED** [review]
I wonder if we want to display this tag on the assignment details page as well? On web the missing tag is displayed and on android side we have this implemented as well.

**Review by vargaat — APPROVED** [review]
QA+1

**Comment by ndrsszsz** [comment]
It seems to be not working on for me now. Or am I missing something?

IMG_196D393EDFB9-1

**Review by ndrsszsz — APPROVED** [review]
I don't understand the logic, but it's in parity with the web app so I approve this PR.

QA +1
Tested on iPad

**Pull request merged**
