### PR TITLE
Fix file upload progress

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-13566
affects: Student
release note: Fixed an issue with reporting submission upload progress

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by vanwagonet** [comment]
Looks like a previous commit fixed the basic upload status on the details screen, but the view file upload progress wasn't working.

The bug would only manifest on assignments that accepted both file uploads & media recordings.

**Comment by inst-danger** [comment]
#### Release Note: 
Fixed an issue with reporting submission upload progress

#### Affected Apps: Student

[MBL-13566](https://instructure.atlassian.net/browse/MBL-13566)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.19% | 79.37% | 13.82%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1012656&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|3
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---
High|3

**Pull request merged**
