### PR TITLE
Add score statistics

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBL-14710
affects: student
release note: Added support for assignment score statistics

### CODE REVIEW

**Comment by armstrongnate** [comment]
Based on #1421

**Comment by armstrongnate** [comment]
@ndrewh,

We'll merge from this PR so that all of the CI checks run.

I removed the fixed height at runtime so that the graph is only as tall as needs to be. I also updated the labels to be consistent with web and localized them as well.

Your feedback here is welcome.

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/thexk9k) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fthexk9k)
teacher: [Link](https://rebrand.ly/wz4fq78) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fwz4fq78)
parent: [Link](https://rebrand.ly/k9fy7uv) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fk9fy7uv)

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add a reference to a jira ticket. For example: `refs: MBL-10023`
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: Swift lint</summary>


    ⚠️  /Users/vagrant/git/Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsPresenterTests.swift:315:1: Line Length Violation: Line should be 200 characters or less: currently 263 characters (line_length)
    [teacher]
    [parent]
</details>


#### Affected Apps: Student

#### Release Note: 
Add assignment score statistics (min, max, mean) for graded assignments
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by armstrongnate** [comment]
@vanwagonet danger mad about a ref in the commit message but I have one in the pr body. should be fine.

**Review by vanwagonet — APPROVED** [review]
QA+1

**Comment by ndrewh** [comment]
Thank you very much @armstrongnate! I'm pleased to see this feature added to the mobile app and am happy to have helped.

**Pull request merged**
