### PR TITLE
Skip flaky tests

### PR DESCRIPTION
**Pull request by shichongrui**
refs: none
affects: none
release note: none

See https://app.bitrise.io/build/4b45aacb33152112#?tab=log and https://app.bitrise.io/build/101a312e940eee1c#?tab=log

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by armstrongnate** [comment]
Have you created tickets in JIRA for these?

**Comment by shichongrui** [comment]
Currently in the process of doing so.

**Comment by armstrongnate** [comment]
Thanks!

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1005483&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by shichongrui** [comment]
Don't need this anymore.

**Pull request closed without merging**
