### PR TITLE
Filter out threshold alerts for courses where quantitative data restriction is enabled

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-17542
affects: Parent
release note: Threshold alerts are hidden now for courses where quantitative data restriction is enabled.

test plan:
- Have a course where restrict quantitative data is disabled.
- Set up alert threshold for a student in parent app.
- Grade a submission in a way to trigger the threshold.
- Open the parent app and check the alert.
- Turn on restrict quantitative data for the course.
- Refresh the alerts page and check if the alerts have disappeared.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [x] Tested on phone
- [ ] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Threshold alerts are hidden for courses where quantitative data restriction is enabled.

#### Affected Apps: Parent

[MBL-17542](https://instructure.atlassian.net/browse/MBL-17542)

<details><summary>:x: XCTest failed: CoreTests/CourseSyncCleanupInteractorTests/testSharedOfflineDirectoryForUserDeleted</summary>


    XCTAssertFalse failed
</details>
<details><summary>:x: XCTest failed: ParentUnitTests/ObserverAlertsInteractorTests/testLoadsAlertsWhereQuantitativeDataIsNotEnabled</summary>


    XCTAssertEqual failed: ("Optional(["c2", "c1"])") is not equal to ("Optional(["c1", "c2"])")
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d612a15d700b71b9dc5c0a69c38adfc88886d8e9
</p>

**Review by rh12 — APPROVED** [review]
QA + 1

**Review by szabinst — APPROVED** [review]
QA + 1

**Pull request merged**
