### PR TITLE
render tests for global nav

### PR DESCRIPTION
**Pull request by bluwave**
refs: MBL-13536
affects: Student
release note: none

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-13536](https://instructure.atlassian.net/browse/MBL-13536)

<details><summary>:x: XCTest failed: CoreTests/APIErroReportTests/testMaximalPostErrorReportRequest</summary>


    Assertion Failure: APIErrorReportTests.swift:79: XCTAssertEqual failed: ("Optional(["Hostname": "https://canvas.instructure.com", "User": "1", "Email": "automated-test-Eve@instructure.com", "extra": "info", "App Version": "1.0 (1)", "Platform": "iPhone", "OS Version": "13.2.2"])") is not equal to ("Optional(["App Version": "1.0 (1)", "OS Version": "13.2.2", "extra": "info", "Platform": "iPhone", "User": "1", "Hostname": "https://canvas.instructure.com"])")
</details>
<details><summary>:x: XCTest failed: CoreTests/APIErroReportTests/testMinimalPostErrorReportRequest</summary>


    Assertion Failure: APIErrorReportTests.swift:27: XCTAssertEqual failed: ("Optional("\n\n\n-----------------------------------\nUser: 1\nEmail: automated-test-Eve@instructure.com\nHostname: https://canvas.instructure.com\nApp Version: 1.0 (1)\nPlatform: iPhone\nOS Version: 13.2.2\n-----------------------------------")") is not equal to ("Optional("\n\n\n-----------------------------------\nUser: 1\nEmail: \nHostname: https://canvas.instructure.com\nApp Version: 1.0 (1)\nPlatform: iPhone\nOS Version: 13.2.2\n-----------------------------------")")
    Assertion Failure: APIErrorReportTests.swift:42: XCTAssertEqual failed: ("Optional(["User": "1", "Hostname": "https://canvas.instructure.com", "OS Version": "13.2.2", "Email": "automated-test-Eve@instructure.com", "App Version": "1.0 (1)", "Platform": "iPhone"])") is not equal to ("Optional(["User": "1", "App Version": "1.0 (1)", "OS Version": "13.2.2", "Platform": "iPhone", "Hostname": "https://canvas.instructure.com"])")
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1013982&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by vanwagonet** [comment]
Not sure how the test failing have anything to do with this change, but it's worth looking into, or at least retriggering.

**Pull request merged**
