### PR TITLE
User profile display full name instead of display name

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15130
affects: Student, Teacher
release note: Fix display name in side menu.
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/79914192/p/678299ac57eab0e38d6cec34618c27ff">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/79914215/p/4d9296b82d9b05e52ea9cb4fc9aa899b">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/79914168/p/6b19955e773fc3cb5d3e76356dc97e42">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.97% | 91.97% | 0%

[MBL-15130](https://instructure.atlassian.net/browse/MBL-15130)

#### Affected Apps: Student, Teacher

#### Release Note: 
Fix display name in side menu.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
