### PR TITLE
Enabled embedded videos on the front page to play

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-17604
affects: Parent
release note: Enabled embedded videos on the front page to play.

test plan:
- Create a page that has a embedded Studio video in it.
- Set this page as the course home.
- Start the parent app and check if the embedded video loads.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [x] Tested on phone
- [ ] Tested on tablet
- [x] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
#### Release Note: 
Enabled embedded videos on the front page to play.

#### Affected Apps: Parent

[MBL-17604](https://instructure.atlassian.net/browse/MBL-17604)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.54% | 91.54% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e42e3b9ad011046853523a65075e6e531e2681d0
</p>

**Review by rh12 — APPROVED** [review]
QA + 1

**Review by szabinst — APPROVED** [review]
QA+1

**Review by ndrsszsz — APPROVED** [review]
QA +1

**Pull request merged**
