### PR TITLE
Fix accent marks not appearing in discussions and announcements

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-17167
affects: Student, Teacher
release note: Fixed accent marks not appearing in discussions and announcements.

test plan: See ticket for details. Check if special characters discussed in MBL-17012 load the web based discussion instead of showing an empty page.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Tested on phone
- [ ] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Release Note: 
Fixed accent marks not appearing in discussions and announcements.

#### Affected Apps: Student, Teacher

[MBL-17167](https://instructure.atlassian.net/browse/MBL-17167)
[MBL-17012](https://instructure.atlassian.net/browse/MBL-17012)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.66% | 91.66% | -0%
Core/Core/Inbox/ComposeMessage/Model/ComposeMessageInteractorLive.swift | 0% | 0% | 0%
Core/Core/Inbox/ComposeMessage/ViewModel/ComposeMessageViewModel.swift | 33.97% | 33.97% | 0%
Core/Core/Inbox/Addressbook/ViewModel/AddressbookViewModel.swift | 0% | 0% | 0%
Core/Core/Inbox/Addressbook/Model/AddressbookInteractorLive.swift | 0% | 0% | 0%
Core/Core/Inbox/ComposeMessage/Model/MessageParameters.swift | 0% | 0% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 470863403aa342d69b9cc7fb6a3cec93854dae00
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
