### PR TITLE
Correct default allowed attempt number in Quiz Editor

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-17139
affects: Teacher
release note: Fixed multiple attempt setting in classic quiz editor.

test plan: see ticket

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Fixed multiple attempt setting in classic quiz editor.

#### Affected Apps: Teacher

[MBL-17139](https://instructure.atlassian.net/browse/MBL-17139)

<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/CoreTests/Quizzes/QuizDetails/QuizEditorViewModelTests.swift:293:1: Trailing Whitespace Violation: Lines should not have trailing whitespace (trailing_whitespace)
    
    
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a836794c87686e68bf1a81eefe09cc770e6def09
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by szabinst — APPROVED** [review]
QA + 1

**Pull request merged**
