### PR TITLE
Change keep alive request method from GET to HEAD

### PR DESCRIPTION
**Pull request by rh12**
refs: [MBL-15465](https://instructure.atlassian.net/browse/MBL-15465)
affects: Student, Teacher, Parent
release note: none

## What's changed
- Changed keep alive request method from `GET` to `HEAD`
- Changed keep alive request path from `/users/self` to `/`
- Fixed initial request duplication

## Test plan
- Observe requests sent to `https://*.instructure.com/`
  - Make sure you are not filtering only for the given app, but for the domain
- Start the app
- Find the first `HEAD https://*.instructure.com/?session_token=...` request
  - Verify it's response code is `302`
  - Verify it's response header has `Set-Cookie` with `canvas_session`
- Verify it's followed by a `HEAD https://*.instructure.com/` request
  - Verify it's response code is `200`
  - Verify it's request header has `canvas_session` cookie matching the value set in the previous request
- Verify it doesn't cause any failing requests

[MBL-15465]: https://instructure.atlassian.net/browse/MBL-15465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student, Teacher, Parent

[MBL-15465](https://instructure.atlassian.net/browse/MBL-15465)

<details><summary>:x: XCTest failed: StudentUnitTests/AssignmentRemindersInteractorLiveTests/testListsRemindersInChronologicalOrder</summary>


    failed - waitUntil timed out
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 016b5724c38ae3b880800d5158807eed49e087ca
</p>

**Review by vargaat — DISMISSED** [review]
QA+1

**Review by vargaat — APPROVED** [review]

**Review by ndrsszsz — APPROVED** [review]
QA +1

**Pull request merged**
