### PR TITLE
Fix grading periods not displaying total grades.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15718
affects: Parent
release note: Fixed grading periods not displaying total grades when they should.

test plan: See ticket.

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.22% | 91.16% | 0.06%

[MBL-15718](https://instructure.atlassian.net/browse/MBL-15718)

#### Affected Apps: Parent

#### Release Note: 
Fixed grading periods not displaying total grades when they should.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/100800659/p/c0ef3c984009a2593ece6d4d39e19214">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/100800673/p/627146336cfac827dca10ee70c4796fe">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/100800637/p/e62d1340f2f30ed91a897cca53b887ca">
    
  </a>
</details>

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
