### PR TITLE
Course sync progress screen fix

### PR DESCRIPTION
**Pull request by szabinst**
Course sync progress screen fixes

refs: MBL-17178
affects: Student
release note: none
test plan: See ticket

## Checklist

- [x] Tested on phone
- [x] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-17178](https://instructure.atlassian.net/browse/MBL-17178)

<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncNotificationInteractorTests.swift:93:1: Trailing Whitespace Violation: Lines should not have trailing whitespace (trailing_whitespace)
    
    
</details>
<details><summary>:x: XCTest failed: CoreTests/CourseSyncListInteractorLiveTests/testInteractorDeallocationNotCrashesActiveStream</summary>


    Asynchronous wait failed: Exceeded timeout of 1 seconds, with unfulfilled expectations: "".
</details>
<details><summary>:x: XCTest failed: CoreTests/CourseSyncSelectorInteractorLiveTests/testDefaultSelection</summary>


    XCTAssertFalse failed
    XCTAssertEqual failed: ("1") is not equal to ("0")
    XCTAssertEqual failed: ("2") is not equal to ("0")
</details>
<details><summary>:x: XCTest failed: CoreTests/CourseSyncSelectorInteractorLiveTests/testSavesSelectionState</summary>


    XCTAssertEqual failed: ("["courses/1", "courses/2"]") is not equal to ("["courses/2"]")
</details>
<details><summary>:x: XCTest failed: CoreTests/CourseSyncSelectorInteractorLiveTests/testSelectedEntries</summary>


    XCTAssertEqual failed: ("2") is not equal to ("1")
    XCTAssertEqual failed: ("0") is not equal to ("1")
    XCTAssertEqual failed: ("0") is not equal to ("1")
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 62d23a90f35b06ba90a45474a234245b40b43da0
</p>

**Review by balintbartok — DISMISSED** [review]
QA + 1

**Review by vargaat — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]

**Pull request merged**
