### PR TITLE
Use API order for announcements

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-15324
affects: Teacher, Student
release note: Fix imported Announcement ordering

test plan: see ticket
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80498573/p/09acbcbf6ad856ce045af3a6c583fa07">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80498614/p/f0b0397d96cc73a19f42df1fbd79c472">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80498527/p/c0e619d2bdb467a0e07e7a9f07534975">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.97% | 91.96% | 0.01%

[MBL-15324](https://instructure.atlassian.net/browse/MBL-15324)

#### Affected Apps: Teacher, Student

#### Release Note: 
Fix imported Announcement ordering
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
