### PR TITLE
Fix assignment routing for cross shard users.

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15404
affects: Teacher
release note: Fix cross shard user assignments.
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80804318/p/d53f02af0004424398dcbeab3899428a">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80804370/p/41f605c0d985cc238f90d30bc6808632">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80804282/p/616c521def0c890cfa976ad2e4304816">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.98% | 91.98% | -0%

[MBL-15404](https://instructure.atlassian.net/browse/MBL-15404)

#### Affected Apps: Teacher

#### Release Note: 
Fix cross shard user assignments.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
