### PR TITLE
Add commas to todo cells

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-14538
affects: Teacher
release note: Improved accessibility

### CODE REVIEW

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/2k3h4bs) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2F2k3h4bs)
teacher: [Link](https://rebrand.ly/0kkbsxs) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2F0kkbsxs)
parent: [Link](https://rebrand.ly/pjltjp8) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fpjltjp8)

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.4% | 93.4% | 0%

[MBL-14538](https://instructure.atlassian.net/browse/MBL-14538)

#### Affected Apps: Teacher

#### Release Note: 
Improved accessibility
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by cobbal** [comment]
There's a UI test that will need changing too

**Comment by vanwagonet** [comment]
I tested the ad-hoc build, and I think I need to do another pass anyway. There is no comma between published status, title & course name. published status is the hardest, but as is, I don't think this is better enough.

**Pull request merged**
