### PR TITLE
Leave student view button logs out teacher as well

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15915
affects: Student, Teacher
release note: Fixed leaving student view would log out the teacher.
test plan: see ticket

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/115003136/p/59f819357d995b9bba8285ee08a361ab">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/115003144/p/fa9b6953aa00ca7573b75eaf6dc37ff8">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/115003132/p/8a9f1e463e055ceba5a1e96b8b98373d">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.47% | 91.47% | 0%

[MBL-15915](https://instructure.atlassian.net/browse/MBL-15915)

#### Affected Apps: Student, Teacher

#### Release Note: 
Fixed leaving student view would log out the teacher.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
