### PR TITLE
Dashboard course card reorder

### PR DESCRIPTION
**Pull request by vargaat**
### What's new?

- Added drag&drop course card re-order functionality to dashboard for the Student and Teacher apps.
- Course card order is saved to user profile via Canvas API.
- Added a hint to dashboard settings on how the feature works.
- Bumped instui icons to their latest version. Slight changes in icons to be expected. This was done to be able to use the 'sort' icon which wasn't available in the old version we were using.

[ignore-commit-lint]

## Screenshots

<table>
<tr><th>Hint on how re-ordering works</th><th>Reorder in action</th></tr>
<tr>
<td></td>
<td>

https://github.com/instructure/canvas-ios/assets/72396990/d6d3176a-c283-4eb8-bfd2-6a09666a27d6

</td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [x] A11y checked
- [x] Tested on phone
- [x] Tested on tablet
- [x] Tested in dark mode
- [x] Tested in light mode
- [x] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.02% | 92.07% | -0.04%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 683866a4f3021a5f9b6eaa9deb0fdae6bc0cf310
</p>

**Comment by vargaat** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by vargaat** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Review by szabinst — DISMISSED** [review]
awesome feature! QA + 1

**Review by balintbartok — APPROVED** [review]
QA + 
nice!

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by balintbartok — APPROVED** [review]

**Pull request merged**
