### PR TITLE
Fix error when starting Student View

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-14767
affects: Student
release note: Fixed an error when launching from Student View in Teacher app

### CODE REVIEW

**Comment by vanwagonet** [comment]
Test Plan:
- Log in to the Student app with a different student, then launching Student View from the Teacher app
- You should not see any error, and should be logged in appropriately.

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.92% | 92.93% | -0%

[MBL-14767](https://instructure.atlassian.net/browse/MBL-14767)

#### Affected Apps: Student

#### Release Note: 
Fixed an error when launching from Student View in Teacher app
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/50561853/p/6fa759e7a0eb9c5facfcd0f904e6c0d8">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/50561859/p/457c0b476b4e5e86587b7b18fe079bf4">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/50561814/p/433f23373c2f44502c7ee4fc77d4ac46">
    
  </a>
</details>

**Review by armstrongnate — COMMENTED** [review]
I still see the error but it goes away and the Student View launch ends up working.. Is that better than it was?

**Review by armstrongnate — APPROVED** [review]
Installing the app that matters made a big difference.

**Pull request merged**
