### PR TITLE
Fix adding new comments in Speed Grader

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBL-13966
affects: teacher
release note: Fixed adding comments in Speed Grader

Test plan:
* Add a new comment in Speed Grader, ensure it does not Whoops out
* Add a new media comment and make sure it all works
* narmstrong > s
* CS 1400 > Assignments > File Upload > Student 1 > Comments > Add a new text, audio, and video comment

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/r7dvf8b) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fr7dvf8b)
teacher: [Link](https://rebrand.ly/06fa020) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2F06fa020)
parent: [Link](https://rebrand.ly/o305771) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fo305771)

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Fixed adding comments in Speed Grader

#### Affected Apps: Teacher

[MBL-13966](https://instructure.atlassian.net/browse/MBL-13966)

<details><summary>:x: Yarn lint</summary>


    
    /Users/vagrant/git/rn/Teacher/src/modules/speedgrader/comments/__tests__/CommentsTab.test.js
      512:1  error  Block must not be padded by blank lines  padded-blocks
    
    ✖ 1 problem (1 error, 0 warnings)
      1 error and 0 warnings potentially fixable with the `--fix` option.
    
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1022120&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|17
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1022122&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|17
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Pull request merged**
