### PR TITLE
Improve course sync interactor setup

### PR DESCRIPTION
**Pull request by vargaat**
- Extract offline syncable tabs array to a public property.
- Update CourseSyncInteractor to automatically sync all offline syncable tabs.
- Added a safety check that triggers in debug builds when the CourseSyncInteractor received no CourseSyncContentInteractor from the assembly.

CI: I want a Student build so we can check if sync still works.

[ignore-commit-lint]

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.42% | 92.42% | -0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 506989859b1de49116d1bf6edb735d936ba3bb1a
</p>

**Review by idevainstr — APPROVED** [review]
QA +1 🏅

**Review by szabinst — APPROVED** [review]
QA + 1

**Pull request merged**
