### PR TITLE
Add edit courses button on empty dashboard

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15962
affects: Student
release note: Fixed missing edit dashboard button in case there were no active courses on the dashboard.

test plan: 
- Edit dashboard button should be visible even if there are no courses.
- Layout selector button should be hidden in case there are no course cards.
- Interactive empty panda!
- User's groups should be visible even if there are no active courses.
- Empty panda shouldn't be visible for a second upon first login before course cards are displayed.

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/965f271a-17d3-4cc3-91e4-5c2fe3b28108/artifact/60e4e2328730addd/p/22aea17a0196d76ecb08e544d2668fe7">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/965f271a-17d3-4cc3-91e4-5c2fe3b28108/artifact/4ef5f8e7eb45dd21/p/ba7bfe8f271b558e675b3c396394a769">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/965f271a-17d3-4cc3-91e4-5c2fe3b28108/artifact/094b4d4762cb78dc/p/ec6c450a24178559b2f85b1b58a8581b">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.17% | 91.18% | -0%

[MBL-15962](https://instructure.atlassian.net/browse/MBL-15962)

#### Affected Apps: Student

#### Release Note: 
Fixed missing edit dashboard button in case there were no active courses on the dashboard.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
