### PR TITLE
Reset voiceover focus to the top of the page after a screen is loaded as a module sequence item

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15102
affects: Student, Teacher
release note: none

test plan: See ticket.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74487409/p/4f8d7661481acb91af86b4c8fbc83999">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74487440/p/92700193519abc771d18370f613b0a37">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74487379/p/896237a323288d3d3d409e2f67c51c4f">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92% | 92% | 0%

[MBL-15102](https://instructure.atlassian.net/browse/MBL-15102)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1 (tested on iPad)

**Comment by davidvarga93** [comment]
QA +1 manual (iPhone)

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
