### PR TITLE
Remove xml escaping while parsing a url from JSON.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15356
affects: Parent, Student, Teacher
release note: none

test plan: See ticket.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73589557/p/1bf181b01f336f2e8012cc2a3b8f7fe6">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73589575/p/49380aca7e8f386afa94072a675fe23a">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73589530/p/e17af548c3d0444e39e8b8fc38d24374">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/Core/Extensions/StringExtensions.swift:53:27: Trailing Comma Violation: Multi-line collection literals should have trailing commas. (trailing_comma)
    
    
</details>


[MBL-15356](https://instructure.atlassian.net/browse/MBL-15356)

#### Affected Apps: Parent, Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
reviewed

**Pull request merged**
