### PR TITLE
Fix QuizEditor CoreData crash

### PR DESCRIPTION
**Pull request by szabinst**
refs: MBL-16855
affects: Teacher
release note: Fixed an issue where opening quiz editor  crashes the application

I wasn't able to reproduce the issue but my assumption is that making the network requests run after each other, therefore making the core data writes run after each other will resolve the issue. 

## Checklist

- [ ] Tested on phone
- [ ] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Release Note: 
Fixed an issue where opening quiz editor  crashes the application

#### Affected Apps: Teacher

[MBL-16855](https://instructure.atlassian.net/browse/MBL-16855)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.33% | 92.34% | -0.02%
Core/Core/Offline/ViewModel/OfflineModeViewModel.swift | 0% | 0% | 0%
Core/Core/Extensions/BoolExtensions.swift | 0% | 0% | 0%
Core/Core/CourseSync/CourseSyncProgress/Model/CourseSyncProgressInteractor.swift | 0% | 0% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0ff71e1796f630fbc4c7912e6719bccfec3b6ef3
</p>

**Review by balintbartok — APPROVED** [review]

**Review by vargaat — CHANGES_REQUESTED** [review]
The issue here is that the `UseCase.fetch` method calls back on a background thread and from this background thread a synchronous `database.viewContext.fetch` method is called. The view context is bound to the main thread so working with it from a background thread is potentially dangerous. Either the callback blocks from all fetch methods should be dispatched back to the main queue or the work on the view context should be done using a `performAndWait` method. I think the parallel API calls can be safely reverted back to, we do this across the application and should be safe.

**Comment by szabinst** [comment]
@vargaat Good observation, I chose to dispatch the `useCase.fetch's` result to the main queue.

**Review by vargaat — APPROVED** [review]
QA+1

**Review by idevainstr — APPROVED** [review]

**Pull request merged**
