### PR TITLE
Fix Grade screen crash

### PR DESCRIPTION
**Pull request by szabinst**
refs: MBL-17450
affects: Student, Parent
release note: Fixed an issue that caused an occasional crash on Grades Screen.
test plan: Wasn't able to reproduce, check if everything still works.

## Checklist

- [x] Tested on phone
- [x] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Fixed an issue that caused an occasional crash on Grades Screen.

#### Affected Apps: Student, Parent

[MBL-17450](https://instructure.atlassian.net/browse/MBL-17450)

<details><summary>:x: XCTest failed: CoreTests/BackgroundVideoPlayerTests/testDisconnect</summary>


    XCTAssertNil failed: "<AVPlayerViewController: 0x104270e00>"
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0aec486b9f750358bdb7768204d8802720639f54
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
