### PR TITLE
Letter grade only feature

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-16934, MBL-16910, MBL-16916, MBL-16912, MBL-16914, MBL-16918, MBL-16922, MBL-16920, MBL-16928, MBL-16930, MBL-16924
affects: Parent, Student
release note: Added support for restricted view of quantitative data.
test plan: See ticket.

## Checklist

- [x] [Follow-up e2e test ticket created](https://instructure.atlassian.net/browse/MBL-16991)
- [ ] A11y checked
- [x] Tested on phone
- [x] Tested on tablet
- [ ] Tested in dark mode
- [x] Tested in light mode
- [x] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
#### Release Note: 
Added support for restricted view of quantitative data.

#### Affected Apps: Parent, Student

[MBL-16934](https://instructure.atlassian.net/browse/MBL-16934)
[MBL-16910](https://instructure.atlassian.net/browse/MBL-16910)
[MBL-16916](https://instructure.atlassian.net/browse/MBL-16916)
[MBL-16912](https://instructure.atlassian.net/browse/MBL-16912)
[MBL-16914](https://instructure.atlassian.net/browse/MBL-16914)
[MBL-16918](https://instructure.atlassian.net/browse/MBL-16918)
[MBL-16922](https://instructure.atlassian.net/browse/MBL-16922)
[MBL-16920](https://instructure.atlassian.net/browse/MBL-16920)
[MBL-16928](https://instructure.atlassian.net/browse/MBL-16928)
[MBL-16930](https://instructure.atlassian.net/browse/MBL-16930)
[MBL-16924](https://instructure.atlassian.net/browse/MBL-16924)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.44% | 92.4% | 0.03%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5b830b57df9cb866c8b4073057e4384683c9c4d6
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by szabinst — APPROVED** [review]

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
