### PR TITLE
update pspdf kit to 8.2.2 ( to support apple pencle 2nd gen double click )

### PR DESCRIPTION
**Pull request by bluwave**
refs: MBL-12173
affects: Student
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-12173](https://instructure.atlassian.net/browse/MBL-12173)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Core** | 93.92% | 93.9% | 0.02%
**Student** | 93.16% | 93.16% | 0%
**Teacher** | 100% | 100% | 0%
**React Native** | 92.53% | 92.53% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by armstrongnate** [comment]
IMG_B3ED6C4D2DFB-1

See how there are two toolbars at the top?

To repro: Teacher > narmstrong > s/password > CS 1400 > Assignments > File Upload > Long press on submission > tap any of the tools from the black menu that shows up (like eraser) > notice new toolbar at top of screen.

I think we should fix this as part of upgrading PSPDFKit. Either we disable long pressing or we prevent the second toolbar from showing up somehow.

**Comment by bluwave** [comment]
@armstrongnate will i need the pencil to reproduce this?

**Comment by armstrongnate** [comment]
No, it happens when I tap and hold with my finger too.

**Pull request merged**
