### PR TITLE
K5 course cards

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15377
affects: Student
release note: none

test plan: Non-homeroom course cards should work on the K5 dashboard.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/78619817/p/64c5568ee17f195623603f6213de05dd">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/78619824/p/0a86096c19274c60fd606a55303e8037">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/78619798/p/8c3b423c284ab046d265270644039067">
    
  </a>
</details>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Pull request merged**
