### PR TITLE
Fix lock description background color

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-13348
affects: Student
release note: Fixed a flash of grey on locked assignment details

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by bluwave** [comment]
nice 👍

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1007753&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by inst-danger** [comment]
#### Release Note: 
Fixed a flash of grey on locked assignment details

#### Affected Apps: Student

[MBL-13348](https://instructure.atlassian.net/browse/MBL-13348)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.36% | 93.36% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Pull request merged**
