### PR TITLE
Add tap action for numbers at the ends of the Speedgrader slider

### PR DESCRIPTION
**Pull request by idevainstr**
Add tap and long press gesture grading actions on min/max value texts on the grade slider.

refs: MBL-15349
affects: Teacher
release note: Speedgrader slider now supports grading by tapping on the min and max value numbers and no mark / excused on long press.

test plan:
see ticket
try tapping an long press on the min/max values of the slider

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73568034/p/8ea0d4e9803ee28ccae08f8ea39c6fac">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73568061/p/24c87ebd6008d8293fc77da8e857bc46">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73567968/p/f5878e773dea7451c6c568aa7629cf3c">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92% | 92% | 0%

[MBL-15349](https://instructure.atlassian.net/browse/MBL-15349)

#### Affected Apps: Teacher

#### Release Note: 
Speedgrader slider now supports grading by tapping on the min and max value numbers and no mark / excused on long press.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
