### PR TITLE
Update PSPDFKit version

### PR DESCRIPTION
**Pull request by vargaat**
As a side effect of the migration to the new PSPDFKit menu system the Style menu on text highlight annotations got lost. We've never had the Style menu available for the strikeout annotations. Now they are in sync...

refs: MBL-16372
affects: Student, Teacher
release note: none
test plan: 
- Test annotating in general both in the Teacher and Student apps.
- Annotation context menus (the text based menu that appears when you tap on an already existing annotation) got revamped under the hood so take extra care on testing those.

## Checklist

- [x] Tested on iOS 14
- [x] Tested on iPadOS 14
- [x] Tested on iOS 15
- [x] Tested on iPadOS 15
- [x] Tested on iOS 16
- [x] Tested on iPadOS 16

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by szabolcs-instructure — APPROVED** [review]
QA + 1 
iPhone 12, iOS 15.6.1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
