### PR TITLE
Remove context restriction from file details

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBL-13981
affects: student
release note: Fixed a bug that could prevent files from loading

Test plan:
* Make sure file loads from [ticket](https://instructure.atlassian.net/browse/MBL-13981)
* Course and user files should also load (use narmstrong > s)

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/8schmlo) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2F8schmlo)
teacher: [Link](https://rebrand.ly/svby049) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fsvby049)
parent: [Link](https://rebrand.ly/ocr097f) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Focr097f)

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Fixed a bug that could prevent files from loading

#### Affected Apps: Student

[MBL-13981](https://instructure.atlassian.net/browse/MBL-13981)

<details><summary>:x: Swift lint</summary>


    ⚠️  /Users/vagrant/git/Core/CoreTests/Files/FileDetails/FileDetailsViewControllerTests.swift:165:1: Vertical Whitespace Violation: Limit vertical whitespace to a single empty line. Currently 2. (vertical_whitespace)
    Linting 'APIErrorTests.swift' (394/675)
    Linting 'APIModuleRequestableTests.swift' (395/675)
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1022294&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|17
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1022317&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|17
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Pull request merged**
