### PR TITLE
Fix disappearing course.

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-15841
affects: Student, Teacher
release note: Fixed courses with multiple enrollments disappearing from dashboard.

test plan: see ticket, check on K5 as well

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/108700433/p/41ebe3c66f65425647f7ac910660995a">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/108700460/p/aeeb571354f25fadfd1cce1269d9668a">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/108700423/p/4724edef4486d5c831bf78bb0d5312b6">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.5% | 91.49% | 0.01%

[MBL-15841](https://instructure.atlassian.net/browse/MBL-15841)

#### Affected Apps: Student, Teacher

#### Release Note: 
Fixed courses with multiple enrollments disappearing from dashboard.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1 🏅

**Pull request merged**
