### PR TITLE
Add SubmissionsE2E tests for teacher

### PR DESCRIPTION
**Pull request by davidvarga93**
refs: MBL-15509
affects: Teacher
release note: none

test plan:

### CODE REVIEW

**Comment by davidvarga93** [comment]
Nightly:
https://app.bitrise.io/build/566479fa-b5b1-44e8-b88d-9e35045e740f#?tab=log

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.98% | 91.98% | 0%

[MBL-15509](https://instructure.atlassian.net/browse/MBL-15509)

#### Affected Apps: Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by davidvarga93** [comment]
SubmissionsE2ETests
    ✔ testSubmissionsE2E (21.993 seconds)

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/81986290/p/17e02bfdfd81a371c4ea4fc6632ccce8">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/81986294/p/84627f74cade074fa0d21a43799532fc">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/81986286/p/a275336025178dbb6beaa2e4567c32a7">
    
  </a>
</details>

**Review by idevainstr — APPROVED** [review]

**Pull request merged**
