### PR TITLE
Improve k5 grading period selector

### PR DESCRIPTION
**Pull request by tamasiscoming**
refs: MBL-16001
affects: Student
release note: none
test plan: See ticket

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/e81d314c-65f5-4f26-9bf2-407e7a9d6137/artifact/db073bd666ef6927/p/0f035e84b542d76bbd6a14bb85ff6537">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/e81d314c-65f5-4f26-9bf2-407e7a9d6137/artifact/ddc28a90010c6622/p/263806020d0c41ebabcaa68fa3857f1d">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/e81d314c-65f5-4f26-9bf2-407e7a9d6137/artifact/9f49278cb512999d/p/bda34631b8939ad5d8086a9363e5bde7">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.83% | 91.83% | 0%

[MBL-16001](https://instructure.atlassian.net/browse/MBL-16001)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by idevainstr — COMMENTED** [review]
QA+1

**Review by idevainstr — APPROVED** [review]

**Pull request merged**
