### PR TITLE
Fix grade rounding

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-15220
affects: Student, Teacher
release note: Fixed rounding for grades

test plan: see ticket, Grade should be 40 instead of 39.99

### CODE REVIEW

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92% | 92% | -0%

[MBL-15220](https://instructure.atlassian.net/browse/MBL-15220)

#### Affected Apps: Student, Teacher

#### Release Note: 
Fixed rounding for grades
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73749809/p/67ec2b3c98f1fb956df3bdf9eace46ac">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73749818/p/88d8ba36d7e1c6b3837123b0e8b0f0fa">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73749795/p/4ac76cce3ea470c300c58da799462bda">
    
  </a>
</details>

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by vargaat — APPROVED** [review]

**Comment by vargaat** [comment]
QA+1

**Pull request merged**
