### PR TITLE
Graded does not necessarily mean submitted

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-13629
affects: Parent
release note: Fixed an issue where graded missing assignments were not marked missing

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1014747&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by inst-danger** [comment]
#### Release Note: 
Fixed an issue where graded missing assignments were not marked missing

#### Affected Apps: Parent

[MBL-13629](https://instructure.atlassian.net/browse/MBL-13629)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.3% | 93.32% | -0.02%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by armstrongnate** [comment]
What do you think about adding a test for this? I know it won't be particularly straightforward. Is it worth it?

**Comment by armstrongnate** [comment]
I think we take CanvasCore tests case by case. This seems like one of those cases where it's not worth adding unit tests right now. Maybe we can get some time to prime CanvasCore and its models for unit testing some time soon.

Just want to make sure we are calling it out when we don't include tests.

**Comment by armstrongnate** [comment]
An api submission should have a `missing` bool that might make determining missing state easier.

**Comment by armstrongnate** [comment]
Assignment 1 for the user in the ticket is missing but the color is green instead of red.

IMG_9376220AC344-1

**Comment by armstrongnate** [comment]
As an aside: Assignment 1 doesn't show as missing on the Grades list. I'll create a separate ticket for that.

**Pull request merged**
