### PR TITLE
Update PSPDFKit

### PR DESCRIPTION
**Pull request by vargaat**
- Updated PSPDFKit to 12.3.0.
- It turned out that we used a helper method from this SDK for navigation bars that is no longer available.
- I added a new helper method that can be used to set a navigation bar title view with a SwiftUI view.

refs: MBL-16828
affects: Student, Teacher
release note: none

test plan:
- Check if SpeedGrader annotations work.
- Check if student annotation works.
- Check if file submit extension screen titles and offline sync selector title appear.

## Checklist

- [x] Tested on phone
- [ ] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student, Teacher

[MBL-16828](https://instructure.atlassian.net/browse/MBL-16828)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.41% | 92.4% | 0.01%
Core/Core/CourseSync/CourseSyncProgress/Model/CourseSyncProgressInteractor.swift | 0% | 0% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7609c7724256498b8217b979d747efcd9f13566f
</p>

**Comment by vargaat** [comment]
Teacher

**Comment by vargaat** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by idevainstr — CHANGES_REQUESTED** [review]
Student annotation comments won't show up in the Teacher app. Text annotations cut in half or disappear sometimes when revisiting the submission in the Student app.

**Review by szabinst — APPROVED** [review]
QA + 1, iPhone 12, iOS 15.6.1 

I didn't experience those issues Istvan mentioned.

**Review by balintbartok — APPROVED** [review]
QA + 1,
tested on iOS 16.5, iPhone 14

**Review by ndrsszsz — APPROVED** [review]
QA +1
iPhone 11 - iOS 16.5.1

**Comment by vargaat** [comment]
> the rectangle tool has bolder edges with no control to change the line width in the student app, it's thinner in the teacher app.

I could reproduce this on my iOS 16 iPhone, on iOS 15 iPad it worked correctly with thin edges. Looking into it...

**Comment by vargaat** [comment]
> Text annotations cut in half or disappear sometimes when revisiting the submission in the Student app.
I've also seen this one time but I'm unable to reproduce it anymore.

**Comment by vargaat** [comment]
> Student annotation comments won't show up in the Teacher app. 
This worked for me.

**Review by idevainstr — APPROVED** [review]

**Pull request merged**
