### PR TITLE
Use courses API to fetch courses list content

### PR DESCRIPTION
**Pull request by vargaat**
Changes:
- Use new courses API to fetch past, current and future sections of the course list instead of locally calculating availability dates. This is now in sync with the android client.
- Course list CoreData entity is now independent from the shared Course entity fixing a glitch that caused entries on the course list to disappear while navigating back to the dashboard.
- Removed the star option from future enrolments since tapping those had no effect.
- There are discrepancies between the mobile apps and the web interface. In case of inquiries we will reach out to the web/API teams since both of these show strange behaviour.
- Student app no longer displays a green checkmark for published courses.
- Removed the `isFutureEnrollment` calculated property since it's no longer used and added a comment to the 'isPastEnrollment' one explaining its behavior.

refs: MBL-16062
affects: Student, Teacher
release note: none

test plan: Test course list in general.

## Checklist

- [x] Tested on phone
- [x] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add a release note. If no release note is wanted, use `none`. Example: `release note: Fixed a bug that prevented users from enjoying the app.`
  </td>
    </tr>
  </tbody>
</table>



Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.16% | 92.11% | 0.04%

[MBL-16062](https://instructure.atlassian.net/browse/MBL-16062)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by balintbartok** [comment]
Unpublished courses are now visible in the course list, which is in parity with web and android. However on other platforms these are inactive, but here you can tap and star these courses, but it won't load.

**Comment by balintbartok** [comment]
Teacher - a past enrollment course is visible under current enrollments (it's correct on student) - balintbartok sandbox - t

**Review by idevainstr — DISMISSED** [review]
QA +1

**Comment by vargaat** [comment]
> Unpublished courses are now visible in the course list, which is in parity with web and android. However on other platforms these are inactive, but here you can tap and star these courses, but it won't load.

Nice catch, fixed.

**Comment by vargaat** [comment]
> Teacher - a past enrollment course is visible under current enrollments (it's correct on student) - balintbartok sandbox - t

Unfortunately, that's how we receive it from the API, we do no local processing on the data and the iOS client is sync with the android one. If this is really a bug we should raise a ticket either to the web team to remove the course from the past courses section or to the API team to return this course as a past one.

**Review by szabinst — APPROVED** [review]
I have one suggestion only, otherwise looks good! QA + 1

**Review by idevainstr — APPROVED** [review]

**Pull request merged**
