### PR TITLE
Fix issue of Groups of Unpublished Courses showing in All Courses screen

### PR DESCRIPTION
**Pull request by suhaibabsi-inst**
refs: [MBL-18147](https://instructure.atlassian.net/browse/MBL-18147)
affects: Student
release note: Fixed groups from unpublished courses showing up on All Courses list.

## Test Plan

See [ticket](https://instructure.atlassian.net/browse/MBL-18147) description.

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

[MBL-18147]: https://instructure.atlassian.net/browse/MBL-18147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Release Note: 
Fixed groups from unpublished courses showing up on All Courses list.

#### Affected Apps: Student

[MBL-18147](https://instructure.atlassian.net/browse/MBL-18147)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.16% | 91.17% | -0.01%
Core/Core/AppEnvironment/AppEnvironmentOverride.swift | 32.76% | 32.76% | 0%
Core/Core/Extensions/CGSizeExtensions.swift | 0% | 0% | 0%
Core/Core/Search/Model/SearchSupportButtonModel.swift | 0% | 0% | 0%
Core/Core/Courses/SmartSearch/View/CourseSmartSearchViewsProvider.swift | 13.64% | 13.64% | 0%
Core/Core/Courses/SmartSearch/Model/CourseSmartSearchViewAttributes.swift | 30.77% | 30.77% | 0%
Core/Core/Store/FetchedCollection.swift | 48.72% | 48.72% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2ee22a586fbd2187d813f60365815b6edd3286d9
</p>

**Review by rh12 — APPROVED** [review]
QA + 1

**Review by ndrsszsz — APPROVED** [review]
QA +1

**Review by vargaat — APPROVED** [review]

**Pull request merged**
