### PR TITLE
Use K5 flag from user profile

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15478
affects: Student
release note: none

test plan:
- Experimental K5 feature flag shouldn't be visible anymore in developer menu.
- K5 dashboard should only appear to K5 users.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/79038931/p/21e6771767143a8e364a81bf1be03f1f">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/79038933/p/ba169253762f30dbb9958d918b28c117">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/79038923/p/28fb7de026d0d1515de7841009c493e3">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.92% | 91.91% | 0%
Core/Core/Dashboard/K5/ViewModel/Grades/K5GradesViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Schedule/K5ScheduleViewModel.swift | 47.37% | 47.37% | 0%
Core/Core/Dashboard/K5/ViewModel/Resources/K5ResourcesViewModel.swift | 0% | 0% | 0%

[MBL-15478](https://instructure.atlassian.net/browse/MBL-15478)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
