### PR TITLE
Fix file name parameter in API response being case sensitive.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-14979
affects: Student
release note: Fix files not getting correctly uploaded during a submission.

test plan:
- See ticket.

### CODE REVIEW

**Review by balintbartok — APPROVED** [review]
QA + 1

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.1% | 92.1% | 0%

[MBL-14979](https://instructure.atlassian.net/browse/MBL-14979)

#### Affected Apps: Student

#### Release Note: 
Fix file not getting correctly uploaded during a submission.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/58920335/p/65fd8f9c7feb9435309702a851c9320f">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/58920353/p/1cb21801e01c0ed3efce3e48924ea472">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/58920312/p/647cd55127256df37fc3fb23ede639da">
    
  </a>
</details>

**Comment by Rosecarnagey9695420** [comment]
Really

**Pull request merged**
