### PR TITLE
Update tab bar theme settings.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16506
affects: Student, Teacher, Parent
release note: none

test plan:
- Check tab bar appearance both in light and dark mode both on iPhones and iPads on various iOS versions.
- Tab bar background color shouldn't flicker and its top separator should be always visible.

## Checklist

- [x] Tested on phone, iOS 15, dark theme
- [x] Tested on phone, iOS 15, light theme
- [ ] Tested on phone, iOS 16, dark theme
- [ ] Tested on phone, iOS 16, light theme
- [x] Tested on tablet, iPadOS 15, dark theme
- [x] Tested on tablet, iPadOS 15, light theme
- [x] Tested on tablet, iPadOS 16, dark theme
- [x] Tested on tablet, iPadOS 16, light theme

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/Core/Extensions/UITabBarExtensions.swift:48:54: Trailing Comma Violation: Multi-line collection literals should have trailing commas. (trailing_comma)
    /Users/vagrant/git/Core/Core/AppEnvironment/Brand.swift:75:1: error: Vertical Whitespace Violation: Limit vertical whitespace to a single empty line. Currently 2. (vertical_whitespace)
    
</details>
<details><summary>:x: XCTest failed: CoreTests/FontAppearanceTests/testTabBarItemFont</summary>


    Test crashed with signal ill.
</details>
<details><summary>:x: XCTest failed: CoreTests/K5StateTests/testFontAppearanceUpdated</summary>


    Crash: CoreTester (18989) K5StateTests.testFontAppearanceUpdated()
</details>
<details><summary>:x: XCTest failed: CoreTests/UITabBarExtensionsTests/testUseGlobalNavStyle</summary>


    XCTAssertEqual failed: ("#007aff") is not equal to ("#333333")
    XCTAssertEqual failed: ("nil") is not equal to ("Optional(<UIDynamicCatalogColor: 0x6000000014a0; name = backgroundLightest>)")
    XCTAssertEqual failed: ("nil") is not equal to ("Optional(<UIDynamicCatalogColor: 0x600000007d90; name = textDark>)")
    XCTAssertEqual failed: ("#007aff") is not equal to ("#b7b7b7")
</details>


[MBL-16506](https://instructure.atlassian.net/browse/MBL-16506)

#### Affected Apps: Student, Teacher, Parent
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by szabinst — APPROVED** [review]
QA + 1; iPhone 12, iOS 15.6.1

**Review by idevainstr — CHANGES_REQUESTED** [review]
Tabbar doesn't extend into the bottom safe are in Canvas Parent on iPad.

**Comment by vargaat** [comment]
> Tabbar doesn't extend into the bottom safe are in Canvas Parent on iPad.

Nice catch, fixed.

**Review by idevainstr — APPROVED** [review]
QA +1

**Review by szabinst — APPROVED** [review]
QA + 1

**Pull request merged**
