### PR TITLE
Update grades routing in K5 homeroom.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15756
affects: Student
release note: none

test plan:
- Login to a K5 account as student
- On the K5 homeroom, go to grades tab
- Tap on a subject
- Elementary subject page should load with the grades tab selected

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.22% | 91.22% | -0%

[MBL-15756](https://instructure.atlassian.net/browse/MBL-15756)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/101365393/p/992d8afbe3eccd313923c5ea6fb8158f">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/101365402/p/d73f9c8725c3863bd613e865b07ecd01">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/101365298/p/6667ad3ddea13874b051a4a8c69c590a">
    
  </a>
</details>

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by idevainstr — DISMISSED** [review]

**Review by davidvarga93 — APPROVED** [review]

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
