### PR TITLE
Use SVG for icon vector assets instead of PDF or SF Symbols

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: none
affects: Student, Teacher, Parent
release note: none

test plan: Make sure icons still look right in the app

### CODE REVIEW

**Comment by vanwagonet** [comment]
Pandas and other pdf assets could likely be using svg now too. As I understand it, they should work Xcode 12+ & iOS 13+.

**Comment by vargaat** [comment]
Thanks @vanwagonet, that's a huge contribution, we'll take a look. :)

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.99% | 92% | -0.01%

#### Affected Apps: Student, Teacher, Parent
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA +1 , Thanks @vanwagonet, you're always welcome to contribute ;)

**Comment by armstrongnate** [comment]
Nice to see you again @vanwagonet! 😄 👏

**Pull request merged**
