### PR TITLE
Add SimilarityScore for native speedgrader

### PR DESCRIPTION
**Pull request by vanwagonet**
Also disable page panning while picking an attempt

refs: MBL-14816
affects: Teacher
release note: none

### CODE REVIEW

**Comment by vanwagonet** [comment]
Test Plan:
turnitin / teacher1
* Verify the similarity score shows for submissions in the todo list.
* Make sure you can drag on attempt picker

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/52632741/p/a2b390ba61173ed08bf992687370751b">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/52632759/p/9d73f4057f107258624f245193ff7f7c">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/52632714/p/cf322208e3e3d3e911c9e89c50c94e79">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.3% | 93.33% | -0.03%

[MBL-14816](https://instructure.atlassian.net/browse/MBL-14816)

#### Affected Apps: Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by armstrongnate — APPROVED** [review]
Similarity Scores look great and the picker is working correctly now. Do you know if tapping the similarity score should ask me to log in or should I be logged in automatically? I'd have to check if that's what happens on master.

**Comment by vanwagonet** [comment]
> Similarity Scores look great and the picker is working correctly now. Do you know if tapping the similarity score should ask me to log in or should I be logged in automatically? I'd have to check if that's what happens on master.

Master doesn't even take you to the url. Tapping does nothing. 😆 The url isn't for a canvas site, it's for TurnItIn, so I assume auth is their thing.

**Pull request merged**
