### PR TITLE
Use safe bar button items

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16949
affects: Teacher
release note: Fixed a crash that triggered when an assignment or quiz that was part of a module was opened.

test plan:
- See ticket for repro steps.
- Also test if the teacher app denies the edit action on the assignment details screen when logged in with a student.

## Checklist

- [x] Tested on phone
- [ ] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
#### Release Note: 
Fixed a crash that triggered when an assignment or quiz that was part of a module was opened.

#### Affected Apps: Teacher

[MBL-16949](https://instructure.atlassian.net/browse/MBL-16949)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.41% | 92.4% | 0.01%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c3617bb48ddeee297b8b0b77b98b60ae30987a17
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA +1

**Pull request merged**
