### PR TITLE
Fix push notifications for vanity domain users

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBL-14220, MBL-14325
affects: student
release note: Fixed a bug that could cause push notifications to open up in Safari

Test plan:
* Check out the changes locally (so you can simulate a push notification)
* Log in as narmstrong > s
* Drag the attached `push.apns` file over the simulator and tap the notification
* Should launch the course details

### CODE REVIEW

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/myn3w2u) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fmyn3w2u)
teacher: [Link](https://rebrand.ly/ap1rko1) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fap1rko1)
parent: [Link](https://rebrand.ly/tu4sm0z) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Ftu4sm0z)

**Comment by inst-danger** [comment]
#### Release Note: 
Fixed a bug that could cause push notifications to open up in Safari

#### Affected Apps: Student

[MBL-14220](https://instructure.atlassian.net/browse/MBL-14220)
[MBL-14325](https://instructure.atlassian.net/browse/MBL-14325)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.65% | 93.64% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by armstrongnate** [comment]
[push.apns.zip](https://github.com/instructure/canvas-ios/files/4548738/push.apns.zip)

**Comment by armstrongnate** [comment]
Here's the ticket https://instructure.atlassian.net/browse/MBL-14328

**Pull request merged**
