### PR TITLE
Add support for locked parent alerts

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15735
affects: Parent
release note: Fixed handling of missing assignment alerts where the course is no longer available.

test plan: See ticket and its comments. There's a new API field which indicates if the alert is from a no longer available course. This field only works if the course is deleted but doesn't if the course is concluded. If the API team fixes this we'll need no client side modifications.

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/103302302/p/41a73282e1d9bfc0d1071b72fab9e4a0">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/103302315/p/3ea5761f28cfc5bdffa3442c4c6247e1">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/103302270/p/9ff9c3b337ddb4c17ead4a7b79b6110f">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.45% | 91.45% | 0%

[MBL-15735](https://instructure.atlassian.net/browse/MBL-15735)

#### Affected Apps: Parent

#### Release Note: 
Updated alerts screen to reflect the locked state of the course from where the alert came.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
