### PR TITLE
Invited K5 course shown on dashboard

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15776
affects: Student
release note: Fixed invited courses shown on dashboard
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/104726250/p/4900ba5370d9e6e333467cc510c707a6">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/104726263/p/617d920ddb3c2dd42d6f7ba25cf98933">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/104726161/p/9ab47450dfdfc927eb6d0821971acc74">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/K5HomeroomViewModelTests/testLoadsNonHomeroomCourses</summary>


    Assertion Failure at K5HomeroomViewModelTests.swift:106: XCTAssertEqual failed: ("0") is not equal to ("1")
</details>


[MBL-15776](https://instructure.atlassian.net/browse/MBL-15776)

#### Affected Apps: Student

#### Release Note: 
Fixed invited courses shown on dashboard for Elementary
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
