### PR TITLE
Add entity to be able to decode two different data types in APIPlannable response.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15498
affects: Student
release note: none

test plan: See ticket

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


[MBL-15498](https://instructure.atlassian.net/browse/MBL-15498)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/79546457/p/3b667614efbb2354365238c1e3d0110f">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/79546469/p/f6c988397a5f2baa98fd5aa3bd7bbe90">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/79546443/p/237976e435411214d476c6f2012dae38">
    
  </a>
</details>

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
