### PR TITLE
Module requirements do not work correctly

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15577
affects: Student
release note: Fix sequential module requirements.
test plan: see ticket, should match web, you can also test the sequential module requirement in my 'This test course'.

### CODE REVIEW

**Review by balintbartok — CHANGES_REQUESTED** [review]
Can we include these in some unit tests?

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/ModuleTests/testRequireSequentialLocking</summary>


    Assertion Failure at ModuleTests.swift:65: XCTAssertTrue failed
    Assertion Failure at ModuleTests.swift:66: XCTAssertTrue failed
    Assertion Failure at ModuleTests.swift:70: XCTAssertTrue failed
</details>


[MBL-15577](https://instructure.atlassian.net/browse/MBL-15577)

#### Affected Apps: Student

#### Release Note: 
Fix sequential module requirements.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/89394252/p/9a85351a5f0b96deef0852373412f94d">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/89394279/p/44b004d1009ede449965c2f0cc1f10ea">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/89394179/p/f4fd9ed9b6c61eabf5622671c8186ced">
    
  </a>
</details>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
