### PR TITLE
Make K5 top navbar scroll to the selected item

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15374
affects: Student
release note: none

test plan: Items should scroll to screen on iOS 14 when selected if a part of them is off-screen.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/76781357/p/9dd2f0055eba6002247e3b5311e1d3c6">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/76781400/p/80146bfd04d64faf1041fcd701926fb9">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/76781334/p/d637c7b7653e25e4435656317d6cbc79">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.7% | 91.7% | 0%
Core/Core/Dashboard/K5/ViewModel/K5DashboardViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Grades/K5GradesViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/K5DashboardNavigationViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Schedule/K5ScheduleViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Homeroom/K5HomeroomViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Resources/K5ResourcesViewModel.swift | 0% | 0% | 0%

[MBL-15374](https://instructure.atlassian.net/browse/MBL-15374)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
not on iOS 13, but it works

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
