### PR TITLE
Assign to everyone else still shows up when it does not apply to an assignment

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-16189
affects: Teacher
release note: Fixed assign to everyone else still shows up when it does not apply to an assignment.
test plan: See ticket.

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



[MBL-16189](https://instructure.atlassian.net/browse/MBL-16189)

#### Affected Apps: Teacher

#### Release Note: 
Fixed assign to everyone else still shows up when it does not apply to an assignment.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Review by szabolcs-instructure — APPROVED** [review]
QA + 1

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
