### PR TITLE
Darken the grey color commonly used for descriptions dates or reply text

### PR DESCRIPTION
**Pull request by idevainstr**
Update 'ash' normal color to the requested high contrast one.

refs: MBL-15328
affects: Student, Teacher
release note: Improve contrast on several screen item sub titles.
test plan: See ticket.

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74487563/p/47af86d75808bcbc9f73c04b6dab4552">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74487583/p/a7dac35f67325125155f8ed9e54f1bf1">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/74487509/p/b2b0d858a84e645fc72421c9358e0a18">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92% | 92% | 0%

[MBL-15328](https://instructure.atlassian.net/browse/MBL-15328)

#### Affected Apps: Student, Teacher

#### Release Note: 
Improve contrast on several screen item sub titles.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by davidvarga93 — APPROVED** [review]
QA +1 manual

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
