### PR TITLE
Fix issue of user not being able to submit assignment when logged in root account

### PR DESCRIPTION
**Pull request by suhaibabsi-inst**
refs: [MBL-18064](https://instructure.atlassian.net/browse/MBL-18064)
affects: Student, Teacher
release note: Fixes issue of user not being able to submit assignment when logged in root account.

## Test Plan

See [ticket](https://instructure.atlassian.net/browse/MBL-18064) description.

## Screen Record

https://github.com/user-attachments/assets/bd0ce39c-8939-44f5-ab78-c96b6610c674

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

[MBL-18064]: https://instructure.atlassian.net/browse/MBL-18064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add a release note. If no release note is wanted, use `none`. Example: `release note: Fixed a bug that prevented users from enjoying the app.`
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add which apps this change affects. Example: `affects: Teacher, Student` or `affects: none`
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add a reference to a Jira ticket. For example: `refs: MBL-10023`
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b0e16312dba8e28c3ee39569e7b857cac89baa3b
</p>

**Review by vargaat — CHANGES_REQUESTED** [review]
The text submission worked fine but the file upload one still failed for me. The file was successfully uploaded but the submission itself failed with an internal server error. The successful submission went to `apac-consortia-03` while the failed file upload and submission calls targeted `apac-consortia`. We should also consider the scenario when we submit files via the file share extensions.

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by vargaat** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by suhaibabsi-inst** [comment]
Closing this as it will be replaced with this one:
https://github.com/instructure/canvas-ios/pull/2989

**Pull request closed without merging**
