### PR TITLE
Fix Navigation title disappearing when rotated, backgrounded or fullscreened

### PR DESCRIPTION
**Pull request by rh12**
refs: [MBL-17401](https://instructure.atlassian.net/browse/MBL-17401)
affects: Student, Teacher, Parent
release note: Fix Navigation title disappearing when rotated, backgrounded or fullscreened
test plan: Please see ticket for details.

## Checklist

- [x] Tested on phone
- [x] Tested on tablet

[MBL-17401]: https://instructure.atlassian.net/browse/MBL-17401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
#### Release Note: 
Fix Navigation title on Page disappearing when rotated or backgrounded

#### Affected Apps: Student, Teacher, Parent

[MBL-17401](https://instructure.atlassian.net/browse/MBL-17401)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.85% | 91.86% | -0.01%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a6362b68f491545eb8ea52bf1b4637a248b0a038
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Pull request merged**
