### PR TITLE
Forward external url to system instead of opening in-app browser.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16535
affects: Student
release note: Fixed external urls not opening 3rd party apps but displaying the url's content in a dialog.

test plan: See ticket.

## Checklist

- [x] Tested on phone
- [ ] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.89% | 91.9% | -0%
Core/Core/Courses/CourseDetails/ViewModel/CourseDetailsViewModel.swift | 48.89% | 48.89% | 0%

[MBL-16535](https://instructure.atlassian.net/browse/MBL-16535)

#### Affected Apps: Student

#### Release Note: 
Fixed external urls not opening 3rd party apps but displaying the url's content in a dialog.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA +1

**Pull request merged**
