### PR TITLE
Remove Google Analytics tracking

### PR DESCRIPTION
**Pull request by szabolcs-instructure**
refs: MBL-16169
affects: Student, Teacher, Parent
release note: Remove Google Analytics tracking

test plan:

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: Yarn lint</summary>


    
    /Users/vagrant/git/rn/Teacher/src/common/CanvasAnalytics.js
      30:1  error  Expected indentation of 2 spaces but found 4  indent
    
    ✖ 1 problem (1 error, 0 warnings)
      1 error and 0 warnings potentially fixable with the `--fix` option.
    
</details>


[MBL-16169](https://instructure.atlassian.net/browse/MBL-16169)

#### Affected Apps: Student, Teacher, Parent

#### Release Note: 
Remove Google Analytics tracking
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by szabolcs-instructure** [comment]
There are some unintended Firebase changes in `Podfile.lock` caused by `pod install --no-repo-update` even though pod versions seem to be locked.

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by vargaat — APPROVED** [review]

**Review by balintbartok — APPROVED** [review]

**Review by idevainstr — APPROVED** [review]

**Pull request merged**
