### PR TITLE
Fix module page removes sub page navigation items.

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15711
affects: Student
release note: Fixed the options menu on module discussion pages.
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/100546223/p/284ba8bbe546ba1374fcf2d94c3418ae">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/100546236/p/414a99812a388183f4cbc6a1b5f2a0f5">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/100546213/p/cb12a89347b9d482ffd83a3d7c0ef823">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.22% | 91.16% | 0.06%

[MBL-15711](https://instructure.atlassian.net/browse/MBL-15711)

#### Affected Apps: Student

#### Release Note: 
Fixed the options menu on module discussion pages.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
