### PR TITLE
Fix bugs in native speedgrader

### PR DESCRIPTION
**Pull request by vanwagonet**
- prevent rotate in compact
- add tooltips to rubric ratings
- ensure grading only updates relevant properties

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add a reference to a jira ticket. For example: `refs: MBL-10023`
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add which apps this change affects. Example: `affects: Teacher, Student` or `affects: none`
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add a release note. If no release note is wanted, use `none`. Example: `release note: Fixed a bug that prevented users from enjoying the app.`
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/LoginWebViewControllerTests/testPreloaded</summary>


    Assertion Failure at LoginWebViewControllerTests.swift:56: Asynchronous wait failed: Exceeded timeout of 9 seconds, with unfulfilled expectations: "Expect value of 'URL' of <WKWebView: 0x7fd249302e00; frame = (0 0; 375 667); layer = <CALayer: 0x60000df24000>> to be 'https://localhost:1/?username=u&password=p'".
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/55784767/p/64b61e765dadea0a0e26211ecb1f8e8f">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/55784784/p/274dea99c9bf0066153af1c14f255430">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/55784746/p/ea44dad30a62d354c6bfdae59d452f32">
    
  </a>
</details>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Comment by vanwagonet** [comment]
I'd like to also get some QA from @armstrongnate since this is such a critical piece of the app.

**Review by armstrongnate — CHANGES_REQUESTED** [review]
Here are a few issues I've found:

- Needs to refresh To Do list (in another PR is fine)
- Annotation comments, stamp annotations, strikethrough and highlight are not saving
- Ink annotations at 6 and 7 don’t save
- Rubric criterion tooltips are showing more text than release. twilson > teacher1 > Rubrics > Assignments > Assignment with Outcome > Speed Grader > Test Outcome > Only ‘Meets Expectations’ shows on release. Which one is wrong?
- Can the tooltip on rubric criterions have a smaller max width so that text wraps?
- Rubrics grading messed up. I'll send you a video. On web there are two grades: One for the total points given for the rubric and one for the entered grade. We probably always show the entered grade. Release build gets this right. twilson > teacher1 > Rubrics > Assignments > Assignment with Rubric Grading > Change the grade. Notice it updates in the submission list (and on web) but not in the grades tab

**Review by armstrongnate — APPROVED** [review]

**Pull request merged**
