### PR TITLE
Bugfix/mbl 15555 people context card opening resets invited users role on people list

### PR DESCRIPTION
**Pull request by balintbartok**
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/89019437/p/404012f6cc2e1ac23a4614148afcecd0">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/89019452/p/4b21b0be2f0bf8e534bca964e1c51fa2">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/89019424/p/6328523969762182cd3140d31b6aba71">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.86% | 91.85% | 0.01%

[MBL-15555](https://instructure.atlassian.net/browse/MBL-15555)

#### Affected Apps: Student, Teacher

#### Release Note: 
Fixed invited user state disappearing from people list
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
