### PR TITLE
Student names displayed anonymous survey responses

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-7529
affects: Teacher
release note: Fixed anonymous survey submissions.
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.84% | 91.84% | -0%
Core/Core/Dashboard/K5/ViewModel/K5DashboardViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Grades/K5GradesViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/K5DashboardNavigationViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Schedule/K5ScheduleViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Homeroom/K5HomeroomViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Resources/K5ResourcesViewModel.swift | 0% | 0% | 0%

[MBL-7529](https://instructure.atlassian.net/browse/MBL-7529)

#### Affected Apps: Teacher

#### Release Note: 
Fixed anonymous survey submissions.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/75333928/p/80e9cb5344e17b33b60d974b646f2512">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/75333933/p/6da5f7648c53c8e0f75a9f1bd5b1be76">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/75333924/p/1a252c817e21a670bb275a90cc2f41cc">
    
  </a>
</details>

**Comment by vargaat** [comment]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Review by vargaat — APPROVED** [review]

**Pull request merged**
