### PR TITLE
Student view does not work for Consortium accounts

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-16076
affects: Teacher
release note: Fixed student view for Consortium accounts.
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.76% | 91.76% | 0%

[MBL-16076](https://instructure.atlassian.net/browse/MBL-16076)

#### Affected Apps: Teacher

#### Release Note: 
Fixed student view for Consortium accounts
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/1b9380d3-66a0-41f2-ba92-0128d2cb27e4/artifact/c05b33b34e901dd8/p/f1dcf2e28d9f199901068bbacfc182ed">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/1b9380d3-66a0-41f2-ba92-0128d2cb27e4/artifact/0e54a8c593e9b615/p/acd71cb3fbc066dd69207f5e2ba23596">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/1b9380d3-66a0-41f2-ba92-0128d2cb27e4/artifact/6f455d83ccab2e8c/p/a282a61ff3e5c6b7ac6a5a21bbce5d2e">
    
  </a>
</details>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
