### PR TITLE
K5 course colors

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15504
affects: Student
release note: none

test plan: K5 course colors in the app should match what is set on the web interface by the teacher.

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.99% | 91.97% | 0.01%

[MBL-15504](https://instructure.atlassian.net/browse/MBL-15504)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80329792/p/c91113a13dc99708b17d002dfd5c8ec3">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80329820/p/c4e045c17e2353189d262d403e347ff9">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80329762/p/8ba050e5a08dc4523552d528ed35c8fc">
    
  </a>
</details>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Pull request merged**
