### PR TITLE
Avoid using layoutSubviews which can cause infinite cycle.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15641
affects: Teacher, Student
release note: Fixed app getting frozen when opening SpeedGrader on landscape iPhones.

test plan: See ticket.

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/ComposeReplyViewControllerTests/testLayout</summary>


    Assertion Failure at ComposeReplyViewControllerTests.swift:34: XCTAssertEqual failed: ("-86.5") is not equal to ("-103.5")
</details>


[MBL-15641](https://instructure.atlassian.net/browse/MBL-15641)

#### Affected Apps: Teacher, Student

#### Release Note: 
Fixed app getting frozen when opening SpeedGrader on landscape iPhones.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/93186884/p/0bd46013777641f8520d3061acf4f6ca">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/93186894/p/099417c4a114ff08b13b67df18d4fe8a">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/93186879/p/814ff9e717e3d295ecd38cf3e5a5a4e1">
    
  </a>
</details>

**Review by davidvarga93 — APPROVED** [review]
QA + 1 w/ iPad

**Review by balintbartok — DISMISSED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]

**Pull request merged**
