### PR TITLE
Add syllabus downloader

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16767
affects: Student
release note: none

test plan:
- Sync the syllabus tab for offline usage.
- Turn off internet on the device.
- Go to syllabus page.
- Syllabus html content should display along with any assignments if syllabus summary is enabled.

## Checklist

- [x] Tested on phone
- [ ] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-16767](https://instructure.atlassian.net/browse/MBL-16767)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.38% | 92.36% | 0.02%
Core/Core/Offline/ViewModel/OfflineModeViewModel.swift | 0% | 0% | 0%
Core/Core/Extensions/BoolExtensions.swift | 0% | 0% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7c0f43c2a8774129f5bd1e0c374dd4b4ec6b6356
</p>

**Review by szabinst — CHANGES_REQUESTED** [review]
Works great, however I'd add tests to `CourseSyncInteractorLiveTests` as well.

**Comment by vargaat** [comment]
> Works great, however I'd add tests to `CourseSyncInteractorLiveTests` as well.

I added a test to check if syllabus selection correctly invokes the download method on the syllabus interactor.

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by szabinst — APPROVED** [review]

**Review by idevainstr — APPROVED** [review]
QA +1

**Pull request merged**
