### PR TITLE
K5 Top Navigation Bar

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15374
affects: Student
release note: none

test plan: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/Core/Extensions/InstIconExtensions.swift:407:1: Trailing Whitespace Violation: Lines should not have trailing whitespace. (trailing_whitespace)
    
    
</details>


[MBL-15374](https://instructure.atlassian.net/browse/MBL-15374)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/76158714/p/55e1f6695ad7f0df0cdf55ab3ddd84cd">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/76158728/p/c6ee5d410d8ffedb1a5b2989e61f8ce3">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/76158705/p/9e84e9486b491b3a8d6a559b43b477c3">
    
  </a>
</details>

**Review by balintbartok — APPROVED** [review]
looks good so far

**Review by idevainstr — APPROVED** [review]
reviewed

**Pull request merged**
