### PR TITLE
Upload dSYMs

### PR DESCRIPTION
**Pull request by vargaat**
- The Cocoapods based dSYM uploads were removed from Bitrise workflows.
- I added dSYM uploads to Xcode projects using the SPM based Firebase installation. This is based on an environment variable that the app store bitrise workflows pass down to xcodebuild so only the app store builds are executing this step.
- Created a dedicated folder for scripts used in Xcode build phases.
- Updated Swiftlint configuration after Pods and React removal.

affects: Student, Teacher, Parent

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.12% | 91.12% | 0%
Core/Core/Planner/CalendarEvent/Model/API/PostCalendarEventRequest.swift | 0% | 0% | 0%
Core/Core/Planner/CalendarEvent/View/CustomFrequencyComponents/OccurrencesCountInputDialog.swift | 0% | 0% | 0%
Core/Core/Planner/CalendarEvent/Model/Helpers/RecurrenceRule+SelectionDescription.swift | 43.33% | 43.33% | 0%
Core/Core/Grades/View/CustomSwipeAction.swift | 0% | 0% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e6a647fef6e57de48cb2bfa6d3e30254babc19ec
</p>

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by rh12 — APPROVED** [review]

**Review by szabinst — APPROVED** [review]

**Pull request merged**
