### PR TITLE
Dark Mode | + Button in "To" field is dark on black

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-16222
affects: Student
release note: none
test plan: See ticket.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>
## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] A11y checked
- [x] Tested on phone
- [x] Tested on tablet
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


<details><summary>:x: JS tests</summary>


    Summary of all failing tests
     FAIL  src/modules/inbox/__tests__/Compose.test.js
      ● Compose › renders after picking a course
    
        expect(received).toMatchSnapshot()
    
        Snapshot name: `Compose renders after picking a course 1`
    
        - Snapshot  - 1
        + Received  + 1
    
        @@ -189,11 +189,11 @@
                          "testUri": "../../../src/images/Add.png",
                        }
                      }
                      style={
                        Object {
        -                 "tintColor": undefined,
        +                 "tintColor": "#556572",
                        }
                      }
                    />
                  </TouchableOpacity>
                </View>
    
           98 |     onSelect(course)
           99 |     expect(navigator.pop).toHaveBeenCalled()
        > 100 |     expect(tree).toMatchSnapshot()
              |                  ^
          101 |   })
          102 | 
          103 |   it('sets all the data and then send the message', () => {
    
          at Object.<anonymous> (src/modules/inbox/__tests__/Compose.test.js:100:18)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at emitInitNative (node:internal/async_hooks:202:43)
          at emitInitScript (node:internal/async_hooks:505:3)
          at promiseInitHook (node:internal/async_hooks:324:3)
          at promiseInitHookWithDestroyTracking (node:internal/async_hooks:328:3)
    
      ● Compose › renders reply
    
        expect(received).toMatchSnapshot()
    
        Snapshot name: `Compose renders reply 1`
    
        - Snapshot  - 1
        + Received  + 1
    
        @@ -187,11 +187,11 @@
                          "testUri": "../../../src/images/Add.png",
                        }
                      }
                      style={
                        Object {
        -                 "tintColor": undefined,
        +                 "tintColor": "#556572",
                        }
                      }
                    />
                  </TouchableOpacity>
                </View>
    
          343 |       canEditSubject: false,
          344 |     }
        > 345 |     expect(shallow(<Compose {...props} />)).toMatchSnapshot()
              |                                             ^
          346 |   })
          347 | 
          348 |   it('renders the forwarded message body', () => {
    
          at Object.<anonymous> (src/modules/inbox/__tests__/Compose.test.js:345:45)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at emitInitNative (node:internal/async_hooks:202:43)
          at emitInitScript (node:internal/async_hooks:505:3)
          at promiseInitHook (node:internal/async_hooks:324:3)
          at promiseInitHookWithDestroyTracking (node:internal/async_hooks:328:3)
    
    
    Snapshot Summary
     › 2 snapshots failed from 1 test suite. Inspect your code changes or run `yarn run test:ci -u` to update them.
    
    Test Suites: 1 failed, 173 passed, 174 total
    Tests:       2 failed, 1148 passed, 1150 total
    Snapshots:   2 failed, 270 passed, 272 total
    Time:        61.958s
</details>


[MBL-16222](https://instructure.atlassian.net/browse/MBL-16222)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by vargaat — APPROVED** [review]
QA+1

This also affects the teacher app, make sure to include `Teacher` in the affects field when merging.

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
