### PR TITLE
Filter Coursecards for Teachers

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-15277
affects: Teacher
release note: Fixed Teachers seeing their student enrollments on dashboard

test plan: see ticket

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/69797622/p/d58cf9bcfeed1810b3add8773d3c79a1">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/69797638/p/6ee4341a9b7ea1a55c0ab3dd9bf5246d">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/69797592/p/571c0ed21f3d296e913975daa4a37421">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.06% | 92.06% | 0%

[MBL-15277](https://instructure.atlassian.net/browse/MBL-15277)

#### Affected Apps: Teacher

#### Release Note: 
Fixed Teachers seeing their student enrollments on dashboard
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by vargaat** [comment]
QA+1

**Review by vargaat — APPROVED** [review]

**Review by idevainstr — APPROVED** [review]
QA+1

**Comment by mo523** [comment]
This change breaks the dashboard for a ta on the teacher app. The `isTeacherEnrollment` bool in [DashboardCard](https://github.com/instructure/canvas-ios/blob/master/Core/Core/Dashboard/DashboardCard.swift) checks for an enrollment type containing 'teacher'. [DashboardCardView](https://github.com/instructure/canvas-ios/blob/master/Core/Core/Dashboard/DashboardCardView.swift) ends up hiding a ta's courses from the teacher app dashboard and showing them on the student app dashboard (where grading, commenting, etc are not available). 
The courses are of course still accessible on the teacher app through the menu, but the convenience of the dashboard is gone as well as clogging up the student dashboard with ta enrollments.
The fix seems to be as simple as checking for an enrollment type of ta and I would make it myself if I was more familiar with swift.

Thank you

**Comment by balintbartok** [comment]
Hey @mo523! Nice find, we missed this one. The fix is on it's way:
https://github.com/instructure/canvas-ios/pull/1800
This fixes the teacher app. The student app will still show every enrollments, apparently many teachers use it that way, so I won't change that for now, but will take into consideration for the future. 
Thanks again!

**Pull request merged**
