### PR TITLE
Introduce url stub

### PR DESCRIPTION
**Pull request by vargaat**
[ignore-commit-lint]

Bitrise: Build Student, Parent and the Teacher app as well!

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.64% | 91.63% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 25468b13386594c0f569e906b9f46696d480392f
</p>

**Review by rh12 — APPROVED** [review]
Built and run tests locally

**Review by szabinst — APPROVED** [review]

**Pull request merged**
