### PR TITLE
Fix add assignee screen buttons

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15585
affects: Teacher
release note: Fixed edit assignment dialog navigation issues.

test plan:
- Open assignment details
- Tap on edit
- Close the edit dialog either with cancel or done
- Edit button should work again from assignment details
---
- Open assignment details
- Tap on due dates section
- Tap on edit
- Edit dialog should have a cancel and done button
 ---
- Open assignment details on a big enough iPhone to support master-detail split view
- Tap on edit
- Rotate the phone to landscape
- Layout should still be usable

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/88294354/p/625a117fb5d112d7929b8722562d01a3">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/88294362/p/c135adeaca0303f518f0e406b42cc7c4">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/88294294/p/701b6f372d4b79b52546d373549106a1">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.85% | 91.85% | -0%

[MBL-15585](https://instructure.atlassian.net/browse/MBL-15585)

#### Affected Apps: Teacher

#### Release Note: 
Fixed edit assignment dialog navigation issues.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
