### PR TITLE
Detect links in inbox messages, copy and select text

### PR DESCRIPTION
**Pull request by bluwave**
refs: MBL-14244, MBL-14245
affects: Parent
release note: none

### CODE REVIEW

**Comment by armstrongnate** [comment]
You have `affects: Student` but I don't think this one will affect student.

**Comment by bluwave** [comment]
doh

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/rn8izrs) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Frn8izrs)
teacher: [Link](https://rebrand.ly/foahaom) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Ffoahaom)
parent: [Link](https://rebrand.ly/b78g4ha) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fb78g4ha)

**Comment by bluwave** [comment]
@armstrongnate force pushed, but did not change any code, just original commit mesesage

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Parent

[MBL-14244](https://instructure.atlassian.net/browse/MBL-14244)
[MBL-14245](https://instructure.atlassian.net/browse/MBL-14245)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.6% | 93.6% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Pull request merged**
