### PR TITLE
Fix course invite action animation. Add make pod command to work around code signing issues.

### PR DESCRIPTION
**Pull request by vargaat**
[ignore-commit-lint]

CI: Give me a Student and a Teacher build, please!

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><video src="https://github.com/instructure/canvas-ios/assets/72396990/7f634eeb-6d26-41c7-a159-7871ddf27e45"/></td>
<td><video src="https://github.com/instructure/canvas-ios/assets/72396990/61636ad6-5d66-4722-a9f2-54bf92488c73"/></td>
</tr>
</table>

## Checklist

- [ ] Tested on phone
- [x] Tested on tablet
- [x] Tested in dark mode
- [ ] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/AssignmentDueDatesInteractorLiveTests/testPopulatesListItems</summary>


    Asynchronous wait failed: Exceeded timeout of 1 seconds, with unfulfilled expectations: "Expected state reached".
    XCTAssertEqual failed: ("loading") is not equal to ("data")
    XCTAssertEqual failed: ("0") is not equal to ("3")
    XCTAssertEqual failed: ("nil") is not equal to ("Optional("april")")
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0a1a0cbc13e79c90849ea8949d6ca3d2a121158a
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by szabinst — APPROVED** [review]
QA + 1

**Pull request merged**
