### PR TITLE
Add conference banner to homeroom view

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15694
affects: Student
release note: Added conference banner to homeroom view.

test plan:
- Create conferences both for a K5 and a non-K5 account and start them.
- Log in with the K5 user.
- Conference banner should be visible, tapping on it should launch it in a browser, tapping on X should hide it.
- Log in with the non-K5 user and check the same.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/101688319/p/44e61988eda00aec38bdd25dfc450b7d">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/101688330/p/3ac73745ef1b30d0e970c73ee1e4d3ca">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/101688261/p/546cb11316f42d62e084d7c5719a010d">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.38% | 91.23% | 0.15%

[MBL-15694](https://instructure.atlassian.net/browse/MBL-15694)

#### Affected Apps: Student

#### Release Note: 
Added conference banner to homeroom view.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
