### PR TITLE
Move webview reload call to main thread.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15863
affects: Student
release note: Fixed a crash upon assignment submission in homeroom view.

test plan:
- Log in to a K5 account which has a course with a file upload assignment in a module.
- Go to subject page, modules tab.
- Tap on the assignment and submit a file to it.
- App shouldn't crash.

### CODE REVIEW

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.37% | 91.37% | 0%

[MBL-15863](https://instructure.atlassian.net/browse/MBL-15863)

#### Affected Apps: Student

#### Release Note: 
Fixed a crash upon assignment submission in homeroom view.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/111512043/p/9a4680deb6efb3814fe5cebb06ddf0cf">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/111512085/p/99f24258161230562a4f8fda42b0d90b">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/111511978/p/217419d39e2473360491dafce50b2bfa">
    
  </a>
</details>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
