### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by inst-danger**
[ignore-commit-lint]

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.36% | 93.62% | -0.26%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1014288&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by lensovet** [comment]
hi there, where do these imported translations come from?

**Comment by shichongrui** [comment]
Our company uses a third party translation service.

**Comment by lensovet** [comment]
How does one go about reporting/fixing bugs in the translations?

**Comment by armstrongnate** [comment]
@lensovet feel free to comment here or email us at ios@instructure.com with corrections.

**Pull request merged**
