### PR TITLE
Fix build warnings

### PR DESCRIPTION
**Pull request by szabolcs-instructure**
## Description
The following changes have been made: 
- ~~Build order set to `Dependency order` (was `Manual`)~~
- Lottie linter warning
- Link `Heap.xcframework` to App targets (was linked to `Core`) 
- Explicitly set `SwiftLint` to run at every build
- Rename Build Phase `Embed App Extensions` to  `Embed ExtensionKit Extensions`
- Explicitly set `Start Packager`, `Bundle React Native Code and Images` build phases to run at every build
- Fix Pod project warning regarding DEAD_CODE_STRIPPING settings
- Fix Pod project warning regarding ARCHS settings

--- 
refs: MBL-16374
affects: Student, Teacher, Parent
release note: none

test plan: We should test all three apps because every schema has been affected by the changes.   

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] A11y checked
- [x] Tested on phone
- [ ] Tested on tablet
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


[MBL-16374](https://instructure.atlassian.net/browse/MBL-16374)

#### Affected Apps: Student, Teacher, Parent
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by vargaat — DISMISSED** [review]
QA+1

**Comment by vargaat** [comment]
As an improvement we could fix warnings on CoreTests as well:
Screenshot 2022-11-10 at 18 05 29

**Review by idevainstr — DISMISSED** [review]

**Review by vargaat — APPROVED** [review]

**Pull request merged**
