### PR TITLE
Fix submission being selected before force update finishes.

### PR DESCRIPTION
**Pull request by vargaat**
refs:  MBL-16122
affects: Student
release note: none

test plan: See ticket.

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] Tested on phone
- [x] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.69% | 91.69% | 0%
Core/Core/Submissions/SubmissionBreakdown/SubmissionBreakdownViewModelProtocol.swift | 0% | 0% | 0%
Core/Core/Quizzes/QuizDetails/ViewModel/PreviewQuizDetailsViewModel.swift | 0% | 0% | 0%

[MBL-16122](https://instructure.atlassian.net/browse/MBL-16122)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by szabolcs-instructure — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA +1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
