### PR TITLE
Fix rubric tooltip going under submission view. Add rubric long description to bubble.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15261
affects: Teacher
release note: Fixed rubric rating description not displaying correctly.

test plan: See ticket. Also added long description of the rating.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/69406054/p/50c3cf4b86c4931eed067d884126c598">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/69406064/p/3de4cf5dbd252ef995328cebc27d4c54">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/69406052/p/57a20ebffb827e0dcac568d2278cdc55">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.11% | 92.11% | 0%

[MBL-15261](https://instructure.atlassian.net/browse/MBL-15261)

#### Affected Apps: Teacher

#### Release Note: 
Fixed rubric rating description not displaying correctly.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Comment by vargaat** [comment]
> Hi - Teacher here. Tried reporting this via support, but no dice. Looks like rubric tooltips no longer work or display. Tested on iOS and iPad is 18.3, and on 1.32 and 1.33. Thanks for all the awesome work you’re doing.

@toddresley We've got a report about this issue on Feb 5. We'll definitely include this in the next release.

**Comment by toddresley** [comment]
Awesome.   I submitted a pretty comprehensive email through the app support that made its way up to L2, and then passed to “engineering”, which I assumed was your team.  If you’re running TestFlights and need testers, I’d love to help.

**Pull request merged**
