### PR TITLE
Send complete progress for RN

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-13298
affects: Student, Teacher
release note: Fixed attachment uploading to show correct file size sent

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by vanwagonet** [comment]
Note that this only sends progress at the end. There is no progress reporting at the beginning of the upload or along the way.

**Comment by inst-danger** [comment]
#### Release Note: 
Fixed attachment uploading to show correct file size sent

#### Affected Apps: Student, Teacher

[MBL-13298](https://instructure.atlassian.net/browse/MBL-13298)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.26% | 93.25% | 0.01%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1007136&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by armstrongnate** [comment]
Merging so that I can cut release.

**Pull request merged**
