### PR TITLE
Fixed undefined return statement causing Inbox to fail to load.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15927
affects: Student
release note: Fixed inbox not loading in case there are locked courses.

test plan: See ticket.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/114763146/p/939f8036afb7cc61ae7aa9b16a33085b">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/114763167/p/0771ce77c510d913527a798d90949c2c">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/114763126/p/50f016ff556d98f6f740a4adaabe4d9d">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.45% | 91.45% | 0%

[MBL-15927](https://instructure.atlassian.net/browse/MBL-15927)

#### Affected Apps: Student

#### Release Note: 
Fixed inbox not loading in case there are locked courses.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
