### PR TITLE
Add mastery connect to side menu

### PR DESCRIPTION
**Pull request by vargaat**
### What's new?
- Added native routes to parent app for pages and wikis. Links in the course syllabus to these will no longer open a modal web browser.
- Added Mastery LTI tool to the allowed LTIs list for all apps for Student, Teacher, Parent and Admin roles.
- Enabled LTI tool display for the Parent app in the side menu.
- Fixed modal web browser's status bar blending in to the background when opened from the side menu.

refs: MBL-17408
affects: Student, Teacher Parent
release note: Added Mastery to side menu.

test plan:
- See ticket for an account with Mastery already added.
- Check if Mastery appears in all three apps.
- Test if status bar's foreground color is different than its background color.
- Test if tapping on a link to a page from the front page in the parent app displays the native page viewer.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>You have included an invalid app. Valid values are: Student, Teacher, Parent, None</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Release Note: 
Added Mastery to side menu.

[MBL-17408](https://instructure.atlassian.net/browse/MBL-17408)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.86% | 91.87% | -0.01%
Core/Core/LTI/LTIDomains.swift | 0% | -- | --
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 17519b86481d0892f09f0bfdb97cb22cfe5a9c6c
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by ndrsszsz — APPROVED** [review]
QA +1

**Review by rh12 — APPROVED** [review]
QA + 1

**Pull request merged**
