### PR TITLE
Move document rotation setup out of annotation provider initializer

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-17249
affects: Student, Teacher
release note: none

test plan:
- Upload a pdf file using web to your user's files.
- Open the file on web and rotate it.
- Submit this file on web to an assignment.
- Open teacher app and check if the file appears rotated in SpeedGrader.
- Open student app and go to submission and rubric of the assignment and check if the file appears rotated.
- Neither app should crash while doing these.

## Checklist

- [ ] Tested on phone
- [ ] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student, Teacher

[MBL-17249](https://instructure.atlassian.net/browse/MBL-17249)

<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/Core/DocViewer/DocViewerViewController.swift:124:1: Trailing Whitespace Violation: Lines should not have trailing whitespace (trailing_whitespace)
    
    
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 71812887ff295cffa6749ed38b816d7f20d61802
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by szabinst — APPROVED** [review]
QA + 1, Initial rotation as a student doesn't seem to have an effect after the file is submitted, but if I rotate the file in SpeedGrader as a teacher, then both the Student and the Teacher app displays it correctly.

**Pull request merged**
