### PR TITLE
Disable swipe action when What-if is disabled

### PR DESCRIPTION
**Pull request by szabinst**
[ignore-commit-lint]

affects: Student 

## Checklist

- [x] Tested on phone
- [ ] Tested on tablet

### CODE REVIEW

**Review by ndrsszsz — APPROVED** [review]
QA +1

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.83% | 91.83% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 429554b17a65c92a336658002967619b99979e43
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
