### PR TITLE
User viewing people in a course shows their enrollment roles from other courses

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15435
affects: Student, Teacher
release note: Fix roles display on the People page. 
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/Core/People/User.swift:53:36: Redundant Optional Initialization Violation: Initializing an optional variable with nil is redundant. (redundant_optional_initialization)
    
    
</details>
<details><summary>:x: XCTest failed: CoreTests/PeopleListViewControllerTests/testLayout</summary>


    Assertion Failure at PeopleListViewControllerTests.swift:64: XCTAssertEqual failed: ("Optional("")") is not equal to ("Optional("Custom and Student")")
</details>


[MBL-15435](https://instructure.atlassian.net/browse/MBL-15435)

#### Affected Apps: Student, Teacher

#### Release Note: 
Fix roles display on the People page.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80329008/p/bf4727588d416adbac50ae87df4524de">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80329020/p/b944477f68fd0acd5603e639e7ad977b">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80328981/p/eee74f6441b4211b80c484bdbdb3e629">
    
  </a>
</details>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
