### PR TITLE
Fix context cards from Inbox

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBL-13754
affects: teacher
release note: Fixed a bug when tapping on user avatars in Inbox

Test plan: See [ticket](https://instructure.atlassian.net/browse/MBL-13754)

Apparently we can't trust the `context_code` in the conversation payload because in this case the ID was completely wrong.

### CODE REVIEW

**Comment by inst-danger** [comment]
#### Release Note: 
Fixed a bug when tapping on user avatars in Inbox

#### Affected Apps: Teacher

[MBL-13754](https://instructure.atlassian.net/browse/MBL-13754)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.4% | 93.4% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1017918&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|23
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Pull request merged**
