### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by inst-danger**
affects: Parent, Student, Teacher<br/><br/>[ignore-commit-lint]

### CODE REVIEW

**Review by vargaat — APPROVED** [review]

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.65% | 91.66% | -0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 64e65b8849101442fe67a2814dc0202b9f75cee9
</p>

**Pull request merged**
