### PR TITLE
Student View

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBL-13855
affects: teacher
release note: Adds Student View

Test plan:
* Install both Teacher and Student builds from this PR
* Log in as a teacher (narmstrong/t)
* Tap in to a course and choose Student View from course nav (CS 1400 > Student View)
* Student app should launch and you should be logged in as the Test Student
* Poke around the course and do student things (submit an assignment, reply to a discussion, etc)
* Tap the masquerading avatar and make sure it prompts you to "Leave Student View"
* Tap Cancel to make sure it works
* Tap OK and see that you are logged out
* Delete the Student App
* In Teacher app, tap to launch Student View again
* See that you are redirected to the App Store page for Student app

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/wjzk7ke) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fwjzk7ke)
teacher: [Link](https://rebrand.ly/eyqb1pw) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Feyqb1pw)
parent: [Link](https://rebrand.ly/06xex5r) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2F06xex5r)

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1023160&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|3
Medium|17
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---
High|1

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Adds Student View

#### Affected Apps: Teacher

[MBL-13855](https://instructure.atlassian.net/browse/MBL-13855)

<details><summary>:x: Swift lint</summary>


    ⚠️  /Users/vagrant/git/Student/Student/CanvasAppDelegate.swift:103:74: Unused Closure Parameter Violation: Unused parameter "error" in a closure should be replaced with _. (unused_closure_parameter)
    Linting 'GroupNavigationViewController.swift' (47/139)
    Linting 'UIViewControllerExtensions.swift' (48/139)
</details>
<details><summary>:x: XCTest failed: CoreTests/KeychainTests/testSharedInstance</summary>


    Crash: CoreTester (9750): Namespace SIGNAL, Code 0x4
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1023350&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|17
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1023352&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|17
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1023353&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|17
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Pull request merged**
