### PR TITLE
Add a11y identifier for titleSubtitleView in Header Views

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-15106
affects: Student, Teacher
release note: none

test plan:
see 
https://instructure.atlassian.net/browse/MBL-15106
https://instructure.atlassian.net/browse/MBL-15123
on iPad: check all the splitview headers. SwiftUI views (assignments e. g.) are different, so make sure, to check all

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/71483904/p/1e22c22351a667b9cf45c2554611b141">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/71483914/p/9a2a4743e4186743d22f830116e13072">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/71483882/p/a0662c01ac430b7527b2664cf339aa89">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.07% | 92.07% | -0%

[MBL-15106](https://instructure.atlassian.net/browse/MBL-15106)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by vargaat — CHANGES_REQUESTED** [review]
I noticed that a few screen titles are still off:
- Assignment details screen header not read by VoiceOver but focusable.
- After entering a file or directory details in Files section there's an extra comma after "< Files".
- Directory details screen in Files section announces "Files, heading" instead of the actual screen title (Submissions, profile pictures).
- Subtitle of the Grades page isn't announced, only the main title.
- Home page of an account level user group includes an extra comma at the end of the back button and its title isn't there but the app logo is displayed instead.

**Review by vargaat — APPROVED** [review]

**Review by vargaat — APPROVED** [review]
QA+1

**Review by idevainstr — APPROVED** [review]
reviewed

**Pull request merged**
