### PR TITLE
Inbox String polish

### PR DESCRIPTION
**Pull request by bluwave**
refs: MBL-13985
affects: Parent
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/v2h75ox) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fv2h75ox)
teacher: [Link](https://rebrand.ly/p0fhx5x) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fp0fhx5x)
parent: [Link](https://rebrand.ly/r27ydof) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fr27ydof)

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Parent

[MBL-13985](https://instructure.atlassian.net/browse/MBL-13985)

<details><summary>:x: Swift lint</summary>


    ⚠️  /Users/vagrant/git/Parent/ParentUnitTests/Course/CourseDetailsViewControllerTests.swift:60:1: Line Length Violation: Line should be 200 characters or less: currently 222 characters (line_length)
    Linting 'ConversationCoursesActionSheetTests.swift' (105/117)
    Linting 'EditComposeRecipientsViewControllerTests.swift' (106/117)
</details>
<details><summary>:x: XCTest failed: ParentUnitTests/AssignmentDetailsViewControllerTests/testInboxReplyButton</summary>


    Assertion Failure: AssignmentDetailsViewControllerTests.swift:54: XCTAssertTrue failed
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1022319&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|17
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1022321&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|17
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Pull request merged**
