### PR TITLE
Offline download logic error handling rework

### PR DESCRIPTION
**Pull request by szabinst**
The error handling logic has been reworked so that any errors that arise during the download of a course will not cause the download logic to fail. 

refs: MBL-16961
affects: Student
release note: none
test plan: See ticket

## Checklist

- [x] Tested on phone
- [ ] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-16961](https://instructure.atlassian.net/browse/MBL-16961)

<details><summary>:x: XCTest failed: CoreTests/CourseSyncInteractorLiveTests/testFilesPartialSelection</summary>


    XCTAssertEqual failed: ("loading(nil)") is not equal to ("idle")
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against dfedd478ae0aa73216433e986615a33c13fd81b9
</p>

**Review by idevainstr — APPROVED** [review]
QA +1

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
