### PR TITLE
Dashboard layout switcher button is too small

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15921
affects: Student, Teacher
release note: It’s now easier to touch the dashboard menu and layout toggle buttons.
test plan: see ticket

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/117059458/p/26f2c23bb79a00900920507ba8d48edf">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/117059466/p/af945c8f41a276ba9a49dd5cf3a815f9">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/117059451/p/28acc68f9c3b8a011b35876b9ef5e7a7">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.45% | 91.46% | -0.01%

[MBL-15921](https://instructure.atlassian.net/browse/MBL-15921)

#### Affected Apps: Student, Teacher

#### Release Note: 
It’s now easier to touch the dashboard menu and layout toggle buttons.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by vargaat — COMMENTED** [review]
QA+1

**Pull request merged**
