### PR TITLE
Fix course sync modules file selection

### PR DESCRIPTION
**Pull request by szabinst**
refs: MBL-17221
affects: Student
release note: none
test plan: See ticket

## Checklist

- [ ] Tested on phone
- [ ] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-17221](https://instructure.atlassian.net/browse/MBL-17221)

<details><summary>:x: XCTest failed: StudentUnitTests/RoutesTests/testRoutes</summary>


    Crash: Student (41237) <external symbol>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 71eb7cc6c92e145360fa5bd8ce8a4081b8dc625d
</p>

**Review by vargaat — APPROVED** [review]
QA+1, Selecting Modules item also selects the Files item and all files in it.

**Review by balintbartok — APPROVED** [review]
QA+ 1

**Pull request merged**
