### PR TITLE
Courses Smart Search Experience

### PR DESCRIPTION
**Pull request by suhaibabsi-inst**
refs: [MBL-17907](https://instructure.atlassian.net/browse/MBL-17907), [MBL-17906](https://instructure.atlassian.net/browse/MBL-17906), [MBL-17905](https://instructure.atlassian.net/browse/MBL-17905), [MBL-17904](https://instructure.atlassian.net/browse/MBL-17904), [MBL-17903](https://instructure.atlassian.net/browse/MBL-17903), [MBL-17902](https://instructure.atlassian.net/browse/MBL-17902)
affects: Student
release note: Courses Smart Search Experience for Student

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

[MBL-17906]: https://instructure.atlassian.net/browse/MBL-17906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MBL-17904]: https://instructure.atlassian.net/browse/MBL-17904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MBL-17903]: https://instructure.atlassian.net/browse/MBL-17903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MBL-17902]: https://instructure.atlassian.net/browse/MBL-17902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-17907]: https://instructure.atlassian.net/browse/MBL-17907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MBL-17905]: https://instructure.atlassian.net/browse/MBL-17905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add a release note. If no release note is wanted, use `none`. Example: `release note: Fixed a bug that prevented users from enjoying the app.`
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add which apps this change affects. Example: `affects: Teacher, Student` or `affects: none`
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add a reference to a Jira ticket. For example: `refs: MBL-10023`
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Student/Student/Routes.swift:574:1: Trailing Whitespace Violation: Lines should not have trailing whitespace (trailing_whitespace)
    /Users/vagrant/git/Core/Core/Courses/SmartSearch/Model/SearchResult.swift:161:1: error: Line Length Violation: Line should be 200 characters or less; currently it has 252 characters (line_length)
    /Users/vagrant/git/Core/Core/Courses/SmartSearch/Model/SearchResult.swift:166:1: error: Line Length Violation: Line should be 200 characters or less; currently it has 376 characters (line_length)
    ❌ /Users/vagrant/git/Core/Core/Courses/SmartSearch/Model/SearchResult.swift:171:1: Line Length Violation: Line should be 200 characters or less; currently it has 446 characters (line_length)
    /Users/vagrant/git/Core/Core/Courses/SmartSearch/Model/SearchResult.swift:176:1: error: Line Length Violation: Line should be 200 characters or less; currently it has 252 characters (line_length)
    /Users/vagrant/git/Core/Core/Courses/SmartSearch/Model/SearchResult.swift:181:1: error: Line Length Violation: Line should be 200 characters or less; currently it has 446 characters (line_length)
    ❌ /Users/vagrant/git/Core/Core/Courses/SmartSearch/Model/SearchResult.swift:186:1: Line Length Violation: Line should be 200 characters or less; currently it has 252 characters (line_length)
    /Users/vagrant/git/Core/Core/Courses/SmartSearch/Model/SearchResult.swift:191:1: error: Line Length Violation: Line should be 200 characters or less; currently it has 376 characters (line_length)
    /Users/vagrant/git/Core/Core/Courses/SmartSearch/Model/SearchResult.swift:90:1: error: Trailing Whitespace Violation: Lines should not have trailing whitespace (trailing_whitespace)
</details>
<details><summary>:x: XCTest failed: StudentUnitTests/RoutesTests/testK5SubjectViewRoute</summary>


    XCTAssertTrue failed
</details>
<details><summary>:x: XCTest failed: StudentUnitTests/RoutesTests/testRegularCourseDetailsInK5Mode</summary>


    XCTAssertTrue failed
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 71d2b95d749c04fc5a16319af8e1da2bd6e169b7
</p>

**Comment by vargaat** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by suhaibabsi-inst** [comment]
Closing this for replacing with this one:
https://github.com/instructure/canvas-ios/pull/2932

**Pull request closed without merging**
