### PR TITLE
Lowering the timeout needed for element checking

### PR DESCRIPTION
**Pull request by davidvarga93**
refs: MBL-15635
affects: Student, Teacher
release note: none

test plan:

### CODE REVIEW

**Comment by davidvarga93** [comment]
First check for nightly:
https://app.bitrise.io/build/f91794a1-4ce9-46be-b6b0-1e7195a41f02#?tab=log

**Comment by vargaat** [comment]
It might also worth searching this file for the string "30" as this timeout is hardcoded in many methods. The best would be if we could create a few timeout variables and use that across the file instead of these hardcoded values.

**Comment by davidvarga93** [comment]
> It might also worth searching this file for the string "30" as this timeout is hardcoded in many methods. The best would be if we could create a few timeout variables and use that across the file instead of these hardcoded values.

First lets see what happens with these lowered values, if all goes well, we can tweak them further

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/91438023/p/68a5766019cd98b39d882c688e6df225">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/91438044/p/fc5fb137c72c056952a1652d8cd78ee6">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/91438012/p/cd2c202c32cc7897cb85502efae72f53">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


<details><summary>:x: XCTest failed: CoreTests/APITests/testRetryOnRateLimitedRequest</summary>


    Assertion Failure at APITests.swift:380: Asynchronous wait failed: Exceeded timeout of 0.5 seconds, with unfulfilled expectations: "API response".
</details>


[MBL-15635](https://instructure.atlassian.net/browse/MBL-15635)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by vargaat — APPROVED** [review]

**Pull request merged**
