### PR TITLE
Fix submission needs grading for excused students

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15318
affects: Teacher
release note: Fixed excused student submissions listing.
test plan: see ticket

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73728248/p/a6418df98f2cf14795632c3a457f517a">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73728275/p/0e5a54df055300d4a7b415e41d39f342">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73728186/p/8b5e3e0ccd141aac1c952b3c8905aaa3">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/GetSubmissionsTests/testGetSubmissionsFilterPredicate</summary>


    Assertion Failure at GetSubmissionsTests.swift:269: XCTAssertEqual failed: ("excusedRaw != 1 AND typeRaw != nil AND (workflowStateRaw == "pending_review" OR (workflowStateRaw IN {"graded", "submitted"} AND (scoreRaw == nil OR gradeMatchesCurrentSubmission == 0)))") is not equal to ("typeRaw != nil AND (workflowStateRaw == "pending_review" OR (workflowStateRaw IN {"graded", "submitted"} AND (scoreRaw == nil OR gradeMatchesCurrentSubmission == 0)))")
</details>


[MBL-15318](https://instructure.atlassian.net/browse/MBL-15318)

#### Affected Apps: Teacher

#### Release Note: 
Fixed excused student submissions listing.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by balintbartok — APPROVED** [review]

**Review by vargaat — APPROVED** [review]

**Comment by vargaat** [comment]
QA+1

**Pull request merged**
