### PR TITLE
 Change devicetoken parser

### PR DESCRIPTION
**Pull request by yurikor**
%02X will parsed device token with uppercase. Therefore, it will not matched when compared aws token value and current device token.( when verify token in canvas-lms, notification_endpoint model)

### CODE REVIEW

**Comment by armstrongnate** [comment]
This change makes sense to me, I just want to make sure that it is necessary.

> Therefore, it will not matched when compared aws token value and current device token.

We compare the tokens here:

https://github.com/instructure/instructure-ios/blob/1000ac42782c0422b947180e9f2e47be5597628a/CanvasCore/CanvasCore/Push%20Notifications/NotificationKitController.swift#L30-L34

The relevant part being `lhs.token == rhs.token`. Both of those tokens will be the uppercased versions so that check should be safe.

> when verify token in canvas-lms, notification_endpoint model

I looked at [notification_enpoint.rb](https://github.com/instructure/canvas-lms/blob/master/app/models/notification_endpoint.rb) in canvas-lms and I don't see where the token is verified. Would you mind explaining that a little more?

**Comment by yurikor** [comment]
Thank you for your quick reply.

> I looked at notification_enpoint.rb in canvas-lms and I don't see where the token is verified. Would you mind explaining that a little more?

Check the token_changed function. 
`self.token != endpoint_attributes['Token']`

`self.token` is saved data what we sent device token(it will be saved case sensitivity when called communication_channels api) and `endpoint_attributes['Token']` is aws endpoint token(it is save lowercase always).

It caused push_json function(check the notification_endpoints.rb(:31) in canvas-lms) not working well.
The sns_client.publish not be excuted because that function is returned true.

**Comment by armstrongnate** [comment]
> endpoint_attributes['Token'] is aws endpoint token(it is save lowercase always)

Do you have any control over the aws endpoint token?

**Comment by yurikor** [comment]
Yes i have.

**Pull request closed without merging**
