### PR TITLE
fix crash on homescreen

### PR DESCRIPTION
**Pull request by balintbartok**
refs: none
affects: Student
release note: none
test plan: pull to refresh on K5 homeroom like there's no tomorrow, try after opening an announcement previously

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/102018322/p/56b2c272703ed88d1ff70dde47e5a61a">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/102018333/p/ebb9b06c8b331400c890099607000220">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/102018316/p/2c6e618d1207f0f51e075f3c7207c99a">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.23% | 91.23% | 0%

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
