### PR TITLE
Fix closed section courses showing up on dashboard

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15838
affects: Student
release note: Fixed courses with closed sections showing up on dashboard.

test plan: See ticket.

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by vargaat** [comment]
What changed:
- I extracted the dashboard's course card download logic to a separate view model from the SwiftUI view and modified its behaviour to check if the course's section is already over or not and hide the dashboard card if yes.
- I also extracted the business logic to a view model from the course list SwiftUI view, the same section end date check was added there as well so the expired course will correctly show up in the past courses section.
- As a side effect of this later change the blinking of the enrollment state text on the course list screen also got fixed.

There are a few ViewModelState enums across the app now so after merging this I'm going to extract these to a shared place.

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/111368600/p/4ad3f4d0bbe6c60f605e838cd3eb73d4">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/111368618/p/0e628d5fdc56a973205a215b8e1256a0">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/111368592/p/b4afd20f347295ecf4e71b689a23766f">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 90.96% | 91.37% | -0.41%
Core/Core/Courses/CourseList/ViewModel/CourseListViewModel.swift | 5.13% | -- | --
Core/Core/Dashboard/ViewModel/DashboardCardsViewModel.swift | 0% | -- | --

[MBL-15838](https://instructure.atlassian.net/browse/MBL-15838)

#### Affected Apps: Student

#### Release Note: 
Fixed courses with closed sections showing up on dashboard.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
