### PR TITLE
Change webview User Agent name for LTI tools

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-15278
affects: Teacher
release note: Fixed google authentication for LTI tools

test plan: see ticket (use canvas login)

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73906316/p/014f7232fa90b82dec8af41932d60963">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73906331/p/ac041760f09e26edb671b0b407671eff">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/73906287/p/fb048ac61e2a4f44bf186b7a31571b24">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/Core/SwiftUIViews/WebView.swift:31:37: Redundant Optional Initialization Violation: Initializing an optional variable with nil is redundant. (redundant_optional_initialization)
    
    
</details>


[MBL-15278](https://instructure.atlassian.net/browse/MBL-15278)

#### Affected Apps: Teacher

#### Release Note: 
Fixed google authentication for LTI tools
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
