### PR TITLE
Tell api when we are done using a token

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: none
affects: Parent, Teacher, Student
release note: Fixed an issue causing orphaned Approved Integrations for Canvas for IOS

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by vanwagonet** [comment]
Test plan:
- login & identify your new token in the User Settings page.
- Tap Logout from the profile drawer in the app.
- Verify the token is removed from your User Settings page.
- repeat but using the X to remove your user from the Previous Logins on the start page instead of Logout in the profile drawer.

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1009412&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by inst-danger** [comment]
#### Release Note: 
Fixed an issue causing orphaned Approved Integrations for Canvas for IOS

#### Affected Apps: Parent, Teacher, Student

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.24% | 93.25% | -0.02%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Pull request merged**
