### PR TITLE
K5 dashboard toggle in settings

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15526
affects: Student
release note: none

test plan: K5 mode should be controlled by the switch in the settings menu on K5 accounts. The switch shouldn't be visible for non-k5 users or teachers or when the K5 remote/experimental feature flag is turned off.

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.98% | 91.99% | -0.02%

[MBL-15526](https://instructure.atlassian.net/browse/MBL-15526)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/82897625/p/b50bead8797fbc40faafca644e62b794">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/82897640/p/aacb348fc5ea2fb1ceea5acd1cd6b06a">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/82897602/p/9e2e393aca0db0063391692a419a201f">
    
  </a>
</details>

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]

**Pull request merged**
