### PR TITLE
Rewrite TodoList with tests

### PR DESCRIPTION
**Pull request by vanwagonet**
extra: Update PageList spacing & sizing

refs: MBL-13527
affects: Student
release note: Minor updates to do list appearance

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by vanwagonet** [comment]
tests aren't written yet.

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Minor updates to do list appearance

#### Affected Apps: Student

[MBL-13527](https://instructure.atlassian.net/browse/MBL-13527)

<details><summary>:x: Swift lint</summary>


    ⚠️  /Users/vagrant/git/Core/Core/Todos/Todo.swift:22:1: Duplicate Imports Violation: Imports should be unique. (duplicate_imports)
    Linting 'DocViewerViewController.swift' (141/607)
    Linting 'DocViewerAnnotationProvider.swift' (142/607)
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1012380&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by shichongrui** [comment]
Are we ok with this going out not behind a feature flag?

**Comment by vanwagonet** [comment]
> Are we ok with this going out not behind a feature flag?

Our Experimental flags are to help us not ship incomplete implementations, or where we'd like some time to make sure it's not going to cause problems. This screen is simple & it would introduce more risk & complexity to keep both around than to simply use the new one.

**Comment by vanwagonet** [comment]
> On iPad it is loading the assignment details in the master view and not the details view.

Fixed. Nice catch!

**Pull request merged**
