### PR TITLE
Student app landscape mode support for iPhones

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-14893, MBL-15008, MBL-15009
affects: Student
release note: none

test plan: Check all screens of the app, all should look good and functioning.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/71698187/p/a600b98ca13562d8af335abd5e17e174">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/71698197/p/8644080bd569ac647a4ecf5724d02dbf">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/71698166/p/81ce36d3ce14c135691ba9799ccc2e27">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


<details><summary>:x: Yarn lint</summary>


    
    /Users/vagrant/git/rn/Teacher/src/modules/tabs/HomeTabRow.js
      23:24  error  'Image' is defined but never used              no-unused-vars
      23:31  error  'ActivityIndicator' is defined but never used  no-unused-vars
    
    ✖ 2 problems (2 errors, 0 warnings)
    
</details>
<details><summary>:x: XCTest failed: CoreTests/LoginStartViewControllerTests/testAnimateIn</summary>


    Crash: CoreTester (12335): Namespace SIGNAL, Code 0x4
    Assertion Failure: Crash: CoreTester (12335): Namespace SIGNAL, Code 0x4
</details>


[MBL-14893](https://instructure.atlassian.net/browse/MBL-14893)
[MBL-15008](https://instructure.atlassian.net/browse/MBL-15008)
[MBL-15009](https://instructure.atlassian.net/browse/MBL-15009)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
