### PR TITLE
Save annotations on viewWillDisappear

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBL-13959
affects: student
release note: Fixed a bug that could cause annotations to not be saved

Test plan: Follow steps in [ticket](https://instructure.atlassian.net/browse/MBL-13959)

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1021608&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|1
Medium|17
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---
High|1

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/lhthw3a) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Flhthw3a)
teacher: [Link](https://rebrand.ly/rb6xjo0) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Frb6xjo0)
parent: [Link](https://rebrand.ly/ic1xnyg) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fic1xnyg)

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Fixed a bug that could cause annotations to not be saved

#### Affected Apps: Student

[MBL-13959](https://instructure.atlassian.net/browse/MBL-13959)

<details><summary>:x: Swift lint</summary>


    ⚠️  /Users/vagrant/git/Core/CoreTests/Files/FileDetails/FileDetailsViewControllerTests.swift:253:34: Colon Violation: Colons should be next to the identifier when specifying a type and next to the key in dictionary literals. (colon)
    Linting 'APIQuizTests.swift' (247/666)
    Linting 'APILatePolicyRequestableTests.swift' (248/666)
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1021610&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|1
Medium|17
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---
High|1

**Pull request merged**
