### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by inst-danger**
[ignore-commit-lint]

### CODE REVIEW

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/7du8m5k) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2F7du8m5k)
teacher: [Link](https://rebrand.ly/k1pk390) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fk1pk390)
parent: [Link](https://rebrand.ly/m94hzyo) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fm94hzyo)

**Comment by laura-quijada** [comment]
A

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.17% | 93.17% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by laura-quijada** [comment]
A

**Review by vanwagonet — APPROVED** [review]

**Comment by laura-quijada** [comment]
A

**Pull request merged**
