### PR TITLE
Fix assignment details scroll content getting behind submit button.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15094
affects: Student
release note: none

test plan: See ticket.

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


[MBL-15094](https://instructure.atlassian.net/browse/MBL-15094)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/72164516/p/c18cf6a4669b7e7201dede3f03e99b99">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/72164519/p/c85f549777408e89157365d77cd7ec8b">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/72164503/p/bbfee5f060c38a7282095974cbd7cc42">
    
  </a>
</details>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
