### PR TITLE
Use Core PeopleList in Teacher

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-13642
affects: Teacher
release note: Fixed People list display of custom roles

### CODE REVIEW

**Comment by vanwagonet** [comment]
Test plan: See ticket for credentials. Verify custom roles like Grader and teacher2 are displayed in the list.
Note that filtering still displays & operates on base roles.

**Comment by inst-danger** [comment]
#### Release Note: 
Fixed People list display of custom roles

#### Affected Apps: Teacher

[MBL-13642](https://instructure.atlassian.net/browse/MBL-13642)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.46% | 93.44% | 0.02%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1018625&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|23
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1018626&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|23
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Pull request merged**
