### PR TITLE
Offline sync selector dialog text

### PR DESCRIPTION
**Pull request by szabinst**
refs: MBL-17135
affects: Student
release note: none
test plan: Check dialog message

## Screenshots

<table>
<tr><th>Before</th>
<tr>
<td></td>
</tr>
</table>

## Checklist

- [x] Tested on phone
- [x] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-17135](https://instructure.atlassian.net/browse/MBL-17135)

<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/CoreTests/CourseSync/CourseSyncSelector/Model/CourseSyncSelectorInteractorLiveTests.swift:306:1: Vertical Whitespace Violation: Limit vertical whitespace to a single empty line; currently 2 (vertical_whitespace)
    
    
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9d204a6a6558bc717f1d970cb36b2416f4076181
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by vargaat — DISMISSED** [review]
QA+1, the Core and TestsFoundation project changes could be reverted

**Review by balintbartok — APPROVED** [review]

**Pull request merged**
