### PR TITLE
Fix viewing discussion topics without an author

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBL-13702
affects: parent
release note: none

Test plan: View Parent announcement in ticket

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1014883&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Parent

[MBL-13702](https://instructure.atlassian.net/browse/MBL-13702)

<details><summary>:x: XCTest failed: CoreTests/LoginWebViewControllerTests/testOpenTab</summary>


    Assertion Failure: LoginWebViewControllerTests.swift:165: Asynchronous wait failed: Exceeded timeout of 9 seconds, with unfulfilled expectations: "credentials get posted".
    Assertion Failure: LoginWebViewControllerTests.swift:166: XCTAssertEqual failed: ("Optional(https://localhost:1/)") is not equal to ("Optional(data:text/plain,)")
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by bluwave** [comment]
tested, working great

**Pull request merged**
