### PR TITLE
Darken the green assignment status text, login screen accessibility update

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-16974
affects: Parent, Student, Teacher
release note: none.
test plan: 
- 'success green' should be darker in light mode to fulfil accessibility contrast requirements
- it should stay brighter in dark mode 
- also test the login screen logo group with voiceover

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [x] A11y checked
- [x] Tested on phone
- [ ] Tested on tablet
- [x] Tested in dark mode
- [x] Tested in light mode
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
#### Release Note: 
none.

#### Affected Apps: Parent, Student, Teacher

[MBL-16974](https://instructure.atlassian.net/browse/MBL-16974)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.42% | 92.42% | -0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b4c21becc08ef900fa436d2583c5bb2578168d6c
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by szabinst — APPROVED** [review]
QA + 1

**Pull request merged**
