### PR TITLE
Enable native files & page editor

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: none
affects: Student, Teacher
release note: Fixed some layout issues in editing pages & files

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/51325017/p/45dfb1ed169402d1f5ff1fe0663f8857">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/51325033/p/6fc51d70506d911273929790ff291679">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/51324999/p/f091382442b61eb65d814dbf85fcddb2">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/PageDetailsViewControllerTests/testUpdatesFrontPageWhenChanged</summary>


    Assertion Failure at PageDetailsViewControllerTests.swift:148: XCTAssertEqual failed: ("true") is not equal to ("false")
    Assertion Failure at PageDetailsViewControllerTests.swift:149: XCTAssertEqual failed: ("Optional(false)") is not equal to ("Optional(true)")
</details>
<details><summary>:x: XCTest failed: CoreTests/PageDetailsViewControllerTests/testUpdatesThePageOnEdit</summary>


    Assertion Failure at PageDetailsViewControllerTests.swift:132: XCTAssertEqual failed: ("Optional("Test Page")") is not equal to ("Optional("Changed")")
    Assertion Failure at PageDetailsViewControllerTests.swift:133: XCTAssertEqual failed: ("test-page") is not equal to ("changed")
</details>


#### Affected Apps: Student, Teacher

#### Release Note: 
Fixed some layout issues in editing pages & files
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by armstrongnate — CHANGES_REQUESTED** [review]
Editing a folder name causes the form to disappear and I noticed something weird when adding new files to a nested folder. Videos sent over slack.

**Review by armstrongnate — APPROVED** [review]
QA +1. I noticed that published icons weren't updating but then they were and I couldn't repro again. I added and edited folders, added and edited files. Changed the settings on all those things. Looks good to me.

**Pull request merged**
