### PR TITLE
Add course code to dashboard card's a11y label.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15451
affects: Student, Teacher
release note: Improved accessibility.

test plan: Dashboard cards should announce course code after course name.

### CODE REVIEW

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.96% | 91.96% | 0%

[MBL-15451](https://instructure.atlassian.net/browse/MBL-15451)

#### Affected Apps: Student, Teacher

#### Release Note: 
Improved accessibility.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80329004/p/360af36b41c863e237931ca4f8fa5820">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80329030/p/73baea5c4ccd60b645785eaf5377b6ad">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80328881/p/855e69ad853ed3b4ffe4db698afbab59">
    
  </a>
</details>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
