### PR TITLE
Fix Update Calendar Event issue

### PR DESCRIPTION
**Pull request by rh12**
refs: [MBL-17968](https://instructure.atlassian.net/browse/MBL-17968)
affects: Student, Teacher
release note: none

## Test plan
See ticket for details.

## Checklist
- [ ] Follow-up e2e test ticket created
- [ ] Tested on phone
- [x] Tested on tablet

[MBL-17968]: https://instructure.atlassian.net/browse/MBL-17968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student, Teacher

[MBL-17968](https://instructure.atlassian.net/browse/MBL-17968)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.08% | 91.11% | -0.03%
Core/Core/Planner/CalendarEvent/Model/API/PostCalendarEventRequest.swift | 0% | 0% | 0%
Core/Core/Planner/CalendarEvent/View/CustomFrequencyComponents/OccurrencesCountInputDialog.swift | 0% | 0% | 0%
Core/Core/Planner/CalendarEvent/Model/Helpers/RecurrenceRule+SelectionDescription.swift | 43.33% | 43.33% | 0%
Core/Core/Grades/View/CustomSwipeAction.swift | 0% | 0% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 215e302c1228655ce395d8ddfc85ce17f185f298
</p>

**Review by suhaibabsi-inst — APPROVED** [review]
Thanks @rh12 !
Seems good to me.

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
