### PR TITLE
Fix the issue of annotation bar move button being cut off on landscape mode

### PR DESCRIPTION
**Pull request by suhaibabsi-inst**
refs: [MBL-17988](https://instructure.atlassian.net/browse/MBL-17988)
affects: Student,Teacher
release note: Fix the issue of annotation bar move button being cut off on landscape mode.

## Test Plan

See ticket description for more information about use case testing:
https://instructure.atlassian.net/browse/MBL-17988

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

<table>
<tr><th colspan="2">More Fixed (iPhone)</th></tr>
<tr><td colspan="2"></td></tr>
<tr><td colspan="2"></td></tr>
</table>

<table>
<tr><th colspan="2">More Fixed (iPad)</th></tr>
<tr><td colspan="2"></td></tr>
<tr><td colspan="2"></td></tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [x] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [x] Tested in light mode
- [ ] Approve from product

[MBL-17988]: https://instructure.atlassian.net/browse/MBL-17988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
#### Release Note: 
Fix the issue of annotation bar move button being cut off on landscape mode.

#### Affected Apps: Student, Teacher

[MBL-17988](https://instructure.atlassian.net/browse/MBL-17988)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.7% | 91.7% | 0.01%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e3fba1a3dd09935f8433d389767f246f7bea2284
</p>

**Review by ndrsszsz — APPROVED** [review]
QA +1
Tested on iPhone 11, iOS 18.1

**Pull request merged**
