### PR TITLE
Fix quiz detail routing url.

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-14834
affects: Teacher
release note: Fix cross shard user quizzes.
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/77700293/p/72187590b363de95d3ba46818f932488">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/77700299/p/b03168583973ac0cc96138d7e8bb2a56">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/77700268/p/ec49f8a754ca73b72ca44fe2fd206bd1">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.7% | 91.71% | -0%
Core/Core/Dashboard/K5/ViewModel/K5DashboardViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Grades/K5GradesViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/K5DashboardNavigationViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Schedule/K5ScheduleViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Homeroom/K5HomeroomViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Resources/K5ResourcesViewModel.swift | 0% | 0% | 0%

[MBL-14834](https://instructure.atlassian.net/browse/MBL-14834)

#### Affected Apps: Teacher

#### Release Note: 
Fix cross shard user quizzes.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by vargaat — CHANGES_REQUESTED** [review]
Opening the quizzes tab on an iPad still produces the error. It goes away if I tap on the quiz item in the list however.
IMG_2EA4F5E16380-1

**Review by balintbartok — DISMISSED** [review]
QA + 1

**Review by vargaat — CHANGES_REQUESTED** [review]
Could you check the assignments list screen as well? The quiz doesn't open from assignments but opens from quizzes list, guess we have the same issue here.
IMG_B195A3757AEB-1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
