### PR TITLE
Fix math equations in quizzes

### PR DESCRIPTION
**Pull request by vargaat**
- Extracted almost 200 lines from CoreWebView.
- Created a dedicated Xcode group for webview related files.
- Converted webview initializer flags to features, each having its own implementation file.
- Functionality shouldn't have changed except for the MathJax injection being disabled for classic quizzes.
- Removed the mandatory `pullToRefresh` parameter. To make it disabled simply don't add the feature to the webview.

refs: MBL-16457
affects: Student, Teacher
release note: Fixed some math equations not rendered correctly in quizzes.

test plan:
- See ticket to test the render bug.
- Test webviews in general. (Dark mode, pull to refresh)

## Screenshots

<table>
<tr>
<td></td>
</tr>
</table>

## Checklist

- [ ] Tested on phone
- [x] Tested on tablet
- [x] Tested in dark mode
- [ ] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: TeacherTests/AttendanceViewControllerTests/testCourseError</summary>


    XCTAssertEqual failed: ("Optional(true)") is not equal to ("Optional(false)")
</details>


[MBL-16457](https://instructure.atlassian.net/browse/MBL-16457)

#### Affected Apps: Student, Teacher

#### Release Note: 
Fixed some math equations not rendered correctly in quizzes.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
