### PR TITLE
Testing triggers, Do Not Merge

### PR DESCRIPTION
**Pull request by davidvarga93**
refs: MBL-15741
affects: Student
release note: none

test plan:

### CODE REVIEW

**Comment by inst-danger** [comment]
Student Build QR Code: 
https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F0c864362-1a37-4b7c-baf7-7a3022549876%2Fartifact%2F0645e5f267d695a1%2Fp%2F4a933df00a700c88202017a946096569&size=150x150

**Comment by inst-danger** [comment]
Student Build QR Code: 
Bitrise Install Page QR Code

**Comment by davidvarga93** [comment]
Dont mind me
<details><summary>Student Build QR Code:</summary>
Bitrise Install Page QR Code
</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Pull request closed without merging**
