### PR TITLE
Activate teacher calendar

### PR DESCRIPTION
**Pull request by vargaat**
### What's new?
- A new feature flag for the teacher calendar was added.
- When the flag is on the calendar is added to the teacher app's tab bar.
- Added routes for the event details pages and moved the view controller from the Student to the Core project.
- Hid the calendar filter and the new todo buttons on the calendar page since those are not working for teachers right now.
- Reorganized calendar related files into MVVM groups.

refs: MBL-17295
affects: Teacher, Student
release note: none

test plan:
- Check if calendar appears when feature flag is enabled in teacher app.
- Calendar filter and new todo button shouldn't be visible.
- Events created on web to the teacher's private calendar should appear in the app.
- Tapping on an event should route to the appropriate detail screen.
- Test if calendar event details still open in the Student app after the file movement.

## Checklist

- [ ] Follow-up e2e test ticket created
- [x] Tested on phone
- [x] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Teacher, Student

[MBL-17295](https://instructure.atlassian.net/browse/MBL-17295)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9343bf8d5b3322cfd7ecc1234f256f48a7eaf17c
</p>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by rh12 — APPROVED** [review]
QA + 1

**Review by szabinst — APPROVED** [review]
QA + 1

**Pull request merged**
