### PR TITLE
E2E tests - Maintenance

### PR DESCRIPTION
**Pull request by ndrsszsz**
Fixed all failing E2E tests for all apps
Updated discussion-related test cases (new discussion released to beta)
Updated calendar and people detail test cases regarding the recent changes

[Latest Student E2E Test Build](https://app.bitrise.io/build/4b2cb11a-c568-4bc0-92be-7fc8f8d66397)
[Latest Teacher E2E Test Build](https://app.bitrise.io/build/8eb5de6a-49f6-4efd-8be8-ff808630b088)
[Latest Parent E2E Test Build](https://app.bitrise.io/build/662fb413-361a-41df-990e-376d3bf733b8)

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: None

[MBL-17656](https://instructure.atlassian.net/browse/MBL-17656)

<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/TestsFoundation/Extensions/XCUIElementExtensions.swift:370:1: Trailing Whitespace Violation: Lines should not have trailing whitespace (trailing_whitespace)
    /Users/vagrant/git/Student/StudentE2ETests/Calendar/CalendarTests.swift:332:1: error: Trailing Whitespace Violation: Lines should not have trailing whitespace (trailing_whitespace)
    
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 663d504ebd540c9aade5c2fb788665a68a10489c
</p>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Review by vargaat — APPROVED** [review]

**Pull request merged**
