### PR TITLE
Check course's published state when determining if a group is active.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-17444
affects: Student
release note: Fixed groups from unpublished courses showing up on dashboard.

test plan: See ticket.

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] Tested on phone
- [ ] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Fixed groups from unpublished courses showing up on dashboard.

#### Affected Apps: Student

[MBL-17444](https://instructure.atlassian.net/browse/MBL-17444)

<details><summary>:x: XCTest failed: CoreTests/CourseSyncCleanupInteractorTests/testApplicationOfflineDirectoryForUserDeleted</summary>


    XCTAssertFalse failed
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d301e2c465505558bd72c883fcf4dab304e9494c
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by rh12 — APPROVED** [review]
QA + 1

**Pull request merged**
