### PR TITLE
Rotating the device back and forth creates a truncated menu item

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-16847
affects: Student, Teacher, Parent
release note: Fixed bottom tab bar text alignment.
test plan: See ticket.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [x] Tested on phone
- [ ] Tested on tablet
- [x] Tested in dark mode
- [ ] Tested in light mode
- [x] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Fixed bottom tab bar text alignment.

#### Affected Apps: Student, Teacher, Parent

[MBL-16847](https://instructure.atlassian.net/browse/MBL-16847)

<details><summary>:x: XCTest failed: CoreTests/BackgroundActivityTests/testStartsBackgroundActivity</summary>


    XCTAssertEqual failed: ("nil") is not equal to ("Optional(Combine.Subscribers.Completion<Core.BackgroundActivity.ActivityError>.finished)")
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e6095dc9353ebf7f431a5f6bce44ee90cedac56b
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by szabinst — APPROVED** [review]
QA + 1

**Pull request merged**
