### PR TITLE
Offline UI preparations

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16648
affects: Student, Teacher, Parent
release note: none

test plan:
- Go to Developer menu and enter Toast Test menu.
- Test layout, a11y, different themes, message queueing

## Demo

https://user-images.githubusercontent.com/72396990/233346872-669bf9e0-c2f6-4bd1-9bda-f28a4d6efa17.MP4

https://user-images.githubusercontent.com/72396990/233346879-eb1fd80e-ba8b-4d3c-ae71-50ce37d4d11d.MP4

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student, Teacher, Parent

[MBL-16648](https://instructure.atlassian.net/browse/MBL-16648)

<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/Core/API/APIMock.swift:22:22: Blanket Disable Command Violation: The disabled 'force_try' rule should be re-enabled before the end of the file (blanket_disable_command)
    /Users/vagrant/git/Core/Core/DocViewer/DocViewerViewController.swift:224:25: error: Blanket Disable Command Violation: The enabled 'function_parameter_count' rule was not disabled (blanket_disable_command)
    
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7b0faabce2de7879b146159ad8edf9f910f50473
</p>

**Review by idevainstr — APPROVED** [review]
QA +1 🏅

**Pull request merged**
