### PR TITLE
Fix Calendar swiping

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-15379
affects: Student, Teacher
release note: Fixed initial calendar swiping.

test plan: see ticket, also try pressing today a few times, and test again

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.84% | 91.84% | 0%
Core/Core/Dashboard/K5/ViewModel/K5DashboardViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Grades/K5GradesViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/K5DashboardNavigationViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Homeroom/K5HomeroomViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Schedule/K5ScheduleViewModel.swift | 0% | 0% | 0%
Core/Core/Dashboard/K5/ViewModel/Resources/K5ResourcesViewModel.swift | 0% | 0% | 0%

[MBL-15379](https://instructure.atlassian.net/browse/MBL-15379)

#### Affected Apps: Student, Teacher

#### Release Note: 
Fixed initial calendar swiping.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/75849748/p/7ca72b743e2c30d89b429c8a9384de69">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/75849750/p/e68da413a3ced6c6424f2a5db54e8401">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/75849737/p/c70abcffa65200288b1db2119dab12b6">
    
  </a>
</details>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Pull request merged**
