### PR TITLE
Use pageID to identify edited page

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-15443
affects: Teacher
release note: Fixed page title not updating after edit

test plan: see ticket

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/78210913/p/24a15fa5e57734a2c3b827cdf5de2355">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/78210923/p/c399b4177eb86e06cf6960966ea70525">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/78210843/p/a8af240e56d5ea373c836b92c092bed9">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/PageDetailsViewControllerTests/testLayout</summary>


    Assertion Failure at PageDetailsViewControllerTests.swift:91: XCTAssertEqual failed: ("Optional("Test Page")") is not equal to ("Optional("Refreshed")")
    Assertion Failure at PageDetailsViewControllerTests.swift:92: XCTAssertNil failed: "<UIBarButtonItem: 0x7fe17268da90> target=0x7fe17268d590 action=showOptions: image=<UIImage:0x600000bec3f0 named(com.instructure.icanvas.Core: moreLine) {24, 24}>"
</details>


[MBL-15443](https://instructure.atlassian.net/browse/MBL-15443)

#### Affected Apps: Teacher

#### Release Note: 
Fixed page title not updating after edit
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by vargaat — APPROVED** [review]

**Pull request merged**
