### PR TITLE
Align Student & Teacher routing

### PR DESCRIPTION
**Pull request by vanwagonet**
extra: Allows the FilterHeaderView to be auto sized & have up to 2 lines in the title

refs: MBL-14799
affects: Student, Teacher
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/51641931/p/89c54651749a41c95bf49c9918eb20ae">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/51641952/p/c9273c6313e7b0440dbe0beeaccb0013">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/51641910/p/c95a43132e17628b598b4dabc214d9a2">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.28% | 93.13% | 0.15%

[MBL-14799](https://instructure.atlassian.net/browse/MBL-14799)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by armstrongnate — CHANGES_REQUESTED** [review]
Missing route to syllabus (`/courses/:courseID/assignments/syllabus`) clicking a syllabus shows assignment details with an error. it should show syllabus in a web view.

I noticed that unregistered routes are launching safari proper when they launch sfsafari on master. we want to use sfsafari when possible.

**Review by armstrongnate — CHANGES_REQUESTED** [review]
Tapping an assignment from the To Do list is taking me to the submission list instead of speed grader.

**Review by armstrongnate — APPROVED** [review]
To Do is broke on master. This should be good to go.

**Pull request merged**
