### PR TITLE
Global announcements cannot be expanded

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15944
affects: Student, Teacher
release note: Fixed global announcements cannot be expanded on the dashboard.
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.15% | 91.14% | 0.01%

[MBL-15944](https://instructure.atlassian.net/browse/MBL-15944)

#### Affected Apps: Student, Teacher

#### Release Note: 
Fixed global announcements cannot be expanded on the dashboard.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/0b437c13-4c77-4528-8408-3f5f3c6431da/artifact/c6bde06f90f4f32b/p/b0e32203ad1c7a1d8fdd58e44fd1f706">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/0b437c13-4c77-4528-8408-3f5f3c6431da/artifact/04eb985c75176038/p/3fd507479bd8578faf813eec909e5bff">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/0b437c13-4c77-4528-8408-3f5f3c6431da/artifact/e23884f06d29850a/p/026f2c9cf73bb548b4faef240ec1e1dc">
    
  </a>
</details>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by vargaat — APPROVED** [review]

**Pull request merged**
