### PR TITLE
Add endOfMonth and startOfMonth helpers

### PR DESCRIPTION
**Pull request by bluwave**
refs: MBL-13903
affects: Parent
release note: none

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/4e6nm40) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2F4e6nm40)
teacher: [Link](https://rebrand.ly/mz9xe5k) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fmz9xe5k)
parent: [Link](https://rebrand.ly/kwy338t) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fkwy338t)

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1022840&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|2
Medium|17
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---
High|1

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Parent

[MBL-13903](https://instructure.atlassian.net/browse/MBL-13903)

<details><summary>:x: XCTest failed: CoreTests/DateExtensionsTests/testEndOfMonth</summary>


    Assertion Failure: DateExtensionsTests.swift:86: XCTAssertEqual failed: ("2019-12-31 00:00:00 +0000") is not equal to ("2019-12-31 07:00:00 +0000")
</details>
<details><summary>:x: XCTest failed: CoreTests/DateExtensionsTests/testStartOfMonth</summary>


    Assertion Failure: DateExtensionsTests.swift:79: XCTAssertEqual failed: ("2019-12-01 00:00:00 +0000") is not equal to ("2019-12-01 07:00:00 +0000")
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1022845&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|17
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Pull request merged**
