### PR TITLE
Fix reply button a11y

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-14033
affects: Student, Teacher
release note: Improve accessibility in discussions

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/5kb7465) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2F5kb7465)
teacher: [Link](https://rebrand.ly/8sqat0b) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2F8sqat0b)
parent: [Link](https://rebrand.ly/1uvdn98) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2F1uvdn98)

**Comment by inst-danger** [comment]
#### Release Note: 
Improve accessibility in discussions

#### Affected Apps: Student, Teacher

[MBL-14033](https://instructure.atlassian.net/browse/MBL-14033)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.61% | 93.61% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by bluwave** [comment]
Are traits still needed as well as role on some of these?

**Comment by vanwagonet** [comment]
> Are traits still needed as well as role on some of these?

Nope, we should be using `accessibilityRole` & `accessibilityStates` instead.

**Pull request merged**
