### PR TITLE
Assignment details UI update

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16514, MBL-17187
affects: Student
release note: none

test plan:
- Check all states of the assignment details page.
- Also check if UI updates related to late assignments are implemented according to MBL-17187.

## Screenshots

<table>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-16514](https://instructure.atlassian.net/browse/MBL-16514)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.66% | 91.66% | 0.01%
Core/Core/Inbox/ComposeMessage/Model/ComposeMessageInteractorLive.swift | 0% | 0% | 0%
Core/Core/Inbox/ComposeMessage/ViewModel/ComposeMessageViewModel.swift | 33.97% | 33.97% | 0%
Core/Core/Inbox/Addressbook/ViewModel/AddressbookViewModel.swift | 0% | 0% | 0%
Core/Core/Inbox/Addressbook/Model/AddressbookInteractorLive.swift | 0% | 0% | 0%
Core/Core/Inbox/ComposeMessage/Model/MessageParameters.swift | 0% | 0% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5440a3d3a9603023dd9194a9eba4eb75c5379b8a
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Comment by vargaat** [comment]
Fixed the glitches you mentioned and another one related to incomplete assignments.

**Review by domonkosadam — APPROVED** [review]
QA + 1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
