### PR TITLE
Fix annotation menu on read only documents

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15685
affects: Student, Teacher
release note: Fixed annotations being editable on a read-only document.

test plan: 
- As a student, create a file submission with a pdf file that has 3rd party annotations (use Preview app on macOS to create such).
- As a teacher start annotating the document. 3rd party annotations shouldn't be editable (move, style, delete, comment). Add some annotations. Add a comment to one of your annotations.
- As a student go to Submission & Rubric and load your uploaded file.
- Teacher and 3rd party annotations should be visible.
- Neither teacher's nor 3rd party annotations should be editable (move, style, delete).
- Comment menu should display on the annotation where the teacher left a comment.

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.2% | 91.14% | 0.06%

[MBL-15685](https://instructure.atlassian.net/browse/MBL-15685)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/100283956/p/83e07bf2206ea92b3a72f7e357db3005">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/100283970/p/ae02391fa1e88e261eb3802d0ae706cd">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/100283904/p/fc833812cd65f5482592a4c5f368d640">
    
  </a>
</details>

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
