### PR TITLE
Add student annotation icon to submission history screen. Fix confetti not getting animated.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15401
affects: Student
release note: none

test plan:
- As a student submit to a student annotation submission.
- Confetti animation should play.
- Go to Submission & Rubric and check your submission in the comments tab.
- Annotation icon should be visible next to the "Student Annotation" text.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/101861675/p/474f5712e72dbaf3c56151f2408e1367">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/101861733/p/8fbafdb05e56513e9478f0a4aeab2bd2">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/101861452/p/4b70c99c251535d3a28fea0f84f0df73">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.23% | 91.23% | 0%

[MBL-15401](https://instructure.atlassian.net/browse/MBL-15401)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
