### PR TITLE
Update PSPDFKit version

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16480
affects: Student, Teacher
release note: none

test plan:
 - Test annotations in the teacher and student apps.

## Checklist

- [x] Tested on phone, iOS 14
- [ ] Tested on tablet, iOS 14
- [x] Tested on phone, iOS 15
- [x] Tested on tablet, iOS 15
- [ ] Tested on phone, iOS 16
- [x] Tested on tablet, iOS 16

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.85% | 91.85% | 0%
Core/Core/Submissions/SubmissionBreakdown/SubmissionBreakdownViewModelProtocol.swift | 0% | 0% | 0%
Core/Core/Quizzes/QuizDetails/ViewModel/PreviewQuizDetailsViewModel.swift | 0% | 0% | 0%

[MBL-16480](https://instructure.atlassian.net/browse/MBL-16480)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
