### PR TITLE
Fix grades for previously graded submissions

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBL-13454
affects: student
release note: Fixed a bug that would cause an assignment to incorrectly appear as submitted

Test plan:
* See steps [in ticket](https://instructure.atlassian.net/browse/MBL-13454)
* From the assignments in the ticket, only the quiz should have a grade on assignment details
* All other assignments in the ticket should not show the Grade section
* View submitted, excused, graded, late, and unsubmitted assignments using another student (narmstrong > s > CS 1400 has examples)

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1010467&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  You have included an invalid app. Valid values are: Student, Teacher, Parent, None
  </td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Fixed a bug that would cause an assignment to incorrectly appear as submitted

[MBL-13454](https://instructure.atlassian.net/browse/MBL-13454)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.3% | 93.29% | 0.01%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by armstrongnate** [comment]
Whoa 8.75% coverage delta! I'm not sure that I completely trust it but it's something.

**Pull request merged**
