### PR TITLE
MBL-13145 - show location on calendar event details

### PR DESCRIPTION
**Pull request by bluwave**
refs: MBL-13145
affects: Student
release note: Added location to calendar event details

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1005368&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by bluwave** [comment]
@armstrongnate - i'll have dave look at it

**Comment by bluwave** [comment]
we have approval from dave 👍 , thanks for reviewing this

**Pull request merged**
