### PR TITLE
App crash on rotating with Syllabus

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15519
affects: Student, Teacher
release note: Fix Syllabus page rotation.
test plan: see ticket

### CODE REVIEW

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.99% | 91.99% | 0%

[MBL-15519](https://instructure.atlassian.net/browse/MBL-15519)

#### Affected Apps: Student, Teacher

#### Release Note: 
Fix Syllabus page rotation.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/82877660/p/59c80999c3fa587a0baf2ddaf2d4dd8c">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/82877688/p/4a07e73205fe93f885cc66606d06060a">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/82877638/p/6fbd012531c84c3e8eddbf8f66156554">
    
  </a>
</details>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Pull request merged**
