### PR TITLE
Finalize offline progress screen

### PR DESCRIPTION
**Pull request by szabinst**
Finalize offline progress and selector screen

refs: MBL-17091
affects: Student
release note: none
test plan: See ticket

## Screenshots

<table>
<tr><th>Selector - Text (to be changed)</th><th>Dashboard - Progress text</th></tr>
<tr>
<td></td>
<td></td>
<tr><th>Progress - Cancel disabled</th><th>Notification text</th></tr>
<td></td>
<td></td>
</tr>
</table>

<table>
<tr>Progress - Retry unavailable</tr>
<td></td>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [x] Tested on phone
- [x] Tested on tablet
- [x] Tested in dark mode
- [x] Tested in light mode
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-17091](https://instructure.atlassian.net/browse/MBL-17091)

<details><summary>:x: XCTest failed: CoreTests/CourseSyncSelectorViewModelTests/testUpdateConfirmationDialogMessage</summary>


    XCTAssertEqual failed: ("There are 3 courses selected for offline availability. The selected content will be downloaded to the device.") is not equal to ("There are 3 items selected for offline availability. The selected content will be downloaded to the device.")
</details>
<details><summary>:x: XCTest failed: CoreTests/DashboardOfflineSyncProgressCardViewModelTests/testProgressUpdates</summary>


    XCTAssertEqual failed: ("progress(0.1, "1 course is syncing.")") is not equal to ("progress(0.1, "2 items are syncing.")")
    XCTAssertEqual failed: ("progress(0.5, "1 course is syncing.")") is not equal to ("progress(0.5, "2 items are syncing.")")
    XCTAssertEqual failed: ("progress(0.75, "1 course is syncing.")") is not equal to ("progress(0.75, "2 items are syncing.")")
    XCTAssertEqual failed: ("progress(1.0, "1 course is syncing.")") is not equal to ("progress(1.0, "2 items are syncing.")")
</details>
<details><summary>:x: XCTest failed: CoreTests/DashboardOfflineSyncProgressCardViewModelTests/testSubtitleItemCounterIgnoresContainerSelections</summary>


    XCTAssertEqual failed: ("progress(0.5, "1 course is syncing.")") is not equal to ("progress(0.5, "2 items are syncing.")")
</details>
<details><summary>:x: XCTest failed: CoreTests/LocalNotificationsTests/testOfflineSyncCompletedSuccessfullyNotificationPlural</summary>


    XCTAssertEqual failed: ("2 courses have been synced.") is not equal to ("2 items have been synced.")
</details>
<details><summary>:x: XCTest failed: CoreTests/LocalNotificationsTests/testOfflineSyncCompletedSuccessfullyNotificationSingular</summary>


    XCTAssertEqual failed: ("1 course has been synced.") is not equal to ("1 item has been synced.")
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e435b1b0720a99c11d9cced2a3305e4fce4ccf6b
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
