### PR TITLE
Dashboard layout toggle

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15872
affects: Student, Teacher
release note: Added layout selector button to dashboard.

test plan: 
- Check if layout looks good in both settings on multiple devices and orientations.
- Selected layout should be restored after app restart.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/113813714/p/7443bf0cda54ffd4d6fd7acf1b645e44">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/113813722/p/b832339752b0bf662d5519dbc68b2188">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/113813708/p/989535439ee8cc446ebcf6d376b73d84">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: StudentUnitTests/UrlSubmissionPresenterTests/testSubmitSuccess</summary>


    Assertion Failure at UrlSubmissionPresenterTests.swift:70: Asynchronous wait failed: Exceeded timeout of 10 seconds, with unfulfilled expectations: "dismissed".
</details>


[MBL-15872](https://instructure.atlassian.net/browse/MBL-15872)

#### Affected Apps: Student, Teacher

#### Release Note: 
Added layout selector button to dashboard.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by davidvarga93 — APPROVED** [review]
QA + 1 
iPhone 11 iOS 15.4b

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
