### PR TITLE
Fix wrong CalendarEventDetails screen showing in Parent app

### PR DESCRIPTION
**Pull request by rh12**
refs: [MBL-17946](https://instructure.atlassian.net/browse/MBL-17946)
affects: Parent
release note: Fixed issues on calendar event screen.

test plan: See ticket

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist
- [ ] Follow-up e2e test ticket created
- [ ] Tested on phone
- [ ] Tested on tablet

[MBL-17946]: https://instructure.atlassian.net/browse/MBL-17946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Release Note: 
Fixed issues on calendar event screen.

#### Affected Apps: Parent

[MBL-17946](https://instructure.atlassian.net/browse/MBL-17946)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.46% | 91.43% | 0.03%
Core/Core/Planner/CalendarEvent/Model/API/PostCalendarEventRequest.swift | 0% | 0% | 0%
Core/Core/Planner/CalendarEvent/View/CustomFrequencyComponents/OccurrencesCountInputDialog.swift | 0% | 0% | 0%
Core/Core/Planner/CalendarEvent/Model/Helpers/RecurrenceRule+SelectionDescription.swift | 43.33% | 43.33% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against dd1b1445c7a6a9a97b8c8222626932614e3c4918
</p>

**Review by suhaibabsi-inst — APPROVED** [review]
Looks good to me.

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
