### PR TITLE
Fix file module item ui test

### PR DESCRIPTION
**Pull request by armstrongnate**
[ignore-commit-lint]

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by armstrongnate** [comment]
This test needs to have experimental features disabled so I needed to add a way to disable them from tests.

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1006765&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.18% | 93.18% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by armstrongnate** [comment]
Running this locally and it still has issues.. I think we need a better way to disable the refresh tokens feature flag for tests.

**Pull request closed without merging**
