### PR TITLE
Disable horizontal bouncing of hybrid discussion page

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-17317
affects: Student, Teacher
release note: none

test plan: Hybrid discussion page shouldn't bounce horizontally.

## Checklist

- [x] Tested on phone
- [x] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student, Teacher

[MBL-17317](https://instructure.atlassian.net/browse/MBL-17317)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.04% | 92.04% | 0.01%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8d8a216e54fc86c3b3918be5da8cd334a3dbb236
</p>

**Comment by balintbartok** [comment]
I see the same bouncing horizontal behaviour on iPad
https://github.com/instructure/canvas-ios/assets/72031065/7e1df282-3567-4e54-be10-df01b34ac292

**Comment by vargaat** [comment]
I took a different approach by overriding any horizontal contentOffset changes. The previous implementation didn't work in all cases and I couldn't figure out why, it was related to the web content's size but even when it matched the webview's size and the horizontal bouncing was disabled it was still bouncing on iPads but not on iPhones.

**Review by szabinst — APPROVED** [review]
QA + 1, elegant solution!

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
