### PR TITLE
Message teachers from syllabus

### PR DESCRIPTION
**Pull request by bluwave**
refs: MBL-12995
affects: Parent
release note: none

Test plan
1. go to course grades, select a course with multiple different types of tabs
2. click reply, the subject should say students name and the tab title they are on.

Screen Shot 2020-01-10 at 8 39 13 AM

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1018080&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|23
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Parent

[MBL-12995](https://instructure.atlassian.net/browse/MBL-12995)

<details><summary>:x: XCTest failed: CoreTests/GetSearchRecipientsTests/testFilter</summary>


    Assertion Failure: GetSearchRecipientsTests.swift:42: XCTAssertEqual failed: ("?search=&context=course_1&per_page=50") is not equal to ("?context=course_1&search=&per_page=50")
</details>
<details><summary>:x: XCTest failed: CoreTests/GetSearchRecipientsTests/testScope</summary>


    Assertion Failure: GetSearchRecipientsTests.swift:37: XCTAssertEqual failed: ("Scope(predicate: filter == "?search=&context=course_1&per_page=50", order: [(fullName, ascending, compare:)], sectionNameKeyPath: nil)") is not equal to ("Scope(predicate: filter == "?context=course_1&search=&per_page=50", order: [(fullName, ascending, compare:)], sectionNameKeyPath: nil)")
</details>
<details><summary>:x: XCTest failed: CoreTests/LoginWebViewControllerTests/testPreloaded</summary>


    Assertion Failure: LoginWebViewControllerTests.swift:61: Asynchronous wait failed: Exceeded timeout of 9 seconds, with unfulfilled expectations: "credentials get posted".
    Assertion Failure: LoginWebViewControllerTests.swift:62: XCTAssertEqual failed: ("Optional(https://localhost:1/)") is not equal to ("Optional(https://localhost:1/?username=u&password=p)")
</details>
<details><summary>:x: XCTest failed: CoreTests/SearchRecipientTests/testSaveIntoCoreData</summary>


    Assertion Failure: SearchRecipientTests.swift:42: XCTAssertEqual failed: ("?search=&context=course_1&per_page=50") is not equal to ("?context=course_1&search=&per_page=50")
</details>
<details><summary>:x: XCTest failed: CoreTests/SearchRecipientTests/testUpdateExisting</summary>


    Assertion Failure: SearchRecipientTests.swift:53: XCTAssertEqual failed: ("John Doe") is not equal to ("Jane Doe")
</details>
<details><summary>:x: XCTest failed: ParentUnitTests/CourseDetailsViewControllerTests/testInboxReplyButton</summary>


    Assertion Failure: CourseDetailsViewControllerTests.swift:59: XCTAssertTrue failed
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1018081&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|23
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1018082&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|23
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Pull request merged**
