### PR TITLE
Disable first assignment selection in assignment list to fix split rotation issues.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15773
affects: Student, Teacher
release note: none

test plan: See ticket.

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by vargaat** [comment]
I added two overrides to CoreHostingController.swift but in the end I didn't use them for this fix. I thought they might come handy in the future so I left them there.

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


<details><summary>:x: Yarn lint</summary>


    
    /Users/vagrant/git/rn/Teacher/src/modules/assignments/AssignmentList.js
      46:15  error  'TraitCollection' is defined but never used       no-unused-vars
      47:10  error  'isRegularDisplayMode' is defined but never used  no-unused-vars
    
    ✖ 2 problems (2 errors, 0 warnings)
    
</details>


[MBL-15773](https://instructure.atlassian.net/browse/MBL-15773)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1 (iPad)

**Pull request merged**
