### PR TITLE
Statusbar text is black on all screens

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15778
affects: Parent
release note: Fixed the status bar color theming.
test plan: See ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.36% | 91.35% | 0.01%

[MBL-15778](https://instructure.atlassian.net/browse/MBL-15778)

#### Affected Apps: Parent

#### Release Note: 
Fixed the status bar color theming.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/102441416/p/7ea05b9b601a5e68d67fde1f9450a384">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/102441431/p/0eae43d9d2f0ecfa9618b1185e0cd19e">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/102441401/p/c43d3c01355299673cf6bad4b54ab2bf">
    
  </a>
</details>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
