### PR TITLE
Add SwiftLint build phase

### PR DESCRIPTION
**Pull request by szabolcs-instructure**
## Description 
This PR adds `SwiftLint` as a Build Phase to the following targets
- Core
- Student
- Teacher
- Parent

## Setup for features 
1. Main configuration file `.swiftlint.yml` in `$PROJECT_DIR`
2. Child configuration file `$PROJECT_DIR/Target/.swiftlint.yml` that sets 1. as `parent_config` 

## Setup for tests
For some reason referencing a shared configuration file didn't work, so every test target has a `.swiftlint.yml` file with some basic rules.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by idevainstr — APPROVED** [review]
🏅

**Review by vargaat — APPROVED** [review]
Looks good on first try. Let's merge it and see how it goes on the long run!

**Pull request merged**
