### PR TITLE
Update Crashlytics SDK

### PR DESCRIPTION
**Pull request by rh12**
refs: [MBL-17372](https://instructure.atlassian.net/browse/MBL-17372)
affects: All
release note: none

test plan: Build & run all apps

## Checklist

- [x] Tested Teacher
- [x] Tested Student
- [x] Tested Parent

[MBL-17372]: https://instructure.atlassian.net/browse/MBL-17372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>You have included an invalid app. Valid values are: Student, Teacher, Parent, None</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


[MBL-17372](https://instructure.atlassian.net/browse/MBL-17372)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 71142a67e28d791731ea2938bafd148ff8852cd9
</p>

**Review by vargaat — APPROVED** [review]
QA+1, Teacher app didn't log the crashlytics version.

**Review by szabinst — APPROVED** [review]
QA + 1

**Pull request merged**
