### PR TITLE
Make today button visible on all schedule pages

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15608
affects: Student
release note: none

test plan: Today button should be visible on all week pages of the schedule tab, not just on the current week.

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.81% | 91.81% | 0%

[MBL-15608](https://instructure.atlassian.net/browse/MBL-15608)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/90740222/p/17656aa27f3efbf721974b257addd9db">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/90740238/p/972303e9756933371f7a927c300bb9ee">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/90740173/p/4aefd5564bbbd7ebe54a63a885848776">
    
  </a>
</details>

**Review by davidvarga93 — DISMISSED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
