### PR TITLE
Offline announcements

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16770
affects: Student
release note: none

test plan:
- Sync Announcements tab for offline usage.
- Turn off internet on the device.
- Go to Announcements list.
- Announcements should appear.
- Enter an announcement.
- Announcement and replies should render.
- Images/MathJax equations won't be available.
- User actions shouldn't be available beside the replies button that is show is there are too many replies in a thread.

## Checklist

- [ ] Tested on phone
- [x] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-16770](https://instructure.atlassian.net/browse/MBL-16770)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.4% | 92.39% | 0.01%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 970f372188721ca072b635f0b5bfe5cde8101976
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
