### PR TITLE
Add a11y identifier for eye icon

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-15124
affects: Teacher
release note: none

test plan: See ticket ( submission header eye icon identifier)

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.07% | 92.07% | 0%

[MBL-15124](https://instructure.atlassian.net/browse/MBL-15124)

#### Affected Apps: Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/71375412/p/9bebe014446067672edcd0e8a5eba89e">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/71375425/p/3a8845071f53e00e1df5b785556458f8">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/71375379/p/f7a926c4aef0e96042796b0215a5db18">
    
  </a>
</details>

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
