### PR TITLE
[Horizon] - Routes from program details

### PR DESCRIPTION
**Pull request by szabinst**
Adds route handling from program details if the type is already supported. 

Supported types: 
- assignments
- files
- quizzes
- pages

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



<details><summary>:x: Swift lint</summary>


    
    ----- xcbeautify -----
    Version: 2.11.0
    ----------------------
    
    ❌ /Users/vagrant/git/Horizon/Horizon/Sources/Common/View/ExpandingModuleView.swift:78:1: Trailing Whitespace Violation: Lines should not have trailing whitespace (trailing_whitespace)
    
    
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 82db9bbcc56cb9b84927262ac7b7a874078cdb43
</p>

**Comment by Ahmed-Naguib93** [comment]
QA + 1

**Review by Ahmed-Naguib93 — APPROVED** [review]

**Comment by Ahmed-Naguib93** [comment]
When you open the assignment view and then back to the programs details will see the navigation controller color changed  

https://github.com/user-attachments/assets/e8a0ac23-2e9b-436c-9de9-0d620fc614d4

**Comment by szabinst** [comment]
https://github.com/instructure/canvas-ios/pull/2954 was based on this branch and it's already merged, so closing this one.

**Pull request closed without merging**
