### PR TITLE
Update to iOS 14 deployment target

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15704
affects: Parent, Student, Teacher
release note: none

test plan: Check if the UI of all three apps display correctly. Old grades widget got removed.

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.17% | 91.18% | -0%

[MBL-15704](https://instructure.atlassian.net/browse/MBL-15704)

#### Affected Apps: Parent, Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/f54153b1-c138-4411-ae56-4b1d88255ef1/artifact/c6232cc169b27c81/p/a2a4f78a1faeb055d03b7b511d2813d4">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/f54153b1-c138-4411-ae56-4b1d88255ef1/artifact/9c4cf8229c930e47/p/d07dd413c1066707bcfd584651c3ee60">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/f54153b1-c138-4411-ae56-4b1d88255ef1/artifact/6e6126865e21e11f/p/01e4059e55a6f82f13a9491df55caa63">
    
  </a>
</details>

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
