### PR TITLE
Fix dark mode loading state color mismatch

### PR DESCRIPTION
**Pull request by tamasiscoming**
refs: MBL-16121
affects: Student, Teacher
release note: none
test plan: See ticket.

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/c1001d07-d02c-4416-91f6-6dd81cdd447c/artifact/35ca48dfaf9f9efe/p/9cebbdd7f9da7e1deebbbb5c1cc4ec89">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/c1001d07-d02c-4416-91f6-6dd81cdd447c/artifact/8157efebdf2e83b6/p/02cee7e513ae98461760bdef944e9ab5">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/c1001d07-d02c-4416-91f6-6dd81cdd447c/artifact/0751b66958857172/p/206d4d5b3b5c60383fb2cb4c83fbcbda">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.69% | 91.69% | 0%

[MBL-16121](https://instructure.atlassian.net/browse/MBL-16121)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
