### PR TITLE
Move PSPDFKit from cocoapods to swiftpm

### PR DESCRIPTION
**Pull request by vargaat**
Check if debug console commands work.

Computer! I need Student, Teacher and Parent builds.

[ignore-commit-lint]

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.39% | 92.38% | 0.01%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 643caa69958a42d592b2a5b81a03f197d8b5276e
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by szabinst — APPROVED** [review]
QA + 1

**Pull request merged**
