### PR TITLE
Add assignment reminders UI

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-17296
affects: Student
release note: none

test plan:
- Turn on assignment reminder experimental flag.
- Go to an assignment that has a due date set in the future.
- Check if add reminder section is visible.
- Add pre defined and custom reminders.
- Only UI, there's no business logic or notifications really scheduled.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [x] A11y checked
- [x] Tested on phone
- [ ] Tested on tablet
- [x] Tested in dark mode
- [x] Tested in light mode
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-17296](https://instructure.atlassian.net/browse/MBL-17296)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.05% | 92.03% | 0.03%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 702d259d9f727ea5ffbdd869d6d0825a825929e6
</p>

**Review by szabinst — CHANGES_REQUESTED** [review]
In general it looks good but I noticed some areas that could be improved. 

The "Add due date.." text is clipping on my iPhone 12. 



---
After a new date is selected and the selector screen is being dismissed, there's a black background view for a moment. 



---

While in VoiceOver mode, previously added reminders cannot be removed.

**Comment by vargaat** [comment]
> The "Add due date.." text is clipping on my iPhone 12.
Fixed.
> After a new date is selected and the selector screen is being dismissed, there's a black background view for a moment.
Fixed.
> While in VoiceOver mode, previously added reminders cannot be removed.
Delete is added as an action on the reminder row, VoiceOver should announce this by saying "actions available".

I also fixed a bug that caused the section not to fill horizontally the screen on devices without split mode.

**Review by balintbartok — APPROVED** [review]
Looks amazing! I had a hard time finding the voiceover delete, buz got there eventually!

QA + 1

**Pull request merged**
