### PR TITLE
Fix initial placement of images in file details

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-13861
affects: Student
release note: Fixed an issue with image placement on file details

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by bluwave** [comment]
Nice!!!

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1019482&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|15
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by inst-danger** [comment]
#### Release Note: 
Fixed an issue with image placement on file details

#### Affected Apps: Student

[MBL-13861](https://instructure.atlassian.net/browse/MBL-13861)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.56% | 93.56% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Pull request merged**
