### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by inst-danger**
affects: Parent, Student, Teacher<br/><br/>[ignore-commit-lint]

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.75% | 91.75% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e6dd8a8279683ba5804db2317bc4f5c4e710582e
</p>

**Review by vargaat — APPROVED** [review]

**Pull request merged**
