### PR TITLE
Share extension UI update

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15728
affects: Student
release note: Updated UI on the file share component. To submit your files to assignments directly from iOS, tap the share icon and select the Student app.

test plan:
- Log out with all users or reset cache in the application.
- Start the file share extension.
- Please log in via the application message should be shown.
---
- Log in with a student in the app then start the share extension with an image and a video.
- Course list should populate upon entering the course selector screen.
- Assignments of the selected course should show up in the assignments list screen.
- Add a text comment.
- Check the preview of the shared images, their list should be horizontally scrollable, video length should be indicated.
- Tap on submit, UI should disappear and submission success message should be shown in a notification.
---
- Create an assignment which has a file linked in its description.
- Open the student app, go to that assignment, open the file. It should be shown in a separate screen.
- Start the share extension.
- The previously visited course and assignment should be auto selected.
---

IMG_40A438BB8171-1

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/99482741/p/81a4bb628c5c07584937300202ae9b3d">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/99482754/p/db5069ea39ed3afe28ada1885aaa095b">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/99482695/p/910ff26d81e20cae3680aeb9cadc8708">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.17% | 91.32% | -0.14%

[MBL-15728](https://instructure.atlassian.net/browse/MBL-15728)

#### Affected Apps: Student

#### Release Note: 
Updated UI on the file share component. To submit your files to assignments directly from iOS tap the share icon and select the Student app.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by davidvarga93 — DISMISSED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA + 1

**Pull request merged**
