### PR TITLE
Fix double loading indicator on module sequence

### PR DESCRIPTION
**Pull request by szabinst**
refs: MBL-17218
affects: Student, Teacher
release note: Fixed an issue with loading indicator on module sequence screen.
test plan: See ticket

## Checklist

- [x] Tested on phone
- [x] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
#### Release Note: 
Fixed an issue with loading indicator on module sequence screen.

#### Affected Apps: Student, Teacher

[MBL-17218](https://instructure.atlassian.net/browse/MBL-17218)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.07% | 92.07% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c46bc811ed5c6aa0539c080276ff70b571d7311b
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
