### PR TITLE
Add feature flag for letter grade

### PR DESCRIPTION
**Pull request by vargaat**
- Extended already existing course settings entity with the new feature flag.
- Added course settings include to course fetch calls.
- Connect course and course settings coredata entities.
- Tested that both Parent and Student apps fetch course settings on dashboard.

refs: MBL-16908
affects: Student, Teacher, Parent
release note: none

test plan: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student, Teacher, Parent

[MBL-16908](https://instructure.atlassian.net/browse/MBL-16908)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.39% | 92.39% | -0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c7b9218ba884d8f9c93f1a490e00468de4e11058
</p>

**Review by idevainstr — APPROVED** [review]

**Review by szabinst — APPROVED** [review]
QA + 1

**Pull request merged**
