### PR TITLE
Hard-completed enrollments cannot be accessed

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15117
affects: Student
release note: Display completed courses in All courses.
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/81872742/p/7f76474fa894d8e952b8684d7a9447ad">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/81872760/p/0678e905593467d787a2786db1245612">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/81872675/p/7b39eb7f1a9a77cf844ecb0813d37afb">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.96% | 91.98% | -0.02%

[MBL-15117](https://instructure.atlassian.net/browse/MBL-15117)

#### Affected Apps: Student

#### Release Note: 
Display completed courses on dashboard.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by davidvarga93 — DISMISSED** [review]
QA+1

**Review by balintbartok — CHANGES_REQUESTED** [review]
for some reason "normal" courses disappear from all courses. Please check balintbartok/s and see "test course" showing up, then disappearing
IMG_0025
IMG_0026

**Review by vargaat — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]

**Pull request merged**
