### PR TITLE
Use simple space instead of non-breaking space in react snapshots.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16645
affects: Teacher, Student, Parent
release note: none

test plan:

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Teacher, Student, Parent

[MBL-16645](https://instructure.atlassian.net/browse/MBL-16645)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.93% | 91.95% | -0.02%
Core/Core/Courses/CourseDetails/ViewModel/CourseDetailsViewModel.swift | 48.89% | 48.89% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d3aaf754a54f8f3cb49d18bc73fcfe21e6368174
</p>

**Review by idevainstr — APPROVED** [review]
👾

**Pull request merged**
