### PR TITLE
Remove CKIClient & UIWebView from Attendance

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-13251
affects: Teacher
release note: none

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by vanwagonet** [comment]
The only things remaining are the view tests for Date & Attendance.

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1010208&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Teacher

[MBL-13251](https://instructure.atlassian.net/browse/MBL-13251)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.31% | 82.41% | 10.89%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by armstrongnate** [comment]
Oh, it's `Waiting for worker`

**Comment by armstrongnate** [comment]
I re-triggered Canvas iOS Tests because it was aborted for memory. It's now waiting for worker: https://app.bitrise.io/build/54aca6fd8b24d070#?tab=log

**Pull request merged**
