### PR TITLE
Add empty state announcement to date picker cell.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15445
affects: Teacher
release note: none

test plan:
- As the teacher edit an assignment.
- Turn on VoiceOver.
- Focus on Due, Available from and Available until buttons and observe that it now announces that there is no date selected.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/82918483/p/7a3198c4c10fb6abf7434cae52601a64">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/82918523/p/b74d2ace8103304e9f47ede20bcbe08e">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/82918442/p/aac39d034f4195f34b89fdcb972e19f6">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Danger failed to run `dangerfile.js`.
  </td>
    </tr>
  </tbody>
</table>



## Error Error
```
Cannot find module 'commander'
Require stack:
- /Users/vagrant/git/scripts/update-headers.js
- dangerfile.js
- /snapshot/danger-js/distribution/runner/runners/inline.js
- /snapshot/danger-js/distribution/commands/danger-runner.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
Error: Cannot find module 'commander'
Require stack:
- /Users/vagrant/git/scripts/update-headers.js
- dangerfile.js
- /snapshot/danger-js/distribution/runner/runners/inline.js
- /snapshot/danger-js/distribution/commands/danger-runner.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:795:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1287:46)
    at Function.Module._load (internal/modules/cjs/loader.js:688:27)
    at Function._load (/snapshot/danger-js/node_modules/override-require/dist/overrideRequire.js:43:25)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/vagrant/git/scripts/update-headers.js:30:17)
    at Module._compile (internal/modules/cjs/loader.js:957:30)
    at Module._compile (pkg/prelude/bootstrap.js:1222:32)
```
### Dangerfile
```
------------------^
```
  
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0abd884cc87d42892c26950201f49e92a0ea7343
</p>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.99% | 91.99% | 0%

[MBL-15445](https://instructure.atlassian.net/browse/MBL-15445)

#### Affected Apps: Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by davidvarga93** [comment]
Every line of dates (if empty) is announced twice, not sure if this is intended: "No Due Date Set, No Due Date Set"

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]

**Pull request merged**
