### PR TITLE
Fix Notification Freeze

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-16434
affects: Student
release note: Fixed notification screen getting stuck after too many refreh attempts
test plan: See ticket

## Checklist

- [ ] Tested on phone
- [x] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/Core/Submissions/Submission.swift:130:24: Function Body Length Violation: Function body should span 100 lines or less excluding comments and whitespace: currently spans 110 lines (function_body_length)
    
    
</details>


[MBL-16434](https://instructure.atlassian.net/browse/MBL-16434)

#### Affected Apps: Student

#### Release Note: 
Fixed notification screen getting stuck after too many refreh attempts
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by szabinst** [comment]
QA + 1

**Review by szabinst — APPROVED** [review]

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
