### PR TITLE
Ignore 404 errors while downloading studio video metadata.

### PR DESCRIPTION
**Pull request by vargaat**
During offline sync if a course is selected for sync but has no studio videos embedded then the API call for that course fails with a 404 making the whole studio sync stream fail. I extracted the download logic to make it more easily testable and modified it to ignore 404 errors.

refs: [MBL-17806](https://instructure.atlassian.net/browse/MBL-17806)
affects: Student
release note: none

test plan:
- Sync two courses at once for offline availability. One that should have studio videos embedded while the other shouldn't.
- (You can double check this with a proxy, api/public/v1/courses/123/media should return 404 for courses without studio videos.)
- Sync should finish successfully and studio videos should be available in offline mode.
- Check the debug menu's logs if there are any entries for failed studio sync.

[MBL-17806]: https://instructure.atlassian.net/browse/MBL-17806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-17806](https://instructure.atlassian.net/browse/MBL-17806)

<details><summary>:x: XCTest failed: CoreTests/UseCaseTests/testFailureCallbacksOnMain</summary>


    Asynchronous wait failed: Exceeded timeout of 0.1 seconds, with unfulfilled expectations: "Fetch fails.".
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 056776da9faf3d9cfe815186fecc8bd91e6470b2
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by ndrsszsz — APPROVED** [review]
QA +1

**Pull request merged**
