### PR TITLE
MBL-16004 Add next button to find school view

### PR DESCRIPTION
**Pull request by tamasiscoming**
refs: MBL-16004
affects: Parent, Student, Teacher
release note: none

test plan: See ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/CoreTests/Login/LoginFindSchoolViewControllerTests.swift:70:1: Trailing Whitespace Violation: Lines should not have trailing whitespace. (trailing_whitespace)
    /Users/vagrant/git/Core/CoreTests/Login/LoginFindSchoolViewControllerTests.swift:75:1: error: Trailing Whitespace Violation: Lines should not have trailing whitespace. (trailing_whitespace)
    /Users/vagrant/git/Core/CoreTests/Login/LoginFindSchoolViewControllerTests.swift:87:1: error: Trailing Whitespace Violation: Lines should not have trailing whitespace. (trailing_whitespace)
    ❌ /Users/vagrant/git/Core/CoreTests/Login/LoginFindSchoolViewControllerTests.swift:92:1: Trailing Whitespace Violation: Lines should not have trailing whitespace. (trailing_whitespace)
    /Users/vagrant/git/Core/CoreTests/Login/LoginFindSchoolViewControllerTests.swift:97:1: error: Trailing Whitespace Violation: Lines should not have trailing whitespace. (trailing_whitespace)
    /Users/vagrant/git/Core/CoreTests/Login/LoginFindSchoolViewControllerTests.swift:99:1: error: Trailing Whitespace Violation: Lines should not have trailing whitespace. (trailing_whitespace)
    ❌ /Users/vagrant/git/Core/Core/Login/LoginFindSchoolViewController.swift:99:1: Trailing Whitespace Violation: Lines should not have trailing whitespace. (trailing_whitespace)
    /Users/vagrant/git/Core/Core/Login/LoginFindSchoolViewController.swift:141:1: error: Trailing Whitespace Violation: Lines should not have trailing whitespace. (trailing_whitespace)
    /Users/vagrant/git/Core/Core/Login/LoginFindSchoolViewController.swift:151:1: error: Trailing Whitespace Violation: Lines should not have trailing whitespace. (trailing_whitespace)
    ❌ /Users/vagrant/git/Core/Core/Login/LoginFindSchoolViewController.swift:164:1: Trailing Whitespace Violation: Lines should not have trailing whitespace. (trailing_whitespace)
    
    
</details>


[MBL-16004](https://instructure.atlassian.net/browse/MBL-16004)

#### Affected Apps: Parent, Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/a2bd0237-b2fc-4c62-bf8b-f5633316b5da/artifact/1b8e7b15d221d5c6/p/45344b45327eb6f20801c90ebe7c63f8">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/a2bd0237-b2fc-4c62-bf8b-f5633316b5da/artifact/207d75db1fc36e1d/p/f37f5c0a03b97c842493859a4262b0de">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/a2bd0237-b2fc-4c62-bf8b-f5633316b5da/artifact/0e790874c1145db6/p/cfb2f8f36cf0efeac993fb0aa5ece234">
    
  </a>
</details>

**Review by idevainstr — CHANGES_REQUESTED** [review]
Next button won't show up on a device running iOS 14.

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
