### PR TITLE
Revert manual route constructing and use html url instead.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15535
affects: Student, Teacher
release note: none

test plan: See linked ticket. Detail pages listed in MBL-15305 (except files) should open. New quiz won't launch on that test account since the LTI tool is broken there but the detail page should open.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/83473454/p/0534a0b19d18464305bc6c2be1f83718">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/83473467/p/00a9b461252235f5b3ac0d71b686abbc">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/83473414/p/bbc39b0ff52dccc0e80e9a2c8bf72cb5">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.98% | 91.98% | -0%

[MBL-15535](https://instructure.atlassian.net/browse/MBL-15535)
[MBL-15305](https://instructure.atlassian.net/browse/MBL-15305)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]
QA +1

**Pull request merged**
