### PR TITLE
Added test for maintaining session after termination

### PR DESCRIPTION
**Pull request by GabrielPalmer**
refs: MBL-12530
affects: student
release none: none

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by bluwave** [comment]
you may want to let the team know to upgrade to cocoapods 1.7.1

**Comment by instructure-cx** [comment]
#### Checkmarx scan completed with the following findings
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[1](https://github.com/instructure/canvas-ios/blob/MBL-12530/AllTheThings.xcworkspace/xcshareddata/IDETemplateMacros.plist#L1) |High|App_Transport_Security_Bypass|AllTheThings.xcworkspace/xcshareddata/IDETemplateMacros.plist|[Checkmarx](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1000046&projectid=17&pathid=2)
[271](https://github.com/instructure/canvas-ios/blob/MBL-12530/Canvas/CanvasKit1/UI Classes/CKCommentViewController.m#L271) |High|Stored_XSS|Canvas/CanvasKit1/UI Classes/CKCommentViewController.m|[Checkmarx](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1000046&projectid=17&pathid=1)

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add a release note. If no release note is wanted, use `none`. Example: `release note: Fixed a bug that prevented users from enjoying the app.`
  </td>
    </tr>
  </tbody>
</table>



#### Affected Apps: Student

[MBL-12530](https://instructure.atlassian.net/browse/MBL-12530)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Core** | 95.17% | 95.17% | 0%
**Student** | 92.89% | 92.89% | 0%
**Teacher** | 100% | 100% | 0%
**React Native** | 92.69% | 92.69% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Pull request merged**
