### PR TITLE
Add day of week to to-do list cell. Make date field on to-do item cell to shrink text if it's too long.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15251
affects: Student, Teacher
release note: Added day of week to to-do list items' due date.

test plan: To-do list should display the day of week as part of the due date.

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/69566682/p/0ffb51060c81349b2b3d2aa19cce0b00">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/69566689/p/d43a6cb91980db254b7ed3e991709ab8">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/69566658/p/a18b8f30f086f217331173287ee1a121">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/TodoTests/testDistantDueDateString</summary>


    Assertion Failure at TodoTests.swift:74: XCTAssertTrue failed
</details>


[MBL-15251](https://instructure.atlassian.net/browse/MBL-15251)

#### Affected Apps: Student, Teacher

#### Release Note: 
Added day of week to to-do list items' due date.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by idevainstr — APPROVED** [review]
QA+1

**Pull request merged**
