### PR TITLE
Update widgets

### PR DESCRIPTION
**Pull request by vargaat**
### What changed?
- Widget UI was updated to iOS 17 API in a backwards compatible way.
- Widget previews were drastically simplified because Xcode now provides a way to check the widget using different configurations.
- Introduced CoreData cache for announcements instead of direct API calls.
- Keychain is accessible when the device is locked since we introduced the offline background sync so the code that checked the device's locked state and some connected logic was removed.
- Added error reporting to CoreData save method.

refs: MBL-16560
affects: Student
release note: none

test plan:
- Check if widgets are correctly displayed both on iOS 16 and 17.

## Checklist

- [ ] Tested on phone, iOS 16
- [x] Tested on phone, iOS 17
- [x] Tested on tablet, iOS 16
- [ ] Tested on tablet, iOS 17
- [x] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-16560](https://instructure.atlassian.net/browse/MBL-16560)

<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Student/Widgets/Common/View/CompatibleContentMargins.swift:39:1: Trailing Newline Violation: Files should have a single trailing newline (trailing_newline)
    
    
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c9dace0a92ca3988c94203ddc66749e6074fef7d
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by domonkosadam — APPROVED** [review]
QA + 1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
