### PR TITLE
Support users tab visibility

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBL-14820
affects: student
release note: Fixed loading modules

test plan: see ticket

### CODE REVIEW

**Comment by armstrongnate** [comment]
We should probably make it a String on APITab at some point.

**Comment by vanwagonet** [comment]
> We should probably make it a String on APITab at some point.

😆 Yeah, if they're gonna keep adding undocumented cases.

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/52040951/p/44426dec0a1a67b71c24db4e40f09fd5">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/52040965/p/3e332ffe930a7891dfcae51616e23a60">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/52040933/p/7e52bd5bffe568843412e76148f4d9e4">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.27% | 93.27% | 0%

[MBL-14820](https://instructure.atlassian.net/browse/MBL-14820)

#### Affected Apps: Student

#### Release Note: 
Fixed loading modules
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by vanwagonet — APPROVED** [review]
QA+1

**Pull request merged**
