### PR TITLE
Added an error screen to webviews when rendering fails

### PR DESCRIPTION
**Pull request by vargaat**
- Added error screen to webview rendering issues. 
- Reorganized CoreWebView folder.

refs: MBL-17034
affects: Student, Teacher, Parent
release note: Added an error screen to webviews when rendering fails.

test plan: See ticket.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Release Note: 
Added an error screen to webviews when rendering fails.

#### Affected Apps: Student, Teacher, Parent

[MBL-17034](https://instructure.atlassian.net/browse/MBL-17034)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.39% | 92.4% | -0%
Core/Core/CoreWebView/Model/Delegates/CoreWebViewLinkDelegate.swift | 33.33% | -- | --
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2bde2bed745a879703460aa7e6e4a96081434825
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by ndrsszsz — APPROVED** [review]
QA +1

**Pull request merged**
