### PR TITLE
Homeroom updates

### PR DESCRIPTION
**Pull request by vargaat**
### What's in this PR?
- Removed color overlay from subject images.
- Ensured subject card text contrast ratio is high enough.
- Fixed long course names not having a background in homeroom details page.

refs: MBL-17039, MBL-17036, MBL-17037
affects: Student
release note: Fixed contrast issues in homeroom view.

test plan: See tickets

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [x] A11y checked
- [x] Tested on phone
- [x] Tested on tablet
- [x] Tested in dark mode
- [x] Tested in light mode
- [x] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Fixed contrast issues in homeroom view.

#### Affected Apps: Student

[MBL-17039](https://instructure.atlassian.net/browse/MBL-17039)
[MBL-17036](https://instructure.atlassian.net/browse/MBL-17036)
[MBL-17037](https://instructure.atlassian.net/browse/MBL-17037)

<details><summary>:x: XCTest failed: CoreTests/K5HomeroomViewModelTests/testLoadsNonHomeroomCourses</summary>


    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x60001ac5c840; provider = <__NSMallocBlock__: 0x6000322708d0>>)") is not equal to ("Optional(UIExtendedSRGBColorSpace 0.870588 0.678431 0 1)")
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 468bf0a6ffdfb8931b0e7ae886a431df0be3766e
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by szabinst — APPROVED** [review]
QA + 1

**Pull request merged**
