### PR TITLE
Discussion action sheet layout issues

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15410
affects: Student
release note: Fix discussion action sheet layout issues.
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80640987/p/9dd48262c09b08b799f6703eba78bab1">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80640999/p/3ab10d7bc78d87eec1bfd9e6c665b8da">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/80640980/p/76801fc17ca42b13e67310a13511a54c">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.98% | 91.98% | 0%

[MBL-15410](https://instructure.atlassian.net/browse/MBL-15410)

#### Affected Apps: Student

#### Release Note: 
Fix discussion action sheet layout issues.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
