### PR TITLE
Fix a11y in Teacher modules and align icons

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBL-14035
affects: teacher
release note: Accessibility improvements

Test plan:
* Turn on VO in Teacher modules
* VO should say published and expanded states
* Published icons should all be aligned

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/m5cj4r4) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fm5cj4r4)
teacher: [Link](https://rebrand.ly/nrmo2if) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fnrmo2if)
parent: [Link](https://rebrand.ly/b6rzbh3) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fb6rzbh3)

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1024681&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|13
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by inst-danger** [comment]
#### Release Note: 
Accessibility improvements

#### Affected Apps: Teacher

[MBL-14035](https://instructure.atlassian.net/browse/MBL-14035)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.57% | 93.55% | 0.02%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Pull request merged**
