### PR TITLE
Render tests for Discussion details, edit, and list

### PR DESCRIPTION
**Pull request by shichongrui**
refs: MBL-13526
affects: none
release note: none

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by shichongrui** [comment]
Just FYI a couple of the `.test.js` files are collapsed in the diff.

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: None

[MBL-13526](https://instructure.atlassian.net/browse/MBL-13526)

<details><summary>:x: Yarn lint</summary>


    
    /Users/vagrant/git/rn/Teacher/src/modules/discussions/details/__tests__/DiscussionDetails.test.js
       26:3   error  'I18nManager' is defined but never used          no-unused-vars
       28:8   error  'renderer' is defined but never used             no-unused-vars
       31:8   error  'explore' is defined but never used              no-unused-vars
       32:8   error  'setProps' is defined but never used             no-unused-vars
       86:7   error  Duplicate key 'refresh'                          no-dupe-keys
      113:27  error  Missing trailing comma                           comma-dangle
      128:30  error  Missing trailing comma                           comma-dangle
      133:22  error  Missing space before function parentheses        space-before-function-paren
      245:18  error  Missing trailing comma                           comma-dangle
      251:24  error  Missing trailing comma                           comma-dangle
      261:40  error  Missing trailing comma                           comma-dangle
      338:11  error  'discussion' is assigned a value but never used  no-unused-vars
      361:27  error  Missing space before function parentheses        space-before-function-paren
      368:57  error  Missing trailing comma                           comma-dangle
      383:62  error  Missing trailing comma                           comma-dangle
      391:67  error  Missing trailing comma                           comma-dangle
      392:11  error  Missing trailing comma                           comma-dangle
      411:30  error  Missing trailing comma                           comma-dangle
      469:25  error  Missing trailing comma                           comma-dangle
      476:69  error  Missing trailing comma                           comma-dangle
      484:70  error  Missing trailing comma                           comma-dangle
      496:70  error  Missing trailing comma                           comma-dangle
      510:58  error  Missing trailing comma                           comma-dangle
      516:91  error  Missing trailing comma                           comma-dangle
      524:23  error  Missing trailing comma                           comma-dangle
      525:11  error  Missing trailing comma                           comma-dangle
      579:63  error  Missing trailing comma                           comma-dangle
      585:61  error  Missing trailing comma                           comma-dangle
      591:82  error  Missing trailing comma                           comma-dangle
      600:71  error  Missing trailing comma                           comma-dangle
      614:46  error  Missing trailing comma                           comma-dangle
      621:46  error  Missing trailing comma                           comma-dangle
      628:45  error  Missing trailing comma                           comma-dangle
      679:59  error  Missing trailing comma                           comma-dangle
      685:57  error  Missing trailing comma                           comma-dangle
      691:83  error  Missing trailing comma                           comma-dangle
      735:34  error  Missing trailing comma                           comma-dangle
      743:34  error  Missing trailing comma                           comma-dangle
      756:24  error  Missing trailing comma                           comma-dangle
      757:14  error  Missing trailing comma                           comma-dangle
      758:11  error  Missing trailing comma                           comma-dangle
      762:25  error  Missing space before function parentheses        space-before-function-paren
      819:24  error  Missing trailing comma                           comma-dangle
      820:14  error  Missing trailing comma                           comma-dangle
      821:11  error  Missing trailing comma                           comma-dangle
      885:23  error  Missing trailing comma                           comma-dangle
    
    /Users/vagrant/git/rn/Teacher/src/modules/discussions/edit/__tests__/DiscussionEdit.test.js
       21:24  error  'ShallowWrapper' is defined but never used  no-unused-vars
       30:15  error  'isTeacher' is defined but never used       no-unused-vars
      104:9   error  'tree' is assigned a value but never used   no-unused-vars
      278:28  error  Missing trailing comma                      comma-dangle
      288:28  error  Missing trailing comma                      comma-dangle
      422:30  error  Missing trailing comma                      comma-dangle
      502:12  error  Missing trailing comma                      comma-dangle
    
    /Users/vagrant/git/rn/Teacher/src/modules/discussions/list/__tests__/DiscussionsList.test.js
       23:8   error  'renderer' is defined but never used  no-unused-vars
       27:8   error  'explore' is defined but never used   no-unused-vars
       97:31  error  Missing trailing comma                comma-dangle
      123:47  error  Missing trailing comma                comma-dangle
      127:38  error  Missing trailing comma                comma-dangle
      131:31  error  Missing trailing comma                comma-dangle
      132:8   error  Missing trailing comma                comma-dangle
      152:43  error  Missing space before =>               arrow-spacing
      246:44  error  A space is required after '{'         object-curly-spacing
      246:53  error  A space is required before '}'        object-curly-spacing
    
    ✖ 63 problems (63 errors, 0 warnings)
      52 errors and 0 warnings potentially fixable with the `--fix` option.
    
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1014900&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Pull request merged**
