### PR TITLE
Skip test setUp method when test is skippable

### PR DESCRIPTION
**Pull request by davidvarga93**
refs: MBL-15658
affects: Student, Teacher
release note: none

test plan:

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.75% | 91.76% | -0%

[MBL-15658](https://instructure.atlassian.net/browse/MBL-15658)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by davidvarga93** [comment]
Test is disabled, no trace in test logs, advancing to set all the tests marked for skip to disabled.

**Comment by davidvarga93** [comment]
Nightly: https://app.bitrise.io/build/d076fb9f-81a7-4bdf-b3e5-74056687c639#?tab=log

**Review by vargaat — APPROVED** [review]
Nice improvement!

**Pull request merged**
