### PR TITLE
Fix all courses showing roles from deleted enrolments.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15547
affects: Student, Teacher
release note: none

test plan: See ticket.

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.97% | 91.98% | -0%

[MBL-15547](https://instructure.atlassian.net/browse/MBL-15547)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/83688077/p/48585b7e6b078a40d6c3b285b7f7ddeb">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/83688087/p/d3b97df095bc3921698dfd7829e4870b">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/83688063/p/3833a332819560ffe267851ff7048be9">
    
  </a>
</details>

**Review by davidvarga93 — APPROVED** [review]
QA+1

**Review by idevainstr — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]

**Pull request merged**
