### PR TITLE
Background sync

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16723
affects: Student
release note: none

test plan:
- Start an offline sync.
- Put the app into the background.
- If the sync finishes in a reasonable time (OS dependent) you should receive the success notification.
- In case the background activity is interrupted you won't see any notifications.
- Opening the app in this case should display the sync failed banner on the dashboard.
- Opening the sync progress screen should display either completed or failed states.

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] Tested on phone
- [x] Tested on tablet
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-16723](https://instructure.atlassian.net/browse/MBL-16723)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.39% | 92.39% | 0.01%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0461c45b3eb34c944c046bb2e251e2037e7c22ac
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
