### PR TITLE
Fix submitting iWork from device

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBL-13975
affects: student
release note: Fixed a bug with submitting iWork files

Test plan:
* Install Pages, Numbers, and Keynote on your device
* Create a new file for each app
* Use the Files app to copy the files from iCloud Drive to On My Device
* Submit to an assignment that restricts file extensions to iWork
extensions (see [ticket](https://instructure.atlassian.net/browse/MBL-13975) and
also narmstrong > s > CS 1400 > Assignments > iWork
* Verify that you can select the iWork files from both On My Device and
iCloud Drive

### CODE REVIEW

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/uqy5ne2) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fuqy5ne2)
teacher: [Link](https://rebrand.ly/58vb6xk) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2F58vb6xk)
parent: [Link](https://rebrand.ly/vydmbs7) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fvydmbs7)

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Fixed a bug with submitting iWork files

#### Affected Apps: Student

[MBL-13975](https://instructure.atlassian.net/browse/MBL-13975)

<details><summary>:x: XCTest failed: CoreTests/SubmissionTypeTests/testAllowedUTIsAllowedExtensions</summary>


    Assertion Failure: SubmissionTypeTests.swift:69: XCTAssertTrue failed
    Assertion Failure: SubmissionTypeTests.swift:70: XCTAssertTrue failed
    Assertion Failure: SubmissionTypeTests.swift:71: XCTAssertTrue failed
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by cobbal** [comment]
QA+1

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1023515&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|17
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Pull request merged**
