### PR TITLE
People context card resets roles on people list

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15534
affects: Student, Teacher
release note: none
test plan: see ticket

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/83782033/p/97e5867010c023c3c73a9b98d0527194">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/83782043/p/aee568af6d43ffe009339e8886a1b14f">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/83782020/p/501d6921b6aabaf9362d1edf88a35d70">
    
  </a>
</details>

**Review by vargaat — CHANGES_REQUESTED** [review]
The bug is still reproducible on iPads.
IMG_77DDBE6433F2-1

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


<details><summary>:x: XCTest failed: CoreTests/PeopleListViewControllerTests/testFilter</summary>


    Assertion Failure at PeopleListViewControllerTests.swift:81: XCTAssertEqual failed: ("0") is not equal to ("2")
</details>


[MBL-15534](https://instructure.atlassian.net/browse/MBL-15534)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by vargaat — APPROVED** [review]
QA+1

**Pull request merged**
