### PR TITLE
Native inbox list

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-14850
affects: Student, Teacher
release note: none

test plan:
- Turn on app level feature flag for native inbox in developer menu (separate for student and teacher apps).
- Go to inbox.
- Test course and status filters.
- Test swipe gestures to archive, read or unread a message.
- Test paging (page size is 20) that becomes available after pull to refresh.
- Test avatars, participant names, message title, message body, starred, unread and attachment statuses.
- Test if messages load from cache if switching between already visited filters. (Moving messages from/to archive or making them read/unread invalidates the cache.)

## Screenshots

<table>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product or not needed

[MBL-14850]: https://instructure.atlassian.net/browse/MBL-14850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by szabinst — APPROVED** [review]
QA+1

**Pull request merged**
