### PR TITLE
Classic quiz submissions list shows invited users

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-15550
affects: Teacher
release note: Only show quiz submissions from active enrollments.
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.86% | 91.86% | 0%

[MBL-15550](https://instructure.atlassian.net/browse/MBL-15550)

#### Affected Apps: Teacher

#### Release Note: 
Only show quiz submissions from active enrollments.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/89577547/p/f3d475c1377f9b9abb213a8d6fdb3929">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/89577549/p/deab0a71b5478dc32f5e9ad16f993f93">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/89577528/p/c413cef307a6bfea50bf9a740d9888de">
    
  </a>
</details>

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
