### PR TITLE
Fix blinking preview.

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-16201
affects: Student
release note: none

test plan:
- Share a file with the Student file extension.
- Start typing text in the comment field.
- Text should update without the preview being re-generated.

https://user-images.githubusercontent.com/72396990/184637737-46d51f9e-52d3-4eed-b325-dd51ed3e8393.mov

https://user-images.githubusercontent.com/72396990/184637941-1b590204-1d2d-4b54-998b-2b2912deb89e.mov

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.65% | 91.63% | 0.02%

[MBL-16201](https://instructure.atlassian.net/browse/MBL-16201)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
