### PR TITLE
Add scripts to tag fixVersion & label released tickets

### PR DESCRIPTION
**Pull request by vanwagonet**
refs: MBL-13466
affects: none
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/n1e7wa5) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fn1e7wa5)
teacher: [Link](https://rebrand.ly/wau2qc0) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fwau2qc0)
parent: [Link](https://rebrand.ly/l1tazhf) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fl1tazhf)

**Comment by vanwagonet** [comment]
Test plan:
Using the jira username & API token in 1Pass
- run `node ./scripts/generate-release-notes.js Teacher-1.11`
- verify fixVersion is added to all the referenced issues
- run `yarn label-released`
- verify labels are added to the issues missing them

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: None

[MBL-13466](https://instructure.atlassian.net/browse/MBL-13466)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.62% | 93.62% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by vanwagonet** [comment]
I made it so you can still have the feature. just dont break `iOS <App> <version>` prefix.

**Pull request merged**
