### PR TITLE
Add submission button to parent

### PR DESCRIPTION
**Pull request by vargaat**
### What's new?
- Added Submission & Rubric button to parent assignment details screen that opens the web based submission page.
- Created CSS injections to get rid of canvas menus to have a clear browsing experience.
- Added dynamic back button in a toolbar to modal web view in case user navigates away from the root page.

refs: [MBL-17747](https://instructure.atlassian.net/browse/MBL-17747)
affects: Parent, Student, Teacher
release note: Added submission feedback button to assignment details screen.

test plan:
- Go to assignment details screen.
- Tap on submission & rubric button.
- Check if the assignment's submission website loads.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td colspan="2"></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [x] Follow-up e2e test ticket created
- [ ] A11y checked
- [ ] Tested on phone
- [x] Tested on tablet
- [ ] Tested in dark mode
- [x] Tested in light mode
- [ ] Approve from product

[MBL-17747]: https://instructure.atlassian.net/browse/MBL-17747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Added submission feedback button to assignment details screen.

#### Affected Apps: Parent

[MBL-17747](https://instructure.atlassian.net/browse/MBL-17747)

<details><summary>:x: XCTest failed: CoreTests/BackgroundVideoPlayerTests/testDisconnect</summary>


    XCTAssertNil failed: "<AVPlayerViewController: 0x108b4b000>"
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against bee64b00151ef8aeff998ba61c69ad45922baf1e
</p>

**Review by szabinst — DISMISSED** [review]
QA + 1

**Comment by szabinst** [comment]
Please contact @kristofnemere about an issue where some linked files can't be opened.

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Review by szabinst — APPROVED** [review]
QA + 1

**Comment by ndrsszsz** [comment]
https://github.com/user-attachments/assets/5ea3f562-805b-4ed4-b1f7-56217c2a7caa

On the assignment detail screen first it shows the assigment as "submitted", then I tap the "submission and rubrics" button to check that screen too, then I tap done and return to the detail screen which still says "submitted", but after pull to refresh it changes to "not submitted". It might not be in the scope of this ticket, so it's up to you if you fix it in this one or open another one for it.

**Pull request merged**
