### PR TITLE
ReactiveStore crash fix

### PR DESCRIPTION
**Pull request by szabinst**
refs: MBL-17030
affects: Student
release note: none
test plan: See ticket

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [x] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-17030](https://instructure.atlassian.net/browse/MBL-17030)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.4% | 92.4% | -0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 23b2c15d0e1d4864c3a9946b1c80e1591e456a98
</p>

**Review by balintbartok — APPROVED** [review]
I'm not sure this is fixing anything, but it's not causing any harm

**Review by vargaat — APPROVED** [review]
QA+1
I couldn't reproduce the crash anymore.

**Pull request merged**
