### PR TITLE
MBL-13194 - clean up swift lint warnings / errors in parent

### PR DESCRIPTION
**Pull request by bluwave**
refs: MBL-13194
affects: Parent
release note: none

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1005885&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Parent

[MBL-13194](https://instructure.atlassian.net/browse/MBL-13194)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.11% | 93.07% | 0.04%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by bluwave** [comment]
```
Termination Description: DYLD, Library not loaded: @rpath/CanvasKit.framework/CanvasKit | Referenced from: /private/var/containers/Bundle/Application/214CDA93-63BF-4D70-AD5D-2940177DC713/Parent.app/Frameworks/CanvasCore.framework/CanvasCore | Reason: image not found
```
https://github.com/instructure/canvas-ios/pull/592 maybe ??

**Comment by bluwave** [comment]
@armstrongnate this is installing for me now. i pulled in latest.

**Pull request merged**
