### PR TITLE
Update module item associations

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-17489
affects: Teacher
release note: none

test plan: See ticket for detailed description on the issue.

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] Tested on phone
- [x] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Teacher

[MBL-17489](https://instructure.atlassian.net/browse/MBL-17489)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.86% | 91.84% | 0.03%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a30f55b273b8b295a61eed533a661ff5fd47661b
</p>

**Review by rh12 — APPROVED** [review]
QA + 1 (Tested all 4 scenarios)

Super edge case: if one item is included multiple times (ie: in different modules within same course) and it's published in one place then it won't be updated in the other.
But I'm not even sure it's a real case (even though the system allows it)

**Review by szabinst — APPROVED** [review]
QA + 1

**Comment by vargaat** [comment]
> Super edge case: if one item is included multiple times (ie: in different modules within same course) and it's published in one place then it won't be updated in the other. A simple PullToRefresh solves it. But I'm not even sure it's a real case (even though the system allows it)

This is because when a single item is updated we only refresh that item but it seems updating the whole list would be a good idea.

**Pull request merged**
