### PR TITLE
Fix edit dialog buttons floating around

### PR DESCRIPTION
**Pull request by szabolcs-instructure**
refs: MBL-16377
affects: Student, Teacher
release note: Fixed floating edit dialog buttons

test plan: See ticket

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.68% | 91.68% | 0%
Core/Core/Submissions/SubmissionBreakdown/SubmissionBreakdownViewModelProtocol.swift | 0% | 0% | 0%
Core/Core/Quizzes/QuizDetails/ViewModel/PreviewQuizDetailsViewModel.swift | 0% | 0% | 0%

[MBL-16377](https://instructure.atlassian.net/browse/MBL-16377)

#### Affected Apps: Student, Teacher

#### Release Note: 
Fix edit dialog buttons floating around
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by idevainstr — APPROVED** [review]
QA+1

**Comment by vargaat** [comment]
Could you take a look on the `New Page` and `New Discussion` screens as well? The show a similar animating navigation bar button symptom.

**Comment by szabolcs-instructure** [comment]
@vargaat Please check the latest commit. Every animation related code was moved to `DispatchQueue.main.async`

**Review by vargaat — APPROVED** [review]
QA+1

**Review by idevainstr — APPROVED** [review]
QA +1

**Pull request merged**
