### PR TITLE
Offline sync fixes

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-17127
affects: Student
release note: none

test plan:
- Background sync should always send a success/failed notification.
- App shouldn't crash after background sync. (You can trigger a manual background sync via the debugger and wait after the sync a few minutes for the background activity expiration to kick in.)
- Successful background sync notification's course count should match what is actually selected.

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] Tested on phone
- [ ] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-17127](https://instructure.atlassian.net/browse/MBL-17127)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.38% | 92.39% | -0.01%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 066fc418744b74e366cdb18f7f40c37f268398af
</p>

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by szabinst — APPROVED** [review]
QA + 1

**Pull request merged**
