### PR TITLE
Add limited web view explanation

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: MBL-14019
affects: parent
release note: none

Test plan:
* narmstrong > s > Student One > CS 1400 > Front Page > Modules link
* Should display an explanation for why the web view interaction is limited
* Tap the X to dismiss the explanation

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/rwt5lro) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Frwt5lro)
teacher: [Link](https://rebrand.ly/e57zvcs) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fe57zvcs)
parent: [Link](https://rebrand.ly/mvdpfzd) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fmvdpfzd)

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Parent

[MBL-14019](https://instructure.atlassian.net/browse/MBL-14019)

<details><summary>:x: XCTest failed: StudentUnitTests/SubmissionDetailsPresenterTests/testEmbedDiscussion</summary>


    Assertion Failure: SubmissionDetailsPresenterTests.swift:247: XCTAssertEqual failed: ("nil") is not equal to ("Optional("SubmissionDetails.discussionWebView")")
</details>
<details><summary>:x: XCTest failed: StudentUnitTests/SubmissionDetailsPresenterTests/testEmbedQuiz</summary>


    Assertion Failure: SubmissionDetailsPresenterTests.swift:184: XCTAssertEqual failed: ("nil") is not equal to ("Optional("SubmissionDetails.onlineQuizWebView")")
</details>
<details><summary>:x: XCTest failed: StudentUnitTests/SubmissionDetailsPresenterTests/testEmbedTextEntry</summary>


    Assertion Failure: SubmissionDetailsPresenterTests.swift:193: XCTAssertEqual failed: ("nil") is not equal to ("Optional("SubmissionDetails.onlineTextEntryWebView")")
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1023514&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|3
Medium|17
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---
High|1

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1023516&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|3
Medium|17
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---
High|1

**Pull request merged**
