### PR TITLE
Change the asignments list screen's title

### PR DESCRIPTION
**Pull request by idevainstr**
Amend assignment list title.

refs: MBL-15203
affects: Student, Teacher
release note: Update assignment list title
test plan:
- Open the assignments page
- Observe title

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/69093989/p/3bf1230ec640c488814f8c5143c41d6d">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/69094001/p/d7bb3b2f185a9f35845d8e69b1ac6932">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/69093971/p/4f1fdb2e51ca18984537d7de276f1e81">
    
  </a>
</details>

**Comment by inst-danger** [comment]
Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.09% | 92.09% | -0%

[MBL-15203](https://instructure.atlassian.net/browse/MBL-15203)

#### Affected Apps: Student, Teacher

#### Release Note: 
Update assignment list title
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by vargaat — APPROVED** [review]
QA+1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Pull request merged**
