### PR TITLE
Improve assignment list

### PR DESCRIPTION
**Pull request by vargaat**
What's new?
- Assignment filtering was re-written to use on device filtering solving the issue of the last selected filter overwriting/deleting other assignments saved for offline mode.
- Since all assignments are available offline I enabled the grading period selector in this mode on the assignment list screen.
- I fixed a UI issue of section headers having an extra spacing above them by using ScrollView+LazyVStack instead of List.
- Added a reactive exhaust method to API.

refs: MBL-17208
affects: Student
release note: Updated assignments list to allow grading period filter to work in offline mode.

test plan:
- See ticket for issue description.
- Clean your device data.
- Sync a course with multiple grading periods.
- Without entering the assignment list in online mode turn on offline mode.
- Visit assignment details in offline mode.
- Grading period filter should work. Assignment list should match the web for each grading period.
- Go online. Switch grading periods.
- Restart the app in offline mode.
- Check if assignment list still displays the expected assignments.
- Test if grades list still works as expected in terms of displayed assignments and grading periods.
- Test assignment list and grades list without any grading periods.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [x] Tested on phone
- [ ] Tested on tablet

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
#### Release Note: 
Updated assignments list to allow grading period filter to work in offline mode.

#### Affected Apps: Student

[MBL-17208](https://instructure.atlassian.net/browse/MBL-17208)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.67% | 91.64% | 0.04%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0ff33cd5e8829621395e93fd60146b99df2bc73b
</p>

**Review by szabinst — APPROVED** [review]
QA + 1

**Review by ndrsszsz — APPROVED** [review]
QA +1
Tested on iPhone 11, iOS 17.4.1, Dark Mode

**Pull request merged**
