### PR TITLE
Change secondary back button accessibility label

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-15166
affects: Student, Teacher
release note: none

test plan: see ticket

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.05% | 92.05% | -0%

[MBL-15166](https://instructure.atlassian.net/browse/MBL-15166)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/65947802/p/8f712c48d5a9eeffe69874d1e6f19d40">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/65947807/p/464536ac7d51037ae55e728fb5c3492e">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/65947732/p/0e70a7ad12536263d390169e7d20da98">
    
  </a>
</details>

**Review by vargaat — APPROVED** [review]

**Comment by ceciliemariasun** [comment]
How to turn this off?

Last ned Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Fra: Attila Varga <notifications@github.com>
Sendt: Monday, February 22, 2021 10:13:24 AM
Til: instructure/canvas-ios <canvas-ios@noreply.github.com>
Kopi: Subscribed <subscribed@noreply.github.com>
Emne: Re: [instructure/canvas-ios] Change secondary back button accessibility label (#1729)


@vargaat approved this pull request.

**Comment by ceciliemariasun** [comment]
[cid:67197074-278f-42b4-924b-c6c148555666]

Cecilie Maria Ravnanger Sundrehagen-Bergfridsdottir har delt en fil med deg

Her er dokumentet som Cecilie Maria Ravnanger Sundrehagen-Bergfridsdottir delte med deg.

<https://uinnlandet-my.sharepoint.com:443/:o:/g/personal/225007_stud_inn_no/Em78uXj3UhxOgdrqP0CXw1UBJjRqs9JQN2mh4Umib8vy1g?email=reply%2bAS5FPAQSCPJJ2HK3QKFHOQF6H5LLJEVBNHHDAZ7HHU%40reply.github.com&e=5%3ahVth5t&at=9>
[icon]  Cecilie Maria Ravnanger @ Universitetet i Oslo
[permission globe icon]         Koblingen fungerer bare for direkte mottakere av denne meldingen.
Åpne <https://uinnlandet-my.sharepoint.com:443/:o:/g/personal/225007_stud_inn_no/Em78uXj3UhxOgdrqP0CXw1UBJjRqs9JQN2mh4Umib8vy1g?email=reply%2bAS5FPAQSCPJJ2HK3QKFHOQF6H5LLJEVBNHHDAZ7HHU%40reply.github.com&e=5%3ahVth5t&at=9>
[Microsoft logo]        Personvernerklæring <https://northeuroper-notifyp.svc.ms:443/api/v2/tracking/method/Click?mi=im86-xrfSU2uZ1nZVGGcJA&tc=PrivacyStatement&cs=f97d4ae4336b3342c9a937ee3f36e84e&ru=https%3a%2f%2fprivacy.microsoft.com%2fprivacystatement%5c>

**Pull request merged**
