### PR TITLE
Remove unused file which caused export-translations to fail

### PR DESCRIPTION
**Pull request by vargaat**
refs: MBL-15468
affects: Teacher
release note: none

test plan: Export translations script should complete without errors.

### CODE REVIEW

**Comment by vargaat** [comment]
Successful export can be seen [here](https://app.bitrise.io/build/59b45393-4254-41c2-abbc-f578beb6449b#?tab=log).

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Comment by inst-danger** [comment]
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/90927080/p/b805533b2b6267510f2feb8f96534c69">
    
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/90927090/p/24ba53425ca6a6e2ed388a256e699a9b">
    
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/90927066/p/954f99604a87959f8398a72b9d70c2a3">
    
  </a>
</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.81% | 91.81% | 0%

[MBL-15468](https://instructure.atlassian.net/browse/MBL-15468)

#### Affected Apps: Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Review by idevainstr — APPROVED** [review]

**Pull request merged**
