### PR TITLE
Add a11y & ui tests for planner filter

### PR DESCRIPTION
**Pull request by vanwagonet**
Displays course name instead of code to match Android & other parts of the app

[run nightly]
refs: MBL-14079
affects: Parent
release note: none

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by inst-danger** [comment]
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/s3424og) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fs3424og)
teacher: [Link](https://rebrand.ly/3zwi7dp) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2F3zwi7dp)
parent: [Link](https://rebrand.ly/4c24ymb) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2F4c24ymb)

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1026378&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|11
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1026380&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|4
Medium|13
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---
High|1

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Parent

[MBL-14079](https://instructure.atlassian.net/browse/MBL-14079)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.62% | 93.62% | -0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by vanwagonet** [comment]
> The "Calendars (2)" button is always read as "filter events" with no mention of the number. Maybe something like "filter events, 2 calendars selected"? Looks good otherwise

Great idea. I'll add that.

**Pull request merged**
