### PR TITLE
Dark mode brand color modifications

### PR DESCRIPTION
**Pull request by idevainstr**
refs: MBL-16281
affects: Student, Teacher
release note: Improved contrast for dark theme brand colors.
test plan: See ticket.

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] A11y checked
- [x] Tested on phone
- [x] Tested on tablet
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/BrandTests/testColor</summary>


    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x60000440a0a0; provider = <__NSMallocBlock__: 0x600005291dd0>>)") is not equal to ("Optional(<UIDynamicProviderColor: 0x600004409b40; provider = <__NSMallocBlock__: 0x600005292520>>)")
    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x600004171340; provider = <__NSMallocBlock__: 0x60000521c750>>)") is not equal to ("Optional(<UIDynamicProviderColor: 0x600004171300; provider = <__NSMallocBlock__: 0x60000521fd80>>)")
    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x60000417c040; provider = <__NSMallocBlock__: 0x600005218db0>>)") is not equal to ("Optional(<UIDynamicProviderColor: 0x60000417c080; provider = <__NSMallocBlock__: 0x600005218750>>)")
    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x600004178040; provider = <__NSMallocBlock__: 0x600005264840>>)") is not equal to ("Optional(<UIDynamicProviderColor: 0x600004178080; provider = <__NSMallocBlock__: 0x600005267d20>>)")
    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x600004144040; provider = <__NSMallocBlock__: 0x6000052657a0>>)") is not equal to ("Optional(<UIDynamicProviderColor: 0x600004144080; provider = <__NSMallocBlock__: 0x6000052666d0>>)")
    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x600004140040; provider = <__NSMallocBlock__: 0x60000526c150>>)") is not equal to ("Optional(<UIDynamicProviderColor: 0x600004140080; provider = <__NSMallocBlock__: 0x60000526e190>>)")
    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x60000414c040; provider = <__NSMallocBlock__: 0x600005275380>>)") is not equal to ("Optional(<UIDynamicProviderColor: 0x60000414c080; provider = <__NSMallocBlock__: 0x6000052771e0>>)")
    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x600004318040; provider = <__NSMallocBlock__: 0x6000052bf630>>)") is not equal to ("Optional(<UIDynamicProviderColor: 0x600004318080; provider = <__NSMallocBlock__: 0x6000052bf6f0>>)")
    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x600004364040; provider = <__NSMallocBlock__: 0x600005279fb0>>)") is not equal to ("Optional(<UIDynamicProviderColor: 0x600004364080; provider = <__NSMallocBlock__: 0x60000527a250>>)")
    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x600004360040; provider = <__NSMallocBlock__: 0x6000052a6a00>>)") is not equal to ("Optional(<UIDynamicProviderColor: 0x600004360080; provider = <__NSMallocBlock__: 0x6000052a68e0>>)")
    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x60000436c040; provider = <__NSMallocBlock__: 0x600005261da0>>)") is not equal to ("Optional(<UIDynamicProviderColor: 0x60000436c080; provider = <__NSMallocBlock__: 0x600005261440>>)")
    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x600004368040; provider = <__NSMallocBlock__: 0x600005261410>>)") is not equal to ("Optional(<UIDynamicProviderColor: 0x600004368080; provider = <__NSMallocBlock__: 0x6000052634e0>>)")
    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x600004374040; provider = <__NSMallocBlock__: 0x600005261440>>)") is not equal to ("Optional(<UIDynamicProviderColor: 0x600004374080; provider = <__NSMallocBlock__: 0x600005263810>>)")
    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x600004370040; provider = <__NSMallocBlock__: 0x60000526a880>>)") is not equal to ("Optional(<UIDynamicProviderColor: 0x600004370080; provider = <__NSMallocBlock__: 0x600005268870>>)")
    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x60000437c040; provider = <__NSMallocBlock__: 0x60000525d080>>)") is not equal to ("Optional(<UIDynamicProviderColor: 0x60000437c080; provider = <__NSMallocBlock__: 0x60000525cf30>>)")
</details>
<details><summary>:x: XCTest failed: CoreTests/BrandTests/testHeaderImageView</summary>


    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x600004288420; provider = <__NSMallocBlock__: 0x600005211440>>)") is not equal to ("Optional(<UIDynamicProviderColor: 0x600004288500; provider = <__NSMallocBlock__: 0x600005211bc0>>)")
</details>
<details><summary>:x: XCTest failed: CoreTests/ColoredNavViewProtocolTests/testUpdateNavBar</summary>


    XCTAssertEqual failed: ("Optional(UIExtendedSRGBColorSpace 0.93 0 0 1)") is not equal to ("Optional(UIExtendedSRGBColorSpace 1 0 0 1)")
    XCTAssertEqual failed: ("Optional(UIExtendedSRGBColorSpace 0.93 0 0 1)") is not equal to ("Optional(UIExtendedSRGBColorSpace 1 0 0 1)")
</details>
<details><summary>:x: XCTest failed: CoreTests/ConferenceDetailsViewControllerTests/testLayout</summary>


    XCTAssertEqual failed: ("Optional(UIExtendedSRGBColorSpace 0.93 0 0 1)") is not equal to ("Optional(UIExtendedSRGBColorSpace 1 0 0 1)")
</details>
<details><summary>:x: XCTest failed: CoreTests/ConferenceListViewControllerTests/testLayout</summary>


    XCTAssertEqual failed: ("Optional(UIExtendedSRGBColorSpace 0.93 0 0 1)") is not equal to ("Optional(UIExtendedSRGBColorSpace 1 0 0 1)")
</details>
<details><summary>:x: XCTest failed: CoreTests/CoreWebViewTests/testCss</summary>


    XCTAssertTrue failed
</details>
<details><summary>:x: XCTest failed: CoreTests/EmptyViewControllerTests/testEmptyView</summary>


    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x600008096e60; provider = <__NSMallocBlock__: 0x6000115e5500>>)") is not equal to ("Optional(<UIDynamicProviderColor: 0x600008094aa0; provider = <__NSMallocBlock__: 0x6000115e5b60>>)")
</details>
<details><summary>:x: XCTest failed: CoreTests/FloatingButtonTests/testBackgroundColorName</summary>


    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x60000c2c5140; provider = <__NSMallocBlock__: 0x600018a08c90>>)") is not equal to ("Optional(<UIDynamicProviderColor: 0x60000c2c4f20; provider = <__NSMallocBlock__: 0x600018a08990>>)")
</details>
<details><summary>:x: XCTest failed: CoreTests/FloatingButtonTests/testIconColorName</summary>


    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x60000c322940; provider = <__NSMallocBlock__: 0x600018a796b0>>)") is not equal to ("Optional(<UIDynamicProviderColor: 0x60000c323720; provider = <__NSMallocBlock__: 0x600018a78f30>>)")
</details>
<details><summary>:x: XCTest failed: CoreTests/IconViewTests/testIconColorName</summary>


    XCTAssertEqual failed: ("Optional(<UIDynamicProviderColor: 0x6000101d0540; provider = <__NSMallocBlock__: 0x600021770330>>)") is not equal to ("Optional(<UIDynamicProviderColor: 0x6000101d0420; provider = <__NSMallocBlock__: 0x6000217704e0>>)")
</details>
:x: (and 19 other test failures)


[MBL-16281](https://instructure.atlassian.net/browse/MBL-16281)

#### Affected Apps: Student, Teacher

#### Release Note: 
Improved contrast for dark theme brand colors.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by szabolcs-instructure — DISMISSED** [review]
QA + 1, iPhone 12, iOS 15.6.1

**Review by vargaat — APPROVED** [review]
QA+1

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Review by vargaat — APPROVED** [review]

**Review by vargaat — APPROVED** [review]

**Review by szabolcs-instructure — APPROVED** [review]

**Review by davidvarga93 — APPROVED** [review]
QA + 1

**Pull request merged**
