### PR TITLE
Use the comment icon for context compose

### PR DESCRIPTION
**Pull request by armstrongnate**
refs: none
affects: parent
release note: none

Test plan:
* View Grades > compose icon should be comment, not reply
* View Assignment Details > compose icon should be comment, not reply

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by armstrongnate** [comment]
Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-30 at 09 55 50
Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-30 at 09 56 03

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Parent

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.52% | 93.52% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1020412&projectid=17)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|1
Medium|23
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---
High|1

**Pull request merged**
