### PR TITLE
Update projects to xcode 15.0

### PR DESCRIPTION
**Pull request by balintbartok**
refs: MBL-16869
affects: Student, Teacher, Parent
release note: none

test plan:
test everything, react native parts, annotations, dark/light mode, etc

## Checklist

- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student, Teacher, Parent

[MBL-16869](https://instructure.atlassian.net/browse/MBL-16869)

<details><summary>:x: XCTest failed: CoreTests/AnnouncementListViewControllerTests/testCourseAnnouncements</summary>


    XCTAssertEqual failed: ("Optional("Delayed until Nov 3, 2030 at 12:00 AM")") is not equal to ("Optional("Delayed until Nov 3, 2030 at 12:00 AM")")
    XCTAssertEqual failed: ("Optional("Last post Nov 3, 2020 at 12:00 AM")") is not equal to ("Optional("Last post Nov 3, 2020 at 12:00 AM")")
    XCTAssertEqual failed: ("Optional("Nov 2, 2020 at 12:00 AM")") is not equal to ("Optional("Nov 2, 2020 at 12:00 AM")")
</details>
<details><summary>:x: XCTest failed: CoreTests/AnnouncementListViewControllerTests/testGroupAnnouncements</summary>


    XCTAssertEqual failed: ("Optional("Nov 3, 2020 at 12:00 AM")") is not equal to ("Optional("Nov 3, 2020 at 12:00 AM")")
</details>
<details><summary>:x: XCTest failed: CoreTests/AssignmentListRequestableTests/testFormattedDueDate</summary>


    XCTAssertEqual failed: ("Optional("Due May 31, 2037 at 11:59 PM")") is not equal to ("Optional("Due Jun 1, 2037, 7:59 AM")")
</details>
<details><summary>:x: XCTest failed: CoreTests/ConferenceDetailsViewControllerTests/testLayout</summary>


    XCTAssertEqual failed: ("Optional("In Progress | Started Mar 14, 2020 at 12:00 AM")") is not equal to ("Optional("In Progress | Started Mar 14, 2020 at 12:00 AM")")
    XCTAssertEqual failed: ("Optional("Concluded Mar 14, 2020 at 12:00 AM")") is not equal to ("Optional("Concluded Mar 14, 2020 at 12:00 AM")")
    XCTAssertEqual failed: ("Optional("Mar 14, 2020 at 12:00 AM")") is not equal to ("Optional("Mar 14, 2020 at 12:00 AM")")
</details>
<details><summary>:x: XCTest failed: CoreTests/ConferenceListViewControllerTests/testLayout</summary>


    XCTAssertEqual failed: ("Optional("Concluded Mar 14, 2020 at 12:00 AM")") is not equal to ("Optional("Concluded Mar 14, 2020 at 12:00 AM")")
</details>
<details><summary>:x: XCTest failed: CoreTests/ConferenceTests/testProperties</summary>


    XCTAssertEqual failed: ("In Progress | Started Mar 14, 2020 at 1:00 PM") is not equal to ("In Progress | Started Mar 14, 2020 at 1:00 PM")
    XCTAssertEqual failed: ("Concluded Mar 14, 2020 at 1:00 PM") is not equal to ("Concluded Mar 14, 2020 at 1:00 PM")
    XCTAssertEqual failed: ("Concluded Mar 14, 2020 at 1:00 PM") is not equal to ("Concluded Mar 14, 2020 at 1:00 PM")
</details>
<details><summary>:x: XCTest failed: CoreTests/DateExtensionsTests/testDateTimeString</summary>


    XCTAssertEqual failed: ("Optional("Dec 25, 2000 at 11:45 AM")") is not equal to ("Optional("Dec 25, 2000 at 11:45 AM")")
    XCTAssertEqual failed: ("Optional("Dec 25, 2000 at 11:45 AM")") is not equal to ("Optional("Dec 25, 2000, 11:45 AM")")
</details>
<details><summary>:x: XCTest failed: CoreTests/DiscussionDetailsViewControllerTests/testLayout</summary>


    XCTAssertTrue failed
</details>
<details><summary>:x: XCTest failed: CoreTests/DiscussionListViewControllerTests/testCourseDiscussions</summary>


    XCTAssertEqual failed: ("Optional("Last post Nov 3, 2020 at 12:00 AM")") is not equal to ("Optional("Last post Nov 3, 2020 at 12:00 AM")")
    XCTAssertEqual failed: ("Optional("Due Oct 31, 2020 at 12:00 AM")") is not equal to ("Optional("Due Oct 31, 2020, 12:00 AM")")
    XCTAssertEqual failed: ("Optional("Due Oct 31, 2020 at 12:00 AM")") is not equal to ("Optional("Due Oct 31, 2020, 12:00 AM")")
</details>
<details><summary>:x: XCTest failed: CoreTests/DiscussionListViewControllerTests/testGroupDiscussions</summary>


    XCTAssertEqual failed: ("Optional("Last post Nov 3, 2020 at 12:00 AM")") is not equal to ("Optional("Last post Nov 3, 2020 at 12:00 AM")")
</details>
:x: (and 14 other test failures)

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f5a48f6f05229d9f87f574c7d8f8d98e5a124de4
</p>

**Comment by inst-danger** [comment]
<details><summary>Parent Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Teacher Build QR Code:</summary>

</details>

**Comment by inst-danger** [comment]
<details><summary>Student Build QR Code:</summary>

</details>

**Review by szabinst — APPROVED** [review]

**Review by ndrsszsz — APPROVED** [review]

**Pull request merged**
